### ISSUE TITLE
On one host seeing a lot of 'error writing event'

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#3049] opened 2015-06-24 21:14 UTC
It seems we have a single troubled server trying to talk with itself and having issues, we do not witness this behavior on other servers...  

2015/06/24 20:26:18 etcdhttp: error writing event (write tcp 10.1.4.82:56015: broken pipe)

\# ifconfig 
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 9000
        inet 10.1.4.82  netmask 255.255.252.0  broadcast 10.1.7.255

Ohh it's me, trying to talk to myself but huh?
       
\# etcd --version
etcd Version: 2.1.0-alpha.1+git
Git SHA: c0b5cc6
Go Version: go1.4.2

**Comment by xiang90** [comment] 2015-06-24 21:18
@timothysc 

Two questions: 

1. What is your cluster setup? A member is not expected to talk to itself. Are you saying you have two members are on the same physical machine?

2. Is the issue reoccurring? Do you have any log?

**Comment by timothysc** [comment] 2015-06-24 21:22
{
    "members": [
        {
            "clientURLs": [
                "http://host18-rack11.scale.openstack.engineering.redhat.com:2379"
            ],
            "id": "38e8a281731dfb33",
            "name": "host18-rack11",
            "peerURLs": [
                "http://host18-rack11.scale.openstack.engineering.redhat.com:2380"
            ]
        },
        {
            "clientURLs": [
                "http://host18-rack10.scale.openstack.engineering.redhat.com:2379"
            ],
            "id": "acf67291ff5eb498",
            "name": "host18-rack10",
            "peerURLs": [
                "http://host18-rack10.scale.openstack.engineering.redhat.com:2380"
            ]
        },
        {
            "clientURLs": [
                "http://host17-rack10.scale.openstack.engineering.redhat.com:2379"
            ],
            "id": "de3d2b0504a72625",
            "name": "host17-rack10",
            "peerURLs": [
                "http://host17-rack10.scale.openstack.engineering.redhat.com:2380"
            ]
        }
    ]
}

**Comment by xiang90** [comment] 2015-06-24 21:25
@timothysc Are these dns pointing to different IPs?

**Comment by timothysc** [comment] 2015-06-24 21:28
yes the hostnames point to different ip-addresses.

**Comment by xiang90** [comment] 2015-06-24 21:30
@timothysc Can you provide some log? Does it reoccur?

**Comment by yichengq** [comment] 2015-06-24 21:33
Do you have client on the `10.1.4.82`(local) machine?

**Comment by timothysc** [comment] 2015-06-24 21:33
local kube-apiserver: 
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.965926   23912 handlers.go:135] PUT /api/v1/nodes/host08-rack10.scale.openstack.engineering.redhat.com/status: (7.889883ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37685]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.954478   23912 handlers.go:135] GET /api/v1/nodes/host08-rack10.scale.openstack.engineering.redhat.com: (1.793515ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37685]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.602763   23912 handlers.go:135] PUT /api/v1/nodes/host05-rack10.scale.openstack.engineering.redhat.com/status: (7.751687ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37673]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.591831   23912 handlers.go:135] PUT /api/v1/nodes/host12-rack11.scale.openstack.engineering.redhat.com/status: (7.976496ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37992]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.591653   23912 handlers.go:135] GET /api/v1/nodes/host05-rack10.scale.openstack.engineering.redhat.com: (3.173896ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37673]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.580709   23912 handlers.go:135] GET /api/v1/nodes/host12-rack11.scale.openstack.engineering.redhat.com: (3.445177ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37992]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.576023   23912 handlers.go:135] GET /api/v1/watch/namespaces/e2e-tests-svc-latency-aj1nu/pods?labelSelector=name%3Dtrial-404&resourceVersion=2556611: (879.307µs) 0 [[e2e.test/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:38135]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.394592   23912 handlers.go:135] POST /api/v1/namespaces/e2e-tests-svc-latency-aj1nu/services: (18.744264ms) 201 [[e2e.test/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:38135]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.343444   23912 handlers.go:135] PUT /api/v1/nodes/host15-rack11.scale.openstack.engineering.redhat.com/status: (8.765951ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37682]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.331342   23912 handlers.go:135] GET /api/v1/nodes/host15-rack11.scale.openstack.engineering.redhat.com: (1.788931ms) 200 [[kubelet/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:37682]
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com kube-apiserver[23912]: I0624 20:26:25.245258   23912 handlers.go:135] GET /metrics: (8.851249ms) 200 [[Go 1.1 package http] 10.1.4.1:60068]

etcd: 
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:25 etcdhttp: error writing event (write tcp 10.1.4.82:56063: broken pipe)
Jun 24 20:26:25 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:25 etcdhttp: error writing event (write tcp 10.1.4.89:58131: broken pipe)
Jun 24 20:26:24 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:24 etcdhttp: error writing event (write tcp 10.1.4.92:50212: broken pipe)
Jun 24 20:26:24 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:24 etcdhttp: error writing event (write tcp 10.1.4.82:55769: broken pipe)
Jun 24 20:26:23 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:23 etcdhttp: error writing event (write tcp 10.1.4.89:58335: broken pipe)
Jun 24 20:26:23 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:23 etcdhttp: error writing event (write tcp 10.1.4.92:50306: connection reset by peer)
Jun 24 20:26:22 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:22 etcdhttp: error writing event (write tcp 10.1.4.92:50373: broken pipe)
Jun 24 20:26:21 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:21 etcdhttp: error writing event (write tcp 10.1.4.82:55808: broken pipe)
Jun 24 20:26:21 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:21 etcdhttp: error writing event (write tcp 10.1.4.92:50024: connection reset by peer)
Jun 24 20:26:20 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:20 etcdhttp: error writing event (write tcp 10.1.4.82:56035: broken pipe)
Jun 24 20:26:19 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:19 etcdhttp: error writing event (write tcp 10.1.4.92:50340: broken pipe)
Jun 24 20:26:19 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:19 etcdhttp: error writing event (write tcp 10.1.4.82:56049: broken pipe)
Jun 24 20:26:18 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:18 etcdhttp: error writing event (write tcp 10.1.4.82:56015: broken pipe)
Jun 24 20:26:17 host18-rack11.scale.openstack.engineering.redhat.com bash[23867]: 2015/06/24 20:26:17 etcdhttp: error writing event (write tcp 10.1.4.92:49980: connection reset by peer)

**Comment by timothysc** [comment] 2015-06-24 21:35
@yichengq It's a clustered etcd w/ kubernetes in HA-mode.  Yes there is a local client, but there are remote ones as well, along with a batch of errors all close in time.

**Comment by yichengq** [comment] 2015-06-24 21:44
It is the error because v2 server failed to write the response to the connection with client. Could you check the behavior of your client?

```
20:26:25.576023 23912 handlers.go:135] GET /api/v1/watch/namespaces/e2e-tests-svc-latency-aj1nu/pods?labelSelector=name%3Dtrial-404&resourceVersion=2556611: (879.307µs) 0 [[e2e.test/v0.19.3 (linux/amd64) kubernetes/461fc2b] 10.1.4.82:38135]
```
the status is 0, which seems to be strange.

**Comment by timothysc** [comment] 2015-06-25 02:35
@yichengq there is no discernible error from the client side, the only abnormal thing I see are the etcd errors, and again, this only happens on one host.

**Comment by yichengq** [comment] 2015-06-25 16:28
The error only indicates that the connection between etcd client and server is broken. Is there any way to reproduce it clearly and reliably? Or could you run etcd in `-log-package-levels etcdhttp=DEBUG` mode and monitor client requests at server side?

**Comment by timothysc** [comment] 2015-06-25 16:59
Yes we have a clean repro, I can re-conf and will report later today.

**Comment by timothysc** [comment] 2015-06-26 19:15
@yichengq ^ uploaded.  Error occurred on different server post restart.

**Comment by yichengq** [comment] 2015-06-26 20:22
The error only happens when do recursive watch on key `/v2/keys/registry/pods/e2e-tests-svc-latency-ynh3v`. At the server side, it writes HTTP status code first, then writing event into the body, where the error is reported. What does client side see for this request?

**Comment by yichengq** [comment] 2015-06-26 22:08
I get the line that `Jun 26 18:51:34 host17-rack10.scale.openstack.engineering.redhat.com kube-apiserver[41916]: I0626 18:51:34.504716   41916 handlers.go:135] GET /api/v1/watch/namespaces/e2e-tests-svc-latency-ynh3v/pods?labelSelector=name%3Dtrial-380&resourceVersion=3173263: (1.125241ms) 0 [[e2e.test/v0.19.3 (linux/amd64) kubernetes/24de9af] 10.1.4.82:53548]`. But I cannot understand what does http status '0' mean, and whether it indicates some error.

Based on the log, I think all other recursive watch(e.g., on '/v2/keys/registry/services/specs?recursive=true&wait=true&waitIndex=3173396') is successful. Could you confirm that?

**Comment by xiang90** [comment] 2015-07-03 16:17
@timothysc Ping. As @yichengq said, it seems there is a corresponding client side error. The TCP connection was closed for some reason.

**Comment by timothysc** [comment] 2015-07-06 16:15
@xiang90 Sorry was on vacation, I'll add to the todo list this week.

**Comment by yichengq** [comment] 2015-07-14 19:48
@timothysc ping. Have you digged into this one?

**Comment by timothysc** [comment] 2015-07-14 19:51
Sorry it's been put on the back-burner, other higher prio items around HA have usurped my ability to dig further.

**Comment by xiang90** [comment] 2015-07-20 03:36
@timothysc Sorry. We tried to reproduce this. But failed. At this point, we suspect this is a client side issue. I am closing this due to low activity. Please feel free to reopen this if you still have the same issue and are able to reproduce it without k8s dependency. We would love to investigate more. Thanks for reporting!

**Closed by xiang90** 2015-07-20 03:36 UTC

**Comment by timothysc** [comment] 2015-07-20 15:01
@xiang90 sounds good, when if/when I have time to re-create I'll check in the clients and report details. Thanks for trying to hunt it down.
