### ISSUE TITLE
When I import "github.com/coreos/etcd/internal/mvcc/mvccpb"   , prompting not to use how to solve？

### ISSUE THREAD

**Issue by tx991020** [coreos/etcd#9310] opened 2018-02-10 09:39 UTC
import "github.com/coreos/etcd/internal/mvcc/mvccpb"
Use of internal package is not allowed less... (⌘F1) 
Reports invalid imports.

**Comment by hexfusion** [comment] 2018-02-10 11:21
Hi @tx991020 this is a duplicate of https://github.com/coreos/etcd/issues/9293, please follow here.

**Closed** 2018-02-10 11:21 UTC
