### ISSUE TITLE
revoke access to subset of keys not working

### ISSUE THREAD

**Issue by andybrown668** [coreos/etcd#9791] opened 2018-05-31 10:46 UTC
having this structure of keys in etcd:
/config/k1
/config/k2
...
/config/k100

I want the guest user to be able to access all keys except k2.

Following these steps:

1. create root user
2. enable authentication
3. revoke read/write access on guest role to path /*  
4. grant read access on guest role to path /config
5. try to revoke read/write access on guest role to path config/k2

Step 5 fails:
` $ etcdctl --username root:root role revoke guest --path "/config/k2" --readwrite`
`auth: Role not updated. Use grant/revoke to update the role.`

Is it possible to revoke access to k2 while allowing access to all other keys under /config?

**Comment by joelegasse** [comment] 2018-06-05 16:09
@andybrown668 The short answer is "no", but I'll try to explain a bit more in detail.

etcd doesn't have negative permissions, meaning there is no such thing as a "DENY" permission. By default, when you turn authentication on, all access is denied (except for the `root` role, which can access everything by default). When you then run a `grant-permission` command, you're adding "holes" that allow a given role to access key ranges for certain operations (`read`, `write`, `readwrite`). If any one of the granted permissions allow the access, it will work. the `revoke-permission` is just that: it revokes a granted permission, it does not create a "DENY" rule that would patch the metaphorical hole created by a previously granted permission.

The alternative to that would be to grant read access with a range on either side of the "special" key (using set notation): `["/config", "/config/k2")` and `["/config/k3", "/confih")`.

You haven't given much context here, so I can just provide the technical mechanisms involved. However, when I've found myself in these kind of situations before, it's usually a sign that the "special" key (`/config/k2` in your example) doesn't belong in the current prefix/location/grouping.

I hope this has explained things. If you feel this is resolved, please close the issue.

**Comment by andybrown668** [comment] 2018-06-05 16:46
ah, ok - sounds like I need to redo how I'm storing keys then; I'm using etcd for storing configuration settings in this example (although I use it for more than that too).

Some of those settings should only be read/writable by specific microservices so I'd wanted to apply guest role permissions down at the key level with a DENY rule to keep things simple.

It's a bit of an issue because the permissions will likely change over time, and it'd be a pain to have to update the prefix/location/grouping to reflect the new permissions requirements.

DENY is a fairly common way to keep permissions simple; is there a reason it's not in etcd (or is it on a roadmap)?

**Comment by joelegasse** [comment] 2018-06-05 17:13
The permission model without a DENY rule makes the model simpler and easier. It means that as soon as you find a permission that allows the access, you can return immediately from rule processing.

Having DENY rules could have the corresponding problem: How do you create a "hole" in the DENY range? What happens when multiple roles conflict with ALLOW vs. DENY? Which role takes precedence? Keeping the model simple, "everything is restricted and you can only grant access", means that debugging access issues is easy, either:

- A user has access when they shouldn't => They have a granted permission that needs to be adjusted
- A user doesn't have access when they should => They are missing a granted permission

There is no way you'll see a granted permission in one role the user has, but the user is still unable to access the resource.

**Comment by mitake** [comment] 2018-06-07 07:55
@joelegasse thanks a lot for your accurate and detailed explanation. I agree.

@andybrown668 I understood your motivation. But if we work on this feature, we need to be very careful for not allowing counterintuitive access to keys.

**Comment by joelegasse** [comment] 2018-06-18 18:13
I'm going to close this issue because the permission system is working as intended. Redesigning the permission system to include DENY-style rules can be left to future discussions/versions.

**Closed by joelegasse** 2018-06-18 18:13 UTC
