### ISSUE TITLE
etcdctl cluster-health broken in etcd v3.0.15

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#6875] opened 2016-11-19 17:30 UTC
```
./bin/etcdctl cluster-health
```
```
failed to check the health of member 8e9e05c52164694d on http://localhost:2379: Get http://localhost:2379/health: EOF
member 8e9e05c52164694d is unreachable: [http://localhost:2379] are all unreachable
```

Works with v3.0.10:

```
etcd-v3.0.10-darwin-amd64/etcd
```

```
./bin/etcdctl cluster-health
```
```
member 8e9e05c52164694d is healthy: got healthy result from http://localhost:2379
cluster is healthy
```

**Comment by gyuho** [comment] 2016-11-19 18:07
Works fine on Linux.

```
/etcd 

2016-11-19 10:05:44.927805 I | etcdmain: etcd Version: 3.0.15
2016-11-19 10:05:44.927877 I | etcdmain: Git SHA: fc00305
2016-11-19 10:05:44.927882 I | etcdmain: Go Version: go1.6.3
2016-11-19 10:05:44.927886 I | etcdmain: Go OS/Arch: linux/amd64
2016-11-19 10:05:44.927891 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2016-11-19 10:05:44.927895 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-11-19 10:05:44.927960 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-11-19 10:05:44.928152 I | etcdmain: listening for peers on http://localhost:2380
2016-11-19 10:05:44.928181 I | etcdmain: listening for client requests on localhost:2379
```

```
etcdctl --debug cluster-health

Cluster-Endpoints: http://127.0.0.1:4001, http://127.0.0.1:2379
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
member 8e9e05c52164694d is healthy: got healthy result from http://localhost:2379
cluster is healthy
```

We will try on Mac machines next week.

Thanks for report!

**Comment by xiang90** [comment] 2016-11-19 18:09
Cannot reproduce on OSX.

Downloaded 3.0.15 from github release page.

```
./etcd
2016-11-19 10:07:53.587416 W | flags: unrecognized environment variable ETCDCTL_API=3
2016-11-19 10:07:53.587538 I | etcdmain: etcd Version: 3.0.15
2016-11-19 10:07:53.587543 I | etcdmain: Git SHA: fc00305
2016-11-19 10:07:53.587556 I | etcdmain: Go Version: go1.6.3
2016-11-19 10:07:53.587560 I | etcdmain: Go OS/Arch: darwin/amd64
2016-11-19 10:07:53.587564 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-11-19 10:07:53.587571 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
```

```
./etcdctl cluster-health
member 8e9e05c52164694d is healthy: got healthy result from http://localhost:2379
cluster is healthy
```

**Comment by gyuho** [comment] 2016-11-24 01:52
@kelseyhightower How often does this happen? Can you try other hosts like `127.0.0.1`?

Might be related `localhost` resolution on MacOS https://github.com/coreos/etcd/pull/6877#issue-190535105

I don't see this in Linux.

**Comment by heyitsanthony** [comment] 2016-11-28 18:59
Can't repro on 10.10.5. It doesn't look like there was anything between 3.0.10 and 3.0.15 that would have caused breakage on this path.

@kelseyhightower any thoughts on how to reliably reproduce this?

**Comment by michael-px** [comment] 2016-11-30 23:29
I'm seeing something sorta similar with etcdv3.1-rc.1.  I setup a single node with SSL/TLS using cfssl. I logged a separate issue for it.

**Comment by heyitsanthony** [comment] 2016-12-06 19:10
Can't reproduce. Closing.

**Closed by heyitsanthony** 2016-12-06 19:10 UTC

**Comment by glorysdj** [comment] 2017-12-06 01:53
also encounter this problem:

failed to check the health of member 18d1950bae3c1568 on https://172.16.0.183:2379: Get https://172.16.0.183:2379/health: EOF
member 18d1950bae3c1568 is unreachable: [https://172.16.0.183:2379] are all unreachable
failed to check the health of member 60c9314b636087df on https://172.16.0.182:2379: Get https://172.16.0.182:2379/health: EOF
member 60c9314b636087df is unreachable: [https://172.16.0.182:2379] are all unreachable
failed to check the health of member 7044fc88a4b993d7 on https://172.16.0.181:2379: Get https://172.16.0.181:2379/health: EOF
member 7044fc88a4b993d7 is unreachable: [https://172.16.0.181:2379] are all unreachable
cluster is unhealthy

but each etcd node is active and running,
Dec 05 20:44:01 My-Node-081 etcd[151631]: serving client requests on 172.16.0.181:2379
Dec 05 20:44:01 My-Node-081 etcd[151631]: serving client requests on 127.0.0.1:2379
