### ISSUE TITLE
grpc-gateway /kv/range hangs with auth enabled

### ISSUE THREAD

**Issue by sbatschelet** [coreos/etcd#6667] opened 2016-10-18 18:07 UTC
**etcdctl version:** 3.1.0-rc.0
**API version:** 3.1

```
curl -H "Content-Type: application/json" -X POST -d '{"key": "Zm9v"}' https://127.0.0.1:2379/v3alpha/kv/range
```

If auth is disabled this works as expected but otherwise the request will hang.  This response differs from a put.

```
curl -H "Content-Type: application/json" -X POST -d '{"key": "Zm9v", "value": "YmFy"}' https://127.0.0.1:2379/v3alpha/kv/put
```

which although does not work correctly because of https://github.com/coreos/etcd/issues/6643 does respond with {"Error":"auth: revision in header is old","Code":2}.

This appears to be regression from a distance.

**Comment by gyuho** [comment] 2016-10-26 17:46
It works for me? Can you share the full commands to reproduce this?

**Comment by xiang90** [comment] 2016-11-03 19:22
@gyuho I can reproduce it.

@mitake Can you take a look? This will bring etcd into busy loop. etcd starts to eat all CPUs.

**Comment by mitake** [comment] 2016-11-04 04:33
@xiang90 @sbatschelet I also could reproduce the problem. Although the gateway does not support auth currently, it seems to be problematic. I'll work on it.

**Comment by xiang90** [comment] 2017-01-13 21:03
@heyitsanthony I think this is due to the empty user thing you just fixed. Can you help to confirm? Thanks!

**Comment by heyitsanthony** [comment] 2017-01-13 22:32
With patch:
```sh
$ curl -H "Content-Type: application/json" -X POST -d '{"key": "Zm9v"}' http://127.0.0.1:2379/v3alpha/kv/range
{"error":"etcdserver: user name is empty","code":3}
```

Without patch: hangs.

Looks like it's fixed. Closing.

**Closed by heyitsanthony** 2017-01-13 22:32 UTC
