### ISSUE TITLE
followers respond to leader's MsgApp with the index of unstable log, why is there no problem with this?

### ISSUE THREAD

**Issue by abel-von** [coreos/etcd#8144] opened 2017-06-21 03:29 UTC
Hi, while I am reading the codes of etcd v3 these days, I encountered a question that, when follower handle MsgApp, it append the log entries to it's unstable logs and reply with the newest log index in the unstable log. when leader received the MsgAppResp from follower, it set commit based on the Index in the message,     i.e. it set commit to the index that majority of nodes replied in their MsgAppResp. 

I thought the follower should persist the log entries before it reply the index to the leader, otherwise, the safety can not be ensured. 
consider a case like this: in the cluster with 3 nodes,  the leader append an entry with index 3 to it's log and send MsgApp to followers, and the two followers reply with index 3 to leader although they did not persist the log entry to disk. and the leader find that all nodes has appended the log with index 3, so it will apply the log with index 3 to the state machine. after that, all three nodes crashed and restart, one of the former follower become leader(it can be elect leader because the other former follower has the same log index persisted with it,say maybe 2). now when it replicate the log, the former leader should delete it's log entry that was already applied.   I think this is violation to Raft.

I don't know if this is because of my missing of any code to handle the inconsistency or is it a rare case that etcd do not consider.

**Comment by xiang90** [comment] 2017-06-21 03:37
> I thought the follower should persist the log entries before it reply the index to the leader, otherwise, the safety can not be ensured.

this is what etcd does

>  it append the log entries to it's unstable logs and reply with the newest log index in the unstable log.

i guess you missed one thing: the follower persists the unstable log to disk.

closing this out since i do not feel this is a problem.

**Closed by xiang90** 2017-06-21 03:37 UTC

**Comment by abel-von** [comment] 2017-06-21 03:45
but the problem is that it persists the unstable log to disk asynchronously, so it is possible that it may  crash before it persists the unstable log.
so if majority of followers did not persist it's unstable log to disk before it crash. then next in the next startup , one of the these followers may be elected as leader, it will replicate the log to the former leader which already applied the log that former followers did not persist.

**Comment by abel-von** [comment] 2017-06-21 03:46
this is a rare case but i think it is still a problem, isn't it?

**Comment by xiang90** [comment] 2017-06-21 04:26
Can you point out where exactly the problem is? And why do you think it is async?

**Comment by abel-von** [comment] 2017-06-21 04:42
![follower-save](https://user-images.githubusercontent.com/7891772/27367260-48029a3a-567e-11e7-9aa6-ed43b5a52342.png)

it is a goroutine in the raftNode who persist the unstable log to disk, right? the newest index of the unstable log may be send to be leader before the log is persisted to disk. 

`func (r *raft) handleAppendEntries(m pb.Message) {
	if m.Index < r.raftLog.committed {
		r.send(pb.Message{To: m.From, Type: pb.MsgAppResp, Index: r.raftLog.committed})
		return
	}

	if mlastIndex, ok := r.raftLog.maybeAppend(m.Index, m.LogTerm, m.Commit, m.Entries...); ok {
		r.send(pb.Message{To: m.From, Type: pb.MsgAppResp, Index: mlastIndex})
	} else {
		r.logger.Debugf("%x [logterm: %d, index: %d] rejected msgApp [logterm: %d, index: %d] from %x",
			r.id, r.raftLog.zeroTermOnErrCompacted(r.raftLog.term(m.Index)), m.Index, m.LogTerm, m.Index, m.From)
		r.send(pb.Message{To: m.From,
			Type: pb.MsgAppResp,
			Index: m.Index,
			Reject: true,
			RejectHint: r.raftLog.lastIndex(),
		})
	}
}`

**Comment by xiang90** [comment] 2017-06-21 04:43
> it is a goroutine in the raftNode who persist the unstable log to disk, right? 

no. it is not.

**Comment by xiang90** [comment] 2017-06-21 05:09
raft is all logical. nothing gets sent out or persist to disk. real io happens here: https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L165

i would suggest you to read readme in raft pkg before digging into code.

**Comment by abel-von** [comment] 2017-06-21 05:49
That is exactly what i mean,  https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L165  is in a goroutine, isn't it?  

if this happens in the goroutine, then it is possible that follower will reply with the log index before it is persisted into disk.

I have really carefully read the codes, thesis, and doc of etcd, and etcd is of course a very excellent distributed kv store. but this question really troubled me.

**Comment by xiang90** [comment] 2017-06-21 06:02
@abel-von 

> if this happens in the goroutine, then it is possible that follower will reply with the log index before it is persisted into disk.

i do not understand what are you trying to say really... It does not matter if io happens in a routine. what matters is to make sure we persist data to disk before send msg back to leader. and this is exactly what happens in that routine. 

i do not think i will explain this more. if you still feel it is an issue, please provide line by line analysis or provide a test to break etcd. thank you.

**Comment by gyuho** [comment] 2017-06-21 06:09
@abel-von That routine you linked receives `Ready.Entries` from `Ready`, and persists them via `r.storage.Save(rd.HardState, rd.Entries)` below. Till then, they are not committed. So `Ready.Entries` won't be returned. So they are stored on disk before forwarding to leader.

**Comment by abel-von** [comment] 2017-06-21 06:18
对不起，我可能英文表述不够清楚，请允许我用中文重述一遍我的问题。
follower在收到MsgApp以后，会把里面的日志条目append到unstable里面，然后直接返回unstable中最新index给leader。而unstable里面的log是由 https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L165 这个协程来处理，进行持久化的。所以我认为这个地方的持久化是一个异步的行为。
leader收到MsgAppResp以后会用刚刚follower返回的index去做判断，如果多数节点已经append了某个index，就把这条日志设置为commited，然后会有另一个协程apply到kv 存储里面去。

如果所有follower节点在那个持久化协程处理的时候都挂了，而且leader也在这时候挂了（可能性很小）。那么重启的时候其中一个follower可能会被选为leader(因为follower都没有持久化那条日志，所以那些follower是可以同意其中一个follower的选主请求的)。新的leader向上一个Term的leader发送同步日志的请求时，就有可能出现把老leader已经apply的日志覆盖了。

我仔细看了下那个协程的处理我想明白了，https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L242， Ready结构里面如果有MsgAppResp，那么里面的index包含的日志一定在它的Entries里面。所以etcd这里的处理是先持久化日志，再发送消息。

嗯，终于解答了我的疑惑，多谢大牛。

**Comment by abel-von** [comment] 2017-06-21 06:23
我忽略了消息和日志都是那个协程处理的，我忽略了这里的send不是直接就把消息发送出去了，而是也走到那个goroutine里面处理的。

**Comment by abel-von** [comment] 2017-06-21 06:26
@gyuho  thank you for replying.
