### ISSUE TITLE
Negative TTL problem on macOS [etcd v2.3.7]

### ISSUE THREAD

**Issue by Bplotka** [coreos/etcd#7132] opened 2017-01-10 16:23 UTC
Simple TTL usage with single local `etcd` does not work on the newest macOS version. Works for every Linux distro I tested, though. Only valid for `etcd v2.3.7`. Older `v2.3.6` seems to work. Darwin build for `2.3.7` is somehow malformed?

**System**: 
```
System Version:    macOS 10.12.2 (16C67)
Kernel Version:    Darwin 16.3.0
```
**Steps to reproduce**:
On macOS machine:
1. Install etcd using steps stated here: https://github.com/coreos/etcd/releases/tag/v2.3.7
```
curl -L  https://github.com/coreos/etcd/releases/download/v2.3.7/etcd-v2.3.7-darwin-amd64.zip -o etcd-v2.3.7-darwin-amd64.zip
unzip etcd-v2.3.7-darwin-amd64.zip
cd etcd-v2.3.7-darwin-amd64
./etcd
```
2. On another terminal set value with TTL and try to get it periodically. After TTL expiration, we can see negative values and key is not deleted. (exactly follow: https://coreos.com/etcd/docs/latest/v2/api.html#using-key-ttl). Added `date` cmd to show that the clocks are synced.
```
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d value=bar -d ttl=5
Tue 10 Jan 2017 16:19:09 GMT
{"action":"set","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","ttl":5,"modifiedIndex":4,"createdIndex":4}}
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo
Tue 10 Jan 2017 16:19:14 GMT
{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","modifiedIndex":4,"createdIndex":4}}
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo
Tue 10 Jan 2017 16:19:14 GMT
{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","modifiedIndex":4,"createdIndex":4}}
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo
Tue 10 Jan 2017 16:19:16 GMT
{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","ttl":-2,"modifiedIndex":4,"createdIndex":4}}
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo
Tue 10 Jan 2017 16:19:17 GMT
{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","ttl":-3,"modifiedIndex":4,"createdIndex":4}}
:~ $ date && curl http://127.0.0.1:2379/v2/keys/foo
Tue 10 Jan 2017 16:19:19 GMT
{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2017-01-10T16:19:14.01513555Z","ttl":-5,"modifiedIndex":4,"createdIndex":4}}
```

Any ideas?

**Comment by xiang90** [comment] 2017-01-10 21:17
@Bplotka Can you build from source with go 1.7.2 on Darwin 16.3.0? See if it solves the problem?

**Comment by xiang90** [comment] 2017-01-10 21:19
@Bplotka I think you might meet this issue https://github.com/golang/go/issues/16570

**Comment by xiang90** [comment] 2017-01-24 03:08
@Bplotka Kindly ping.

**Comment by Bplotka** [comment] 2017-01-24 10:17
Sorry for delayed response.. I am using Linux & Windows, so had to find volunteer with this version of macOS who could help me to test it (thanks @joshpmcghee). 

When built from source with the go `1.7.1` or `1.7.2` it works fine, but it does not solve our problem: We have the use case that we want to download the newest etcd v2 binary and just use it for dev/testing on any MacOS. 

Is there any way to rebuild it on your side and provide working binary out-of-the-box?

**Comment by xiang90** [comment] 2017-01-24 16:00
> Is there any way to rebuild it on your side and provide working binary out-of-the-box?

I do not think we are going to re-release ALL previous released versions of etcd as the problem is fixed. But we might release a new etcd 2.3.x version sometime next week that built with go 1.7. Closing this issue since we confirmed this is a go runtime problem.

**Closed by xiang90** 2017-01-24 16:00 UTC

**Comment by Bplotka** [comment] 2017-02-13 10:01
Thanks, waiting for next 2.3.x version then (:
