### ISSUE TITLE
follower may use long time to catch up the leader when reboot under reasonable workload

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2698] opened 2015-04-16 18:49 UTC
1. start 3-member cluster
2. write 250k 100byte keys
3. make 200 clients keep writing on these keys on each member
3. kill one member for some time and expect it to recover from incoming snapshot
4. start the member
5. it may take long time to catch up the leader. Here is a gist that it failed to catch up the leader in 40s: https://gist.github.com/yichengq/5097b4c2f5c341a0f76e
it happens about once in 500 rounds.

Reasons are that it may take 5s to recover store from snapshot under this workload in some probability. If it keeps happening, it is always in the process to catch up the leader.

**Comment by xiang90** [comment] 2015-12-29 21:48
@heyitsanthony I feel we can close this with our new snapshot improvements for v3. For v2, we assume the snapshot is small and recover should be fast...

**Comment by xiang90** [comment] 2015-12-29 21:49
@heyitsanthony But it would be good if you can double check this again. In my experimental, etcd can recover from snapshot and catch up smoothly and successfully even if the snapshot is as large as 3GB and the whole cluster is under high workload.

**Comment by heyitsanthony** [comment] 2015-12-30 22:28
Ran this with V3. The restarted member smoothly went from initialization to "applied incoming snapshot" and active in about 10 seconds; meanwhile the cluster continued to take snapshots due to all the put activity.

**Comment by heyitsanthony** [comment] 2015-12-30 23:34
Ran with 250k keys with 8KB value size. Confirmed leader will not snapshot if it's transferring a snapshot; only follower created snapshots while leader was sending. Took 30 seconds to go from leader "start to send database" to restarted member "applied incoming snapshot".

**Comment by xiang90** [comment] 2015-12-30 23:38
@heyitsanthony Thanks for confirming that. We cannot avoid that 30 second delay anyway since it is IO bounded. I think it is good enough to close this issue?

**Comment by heyitsanthony** [comment] 2015-12-30 23:46
Yeah, not much can be done about the IO cost. The obvious brokenness is fixed so I think it's good to close.

**Closed** 2015-12-31 00:03 UTC
Labels: area/performance
