### ISSUE TITLE
clientv3: auth example failed

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6675] opened 2016-10-19 03:45 UTC
output is as follow

```
=== RUN   ExampleAuth
2016-10-19 03:34:05.745878 N | auth: Role root is created
2016-10-19 03:34:05.745966 N | auth: Role root is created
2016-10-19 03:34:05.745982 N | auth: Role root is created
2016-10-19 03:34:05.748193 N | auth: added a new user: root
2016-10-19 03:34:05.748543 N | auth: added a new user: root
2016-10-19 03:34:05.748878 N | auth: granted role root to user root
2016-10-19 03:34:05.749082 N | auth: granted role root to user root
2016-10-19 03:34:05.749554 N | auth: Role r is created
2016-10-19 03:34:05.749725 N | auth: Role r is created
2016-10-19 03:34:05.749912 N | auth: added a new user: root
2016-10-19 03:34:05.749936 N | auth: granted role root to user root
2016-10-19 03:34:05.749953 N | auth: Role r is created
2016-10-19 03:34:05.750111 N | auth: role r's permission of key foo is updated as READWRITE
2016-10-19 03:34:05.750147 N | auth: role r's permission of key foo is updated as READWRITE
2016-10-19 03:34:05.750202 N | auth: role r's permission of key foo is updated as READWRITE
2016-10-19 03:34:05.751792 N | auth: added a new user: u
2016-10-19 03:34:05.752220 N | auth: granted role r to user u
2016-10-19 03:34:05.752559 N | auth: Authentication enabled
2016-10-19 03:34:05.752978 E | etcdserver: invalid authentication request to user u was issued
2016-10-19 03:34:05.753067 I | etcdserver: authentication failed, invalid user ID or password
```

Authentication request for user `u` failed for unknown reason.

/cc @mitake

**Comment by mitake** [comment] 2016-10-19 12:33
@xiang90 sorry for breaking the example, I'll work on it tomorrow.

**Comment by mitake** [comment] 2016-10-20 04:30
I could construct a schedule that can cause the problem potentially.

Let s1 (leader), s2 (follower), s3 (follower) be servers, c be a client.

1. c issues RPCs for preparing auth (e.g., UserAdd(), RoleAdd(), AuthEnable(), etc) to s1
2. s1 tries to propagate them to s2 and s3. But s3 is slow and don't receive log entries from s1
3. c issues an RPC of Authenticate() to s3
4. s3 checks its local authStore with CheckPassword(), and cannot find a user in the argument of Authenticate() because the log entries of the preparation aren't committed to its state

This is a drawback of delegating the password checking to the API layer. This would be able to be resolved with the applyWait mechanism like `EtcdServer.isValidSimpleToken()`.

The problem reported in https://github.com/coreos/etcd/issues/6683 would have a same root cause.

**Comment by mitake** [comment] 2016-10-20 04:37
On the second thought, the applyWait mechanism cannot be used because `Authenticate()` RPC does not take a token (it generates the token)...

**Comment by mitake** [comment] 2016-10-20 05:05
There would be 3 solutions:

1. let `Authenticate()` take a revision number as its argument
2. let followers not serve requests from client (like Chubby and LogCabin)
3. use `bcrypt.MinCost` for password checking (roughly it reduced the cost from 100ms -> 1ms)

1 and 2 wouldn't be acceptable. How do you think about 3? @xiang90

**Comment by xiang90** [comment] 2016-10-24 23:42
@mitake I would suggest to move checkpassword back to apply loop. But we can make checkPassword to be executed asynchronously (concurrently with commands after it, since checkPassword is a readonly request.

**Closed** 2016-11-01 14:51 UTC
Labels: area/testing
