### ISSUE TITLE
SSL Peer Handshake fails because missing IP SANs 

### ISSUE THREAD

**Issue by devx** [coreos/etcd#3496] opened 2015-09-11 20:04 UTC
When trying to build an SSL Peer Cluster on AWS with a wildcard cert, it fails.  The failure is because the SSL Cert Does not have a valid IP.  The error I get is the following.

```  
x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
```
I assume this would be the same as if i used etcd-ca and used the --domain= option.  I will try later to validate that assumption.

**Comment by yichengq** [comment] 2015-09-11 21:42
We document our security model here: https://github.com/coreos/etcd/blob/master/Documentation/security.md and we provide a full cfssl example here: https://github.com/coreos/etcd/tree/master/hack/tls-setup

Stdlib in Go requires you to have SANs that match your identification to use the cert, or it will reject it. @gtank Right?

**Comment by gtank** [comment] 2015-09-14 21:28
That's correct, and I think with IPs there is no wildcard option.

**Comment by devx** [comment] 2015-09-15 01:55
Sorry I did not pay attention to the use of the --domain option.  That being said, would it be possible to support wildcard certs?  

Otherwise we could close this as it's working as intended.

**Comment by gtank** [comment] 2015-09-18 22:06
@devx As far as I know, it's not possible to support wildcard IP SANs in compliance with HTTP. If you look at [RFC2818](https://tools.ietf.org/html/rfc2818#section-3.1), it actually specifies exact match for the special case of IP addresses:
```
   In some cases, the URI is specified as an IP address rather than a
   hostname. In this case, the iPAddress subjectAltName must be present
   in the certificate and must exactly match the IP in the URI.
```

**Comment by xiang90** [comment] 2015-09-23 06:23
@devx I think @gtank has answered your questions. I am closing since this works as intended. Let us know if you have other issues. Thanks!

**Closed by xiang90** 2015-09-23 06:23 UTC
