### ISSUE TITLE
etcd 3.0.1 cannot run normal on Windows 7 64-bit

### ISSUE THREAD

**Issue by kuncao** [coreos/etcd#5882] opened 2016-07-06 08:09 UTC
https://github.com/coreos/etcd/issues/5852
after  manually renamed default.etcd/member/wal.tmp to default.etcd/member/wal. Then etcd will start normally.
but can not provide the service
E:\etcd>etcdctl member list  
   this conmand run hang
http://localhost:2379/ 
  run hang  in IE
E:\etcd>etcdctl set /testdir/testkey "Hello world"
  run hang
E:\etcd>etcd
2016-07-06 15:54:12.173012 I | etcdmain: etcd Version: 3.0.1
2016-07-06 15:54:12.254269 I | etcdmain: Git SHA: a4a52cb
2016-07-06 15:54:12.254269 I | etcdmain: Go Version: go1.6.2
2016-07-06 15:54:12.254269 I | etcdmain: Go OS/Arch: windows/amd64
2016-07-06 15:54:12.255248 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-07-06 15:54:12.255248 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-07-06 15:54:12.255248 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-06 15:54:12.262101 I | etcdmain: listening for peers on http://localhost:2380
2016-07-06 15:54:12.265038 I | etcdmain: listening for client requests on localhost:2379
2016-07-06 15:54:12.270912 W | snap: skipped unexpected non snapshot file db.lock
2016-07-06 15:54:12.270912 I | etcdserver: name = default
2016-07-06 15:54:12.270912 I | etcdserver: data dir = default.etcd
2016-07-06 15:54:12.271891 I | etcdserver: member dir = default.etcd/member
2016-07-06 15:54:12.271891 I | etcdserver: heartbeat = 100ms
2016-07-06 15:54:12.271891 I | etcdserver: election = 1000ms
2016-07-06 15:54:12.271891 I | etcdserver: snapshot count = 10000
2016-07-06 15:54:12.271891 I | etcdserver: advertise client URLs = http://localhost:2379
2016-07-06 15:54:12.275807 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 0
2016-07-06 15:54:12.278744 I | raft: 8e9e05c52164694d became follower at term 0
2016-07-06 15:54:12.282660 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-07-06 15:54:12.318883 I | etcdserver: starting server... [version: 3.0.1, cluster version: to_be_decided]
2016-07-06 15:54:12.320841 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on windows)
2016-07-06 15:54:19.339292 E | etcdserver: publish error: etcdserver: request timed out
2016-07-06 15:54:26.358722 E | etcdserver: publish error: etcdserver: request timed out
2016-07-06 15:54:33.381089 E | etcdserver: publish error: etcdserver: request timed out
2016-07-06 15:54:40.400519 E | etcdserver: publish error: etcdserver: request timed out
2016-07-06 15:54:47.421907 E | etcdserver: publish error: etcdserver: request timed out
2016-07-06 15:54:54.441337 E | etcdserver: publish error: etcdserver: request timed out

**Comment by MartyMacGyver** [comment] 2016-07-06 08:57
I rebuilt etcd just now from master (commit 234c30c) and got the following similar output (but with more verbose errors):

```
C:\etcd\bin>etcdctl cluster-health
member 8e9e05c52164694d is healthy: got healthy result from http://localhost:2379
cluster is healthy

C:\etcd\bin>etcdctl member list
client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout

C:\etcd\bin>etcdctl set /testdir/testkey "Hello world"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout
```

The server output itself seems equivalent:
```
C:\etcd\bin>etcd
2016-07-06 01:48:41.889331 I | etcdmain: etcd Version: 3.0.0+git
2016-07-06 01:48:41.889831 I | etcdmain: Git SHA: 234c30c
2016-07-06 01:48:41.890331 I | etcdmain: Go Version: go1.6.2
2016-07-06 01:48:41.890331 I | etcdmain: Go OS/Arch: windows/amd64
2016-07-06 01:48:41.890831 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2016-07-06 01:48:41.891331 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-07-06 01:48:41.891831 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-06 01:48:41.895332 I | etcdmain: listening for peers on http://localhost:2380
2016-07-06 01:48:41.895832 I | etcdmain: listening for client requests on localhost:2379
2016-07-06 01:48:41.901832 W | snap: skipped unexpected non snapshot file db.lock
2016-07-06 01:48:41.901832 I | etcdserver: name = default
2016-07-06 01:48:41.902332 I | etcdserver: data dir = default.etcd
2016-07-06 01:48:41.902332 I | etcdserver: member dir = default.etcd/member
2016-07-06 01:48:41.902832 I | etcdserver: heartbeat = 100ms
2016-07-06 01:48:41.902832 I | etcdserver: election = 1000ms
2016-07-06 01:48:41.903333 I | etcdserver: snapshot count = 10000
2016-07-06 01:48:41.903833 I | etcdserver: advertise client URLs = http://localhost:2379
2016-07-06 01:48:41.904833 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 65
2016-07-06 01:48:41.904833 I | raft: 8e9e05c52164694d became follower at term 2
2016-07-06 01:48:41.905333 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 2, commit: 65, applied: 0, lastindex: 65, lastterm: 2]
2016-07-06 01:48:41.920835 I | etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
2016-07-06 01:48:41.921335 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on windows)
2016-07-06 01:48:41.921835 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2016-07-06 01:48:41.921835 N | membership: set the initial cluster version to 3.0
2016-07-06 01:48:42.421898 I | api: enabled capabilities for version 3.0
2016-07-06 01:48:42.706935 I | raft: 8e9e05c52164694d is starting a new election at term 2
2016-07-06 01:48:42.706935 I | raft: 8e9e05c52164694d became candidate at term 3
2016-07-06 01:48:42.707435 I | raft: 8e9e05c52164694d received vote from 8e9e05c52164694d at term 3
2016-07-06 01:48:42.707435 I | raft: 8e9e05c52164694d became leader at term 3
2016-07-06 01:48:42.707935 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 3
2016-07-06 01:48:42.708935 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2016-07-06 01:48:42.708935 I | etcdmain: ready to serve client requests
2016-07-06 01:48:42.709435 N | etcdmain: serving insecure client requests on localhost:2379, this is strongly discouraged!
```

**Comment by MartyMacGyver** [comment] 2016-07-06 09:59
I removed my original reply - it confirmed the problem you're seeing but as it became a bit intermittent I  decided to delve deeper. I think I have your answer (though this goes back to the need to document the Windows use case for the Windows deliverables).

localhost and 127.0.0.1 aren't always quite the same on Windows 7 and newer: for me, `localhost` is the IPv6 `::1:` while the only IPv4 loopback is `127.0.0.1`.  My hosts file (`C:\Windows\System32\drivers\etc\hosts`) is a bit ambiguous on this point, having both the ipv4 and ipv6 loopbacks:
```
127.0.0.1       localhost
::1             localhost
```

I tried combinations of endpoints - etcd and etcdctl both using `localhost`, one using `localhost` and the other using `127.0.0.1`, but the only way I got it to work consistently was to explicitly use only the  `127.0.0.1` IPv4 endpoints. Therefore, you'd start the server with:

`etcd --debug --advertise-client-urls http://127.0.0.1:2379`

and access it like so:

`etcdctl --debug --endpoints http://127.0.0.1:2379 <command>`

e.g.:
`etcdctl --debug --endpoints http://127.0.0.1:2379 member list`
`etcdctl --debug --endpoints http://127.0.0.1:2379 set /message "Hello world"`

This is incomplete, as you'll probably need to also set the other parameters that refer to `localhost` to `127.0.0.1` as well... but for one etcd server and one etcdctl client this will suffice.

Note: debug option was added for extra info.

**Comment by MartyMacGyver** [comment] 2016-07-06 10:17
One interesting side-note - if there is no service on port 4001, calls via `etcdctl` using the default values often take an extra second while it tries and fails to use that particular endpoint (if it polls it first). I'd think this would slow things down a bit if nothing else...

**Comment by MartyMacGyver** [comment] 2016-07-06 10:36
Finally, something that gets to the heart of how weird localhost can be when it's defined for both protocols. I started etcd with no special options, so it refers to `localhost`, and then ran the following commands:

etcdctl with `localhost` alone simply never works:
```
etcdctl --debug --endpoints http://localhost:2379 set /message "Hello world"
start to sync cluster using endpoints(http://localhost:2379)
cURL Command: curl -X GET http://localhost:2379/v2/members
got endpoints() after sync
Cluster-Endpoints:
cURL Command: curl -X PUT /v2/keys/message -d "value=Hello+world"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: unsupported protocol scheme ""

error #0: unsupported protocol scheme ""
```

Neither does etcdctl with `127.0.0.1` alone:
```
C:\bin\etcd3>cd /D C:\bin\etcd3 && etcdctl --debug --endpoints http://127.0.0.1:2379 set /message "Hello world"
start to sync cluster using endpoints(http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://localhost:2379) after sync
Cluster-Endpoints: http://localhost:2379
cURL Command: curl -X PUT http://localhost:2379/v2/keys/message -d "value=Hello+world"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout

error #0: client: endpoint http://localhost:2379 exceeded header timeout
```

But combine them and they often work - as long as it happens to poll (and fail) `localhost` first:
```
etcdctl --debug --endpoints http://localhost:2379,http://127.0.0.1:2379 set /message "Hello world"
start to sync cluster using endpoints(http://127.0.0.1:2379,http://localhost:2379)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://localhost:2379) after sync
Cluster-Endpoints: http://localhost:2379
cURL Command: curl -X PUT http://localhost:2379/v2/keys/message -d "value=Hello+world"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout

error #0: client: endpoint http://localhost:2379 exceeded header timeout


etcdctl --debug --endpoints http://localhost:2379,http://127.0.0.1:2379 set /message "Hello world"
start to sync cluster using endpoints(http://localhost:2379,http://127.0.0.1:2379)
cURL Command: curl -X GET http://localhost:2379/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://localhost:2379) after sync
Cluster-Endpoints: http://localhost:2379
cURL Command: curl -X PUT http://localhost:2379/v2/keys/message -d "value=Hello+world"
Hello world
````

It's quite repeatable if the two attempts are in the same program instance, and makes me wonder if this might be a golang quirk as well, if not just a Windows thing.

**Comment by kuncao** [comment] 2016-07-08 02:07
thanks  MartyMacGyver  for deep dive into the issue.
but the configuration and commands cannot run right in my env.

hosts file configed as follow:
127.0.0.1  localhost
start etcd:
E:\etcd>etcd --debug --advertise-client-urls http://127.0.0.1:2379
2016-07-08 09:32:45.902446 I | etcdmain: etcd Version: 3.0.1
2016-07-08 09:32:45.989933 I | etcdmain: Git SHA: a4a52cb
2016-07-08 09:32:45.989933 I | etcdmain: Go Version: go1.6.2
2016-07-08 09:32:45.989933 I | etcdmain: Go OS/Arch: windows/amd64
2016-07-08 09:32:45.989933 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-07-08 09:32:45.989933 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-07-08 09:32:45.989933 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-08 09:32:45.997887 I | etcdmain: listening for peers on http://localhost:2380
2016-07-08 09:32:46.005840 I | etcdmain: listening for client requests on localhost:2379
2016-07-08 09:32:46.013793 W | snap: skipped unexpected non snapshot file db.lock
2016-07-08 09:32:46.013793 I | etcdserver: name = default
2016-07-08 09:32:46.013793 I | etcdserver: data dir = default.etcd
2016-07-08 09:32:46.021747 I | etcdserver: member dir = default.etcd/member
2016-07-08 09:32:46.029700 I | etcdserver: heartbeat = 100ms
2016-07-08 09:32:46.029700 I | etcdserver: election = 1000ms
2016-07-08 09:32:46.030694 I | etcdserver: snapshot count = 10000
2016-07-08 09:32:46.038648 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2016-07-08 09:32:46.051572 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 0
2016-07-08 09:32:46.051572 I | raft: 8e9e05c52164694d became follower at term 0
2016-07-08 09:32:46.051572 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-07-08 09:32:46.075433 I | etcdserver: starting server... [version: 3.0.1, cluster version: to_be_decided]
2016-07-08 09:32:46.083386 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on windows)
2016-07-08 09:32:53.219578 E | etcdserver: publish error: etcdserver: request timed out
2016-07-08 09:33:00.347819 E | etcdserver: publish error: etcdserver: request timed out

E:\etcd>etcdctl --debug member list
start to sync cluster using endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members

and then hang
E:\etcd>etcdctl --debug set /message "Hello world"
start to sync cluster using endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
hang

but stop etcd 
etcdctl --debug member list and etcdctl --debug set /message "Hello world" stopped with the following message
Error:  dial tcp 127.0.0.1:4001: connectex: No connection could be made because the target machine actively refused it.


E:\etcd>etcd --debug --advertise-client-urls http://127.0.0.1:4001
2016-07-08 10:02:05.564094 I | etcdmain: etcd Version: 3.0.1
2016-07-08 10:02:05.658249 I | etcdmain: Git SHA: a4a52cb
2016-07-08 10:02:05.666095 I | etcdmain: Go Version: go1.6.2
2016-07-08 10:02:05.666095 I | etcdmain: Go OS/Arch: windows/amd64
2016-07-08 10:02:05.673942 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-07-08 10:02:05.673942 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-07-08 10:02:05.681788 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-08 10:02:05.689634 I | etcdmain: listening for peers on http://localhost:2380
2016-07-08 10:02:05.697481 I | etcdmain: listening for client requests on localhost:2379
2016-07-08 10:02:05.705327 W | snap: skipped unexpected non snapshot file db.lock
2016-07-08 10:02:05.713173 I | etcdserver: name = default
2016-07-08 10:02:05.713173 I | etcdserver: data dir = default.etcd
2016-07-08 10:02:05.713173 I | etcdserver: member dir = default.etcd/member
2016-07-08 10:02:05.721020 I | etcdserver: heartbeat = 100ms
2016-07-08 10:02:05.721020 I | etcdserver: election = 1000ms
2016-07-08 10:02:05.721020 I | etcdserver: snapshot count = 10000
2016-07-08 10:02:05.721020 I | etcdserver: advertise client URLs = http://127.0.0.1:4001
2016-07-08 10:02:05.728866 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 0
2016-07-08 10:02:05.728866 I | raft: 8e9e05c52164694d became follower at term 0
2016-07-08 10:02:05.728866 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-07-08 10:02:05.756328 I | etcdserver: starting server... [version: 3.0.1, cluster version: to_be_decided]
2016-07-08 10:02:05.768097 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on windows)
2016-07-08 10:02:12.801326 E | etcdserver: publish error: etcdserver: request timed out
2016-07-08 10:02:19.838478 E | etcdserver: publish error: etcdserver: request timed out
2016-07-08 10:02:26.872688 E | etcdserver: publish error: etcdserver: request timed out

**Comment by MartyMacGyver** [comment] 2016-07-08 03:27
There may be other problems with 3.0.1 that are confounding this. Either rebuild from master or try my build (based on master (3.x), commit 234c30c):

https://www.dropbox.com/s/o6onq4bkqei51ss/etcd-Windows-234c30c.zip?dl=0

Let us know if that helps or not.

Also - is 2.3.7 working for you?

**Comment by kuncao** [comment] 2016-07-08 08:23
thanks MartyMacGyver .
for security reason, I can not access dropbox in our office
I will install dropbox in my home and test your compiled etcd windows version
I have not test 2.3.7 version

**Comment by MartyMacGyver** [comment] 2016-07-08 08:56
It's probably easier to simply build your own copy of it from here using Go 1.6.2. Clone this repo to an NTFS drive and run "build.bat". As long as you have PowerShell and Git installed that should work.

**Comment by MartyMacGyver** [comment] 2016-07-08 09:03
Also, if it helps, here's a link that may be easier to access:

https://drive.google.com/open?id=0B3dTI7CdidfqRG1Xb2NGS2ZpZms

**Comment by xiang90** [comment] 2016-10-04 18:17
@sinsharat I know you have Windows env. Can you check if this is still a problem for etcd?

**Comment by sinsharat** [comment] 2016-10-04 18:22
@xiang90 sure will look into it.

**Comment by sinsharat** [comment] 2016-10-04 19:22
@xiang90 : The following were my observations with etcd Version: 3.1.0-alpha.1+git:
1. wal issue referenced in earlier issue #5852 doesn't exist anymore.
2. with etcd V3 api (ETCDCTL_API=3) there are no issues, it works perfectly fine.
3. There is no issue with etcd server startup when using v2 version api, also etcdctl works fine when complete endpoint is specified. For example : 
`PS C:\sharat\workspace\go-projects\src\github.com\coreos\etcd\bin> .\etcdctl.exe --endpoint=http://localhost:2379 member list
8e9e05c52164694d: name=default peerURLs=http://localhost:2380 clientURLs=http://localhost:2379 isLeader=true
PS C:\sharat\workspace\go-projects\src\github.com\coreos\etcd\bin> .\etcdctl.exe --endpoint=http://localhost:2379 set foo bar
bar`
3. The issue for client for v2 api not working on starting default etcd is only when the endpoint is not specified. It gives the below error:
`PS C:\sharat\workspace\go-projects\src\github.com\coreos\etcd\bin> .\etcdctl.exe member list
client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout

PS C:\sharat\workspace\go-projects\src\github.com\coreos\etcd\bin> .\etcdctl.exe set foo bar
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2379 exceeded header timeout

error #0: client: endpoint http://localhost:2379 exceeded header timeout`

**Comment by sinsharat** [comment] 2016-10-04 20:00
@xiang90 Also my suggestion is since default host is not supported on windows, better to modify logging code at places where we print 127.0.0.1 by default.  May be by using windows specific files to avoid confusion while printing details during etcd startup. Also if you want i can look into the reason for etcdctl not working without endpoint for v2 version.
Need your opinion on this.
Thanks!

**Comment by xiang90** [comment] 2016-10-04 20:14
@sinsharat Thanks for checking this. 

> Also my suggestion is since default host is not supported on windows, better to modify logging code at places where we print 127.0.0.1 by default. 

How about adding windows specific code to change the default host to 127.0.0.1 from localhost? Go supports build tag, so it is pretty easy to achieve.

**Comment by sinsharat** [comment] 2016-10-04 20:20
@xiang90 yes that's exactly what i had meant by adding windows specific files. I was already going through the code and had observed that the values are not hard-coded. Hence i referred to the earlier logs and figured out that there is already some code written for the same. Will analyze this in detail in the morning, fix it and raise PR for this.
Thanks!

**Comment by xiang90** [comment] 2016-10-04 20:21
@sinsharat Sounds great! Thanks!

**Comment by xiang90** [comment] 2016-10-07 20:59
@sinsharat Shall we close this issue? It seems etcd now can run on windows?

**Comment by sinsharat** [comment] 2016-10-07 21:01
@xiang90 yes already tested. With the fix provided it works fine. It can be closed.
Thanks!

**Closed** 2016-10-07 21:01 UTC
Labels: area/windows
