### ISSUE TITLE
Restarting etcd proxy instance - fails to start (unknown wal version in data dir)

### ISSUE THREAD

**Issue by wsimmonds** [coreos/etcd#2529] opened 2015-03-18 13:42 UTC
Hi, 

Running version 2.0.5 of etcd (and originally experienced the issue on 2.0.3). One of my proxy nodes was rebooted and did not come online, with the following message:

Mar 18 09:56:05 ip-10-0-1-113.ec2.internal writer_process[1105]: 2015/03/18 09:56:05 etcd: unknown wal version in data dir /opt/etcd

It appears this issue previously existed in #1899 and was fixed in #1913 for 0.50.

I can confirm as per the original issue, deleting the proxy folder results in it starting successfully.

**Comment by xiang90** [comment] 2015-03-18 14:40
This should be fixed by https://github.com/coreos/etcd/pull/2526. Next release will include this fix.

**Comment by philips** [comment] 2015-03-18 18:53
Closing as a duplicate of #2529. Thanks.

**Closed by philips** 2015-03-18 18:53 UTC
