### ISSUE TITLE
etcd unit test fails for etcd/raft in ppc64le

### ISSUE THREAD

**Issue by sudeeshjohn** [coreos/etcd#9850] opened 2018-06-14 08:35 UTC
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

Test test is running in a docker env . This fails in ppc64le too.

ENV:

root@ee6399fb6e87:/go/src/github.com/coreos/etcd# ./bin/etcd --version
etcd Version: 3.3.0+git
Git SHA: 03cec4a
Go Version: devel +7bab1ee Thu Jun 14 02:58:06 2018 +0000
Go OS/Arch: linux/amd64
root@ee6399fb6e87:/go/src/github.com/coreos/etcd# 

```
root@ee6399fb6e87:/go/src/github.com/coreos/etcd# EXPECT_DEBUG=1 PASSED=unit make test
TEST_OPTS: PASSES='unit'
log-file: test-MTUyODk2NDAyNgo.log
PASSES='unit' ./test 2>&1 | tee test-MTUyODk2NDAyNgo.log
Running with TEST_CPUS: 1,2,4
Starting 'unit' pass at Thu Jun 14 08:13:49 UTC 2018
Running unit tests...
ok  	github.com/coreos/etcd	(cached)	coverage: 0.0% of statements
ok  	github.com/coreos/etcd/auth	(cached)	coverage: 66.8% of statements
ok  	github.com/coreos/etcd/client	(cached)	coverage: 17.1% of statements
ok  	github.com/coreos/etcd/clientv3	(cached)	coverage: 22.7% of statements
ok  	github.com/coreos/etcd/clientv3/balancer	(cached)	coverage: 65.8% of statements
ok  	github.com/coreos/etcd/clientv3/clientv3util	(cached)	coverage: 0.0% of statements [no tests to run]
ok  	github.com/coreos/etcd/clientv3/concurrency	(cached)	coverage: 0.0% of statements [no tests to run]
ok  	github.com/coreos/etcd/clientv3/namespace	(cached)	coverage: 11.3% of statements
ok  	github.com/coreos/etcd/clientv3/naming	(cached)	coverage: 78.3% of statements
ok  	github.com/coreos/etcd/clientv3/ordering	(cached)	coverage: 89.2% of statements
ok  	github.com/coreos/etcd/clientv3/snapshot	(cached)	coverage: 64.2% of statements
ok  	github.com/coreos/etcd/clientv3/yaml	(cached)	coverage: 91.3% of statements
ok  	github.com/coreos/etcd/embed	(cached)	coverage: 32.9% of statements
ok  	github.com/coreos/etcd/etcdctl	(cached)	coverage: 0.0% of statements
ok  	github.com/coreos/etcd/etcdctl/ctlv2/command	(cached)	coverage: 0.7% of statements
ok  	github.com/coreos/etcd/etcdctl/ctlv3/command	(cached)	coverage: 3.8% of statements
ok  	github.com/coreos/etcd/etcdmain	(cached)	coverage: 24.4% of statements
ok  	github.com/coreos/etcd/etcdserver	(cached)	coverage: 26.2% of statements
ok  	github.com/coreos/etcd/etcdserver/api/etcdhttp	(cached)	coverage: 25.2% of statements
ok  	github.com/coreos/etcd/etcdserver/api/membership	(cached)	coverage: 55.2% of statements
ok  	github.com/coreos/etcd/etcdserver/api/rafthttp	(cached)	coverage: 71.9% of statements
ok  	github.com/coreos/etcd/etcdserver/api/snap	(cached)	coverage: 49.7% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2auth	(cached)	coverage: 70.9% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2discovery	(cached)	coverage: 61.1% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2error	(cached)	coverage: 85.7% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2http	(cached)	coverage: 73.8% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2http/httptypes	(cached)	coverage: 76.2% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2store	(cached)	coverage: 91.1% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v3compactor	(cached)	coverage: 80.0% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v3rpc	(cached)	coverage: 4.1% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes	(cached)	coverage: 75.0% of statements
ok  	github.com/coreos/etcd/lease	(cached)	coverage: 83.8% of statements
ok  	github.com/coreos/etcd/lease/leasehttp	(cached)	coverage: 66.4% of statements
ok  	github.com/coreos/etcd/mvcc	(cached)	coverage: 81.7% of statements
ok  	github.com/coreos/etcd/mvcc/backend	(cached)	coverage: 78.3% of statements
ok  	github.com/coreos/etcd/pkg/adt	(cached)	coverage: 82.5% of statements
ok  	github.com/coreos/etcd/pkg/crc	(cached)	coverage: 100.0% of statements
# github.com/coreos/etcd/raft
raft/logger.go:117: missing ... in args forwarded to print-like function
ok  	github.com/coreos/etcd/pkg/expect	1.096s	coverage: 95.5% of statements
ok  	github.com/coreos/etcd/pkg/fileutil	(cached)	coverage: 74.7% of statements
ok  	github.com/coreos/etcd/pkg/flags	(cached)	coverage: 66.9% of statements
ok  	github.com/coreos/etcd/pkg/httputil	(cached)	coverage: 62.5% of statements
ok  	github.com/coreos/etcd/pkg/idutil	(cached)	coverage: 100.0% of statements
ok  	github.com/coreos/etcd/pkg/ioutil	(cached)	coverage: 74.6% of statements
ok  	github.com/coreos/etcd/pkg/logutil	(cached)	coverage: 34.9% of statements
ok  	github.com/coreos/etcd/pkg/netutil	(cached)	coverage: 58.1% of statements
ok  	github.com/coreos/etcd/pkg/osutil	(cached)	coverage: 78.4% of statements
ok  	github.com/coreos/etcd/pkg/pathutil	(cached)	coverage: 100.0% of statements
ok  	github.com/coreos/etcd/pkg/pbutil	(cached)	coverage: 76.9% of statements
ok  	github.com/coreos/etcd/pkg/proxy	(cached)	coverage: 66.0% of statements
ok  	github.com/coreos/etcd/pkg/report	(cached)	coverage: 89.0% of statements
ok  	github.com/coreos/etcd/pkg/schedule	(cached)	coverage: 85.5% of statements
ok  	github.com/coreos/etcd/pkg/srv	(cached)	coverage: 87.5% of statements
ok  	github.com/coreos/etcd/pkg/stringutil	(cached)	coverage: 76.5% of statements
ok  	github.com/coreos/etcd/pkg/testutil	(cached)	coverage: 17.1% of statements
ok  	github.com/coreos/etcd/pkg/tlsutil	17.724s	coverage: 6.9% of statements
ok  	github.com/coreos/etcd/pkg/transport	(cached)	coverage: 56.1% of statements
ok  	github.com/coreos/etcd/pkg/types	(cached)	coverage: 90.8% of statements
ok  	github.com/coreos/etcd/pkg/wait	(cached)	coverage: 92.9% of statements
ok  	github.com/coreos/etcd/proxy/grpcproxy	(cached)	coverage: 11.9% of statements
ok  	github.com/coreos/etcd/proxy/httpproxy	(cached)	coverage: 76.1% of statements
ok  	github.com/coreos/etcd/proxy/tcpproxy	(cached)	coverage: 58.5% of statements
FAIL	github.com/coreos/etcd/raft [build failed]
ok  	github.com/coreos/etcd/tools/etcd-dump-logs	(cached)	coverage: 0.0% of statements
ok  	github.com/coreos/etcd/wal	(cached)	coverage: 75.2% of statements
! egrep "(--- FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test-MTUyODk2NDAyNgo.log
root@ee6399fb6e87:/go/src/github.com/coreos/etcd#
```

**Comment by sudeeshjohn** [comment] 2018-06-14 08:37
error message is pointing to the below part of the code: 
```

	os.Exit(1)
}

func (l *DefaultLogger) Panic(v ...interface{}) {
	l.Logger.Panic(v)
}
```

**Comment by gyuho** [comment] 2018-06-14 17:12
@sudeeshjohn Can you help debug and fix this? We have no access to `ppc64le`.

**Comment by glevand** [comment] 2018-06-14 19:43
@gyuho Maybe something like this?
```sh
wget https://d-i.debian.org/daily-images/ppc64el/daily/netboot/mini.iso
qemu-system-ppc64le -machine pseries,usb=off -m 1024 -device spapr-vscsi -nographic -vga none -netdev user,id=net0 -device virtio-net-pci,netdev=net0 -device virtio-blk-pci,drive=drive0 -drive id=drive0,if=none,file=/path/to/host/storage -boot d -cdrom mini.iso
```

**Comment by sudeeshjohn** [comment] 2018-06-15 04:34
@gyuho its not specific to ppc64le, I see this in amd64 also 

```
<snip>
ok  	github.com/coreos/etcd/pkg/testutil	(cached)	coverage: 17.1% of statements
# github.com/coreos/etcd/raft
raft/logger.go:117: missing ... in args forwarded to print-like function
ok  	github.com/coreos/etcd/pkg/tlsutil	18.538s	coverage: 6.9% of statements
ok  	github.com/coreos/etcd/pkg/transport	(cached)	coverage: 55.8% of statements
ok  	github.com/coreos/etcd/pkg/types	(cached)	coverage: 90.8% of statements
ok  	github.com/coreos/etcd/pkg/wait	(cached)	coverage: 92.9% of statements
ok  	github.com/coreos/etcd/proxy/grpcproxy	(cached)	coverage: 12.3% of statements
ok  	github.com/coreos/etcd/proxy/httpproxy	(cached)	coverage: 76.1% of statements
ok  	github.com/coreos/etcd/proxy/tcpproxy	(cached)	coverage: 58.5% of statements
FAIL	github.com/coreos/etcd/raft [build failed]
ok  	github.com/coreos/etcd/tools/etcd-dump-logs	(cached)	coverage: 0.0% of statements
ok  	github.com/coreos/etcd/wal	(cached)	coverage: 75.2% of statements
! egrep "(--- FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test-MTUyOTAzNjkyNwo.log
root@27c619642822:/go/src/github.com/coreos/etcd# TEST_OPTS: PASSES='unit'
bash: TEST_OPTS:: command not found
root@27c619642822:/go/src/github.com/coreos/etcd# ./bin/etcd -version
etcd Version: 3.3.0+git
Git SHA: 7e42c66
Go Version: devel +4eb1c84 Fri Jun 15 02:09:44 2018 +0000
Go OS/Arch: linux/amd64
root@27c619642822:/go/src/github.com/coreos/etcd# 
<snip>
```

**Comment by gyuho** [comment] 2018-06-15 04:40
@sudeeshjohn That's strange. Could you run with `VERBOSE=1 make test`? I want to see which test has failed. Can't reproduce in my amd64 machine.

**Comment by sudeeshjohn** [comment] 2018-06-15 05:05
@gyuho I think below patch to the golang is doing a check on the function arguments , is causing this failure ;

https://github.com/golang/go/commit/c00603607511701ecc9f56fd82ac528ecf6b8fc6#diff-8fa5b0d6191706747ef5773f895781c9

Something like below should fix the issue;

sudeeshjohn:~/Workspace/Automation/IBMPrivateCloud/src/etcd$ git diff
diff --git a/raft/logger.go b/raft/logger.go
index 92e55b373..426a77d34 100644
--- a/raft/logger.go
+++ b/raft/logger.go
@@ -114,7 +114,7 @@ func (l *DefaultLogger) Fatalf(format string, v ...interface{}) {
 }
 
 func (l *DefaultLogger) Panic(v ...interface{}) {
-       l.Logger.Panic(v)
+       l.Logger.Panic(v...)
 }
 
 func (l *DefaultLogger) Panicf(format string, v ...interface{}) {
sudeeshjohn:~/Workspace/Automation/IBMPrivateCloud/src/etcd$

**Comment by gyuho** [comment] 2018-06-15 06:32
@sudeeshjohn Oh, that should be fixed. Do you want to send a PR to fix it? Thanks!

**Comment by sudeeshjohn** [comment] 2018-06-15 06:59
@gyuho sure ..will send noe

**Comment by sudeeshjohn** [comment] 2018-06-15 07:11
sent a PR https://github.com/coreos/etcd/pull/9853

**Closed** 2018-06-15 17:38 UTC
Labels: Help Wanted, Testing
