### ISSUE TITLE
etcdhttp: unexpected error: etcdserver: request timed out

### ISSUE THREAD

**Issue by minjs** [coreos/etcd#2276] opened 2015-02-10 21:26 UTC
2015/02/10 19:28:50 etcd: listening for peers on http://172.16.64.208:7001
2015/02/10 19:28:50 etcd: listening for client requests on http://127.0.0.1:4001
2015/02/10 19:28:50 etcd: listening for client requests on http://172.16.64.208:4001
2015/02/10 19:28:50 etcdserver: name = 042859A6
2015/02/10 19:28:50 etcdserver: data dir = /var/shape/data/54da5725e4b06213fa7173ae.042859A6/member
2015/02/10 19:28:50 etcdserver: heartbeat = 100ms
2015/02/10 19:28:50 etcdserver: election = 5000ms
2015/02/10 19:28:50 etcdserver: snapshot count = 10000
2015/02/10 19:28:50 etcdserver: advertise client URLs = http://127.0.0.1:4001,http://172.16.64.208:4001
2015/02/10 19:28:50 etcdserver: restart member e1bef91ecd5c6c4d in cluster a1ba1bcdd394e13f at commit index 1153
2015/02/10 19:28:50 raft: e1bef91ecd5c6c4d became follower at term 4
2015/02/10 19:28:50 raft: newRaft e1bef91ecd5c6c4d [peers: [], term: 4, commit: 1153, applied: 0, lastindex: 1161, lastterm: 4]
2015/02/10 19:28:50 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1284] rejected msgApp [logterm: 4, index: 1284] from fe6b67e59f6636d7
2015/02/10 19:28:50 raft.node: e1bef91ecd5c6c4d elected leader fe6b67e59f6636d7 at term 4
2015/02/10 19:28:50 etcdserver: added member 8d8017fe43d49e1f [http://172.16.64.207:7001] to cluster a1ba1bcdd394e13f
2015/02/10 19:28:50 etcdserver: added local member e1bef91ecd5c6c4d [http://172.16.64.208:7001] to cluster a1ba1bcdd394e13f
2015/02/10 19:28:50 etcdserver: added member fe6b67e59f6636d7 [http://172.16.64.209:7001] to cluster a1ba1bcdd394e13f
2015/02/10 19:28:51 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1284] rejected msgApp [logterm: 4, index: 1284] from fe6b67e59f6636d7
2015/02/10 19:28:51 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1284] rejected msgApp [logterm: 4, index: 1284] from fe6b67e59f6636d7
2015/02/10 19:28:51 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1285] rejected msgApp [logterm: 4, index: 1285] from fe6b67e59f6636d7
2015/02/10 19:28:51 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1286] rejected msgApp [logterm: 4, index: 1286] from fe6b67e59f6636d7
2015/02/10 19:28:51 raft: e1bef91ecd5c6c4d [logterm: 0, index: 1287] rejected msgApp [logterm: 4, index: 1287] from fe6b67e59f6636d7
2015/02/10 19:28:52 rafthttp: starting client stream to fe6b67e59f6636d7 at term 4
2015/02/10 19:28:54 etcdserver: published {Name:042859A6 ClientURLs:[http://127.0.0.1:4001 http://172.16.64.208:4001]} to cluster a1ba1bcdd394e13f
2015/02/10 19:29:52 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:29:56 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:30:16 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:33:51 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:33:52 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:33:53 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:33:59 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:33:59 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:22 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:24 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:48 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:49 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:53 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:55 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:55 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:34:56 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:35:43 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:16 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:17 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:19 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:35 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:36 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:37 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:41 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:41 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:46 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:37:47 etcdhttp: unexpected error: etcdserver: request timed out

**Comment by yichengq** [comment] 2015-02-11 00:45
one error line indicates that one client request fails because it is not committed in the certain time, which is set to be 5s now.
We will fix the error output.
Is any part of etcd cluster, including local disk, network or CPU, really slow? In normal case, 5s is enough for requests to be committed.

**Comment by minjs** [comment] 2015-02-11 00:56
This cluster is on Esxi server.  network/disk/cpu might slow. 
But we saw same error msg on hardware box (occasionally), where we benchmark the write request normally around 300ms.  Just worry that if there is a bug instead of slow resource.

**Comment by xiang90** [comment] 2015-02-11 01:06
@minjs We could batch fsycn in the future. Currently if your disk is slow, the request might timeout. But from the log, you are experiencing this consistently. And the timeout is actually pretty long (6s). The end-to-end latency includes two disk fsync + network rtt.
It might be a bug in etcd. We will collect metrics to help you debug this in the next release.

**Comment by ghristov** [comment] 2015-02-16 14:26
This problem occurs in a standalone server as well. 
./etcd --data-dir standalone/ --name standalone --listen-client-urls 'http://10.25.2.4:4001'
This is how I start the server.

2015/02/16 16:18:09 etcd: listening for peers on http://localhost:2380
2015/02/16 16:18:09 etcd: listening for peers on http://localhost:7001
2015/02/16 16:18:09 etcd: listening for client requests on http://10.25.2.4:4001
2015/02/16 16:18:09 datadir is valid for the 2.0.1 format
2015/02/16 16:18:09 etcdserver: name = default
2015/02/16 16:18:09 etcdserver: data dir = standalone/
2015/02/16 16:18:09 etcdserver: member dir = standalone/member
2015/02/16 16:18:09 etcdserver: heartbeat = 100ms
2015/02/16 16:18:09 etcdserver: election = 1000ms
2015/02/16 16:18:09 etcdserver: snapshot count = 10000
2015/02/16 16:18:09 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/02/16 16:18:09 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 0
2015/02/16 16:18:09 raft: ce2a822cea30bfca became follower at term 0
2015/02/16 16:18:09 raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 1, lastterm: 1]
2015/02/16 16:18:14 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:19 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:21 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/16 16:18:24 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:27 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/16 16:18:29 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:34 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:39 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:44 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:49 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:54 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:18:59 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:19:04 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:19:09 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:19:14 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:19:19 etcdserver: publish error: etcdserver: request timed out
2015/02/16 16:19:24 etcdserver: publish error: etcdserver: request timed out
^C2015/02/16 16:19:29 received interrupt signal, shutting down

**Comment by xiang90** [comment] 2015-02-16 16:26
> ./etcd --data-dir standalone/ --name standalone --listen-client-urls 'http://10.25.2.4:4001'

If you start etcd with this, you should see `etcd: couldn't find local name "standalone" in the initial cluster configuration`.

From the log, your cluster is somewhat broken. Can you please provide the initial configuration you gave to etcd? Or would you like to send the datadir to me by email?

**Comment by ghristov** [comment] 2015-02-16 16:57
Sorry my bad, I copied the command from another wrong tab. Indeed when i specify the --name that appears.

./etcd --data-dir standalone/ --listen-client-urls 'http://10.25.2.4:4001'

user@host:/opt/etcd$ ./etcd --data-dir standalone/ --listen-client-urls 'http://10.25.2.4:4001'
2015/02/16 18:50:41 etcd: listening for peers on http://localhost:2380
2015/02/16 18:50:41 etcd: listening for peers on http://localhost:7001
2015/02/16 18:50:41 etcd: listening for client requests on http://10.25.2.4:4001
2015/02/16 18:50:41 datadir is valid for the 2.0.1 format
2015/02/16 18:50:41 etcdserver: name = default
2015/02/16 18:50:41 etcdserver: data dir = standalone/
2015/02/16 18:50:41 etcdserver: member dir = standalone/member
2015/02/16 18:50:41 etcdserver: heartbeat = 100ms
2015/02/16 18:50:41 etcdserver: election = 1000ms
2015/02/16 18:50:41 etcdserver: snapshot count = 10000
2015/02/16 18:50:41 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/02/16 18:50:41 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 0
2015/02/16 18:50:41 raft: ce2a822cea30bfca became follower at term 0
2015/02/16 18:50:41 raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 1, lastterm: 1]
2015/02/16 18:50:46 etcdserver: publish error: etcdserver: request timed out
^C2015/02/16 18:50:49 received interrupt signal, shutting down

This is copied 1 to 1 except i changed the username, host and ip.

I just create empty directory standalone and i Invoked this.. and there you go.

Actually after I deleted the data-dir folder and started it again. It's ok.

I can give you backup of the wrong directory if you would like?

**Comment by xiang90** [comment] 2015-02-16 16:58
@ghristov email: xiang.li@coreos.com. Thanks!

**Comment by ghristov** [comment] 2015-02-16 19:28
You should have a mail from 2 hours ago

**Comment by xiang90** [comment] 2015-03-18 21:20
@ghristov @minjs This should be solved by the 2.0.5 release. Please give it a try! Thanks!

**Closed by xiang90** 2015-03-18 21:20 UTC

**Comment by hyperbolic2346** [comment] 2015-06-05 01:16
I'm getting this as well with etcd 2.0.10.
```
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcd: already initialized as member before, starting as etcd member...
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcd: listening for peers on http://10.0.1.19:2380
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcd: listening for peers on http://10.0.1.19:7001
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcd: listening for client requests on http://0.0.0.0:2379
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcd: listening for client requests on http://0.0.0.0:4001
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: datadir is valid for the 2.0.1 format
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found at "/var/lib/etcd2/member/wal"
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: recovered store from snapshot at index 6502375
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: name = host1
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: data dir = /var/lib/etcd2
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: member dir = /var/lib/etcd2/member
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: heartbeat = 100ms
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: election = 10000ms
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: snapshot count = 10000
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: discovery URL= https://discovery.etcd.io/54...
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: advertise client URLs = http://10.0.1.19:2379
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: loaded cluster information from store: host1=http://10.0.1.19:2380,dilbert=http://10.0.1.23:2380,dogbert=http://10.0.1.22:2380,ratbert=http://10.0.1.20:2380,wally=http://10.0.1.21:2380
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 etcdserver: restart member 3a752bcccdefffe9 in cluster 992fd61c39b78ed0 at commit index 6502375
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 raft: 3a752bcccdefffe9 became follower at term 33
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 raft: newRaft 3a752bcccdefffe9 [peers: [3a752bcccdefffe9,588e7deaa28fd696,6a908ca1696ce9a4,bc72cb0ca1efaedb,d9f8cf11e7fb2acd], term: 33, commit: 6502375, applied: 6502375, lastindex: 6502375, lastterm: 33]
Jun 05 01:09:45 host1 etcd2[29965]: 2015/06/05 01:09:45 raft.node: 3a752bcccdefffe9 elected leader 588e7deaa28fd696 at term 33
Jun 05 01:09:50 host1 etcd2[29965]: 2015/06/05 01:09:50 etcdserver: publish error: etcdserver: request timed out
Jun 05 01:09:51 host1 etcd2[29965]: 2015/06/05 01:09:51 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:51 host1 etcd2[29965]: 2015/06/05 01:09:51 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:51 host1 etcd2[29965]: 2015/06/05 01:09:51 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:51 host1 etcd2[29965]: 2015/06/05 01:09:51 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:52 host1 etcd2[29965]: 2015/06/05 01:09:52 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:52 host1 etcd2[29965]: 2015/06/05 01:09:52 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:52 host1 etcd2[29965]: 2015/06/05 01:09:52 raft: 3a752bcccdefffe9 [commit: 6502375] ignored snapshot [index: 6502375, term: 33]
Jun 05 01:09:52 host1 etcd2[29965]: 2015/06/05 01:09:52 rafthttp: starting client stream to 588e7deaa28fd696 at term 33
Jun 05 01:09:55 host1 etcd2[29965]: 2015/06/05 01:09:55 etcdserver: publish error: etcdserver: request timed out
Jun 05 01:09:57 host1 etcd2[29965]: 2015/06/05 01:09:57 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:57 host1 etcd2[29965]: 2015/06/05 01:09:57 rafthttp: encountered error reading the client log stream: read tcp 10.0.1.23:2380: i/o timeout
Jun 05 01:09:57 host1 etcd2[29965]: 2015/06/05 01:09:57 rafthttp: client streaming to 588e7deaa28fd696 at term 33 has been stopped
Jun 05 01:09:58 host1 etcd2[29965]: 2015/06/05 01:09:58 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:58 host1 etcd2[29965]: 2015/06/05 01:09:58 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:09:58 host1 etcd2[29965]: 2015/06/05 01:09:58 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:10:00 host1 etcd2[29965]: 2015/06/05 01:10:00 etcdserver: publish error: etcdserver: request timed out
```

Should I tar up my data directory and email it?

**Comment by xiang90** [comment] 2015-06-05 01:21
@hyperbolic2346 This seems pretty normal. Your cluster were under a leader election. During leader election there might be proposal loss. Is this(request timeout) always the case?

**Comment by hyperbolic2346** [comment] 2015-06-05 01:23
etcdctl cluster-health
cluster is healthy
member 3a752bcccdefffe9 is unhealthy
member 588e7deaa28fd696 is healthy
member 6a908ca1696ce9a4 is healthy
member bc72cb0ca1efaedb is healthy
member d9f8cf11e7fb2acd is healthy

The logs are full of these errors.

```
Jun 05 01:23:09 catbert etcd2[31734]: 2015/06/05 01:23:09 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:10 catbert etcd2[31734]: 2015/06/05 01:23:10 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:10 catbert etcd2[31734]: 2015/06/05 01:23:10 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:11 catbert etcd2[31734]: 2015/06/05 01:23:11 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:11 catbert etcd2[31734]: 2015/06/05 01:23:11 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:11 catbert etcd2[31734]: 2015/06/05 01:23:11 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:11 catbert etcd2[31734]: 2015/06/05 01:23:11 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:11 catbert etcd2[31734]: 2015/06/05 01:23:11 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:12 catbert etcd2[31734]: 2015/06/05 01:23:12 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:12 catbert etcd2[31734]: 2015/06/05 01:23:12 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:12 catbert etcd2[31734]: 2015/06/05 01:23:12 raft: 3a752bcccdefffe9 [commit: 6512391] ignored snapshot [index: 6512391, term: 33]
Jun 05 01:23:12 catbert etcd2[31734]: 2015/06/05 01:23:12 rafthttp: starting client stream to 588e7deaa28fd696 at term 33
Jun 05 01:23:14 catbert etcd2[31734]: 2015/06/05 01:23:14 etcdserver: publish error: etcdserver: request timed out
Jun 05 01:23:15 catbert etcd2[31734]: 2015/06/05 01:23:15 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:15 catbert etcd2[31734]: 2015/06/05 01:23:15 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:16 catbert etcd2[31734]: 2015/06/05 01:23:16 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:16 catbert etcd2[31734]: 2015/06/05 01:23:16 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:17 catbert etcd2[31734]: 2015/06/05 01:23:17 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:17 catbert etcd2[31734]: 2015/06/05 01:23:17 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:17 catbert etcd2[31734]: 2015/06/05 01:23:17 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:17 catbert etcd2[31734]: 2015/06/05 01:23:17 rafthttp: encountered error reading the client log stream: read tcp 10.0.1.23:2380: i/o timeout
Jun 05 01:23:17 catbert etcd2[31734]: 2015/06/05 01:23:17 rafthttp: client streaming to 588e7deaa28fd696 at term 33 has been stopped
Jun 05 01:23:18 catbert etcd2[31734]: 2015/06/05 01:23:18 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:18 catbert etcd2[31734]: 2015/06/05 01:23:18 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:18 catbert etcd2[31734]: 2015/06/05 01:23:18 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:18 catbert etcd2[31734]: 2015/06/05 01:23:18 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:19 catbert etcd2[31734]: 2015/06/05 01:23:19 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:19 catbert etcd2[31734]: 2015/06/05 01:23:19 etcdhttp: unexpected error: etcdserver: request timed out
Jun 05 01:23:19 catbert etcd2[31734]: 2015/06/05 01:23:19 etcdserver: publish error: etcdserver: request timed out
```

**Comment by xiang90** [comment] 2015-06-05 01:27
@hyperbolic2346 Is the cluster under high load? I probably need the full log from all members.

**Comment by hyperbolic2346** [comment] 2015-06-05 01:31
That machine isn't for sure, but I'm not sure what constitutes high load here:
core@catbert ~ $ uptime
 01:28:58 up 4 days,  7:41,  2 users,  load average: 0.08, 0.08, 0.11
core@ratbert ~ $ uptime
 01:29:19 up 22:26,  1 user,  load average: 0.10, 0.19, 0.29
core@wally ~ $ uptime
 01:29:38 up 23:39,  1 user,  load average: 1.15, 1.03, 1.03
core@dogbert ~ $ uptime
 01:30:41 up 4 days,  7:39,  1 user,  load average: 0.89, 0.99, 0.96
core@dilbert ~ $ uptime
 01:31:19 up 4 days,  7:39,  1 user,  load average: 0.39, 0.33, 0.37
I'll start packaging up the logs.

(should I make a new issue or is this still the same thing?)

**Comment by xiang90** [comment] 2015-06-05 01:34
can you give me the log of all members? You can create a new issue if you want.

**Comment by sulphur** [comment] 2015-06-18 16:47
any news about this issuse ? i seem to have the same on etcd-2.0.12 and there is almost no load since i'm testing on my staging environment

**Comment by yichengq** [comment] 2015-06-18 16:53
@sulphur This error may be caused by different reasons. can you share the log and command line of all members?  You can create a new issue if you want.

**Comment by cjcullen** [comment] 2015-06-23 18:46
I'm also seeing this on v2.0.12.

I'm running a single-member cluster in a docker container. The container gets restarted once early on, and every so often (~3% of the time) it triggers this behavior.

Here are the logs from the first run of the container:
```
2015/06/23 04:14:48 etcd: listening for peers on http://localhost:2380
2015/06/23 04:14:48 etcd: listening for peers on http://localhost:7001
2015/06/23 04:14:48 etcd: listening for client requests on http://127.0.0.1:4001
2015/06/23 04:14:48 etcdserver: datadir is valid for the 2.0.1 format
2015/06/23 04:14:48 etcdserver: name = default
2015/06/23 04:14:48 etcdserver: data dir = /var/etcd/data
2015/06/23 04:14:48 etcdserver: member dir = /var/etcd/data/member
2015/06/23 04:14:48 etcdserver: heartbeat = 100ms
2015/06/23 04:14:48 etcdserver: election = 1000ms
2015/06/23 04:14:48 etcdserver: snapshot count = 10000
2015/06/23 04:14:48 etcdserver: advertise client URLs = http://127.0.0.1:4001
2015/06/23 04:14:48 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/06/23 04:14:48 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
```

The container is killed (apparently at just the wrong time), and every subsequent run of the container looks like this:
```
2015/06/23 18:38:56 etcd: already initialized as member before, starting as etcd member...
2015/06/23 18:38:56 etcd: listening for peers on http://localhost:2380
2015/06/23 18:38:56 etcd: listening for peers on http://localhost:7001
2015/06/23 18:38:56 etcd: listening for client requests on http://127.0.0.1:4001
2015/06/23 18:38:56 etcdserver: datadir is valid for the 2.0.1 format
2015/06/23 18:38:56 etcdserver: name = default
2015/06/23 18:38:56 etcdserver: data dir = /var/etcd/data
2015/06/23 18:38:56 etcdserver: member dir = /var/etcd/data/member
2015/06/23 18:38:56 etcdserver: heartbeat = 100ms
2015/06/23 18:38:56 etcdserver: election = 1000ms
2015/06/23 18:38:56 etcdserver: snapshot count = 10000
2015/06/23 18:38:56 etcdserver: advertise client URLs = http://127.0.0.1:4001
2015/06/23 18:38:56 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 0
2015/06/23 18:38:56 raft: ce2a822cea30bfca became follower at term 0
2015/06/23 18:38:56 raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/23 18:39:01 etcdserver: publish error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/23 18:39:02 etcdhttp: unexpected error: etcdserver: request timed out
...
```

My command line is uninteresting, but just in case:
```
/usr/local/bin/etcd --addr 127.0.0.1:4001 --bind-addr 127.0.0.1:4001 --data-dir /var/etcd/data
```
Would you like me to open up a new issue, or can this one be reopened?

**Comment by xiang90** [comment] 2015-06-23 18:53
@cjcullen It is a different issue. But why do you want to kill etcd right after it restarted? We know there is a small chance it can lead etcd cannot restart. We have no plan to fix it.

**Comment by cjcullen** [comment] 2015-06-23 19:02
:) I don't "want" to, and am working on fixing that.

But fixing my known restarts does not guarantee that this will never happen. If docker crashes at just the wrong time, or if my VM decides to die, I could end up with a never-functional etcd cluster. Granted, it is orders of magnitude less likely, but it's still there.

**Comment by xiang90** [comment] 2015-06-23 19:35
@cjcullen 

I think the issue only happens when you kill an just started and uninitialized etcd (within 1second or so), then it might not be able to restart.

If an initialized and running etcd cannot be restarted, then it is a separate issue and we need to fix it. 

I am a little confused which one did you meet. From the log, I think it is the former one.

**Comment by cjcullen** [comment] 2015-06-23 20:32
Yes. It's the first one. Agree that it is not nearly as bad as the latter.
