### ISSUE TITLE
Critical bug - etcd2 clusters do not heal

### ISSUE THREAD

**Issue by kenaniah** [coreos/etcd#3938] opened 2015-12-01 21:52 UTC
If one of the initial nodes (from a cluster of 3) that was part of the discovery URL permanently goes offline, it is currently impossible to heal the etcd2 cluster. Any attempts to add or remove members via `etcdctl` result in `client: etcd cluster is unavailable or misconfigured`. Any attempts to add or remove members via the API result in an internal server error JSON response.

The only remedy appears to be ***rebuilding the cluster from scratch***. 

It would make much more sense to allow a system administrator to manually elect a leader and to add/remove members from each cluster instance, "misconfigured" cluster or not.

```
etcd Version: 2.1.2
Git SHA: ff8d1ec
Go Version: go1.4.2
Go OS/Arch: linux/amd64
```

**Comment by xiang90** [comment] 2015-12-01 21:54
@kenaniah 

> If one of the initial nodes (from a cluster of 3) that was part of the discovery URL permanently goes offline, it is currently impossible to heal the etcd2 cluster.

I do not think this should happen. Can you reproduce it?

**Comment by kenaniah** [comment] 2015-12-02 18:16
Yes. It's predictably reproducible. Easiest use case is to spin up a CoreOS cluster in an auto-scaling group on AWS using CloudFormation templates and then terminate one of the servers from the EC2 console. The auto-scaling group will spin up a new instance to replace the one that was terminated. At this point, the etcd2 cluster is already broken beyond repair.

**Comment by xiang90** [comment] 2015-12-02 18:24
@kenaniah 

> The auto-scaling group will spin up a new instance to replace the one that was terminated.

Will the new machine also start etcd? And how does it start the new etcd? How does the new etcd join to the new cluster?

etcdctl reports etcd cluster is not available does not mean the actual cluster is not running. Probably you misconfigured etcdctl?

**Comment by kenaniah** [comment] 2015-12-02 18:34
To answer your questions, my cloud-config is pasted below:
```
#cloud-config
---
coreos:
  etcd2:
    advertise-client-urls: http://$private_ipv4:2379
    data-dir: /media/etcd
    discovery: https://discovery.etcd.io/bbffada6ec3f1900ff4105a3b67e2115
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  fleet:
    metadata: controlPlane=true,dataPlane=true,routerMesh=true
    public-ip: $private_ipv4
  units:
  - command: start
    content: "\n  [Unit]\n  Description=Formats the added EBS volume for Docker\n\
      \  ConditionPathExists=!/etc/docker-volume-formatted\n  [Service]\n  Type=oneshot\n\
      \  RemainAfterExit=yes\n  ExecStart=/usr/sbin/wipefs -f /dev/xvdf\n  ExecStart=/usr/sbin/mkfs.ext4\
      \ -i 4096 -b 4096 /dev/xvdf\n  ExecStart=/bin/touch /etc/docker-volume-formatted\n"
    name: format-docker-volume.service
  - command: start
    content: "\n  [Unit]\n  Description=Mount Docker volume to /var/lib/docker\n \
      \ Requires=format-docker-volume.service\n  After=format-docker-volume.service\n\
      \  Before=docker.service\n  [Mount]\n  What=/dev/xvdf\n  Where=/var/lib/docker\n\
      \  Type=ext4\n"
    name: var-lib-docker.mount
  - drop-ins:
    - content: "\n  [Unit]\n  Requires=var-lib-docker.mount\n  After=var-lib-docker.mount\n"
      name: 90-after-docker-volume.conf
    name: docker.service
  - command: start
    content: "\n  [Unit]\n  Description=Formats the etcd device\n  ConditionPathExists=!/etc/etcd-volume-formatted\n\
      \  [Service]\n  Type=oneshot\n  RemainAfterExit=yes\n  ExecStart=/usr/sbin/wipefs\
      \ -f /dev/xvdg\n  ExecStart=/usr/sbin/mkfs.ext4 -i 4096 -b 4096 /dev/xvdg\n\
      \  ExecStart=/bin/touch /etc/etcd-volume-formatted\n"
    name: format-etcd-volume.service
  - command: start
    content: "\n  [Unit]\n  Description=Mounts the etcd volume\n  Requires=format-etcd-volume.service\n\
      \  After=format-etcd-volume.service\n  [Mount]\n  What=/dev/xvdg\n  Where=/media/etcd\n\
      \  Type=ext4\n"
    name: media-etcd.mount
  - command: start
    content: "\n  [Unit]\n  Description=Prepares the etcd data directory\n  Requires=media-etcd.mount\n\
      \  After=media-etcd.mount\n  Before=etcd2.service\n  [Service]\n  Type=oneshot\n\
      \  RemainAfterExit=yes\n  ExecStart=/usr/bin/chown -R etcd:etcd /media/etcd\n"
    name: prepare-etcd-data-directory.service
  - drop-ins:
    - content: "\n  [Unit]\n  Requires=prepare-etcd-data-directory.service\n  After=prepare-etcd-data-directory.service\n"
      name: 90-after-etcd-volume.conf
    name: etcd2.service
  - mask: true
    name: etcd.service
  - command: start
    name: etcd2.service
  - command: start
    name: fleet.service
  - command: start
    content: '[Unit]

      Description=Docker Socket for the API


      [Socket]

      ListenStream=2375

      Service=docker.service

      BindIPv6Only=both


      [Install]

      WantedBy=sockets.target

      '
    enable: true
    name: docker-tcp.socket
  - command: stop
    enable: false
    name: update-engine.service
  - drop-ins:
    - content: '[Service]

        Environment="DOCKER_OPTS=--insecure-registry 10.0.0.0/8 --insecure-registry
        172.16.0.0/12 --insecure-registry 192.168.0.0/16 --insecure-registry 100.64.0.0/10"

        '
      name: 50-insecure-registry.conf
    name: docker.service
  - command: start
    drop-ins:
    - content: '[Service]

        ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config ''{"Network":
        "10.244.0.0/16", "SubnetLen": 24, "SubnetMin": "10.244.0.0", "Backend": {"Type":
        "vxlan"}}''

        '
      name: 50-network-config.conf
    name: flanneld.service
  - content: '[Unit]

      Description=Clean up

      DefaultDependencies=no

      After=fleet.service etcd2.service docker.service docker.socket deis-store-admin.service
      deis-store-daemon.service deis-store-volume.service deis-store-monitor.service

      Requires=fleet.service etcd2.service deis-store-admin.service deis-store-daemon.service
      deis-store-volume.service docker.service docker.socket deis-store-monitor.service


      [Install]

      WantedBy=shutdown.target halt.target reboot.target


      [Service]

      ExecStop=/opt/bin/graceful-shutdown.sh --really

      Type=oneshot

      TimeoutSec=1200

      RemainAfterExit=yes

      '
    name: graceful-deis-shutdown.service
  - command: start
    content: '[Unit]

      Description=Install deisctl utility

      ConditionPathExists=!/opt/bin/deisctl


      [Service]

      Type=oneshot

      ExecStart=/usr/bin/sh -c ''curl -sSL --retry 5 --retry-delay 2 http://deis.io/deisctl/install.sh
      | sh -s 1.12.1''

      '
    name: install-deisctl.service
  - content: '[Unit]

      Description=etcd debugging service


      [Service]

      ExecStart=/usr/bin/bash -c "while true; do curl -sL http://127.0.0.1:4001/v2/stats/self
      | jq . ; sleep 1 ; done"

      '
    name: debug-etcd.service
  - command: start
    content: '[Unit]

      Description=Increase the number of connections in nf_conntrack. default is 65536


      [Service]

      Type=oneshot

      ExecStartPre=/usr/sbin/modprobe nf_conntrack

      ExecStart=/bin/sh -c "sysctl -w net.netfilter.nf_conntrack_max=262144"

      '
    name: increase-nf_conntrack-connections.service
  update:
    reboot-strategy: 'off'
write_files:
- content: 'DEIS_RELEASE=v1.12.1

    '
  path: /etc/deis-release
- content: " \e[31m* *    \e[34m*   \e[32m*****    \e[39mddddd   eeeeeee iiiiiii \
    \  ssss\n\e[31m*   *  \e[34m* *  \e[32m*   *     \e[39md   d   e    e    i   \
    \  s    s\n \e[31m* *  \e[34m***** \e[32m*****     \e[39md    d  e         i \
    \   s\n\e[32m*****  \e[31m* *    \e[34m*       \e[39md     d e         i     s\n\
    \e[32m*   * \e[31m*   *  \e[34m* *      \e[39md     d eee       i      sss\n\e\
    [32m*****  \e[31m* *  \e[34m*****     \e[39md     d e         i         s\n  \e\
    [34m*   \e[32m*****  \e[31m* *      \e[39md    d  e         i          s\n \e\
    [34m* *  \e[32m*   * \e[31m*   *     \e[39md   d   e    e    i    s    s\n\e[34m*****\
    \ \e[32m*****  \e[31m* *     \e[39mddddd   eeeeeee iiiiiii  ssss\n\n\e[39mWelcome\
    \ to Deis\t\t\tPowered by Core\e[38;5;45mO\e[38;5;206mS\e[39m\n"
  path: /etc/motd
- content: "function nse() {\n  docker exec -it $1 bash\n}\n"
  path: /etc/profile.d/nse-function.sh
  permissions: '0755'
- content: "#!/usr/bin/env bash\n# usage: get_image <component_path>\nIMAGE=`etcdctl\
    \ get $1/image 2>/dev/null`\n\n# if no image was set in etcd, we use the default\
    \ plus the release string\nif [ $? -ne 0 ]; then\n  RELEASE=`etcdctl get /deis/platform/version\
    \ 2>/dev/null`\n\n  # if no release was set in etcd, use the default provisioned\
    \ with the server\n  if [ $? -ne 0 ]; then\n    source /etc/deis-release\n   \
    \ RELEASE=$DEIS_RELEASE\n  fi\n\n  IMAGE=$1:$RELEASE\nfi\n\n# remove leading slash\n\
    echo ${IMAGE#/}\n"
  path: /run/deis/bin/get_image
  permissions: '0755'
- content: "#!/usr/bin/env bash\n\nCOMPONENTS=(builder controller database logger\
    \ logspout publisher registry router store-daemon store-gateway store-metadata\
    \ store-monitor)\nfor c in \"${COMPONENTS[@]}\"; do\n  image=`/run/deis/bin/get_image\
    \ /deis/$c`\n  docker history $image >/dev/null 2>&1 || docker pull $image\ndone\n"
  path: /run/deis/bin/preseed
  permissions: '0755'
- content: '#!/usr/bin/env bash


    echo ''--- VERSIONS ---''

    source /etc/os-release

    echo $PRETTY_NAME

    source /etc/deis-release

    echo "Deis $DEIS_RELEASE"

    etcd2 -version | head -n1

    fleet -version

    printf "\n"


    echo ''--- SYSTEM STATUS ---''

    journalctl -n 50 -u etcd --no-pager

    journalctl -n 50 -u fleet --no-pager

    printf "\n"


    echo ''--- DEIS STATUS ---''

    deisctl list

    etcdctl ls --recursive /deis

    printf "\n"

    '
  path: /opt/bin/deis-debug-logs
  permissions: '0755'
- content: 'TOOLBOX_DOCKER_IMAGE=alpine

    TOOLBOX_DOCKER_TAG=3.1

    TOOLBOX_USER=root

    '
  owner: core
  path: /home/core/.toolboxrc
- content: 'HTTP_PROXY=

    HTTPS_PROXY=

    ALL_PROXY=

    NO_PROXY=

    http_proxy=

    https_proxy=

    all_proxy=

    no_proxy=

    '
  owner: core
  path: /etc/environment_proxy
- content: '[Coredump]

    Storage=none

    '
  path: /etc/systemd/coredump.conf
- content: "#!/usr/bin/bash\nif [ \"$1\" != '--really' ]; then\n  echo \"command must\
    \ be run as: $0 --really\"\n  exit 1\nfi\n# procedure requires the store-admin\n\
    ADMIN_RUNNING=$(docker inspect --format=\"{{ .State.Running }}\" deis-store-admin)\n\
    if [ $? -eq 1 ] || [ \"$ADMIN_RUNNING\" == \"false\" ]; then\n  echo \"deis-store-admin\
    \ container is required for graceful shutdown\"\n  exit 2\nfi\nset -e -x -o pipefail\n\
    # determine osd id\nCURRENT_STATUS=$(docker exec deis-store-admin ceph health\
    \ | awk '{print $1}')\nOSD_HOSTS=($(etcdctl ls /deis/store/hosts/| awk -F'/' '{print\
    \ $5}'))\nfor HOST in \"${OSD_HOSTS[@]}\"\ndo\n  PUBLIC_IP=$(fleetctl list-machines\
    \ -fields=\"machine,ip\" -full -no-legend| grep `cat /etc/machine-id` | awk '{print\
    \ $2}')\n  if [ \"$HOST\" = \"$PUBLIC_IP\" ] ; then\n    OSD_ID=$(etcdctl get\
    \ /deis/store/osds/$PUBLIC_IP)\n    break\n  fi\ndone\n# if we own an osd and\
    \ its healthy, try to gracefully remove it\nif [ ! -z \"$OSD_ID\" ] && [[ \"$CURRENT_STATUS\"\
    \ == *\"HEALTH_OK\"* ]] && [ ${#OSD_HOSTS[@]} -gt \"3\" ]; then\n  docker exec\
    \ deis-store-admin ceph osd out $OSD_ID\n  sleep 30\n  TIMEWAITED=0\n  until [[\
    \ $(docker exec deis-store-admin ceph health) == *\"HEALTH_OK\"* ]]\n  do\n  \
    \  if [ $TIMEWAITED -gt \"1200\" ]\n    then\n      echo \"ceph graceful removal\
    \ timeout exceeded\"\n      break\n    fi\n    echo \"waiting\" && sleep 5\n \
    \   TIMEWAITED=$((TIMEWAITED+5))\n  done\n  docker stop deis-store-daemon\n  docker\
    \ exec deis-store-admin ceph osd crush remove osd.$OSD_ID\n  docker exec deis-store-admin\
    \ ceph auth del osd.$OSD_ID\n  docker exec deis-store-admin ceph osd rm $OSD_ID\n\
    \  etcdctl rm /deis/store/osds/$PUBLIC_IP\n  etcdctl rm /deis/store/hosts/$PUBLIC_IP\
    \ && sleep 10\n  # remove ceph mon\n  docker stop deis-store-monitor || true\n\
    \  docker exec deis-store-admin ceph mon remove `hostname -f` # fixme\n  docker\
    \ stop deis-store-metadata || true\nfi\n\n# removing the node from etcd\nNODE=$(etcdctl\
    \ member list | grep `cat /etc/machine-id` | cut -d ':' -f 1)\netcdctl member\
    \ remove $NODE\n"
  path: /opt/bin/graceful-shutdown.sh
  permissions: '0755'
- content: "#!/usr/bin/env bash\n# [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen\n\
    [ -n \"$1\" ] && \\\n  until curl -o /dev/null -sIf http://${1}; do \\\n    sleep\
    \ 1 && echo .;\n  done;\nexit $?\n"
  path: /opt/bin/wupiao
  permissions: '0755'
- content: "#!/usr/bin/env bash\nexport K8S_VERSION=\"v1.0.1\"\nmkdir -p /opt/bin\n\
    FILE=$1\nif [ ! -f /opt/bin/$FILE ]; then\n  curl -sSL -o /opt/bin/$FILE https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/$FILE\n\
    \  chmod +x /opt/bin/$FILE\nelse\n  # we check the version of the binary\n  INSTALLED_VERSION=$(/opt/bin/$FILE\
    \ --version)\n  MATCH=$(echo \"${INSTALLED_VERSION}\" | grep -c \"${K8S_VERSION}\"\
    )\n  if [ $MATCH -eq 0 ]; then\n    # the version is different\n    curl -sSL\
    \ -o /opt/bin/$FILE https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/$FILE\n\
    \    chmod +x /opt/bin/$FILE\n  fi\nfi\n"
  path: /opt/bin/download-k8s-binary
  permissions: '0755'
- content: "{\n    \"kind\": \"Policy\",\n    \"apiVersion\": \"v1\",\n    \"predicates\"\
    : [{\"name\": \"PodFitsPorts\"},{\"name\": \"PodFitsResources\"},{\"name\": \"\
    NoDiskConflict\"},{\"name\": \"MatchNodeSelector\"},{\"name\": \"HostName\"}],\n\
    \    \"priorities\": [{\"name\": \"LeastRequestedPriority\",\"weight\": 1},{\"\
    name\": \"BalancedResourceAllocation\",\"weight\": 1},{\"name\": \"ServiceSpreadingPriority\"\
    ,\"weight\": 2},{\"name\": \"EqualPriority\",\"weight\": 1}]\n}\n"
  path: /opt/bin/scheduler-policy.json
```

**Comment by xiang90** [comment] 2015-12-02 18:39
@kenaniah 

You need to remove the failed machines from etcd cluster and add new one back. Just restart a machine will not do the trick for you. Also the original etcd cluster is probably still running just fine. 

You should read https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration. 

And also https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#replace-a-failed-machine

**Comment by kenaniah** [comment] 2015-12-02 18:42
@xiang90 That's unfortunately not possible, as the `etcdctl member` command is what breaks at this point. Hence this bug report.

**Comment by xiang90** [comment] 2015-12-02 18:43
> That's unfortunately not possible, as the etcdctl member command is what breaks at this point. Hence this bug report.

Basically, what you really should reproduce is this:

start a 3 member cluster. kill one. etcd is not working or etcdctl cannot connect to the original etcd cluster.

I cannot reproduce myself on ec2. If you can reproduce this simple case, please report back.

**Comment by kenaniah** [comment] 2015-12-02 18:44
That's exactly what I'm reproducing and what I'm reporting :-(

**Comment by jonboulle** [comment] 2015-12-02 18:45
What's the configuration you're providing to etcdctl?

**Comment by xiang90** [comment] 2015-12-02 18:45
@kenaniah 

> The auto-scaling group will spin up a new instance to replace the one that was terminated.

This is not. Can you just spin out 3 machines and kill one of them instead of trying to replace the old one with a new one?

**Comment by nelsonenzo** [comment] 2015-12-09 20:19
I'm experiencing this exact issue as well.  It seems odd that a "Distributed reliable key-value store" can not elegantly handle losing a node :/

**Comment by xiang90** [comment] 2015-12-09 20:54
@nelsonenzo We kill nodes, restarts nodes every several seconds in our failure injection testing. We have not found any issue recently.

The issue mentioned here seems like a configuration problem. Please provide a way to reproduce your issue, then we would love to help figure out the root reason.

**Comment by gyuho** [comment] 2015-12-30 04:40
Kindly ping @kenaniah and @nelsonenzo. If this happens with etcd bug, we need a way to reproduce the bug. As Xiang linked. please **Do Not Use Public Discovery Service For Runtime Reconfiguration**:

> The public discovery service should only be used for bootstrapping a cluster. To join member into an existing cluster, you should use runtime reconfiguration API.

**Comment by xiang90** [comment] 2016-01-01 02:03
@kenaniah I am going to close this due to low activity. 

First, we cannot reproduce your problem. etcd cluster successfully recovers from failures in our test. 

Second, as @gyuho and I mentioned we guess the issue was the inappropriate usage of discovery service.

**Closed by xiang90** 2016-01-01 02:03 UTC
Labels: reviewed/needs more information

**Comment by rstacruz** [comment] 2016-05-24 09:50
has anyone found a remedy for this? I got the same issue with Deis. @kenaniah any insights?

**Comment by rstacruz** [comment] 2016-05-24 11:28
I've figured out my problem.

- Have a cluster of 3 nodes. etcd has 3 members.
- Take down one node, and replace it with another.

The result is that:

- `etcd members list` will tell you you have 2 nodes up, 1 node down.
- the new node will function correctly and can communicate to the rest of the cluster, but isn't a member.
- after some time, it can happen that the new node's etcd will completely screw up and you'll get a `client: etcd cluster is unavailable or misconfigured` error. this can happen if you, say, reboot it.

The solution is to promote the new node from a proxy node to a full-fledged member.

`systemctl cat etcd2` will tell us the ETCD config used:

```sh
$ systemctl cat etcd2
...
# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://XXX:2379"
Environment="ETCD_DATA_DIR=/media/etcd"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/XXX"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://XXX:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://XXX:2380,http://XXX:7001"
...
```

What I did was add it as a member first. This gives us new ETCD settings to add:

```sh
# In another existing node...
$ etcdctl member add helloworld http://XXX:2380
# ...where XXX is the new node's private IP
...
ETCD_NAME="helloworld"
ETCD_INITIAL_CLUSTER="..."
ETCD_INITIAL_CLUSTER_STATE="existing"
```

Now edit out the config (`20-cloudinit.conf` in my case) and:

- comment out `ETCD_DISCOVERY`
- Add these new `ETCD_*` env variables

Now restart etcd:

- `systemctl daemon-reload`
- `systemctl stop etcd2.service`
- `systemctl start etcd2.service`

...revert your changes to the config, then run `systemctl daemon-reload` again.

(I typed these out from memory, I apologize if I missed a few steps or have a few typos. Good luck.)

cc @kenaniah might be of interest to you :)
