### ISSUE TITLE
client request time out when server space usage reached 85%

### ISSUE THREAD

**Issue by lonelili** [coreos/etcd#7044] opened 2016-12-21 04:27 UTC
## Environment
 - hardware(server side)
three member, hardware are the same
CPU:Intel(R) Xeon(R) CPU L5630  @ 2.13GHz, 16 core
MEM:64GB

- software
etcd --version
etcd Version: 3.0.6
Git SHA: 9efa00d
Go Version: go1.6.3
Go OS/Arch: linux/amd64

## Backgroud
We use etcd to save the data report from monitor agent which is deployed on 60 servers. 

The agent put data to one key every 10 s, so there are many history data.

Server start with "--auto-compaction-retention=168" to save 7 days of history data, but **we don't use command "defrag" to release the storage space**.

## Phenomenon
**Server space quota is 4GB, now use 3.5GB**
 - Client error info
```
rpc error: code = 13 desc = etcdserver: invalid auth token
```
and
```
etcdserver: request timed out
```
 - Server error info
```
etcdserver: timeout of waiting Authenticate() RPC
```

In addition, i found the server disk_write increase from 200KB/s to 6MB/s.
Then i run the command "defrag" to release the space, the server  return to normal.

## Question
Is this problem caused by storage space? Or are there any other possible causes?
If it is because of the space, what is the recommended configuration and usage?

**Comment by xiang90** [comment] 2016-12-21 04:29
what is your disk?

**Comment by lonelili** [comment] 2016-12-21 04:39
DISK:Sas15K 300G x2 Raid1

**Comment by xiang90** [comment] 2016-12-21 04:41
can you get the fsync and disk commit metrics by calling the metrics API for all three members?  do you have server side log when timeout happens?

**Comment by xiang90** [comment] 2016-12-21 04:49
@lonelili 

Also please avoid RAID1 for etcd. See https://github.com/coreos/etcd/blob/master/Documentation/op-guide/hardware.md#disks

**Comment by lonelili** [comment] 2016-12-26 08:24
## Metrics
```
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 3.98248e+06
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 5.386542e+06
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 8.520103e+06
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 1.14307e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 1.1454037e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 1.1459841e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 1.1468272e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 1.148207e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 1.1497782e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 1.1509121e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 1.15143e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 1.1522074e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 1.1526292e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 1.1531985e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 1.153208e+07
etcd_disk_backend_commit_duration_seconds_sum 96434.89068414787
etcd_disk_backend_commit_duration_seconds_count 1.153208e+07


etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 4.9591728e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 4.9636788e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 4.9639625e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 4.9640254e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 4.9640518e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 4.9640546e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 4.9640556e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 4.9640557e+07
etcd_disk_wal_fsync_duration_seconds_sum 6743.907721204662
etcd_disk_wal_fsync_duration_seconds_count 4.9640557e+07
```

**I found the Authenticate method is very slow.**
```
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.0005"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.001"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.002"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.004"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.008"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.016"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.032"} 0
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.064"} 3
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.128"} 3
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.256"} 1.0674728e+07
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="0.512"} 1.6868397e+07
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="1.024"} 1.8585138e+07
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="2.048"} 1.9057494e+07
etcd_grpc_unary_requests_duration_seconds_bucket{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",le="+Inf"} 1.9506429e+07
etcd_grpc_unary_requests_duration_seconds_sum{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth"} 7.27935975046519e+06
etcd_grpc_unary_requests_duration_seconds_count{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth"} 1.9506429e+07
```

### Server Log
```
2016-12-21 00:11:31.055341 I | auth: authorized mmpaymsw, token is XEvSTmXxrJllbeqR.67541570
2016-12-21 00:11:31.055422 W | etcdserver: apply entries took too long [135.366809ms for 1 entries]
2016-12-21 00:11:31.055450 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:31.439835 I | auth: authorized mmpaymsw, token is tibukPfIMQeBRwxD.67541574
2016-12-21 00:11:31.439878 W | etcdserver: apply entries took too long [135.185238ms for 1 entries]
2016-12-21 00:11:31.439892 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:31.640073 I | auth: authorized mmpaymsw, token is rHQXmEJcxWbjoBiO.67541575
2016-12-21 00:11:31.640235 W | etcdserver: apply entries took too long [135.517882ms for 2 entries]
2016-12-21 00:11:31.640252 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.166964 I | auth: authorized mmpaymsw, token is FuxoJlXejSQEMZfa.67541579
2016-12-21 00:11:32.167000 W | etcdserver: apply entries took too long [135.42416ms for 1 entries]
2016-12-21 00:11:32.167015 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.302322 I | auth: authorized mmpaymsw, token is uKEdjvYXGXuUEmrG.67541581
2016-12-21 00:11:32.302355 W | etcdserver: apply entries took too long [135.308686ms for 1 entries]
2016-12-21 00:11:32.302364 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.437609 I | auth: authorized mmpaymsw, token is IppcKPRokOwwKpPd.67541582
2016-12-21 00:11:32.437638 W | etcdserver: apply entries took too long [135.259042ms for 1 entries]
2016-12-21 00:11:32.437647 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.608769 I | auth: authorized mmpaymsw, token is TsbidVXccwvcOxFR.67541586
2016-12-21 00:11:32.608801 W | etcdserver: apply entries took too long [135.191923ms for 1 entries]
2016-12-21 00:11:32.608813 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.744030 I | auth: authorized mmpaymsw, token is jFOREkIHPXpJnKyA.67541587
2016-12-21 00:11:32.744058 W | etcdserver: apply entries took too long [135.229739ms for 1 entries]
2016-12-21 00:11:32.744067 W | etcdserver: avoid queries with large range/delete range!
2016-12-21 00:11:32.880588 I | auth: authorized mmpaymsw, token is xvceUFwHxBIQAHnT.67541590
2016-12-21 00:11:32.880619 W | etcdserver: apply entries took too long [135.824347ms for 1 entries]
2016-12-21 00:11:32.880627 W | etcdserver: avoid queries with large range/delete range!
```

Now the error of "client time out" is still occasionally appear, about 0.5 percent.

**Comment by xiang90** [comment] 2016-12-26 08:29
> etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 1.1497782e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 1.1509121e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 1.15143e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 1.1522074e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 1.1526292e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 1.1531985e+07
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 1.153208e+07

The disk were very slow. Some fsync even took more than 8 seconds. Can you check your disk and fix the disk issue first?

You should expect Auth to take longer than 100ms, since it uses bcrypt.

**Comment by xiang90** [comment] 2016-12-26 08:30
@lonelili We fixed the warning thing in the master branch. So just ignore it.

**Comment by lonelili** [comment] 2016-12-28 08:21
Bcrypt is great! 
But, it means if you use short connection, you'll get a poor performance. Because every request will call the Auth method.

I use a method like this:
```
func EtcdSet(server IConfEtcd, key string, value string) error {

	cfg := clientv3.Config{
		Endpoints: server.GetEndpoints(),
		// set timeout per request to fail fast when the target endpoint is unavailable
		DialTimeout: time.Second * 5,
		Username:    server.GetUsername(),
		Password:    server.GetPassword(),
	}
	c, err := clientv3.New(cfg)
	if err != nil {
		return err
	}
	defer c.Close()

	_, serr := c.Put(context.Background(), key, value)
	if serr != nil {
		return serr
	} else {
		return nil
	}
}
```

Now, I abandoned this code and use long connection in my project.
The error of "client time out" is **no longer happen**,and the load glitch of single CPU is also disappeared.
I will continue to observe and feedback.

I will give you a benchmark of my cluster's disk later, to find the root cause of my issue.

**Comment by lonelili** [comment] 2016-12-28 09:56
The device is used for memcached before, the disk is not very good really.
But now we only have 60 client, request per 10s. So the max QPS may be 60/s?
These requests are too small to produce bottleneck, I think.
And, the monitor curve are all normal.

**So, any other possible causes?**

Here are some test result.
## DD
dd if=/dev/zero bs=512 count=20000000 of=/data/wTest
10240000000 bytes (10 GB) copied, 39.5723 s, 259 MB/s

## fio
Only change bsrange and rw type.
eg:
```
fio -filename=/dev/sda4  -direct=1 -iodepth 1 -thread -rw=write -ioengine=psync -bsrange=4k-1024k -size=2G -numjobs=30 -group_reporting -name=seq_4k_8m_num30 -output=/data/seq_4k_1m_num30
```
| RW type | BlockSize | Thruput | IOPS|
| ------| ------ | ------ | ------ |
| write | 4K ~ 1024K | 99231KB/s | 193 |
| randwrite | 4K ~ 1024K | 46746KB/s | 414 |
| write | 4K | 213024KB/s | 53256 |
| randwrite | 4K | 2573.6KB/s | 643 |

fio result detail(-rw=randwrite -bs=4k):
```
rand_4k_num30: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=psync, iodepth=1
fio-2.0.13
Starting 30 threads

rand_4k_num30: (groupid=0, jobs=30): err= 0: pid=20043: Wed Dec 28 15:44:59 2016
  write: io=1512.3MB, bw=2573.6KB/s, iops=643 , runt=601833msec
    clat (usec): min=46 , max=2001.6K, avg=46612.49, stdev=43794.57
     lat (usec): min=46 , max=2001.6K, avg=46613.69, stdev=43794.57
    clat percentiles (msec):
     |  1.00th=[    8],  5.00th=[   16], 10.00th=[   21], 20.00th=[   28],
     | 30.00th=[   33], 40.00th=[   38], 50.00th=[   42], 60.00th=[   46],
     | 70.00th=[   51], 80.00th=[   57], 90.00th=[   67], 95.00th=[   82],
     | 99.00th=[  343], 99.50th=[  383], 99.90th=[  424], 99.95th=[  445],
     | 99.99th=[  519]
    bw (KB/s)  : min=   16, max= 5322, per=3.41%, avg=87.77, stdev=49.40
    lat (usec) : 50=0.01%, 100=0.16%, 250=0.46%, 500=0.08%, 750=0.02%
    lat (usec) : 1000=0.01%
    lat (msec) : 2=0.01%, 4=0.03%, 10=0.98%, 20=7.63%, 50=59.85%
    lat (msec) : 100=28.01%, 250=1.64%, 500=1.12%, 750=0.01%, 2000=0.01%
    lat (msec) : >=2000=0.01%
  cpu          : usr=0.00%, sys=0.01%, ctx=311007, majf=0, minf=18446744073708280061
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=387130/d=0, short=r=0/w=0/d=0

Run status group 0 (all jobs):
  WRITE: io=1512.3MB, aggrb=2573KB/s, minb=2573KB/s, maxb=2573KB/s, mint=601833msec, maxt=601833msec

Disk stats (read/write):
  sda: ios=69/387132, merge=0/91, ticks=12/17979544, in_queue=48730264, util=100.00%
```

## Disk monitor data(report per minute, list max value in one day)
| block_out | r/s | w/s| avgqu-sz | await | svctm | %util |
| ------| ------ | ------ | ------ | ------| ------ | ------ |
| 425 |  0.1 | 44.2 | 0.03| 0.7 |  0.18 | 1 |

**Comment by xiang90** [comment] 2016-12-28 15:53
> So, any other possible causes?

Are all your problems solved now after using long connection + better disk?

**Comment by lonelili** [comment] 2016-12-29 03:55
I didn't do anything to the disk.
After using long connection, the total error decrease from 4500/day to  600/day.

The detail error stat of yesterday is:

| Error | Num |
| ------| ------ |
| etcdserver: request timed out | 517 |
| rpc error: code = 13 desc = etcdserver: request timed out, possibly due to connection lost | 52 |
| etcdserver: request timed out, possibly due to previous leader failure | 15 |

**Comment by lonelili** [comment] 2016-12-29 06:45
OK, the monitor data is in the previous comment, i didn't found any exception these days.
I'll continue to observe and analyse it.

**Comment by xiang90** [comment] 2016-12-29 06:46
@lonelili Do not use fio monitor your disk. You need to monitor it 24*7 to figure out spikes.

**Comment by lonelili** [comment] 2016-12-29 06:53
Yeah, i know. We have a monitor system monitor the disk 24*7 using /proc/diskstats.
Fio an dd benchmark is to illustrate the performance of the disk.

**Comment by xiang90** [comment] 2016-12-29 06:58
@lonelili OK. I do not know then. It appears to me that the timeout you observed were still caused by long fsync. You'd better monitor etcd's metrics and make sure there is no (or <99.99%) fsyncs/commits take more than 200ms. 8s is abnormal.

If you put etcd in a good environment, there should be no leader election or timeouts unless there is a known machine/network/disk failure.

**Comment by lonelili** [comment] 2016-12-29 07:04
OK. Got it. I'll feedback on any progress.
Thanks.

**Comment by xiang90** [comment] 2017-01-03 19:06
I am going to close this issue. Please reopen if there is any further issue related to this one.

**Closed by xiang90** 2017-01-03 19:06 UTC
Labels: area/performance
