### ISSUE TITLE
Failure of a node results in an extremely slow cluster - v2.0.11

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#3007] opened 2015-06-18 23:48 UTC
Upgraded to 2.0.11 recently for proxy fixes and started noticing this. Is this a known issue?

### To begin with its a 3 node cluster and everything works fine.
[root@tb1-02 ~]# etcdctl cluster-health
cluster is healthy
member 3d1609c2d40cd241 is healthy
member 5f1896a85808518e is healthy
member 934fd562260d4bf0 is healthy
[root@tb1-02 ~]# time etcdctl ls /
/dw
/registry

real	0m0.012s
user	0m0.009s
sys	0m0.003s

### One of the nodes is shut down here
[root@tb1-02 ~]# etcdctl cluster-health
cluster is healthy
member 3d1609c2d40cd241 is healthy
member 5f1896a85808518e is unhealthy
member 934fd562260d4bf0 is healthy
[root@tb1-02 ~]# time etcdctl ls /
/dw
/registry

real	1m0.094s
user	0m0.005s
sys	0m0.014s

**Comment by ravigadde** [comment] 2015-06-18 23:49
[root@tb1-02 ~]# etcd --version
etcd Version: 2.0.11
Git SHA: 4d04fbb
Go Version: go1.4
Go OS/Arch: linux/amd64

**Comment by xiang90** [comment] 2015-06-18 23:51
@ravigadde This is a etcdctl issue (there is a known issue for that to add timeout for etcdctl), not an etcd server issue I guess. Can you try to isolate the problem and report back?

**Comment by ravigadde** [comment] 2015-06-19 01:30
@xiang90 Is the etcdctl problem new to 2.0.11? Haven't see it before. I see the proxy has a notion of available/unavailable nodes in the quorum. So hopefully it doesn't run in to this issue.

The reason I started digging in to this is one of my test cases that uses ttl keys broke with 2.0.11. I cant reproduce that issue yet.

**Comment by xiang90** [comment] 2015-06-19 18:50
@ravigadde I am not sure. I do not think there is a new problem. I have to find a way to reproduce it, then I can dig into it more.

**Comment by xiang90** [comment] 2015-07-03 16:19
@ravigadde ping. Found anyway to reproduce this?

**Comment by philk** [comment] 2015-07-06 18:22
I think this is the same issue I've been trying to track down. We had a node failure over the weekend that caused our whole cluster to behave erratically. flannel nodes lost their subnet leases. fleet timed out causing it's units to be rescheduled elsewhere then it would return after a couple of minutes only to return later. vctl / vulcand was unable to renew TTLs on backend servers consistently enough for nodes not to drop out.

I think I have a pretty solid reproduction (though I can't get quite the same level of flakiness). We're using the master etcd cluster with proxy nodes model, so 3 etcd servers with everything else running it's own local proxy. CoreOS Stable channel (so etcd 2.0.10, fleet 10.2, flannel 0.4.0)

On one of the 3 etcd nodes to simulate a net split or sudden node termination:
```
iptables -A INPUT -p tcp --destination-port 2379 -j DROP
iptables -A INPUT -p tcp --destination-port 2380 -j DROP
iptables -A INPUT -p tcp --destination-port 4001 -j DROP
iptables -A INPUT -p tcp --destination-port 7001 -j DROP
```

Which will cause log spamming on the leader as in #2845 (apparently fixed in master, haven't tested). Within about a minute we'll receive a series of errors in the fleet logs (as well as the node dropping out of fleet long enough for it to be considered down and its units to be rescheduled).

```
ERROR engine.go:149: Unable to determine cluster engine version
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
ERROR engine.go:171: Unable to determine current lessee: timeout reached
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
INFO engine.go:79: Engine leader is a6348b67c73b4878b729e70c374d88a6
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
ERROR reconcile.go:120: Failed fetching Units from Registry: timeout reached
ERROR reconcile.go:73: Unable to determine agent's desired state: timeout reached
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
ERROR engine.go:149: Unable to determine cluster engine version
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
ERROR engine.go:149: Unable to determine cluster engine version
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
ERROR engine.go:149: Unable to determine cluster engine version
INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
```

The logs from the etcd proxy on that same fleet node look like this at the same time:

```
2015/07/06 17:31:34 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:34 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:34 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:34 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:36 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:36 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:36 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:36 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:37 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:37 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:37 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:37 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:37 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 17:31:38 proxy: marked endpoint http://10.0.53.200:2379 available
2015/07/06 17:31:38 proxy: marked endpoint http://10.0.42.196:2379 available
2015/07/06 17:31:40 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:40 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 17:31:40 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:40 proxy: marked endpoint http://10.0.53.200:2379 unavailable
2015/07/06 17:31:40 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:40 proxy: marked endpoint http://10.0.42.196:2379 unavailable
2015/07/06 17:31:40 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:41 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:41 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:41 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:41 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:45 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 17:31:45 proxy: marked endpoint http://10.0.53.200:2379 available
2015/07/06 17:31:45 proxy: marked endpoint http://10.0.42.196:2379 available
2015/07/06 17:31:46 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:46 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 17:31:46 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:46 proxy: marked endpoint http://10.0.53.200:2379 unavailable
2015/07/06 17:31:46 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:46 proxy: marked endpoint http://10.0.42.196:2379 unavailable
2015/07/06 17:31:46 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:47 proxy: failed to direct request to http://10.0.48.105:2379: dial tcp 10.0.48.105:2379: i/o timeout
2015/07/06 17:31:47 proxy: failed to direct request to http://10.0.53.200:2379: http: invalid Read on closed Body
2015/07/06 17:31:47 proxy: failed to direct request to http://10.0.42.196:2379: http: invalid Read on closed Body
2015/07/06 17:31:47 proxy: unable to get response from 3 endpoint(s)
2015/07/06 17:31:51 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 17:31:51 proxy: marked endpoint http://10.0.53.200:2379 available
2015/07/06 17:31:51 proxy: marked endpoint http://10.0.42.196:2379 available
```

The section in those logs where all nodes get marked as unavailable has been fixed in #2994 and I've tried reproducing the issue with etcd 2.0.13 for the proxy however it still stalls long enough to trigger fleet failure. The 2.0.13 logs look like this:

```
2015/07/06 18:04:42 proxy: failed to direct request to http://10.0.48.105:2379: read tcp 10.0.48.105:2379: use of closed network connection
2015/07/06 18:04:42 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 18:04:47 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 18:04:48 proxy: failed to direct request to http://10.0.48.105:2379: read tcp 10.0.48.105:2379: use of closed network connection
2015/07/06 18:04:48 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 18:04:53 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 18:04:56 proxy: failed to direct request to http://10.0.48.105:2379: net/http: request canceled while waiting for connection
2015/07/06 18:04:56 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 18:04:56 proxy: failed to direct request to http://10.0.48.105:2379: net/http: request canceled while waiting for connection
2015/07/06 18:04:56 proxy: failed to direct request to http://10.0.48.105:2379: net/http: request canceled while waiting for connection
2015/07/06 18:05:01 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 18:05:02 proxy: failed to direct request to http://10.0.48.105:2379: net/http: request canceled while waiting for connection
2015/07/06 18:05:02 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 18:05:07 proxy: marked endpoint http://10.0.48.105:2379 available
2015/07/06 18:05:08 proxy: failed to direct request to http://10.0.48.105:2379: net/http: request canceled while waiting for connection
2015/07/06 18:05:08 proxy: marked endpoint http://10.0.48.105:2379 unavailable
2015/07/06 18:05:13 proxy: marked endpoint http://10.0.48.105:2379 available
```

**Comment by OGrape** [comment] 2015-07-07 02:22
I believe I'm experiencing the same problem as you guys

~~~
Jul 07 02:09:00 develop-cluster systemd[1]: Started fleet daemon.
Jul 07 02:09:00 develop-cluster systemd[1]: Starting fleet daemon...
Jul 07 02:09:01 develop-cluster fleetd[716]: INFO fleet.go:56: Starting fleetd version 0.10.2
Jul 07 02:09:01 develop-cluster fleetd[716]: INFO fleet.go:160: No provided or default config file found - proceeding without
Jul 07 02:09:01 develop-cluster fleetd[716]: INFO server.go:152: Establishing etcd connectivity
Jul 07 02:09:01 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 07 02:09:01 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://127.0.0.1:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 07 02:09:11 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://10.1.0.20:2379/: cancelled
Jul 07 02:09:17 develop-cluster fleetd[716]: INFO client.go:298: Response 500 Internal Server Error from http://127.0.0.1:4001/ unusable
Jul 07 02:09:21 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://127.0.0.1:2379/: cancelled
Jul 07 02:09:28 develop-cluster fleetd[716]: INFO client.go:298: Response 500 Internal Server Error from http://127.0.0.1:4001/ unusable
Jul 07 02:09:32 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://127.0.0.1:2379/: cancelled
Jul 07 02:09:38 develop-cluster fleetd[716]: INFO client.go:298: Response 500 Internal Server Error from http://127.0.0.1:4001/ unusable
Jul 07 02:09:42 develop-cluster fleetd[716]: INFO client.go:292: Failed getting response from http://127.0.0.1:2379/: cancelled
~~~

~~~
develope-cluster core # etcdctl -v
etcdctl version 2.0.10
develope-cluster core # etcd2 --version
etcd version 2.0.10
develope-cluster core # fleet --version
fleetd version 0.10.2
develope-cluster core # cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=681.2.0
VERSION_ID=681.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 681.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
~~~

**Comment by yichengq** [comment] 2015-07-07 16:10
@philk @OGrape I think your issues are related to etcd proxy, so it is a different one from the original issue. Could you open a new issue for this?

@philk We haven't backported #2994 to 2.0.x release. Could you give 2.1.rc a try?

**Comment by philk** [comment] 2015-07-09 18:05
I just linked to coreos/fleet#1289 with a number of logs. All etcd nodes were behaving ok when they decided to have a master election which caused cluster wide issues. I have graphs of some of the metrics at the time:

This graph is essentially identical across the cluster:
<img width="756" alt="screen shot 2015-07-09 at 10 47 08 am" src="https://cloud.githubusercontent.com/assets/29562/8602751/e215981c-2628-11e5-93dd-3c2f7f53d0f8.png">

This graph is identical for all proxies but the etcd server nodes are completely flat (no failures)
<img width="469" alt="screen shot 2015-07-09 at 10 48 42 am" src="https://cloud.githubusercontent.com/assets/29562/8602761/eb1212a6-2628-11e5-8382-fc606e9a6ea1.png">

This graph is identical across the cluster and kind of makes me think something might have been running rogue. I'll look into logs for other services and see if something was hammering it (could have been flannel, vulcand, or fleet since those are all that talk to etcd).
<img width="487" alt="screen shot 2015-07-09 at 10 51 16 am" src="https://cloud.githubusercontent.com/assets/29562/8602766/f0dd29dc-2628-11e5-8d04-69f659a091ce.png">

**Comment by yichengq** [comment] 2015-07-09 20:12
@philk The #2994 have not been backported into 2.0 release, please wait for the 2.0.14.

**Comment by ravigadde** [comment] 2015-07-13 20:57
@xiang90 @yichengq 

The only issue I can see is with the frontend. If its a known issue, you can close this. Sorry for the late response.

One other question: When a watch returns, can EtcdIndex be lowered than Node.ModifiedIndex? I probably dont understand these indices very well, I thought EtcdIndex can never be lower than ModifiedIndex. I can open a separate issue if you think this is a bug.

**Comment by yichengq** [comment] 2015-07-13 21:10
> One other question: When a watch returns, can EtcdIndex be lowered than Node.ModifiedIndex?

Yes. The EtcdIndex returns as the header of the response at the very beginning, and watched event may return after some time. So it is possible that etcdindex is lower than node.modifiedindex. For the usage of watch, You could check this paragraph: https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change

**Closed** 2015-07-13 21:10 UTC

**Comment by ravigadde** [comment] 2015-07-14 01:14
@yichengq 

In that case, can you please update the documentation to say - "Use the higher of resp.EtcdIndex + 1 or resp.Node.ModifiedIndex + 1 to set the next watch"

**Comment by yichengq** [comment] 2015-07-14 07:43
We are improving that part doc here: https://github.com/coreos/etcd/pull/3128 . Feel free to come and comment.
