### ISSUE TITLE
grpc timed out when dialling with tls connection

### ISSUE THREAD

**Issue by AnjaniKr** [coreos/etcd#7407] opened 2017-03-02 17:28 UTC
Hi

ETCD VERSION : 
etcd Version: 3.2.0+git
Git SHA: b9bbfda
Go Version: go1.6.2
Go OS/Arch: linux/amd64

ETCDCTL VERSION : 
etcdctl version: 3.2.0+git
API version: 3.2
I am using tls on etcd v3.2 with the following command : 

/usr/bin/etcd --name infra1 --data-dir /var/lib/etcd/default --cert-file=server.pem --key-file=server-key.pem --advertise-client-urls=https://127.0.0.1:2379 --listen-client-urls=https://127.0.0.1:2379

If I try to access using client on same host using below command: 
ETCDCTL_API=3 etcdctl get --endpoints=https://localhost:2379 --cacert="ca.pem" --prefix --cert="server.pem" --key="server-key.pem" /
or 
ETCDCTL_API=3 etcdctl get --endpoints=https://localhost:2379 --cacert="ca.pem" --prefix /

**its throwing grpc timed out error**

Also openssl command works fine : 
openssl s_client -connect 127.0.0.1:2379 </dev/null 2>/dev/null | openssl x509 -outform der | sha256sum | awk '{ print $1 }'
>fetches proper sha256 value

Following is etcd server log:
2017-03-02 07:59:04.709234 I | etcdmain: Git SHA: b9bbfda
2017-03-02 07:59:04.709250 I | etcdmain: Go Version: go1.6.2
2017-03-02 07:59:04.709260 I | etcdmain: Go OS/Arch: linux/amd64
2017-03-02 07:59:04.709274 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-03-02 07:59:04.709330 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-03-02 07:59:04.709347 I | etcdmain: advertising using detected default host "x.x.x.x"
2017-03-02 07:59:04.709631 I | embed: listening for peers on http://localhost:2380
2017-03-02 07:59:04.709675 I | embed: listening for client requests on 127.0.0.1:2379
2017-03-02 07:59:04.711007 I | etcdserver: name = infra1
2017-03-02 07:59:04.711033 I | etcdserver: data dir = /var/lib/etcd/default
2017-03-02 07:59:04.711042 I | etcdserver: member dir = /var/lib/etcd/default/member
2017-03-02 07:59:04.711050 I | etcdserver: heartbeat = 100ms
2017-03-02 07:59:04.711058 I | etcdserver: election = 1000ms
2017-03-02 07:59:04.711065 I | etcdserver: snapshot count = 100000
2017-03-02 07:59:04.711077 I | etcdserver: advertise client URLs = https://localhost:2379
2017-03-02 07:59:04.715899 I | etcdserver: restarting member 6716dda5fbdaac17 in cluster d799484033cea8a2 at commit index 75
2017-03-02 07:59:04.715982 I | raft: 6716dda5fbdaac17 became follower at term 23
2017-03-02 07:59:04.716009 I | raft: newRaft 6716dda5fbdaac17 [peers: [], term: 23, commit: 75, applied: 0, lastindex: 75, lastterm: 23]
2017-03-02 07:59:04.729170 I | etcdserver: starting server... [version: 3.2.0+git, cluster version: to_be_decided]
2017-03-02 07:59:04.729224 I | embed: ClientTLS: cert = server.pem, key = server-key.pem, ca = , trusted-ca = , client-cert-auth = false
2017-03-02 07:59:04.731878 I | etcdserver/membership: added member 6716dda5fbdaac17 [http://10.1.69.144:2380 http://10.1.69.144:7001] to cluster d799484033cea8a2
2017-03-02 07:59:04.731977 N | etcdserver/membership: set the initial cluster version to 3.2
2017-03-02 07:59:04.732020 I | etcdserver/api: enabled capabilities for version 3.2
2017-03-02 07:59:05.716411 I | raft: 6716dda5fbdaac17 is starting a new election at term 23
2017-03-02 07:59:05.716455 I | raft: 6716dda5fbdaac17 became candidate at term 24
2017-03-02 07:59:05.716476 I | raft: 6716dda5fbdaac17 received MsgVoteResp from 6716dda5fbdaac17 at term 24
2017-03-02 07:59:05.716494 I | raft: 6716dda5fbdaac17 became leader at term 24
2017-03-02 07:59:05.716508 I | raft: raft.node: 6716dda5fbdaac17 elected leader 6716dda5fbdaac17 at term 24
2017-03-02 07:59:05.717608 I | etcdserver: published {Name:infra1 ClientURLs:[https://localhost:2379]} to cluster d799484033cea8a2
2017-03-02 07:59:05.717814 I | embed: ready to serve client requests
2017-03-02 07:59:05.717843 E | etcdmain: forgot to set Type=notify in systemd service file?
2017-03-02 07:59:05.718197 I | embed: serving client requests on 127.0.0.1:2379

**Comment by fanminshi** [comment] 2017-03-02 18:30
taking look

**Comment by fanminshi** [comment] 2017-03-02 19:17
etcd on mac os works fine. Let me try it on linux.

setup
```
# build etcd and etcdctl using b9bbfda
etcdmain: etcd Version: 3.2.0+git
etcdmain: Git SHA: b9bbfda
etcdmain: Go Version: go1.6.2
etcdmain: Go OS/Arch: darwin/amd64
```

Start etcd
```
bin/etcd --name my-etcd-1 \
    --listen-client-urls https://127.0.0.1:2379 \
    --advertise-client-urls https://127.0.0.1:2379 \
    --cert-file ~/certs/my-etcd-1.pem \
    --key-file ~/certs/my-etcd-1-key.pem \

2017-03-02 11:14:50.613132 I | etcdmain: etcd Version: 3.2.0+git
2017-03-02 11:14:50.613223 I | etcdmain: Git SHA: b9bbfda
2017-03-02 11:14:50.613226 I | etcdmain: Go Version: go1.6.2
2017-03-02 11:14:50.613229 I | etcdmain: Go OS/Arch: darwin/amd64
2017-03-02 11:14:50.613235 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2017-03-02 11:14:50.613243 W | etcdmain: no data-dir provided, using default data-dir ./my-etcd-1.etcd
2017-03-02 11:14:50.613260 N | etcdmain: failed to detect default host, advertise falling back to "localhost" (default host not supported on darwin_amd64)
2017-03-02 11:14:50.613512 I | embed: listening for peers on http://localhost:2380
2017-03-02 11:14:50.613561 I | embed: listening for client requests on 127.0.0.1:2379
2017-03-02 11:14:50.615990 I | etcdserver: name = my-etcd-1
2017-03-02 11:14:50.616000 I | etcdserver: data dir = my-etcd-1.etcd
2017-03-02 11:14:50.616004 I | etcdserver: member dir = my-etcd-1.etcd/member
2017-03-02 11:14:50.616008 I | etcdserver: heartbeat = 100ms
2017-03-02 11:14:50.616011 I | etcdserver: election = 1000ms
2017-03-02 11:14:50.616013 I | etcdserver: snapshot count = 100000
2017-03-02 11:14:50.616018 I | etcdserver: advertise client URLs = https://localhost:2379
2017-03-02 11:14:50.616023 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2017-03-02 11:14:50.616030 I | etcdserver: initial cluster = my-etcd-1=http://localhost:2380
2017-03-02 11:14:50.684940 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2017-03-02 11:14:50.685006 I | raft: 8e9e05c52164694d became follower at term 0
2017-03-02 11:14:50.685033 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-03-02 11:14:50.685041 I | raft: 8e9e05c52164694d became follower at term 1
2017-03-02 11:14:50.693556 I | etcdserver: starting server... [version: 3.2.0+git, cluster version: to_be_decided]
2017-03-02 11:14:50.693600 I | embed: ClientTLS: cert = /Users/fanminshi/certs/my-etcd-1.pem, key = /Users/fanminshi/certs/my-etcd-1-key.pem, ca = , trusted-ca = , client-cert-auth = false
2017-03-02 11:14:50.693664 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
2017-03-02 11:14:50.694109 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2017-03-02 11:14:51.187298 I | raft: 8e9e05c52164694d is starting a new election at term 1
2017-03-02 11:14:51.187341 I | raft: 8e9e05c52164694d became candidate at term 2
2017-03-02 11:14:51.187365 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2017-03-02 11:14:51.187382 I | raft: 8e9e05c52164694d became leader at term 2
2017-03-02 11:14:51.187397 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2017-03-02 11:14:51.187832 I | etcdserver: published {Name:my-etcd-1 ClientURLs:[https://localhost:2379]} to cluster cdf818194e3a8c32
2017-03-02 11:14:51.187862 I | embed: ready to serve client requests
2017-03-02 11:14:51.187885 I | etcdserver: setting up the initial cluster version to 3.2
2017-03-02 11:14:51.188410 I | embed: serving client requests on 127.0.0.1:2379
2017-03-02 11:14:51.197575 N | etcdserver/membership: set the initial cluster version to 3.2
2017-03-02 11:14:51.197617 I | etcdserver/api: enabled capabilities for version 3.2
```

test put and get
```
$ ETCDCTL_API=3 bin/etcdctl \
>     --endpoints https://localhost:2379  \
>     --cacert ~/certs/etcd-root-ca.pem \
>     --cert ~/certs/my-etcd-1.pem \
>     --key ~/certs/my-etcd-1-key.pem \
>     put foo bar
OK

fanmins-MacBook-Pro:etcd fanminshi$ ETCDCTL_API=3 bin/etcdctl \
>     --endpoints https://localhost:2379  \
>     --cacert ~/certs/etcd-root-ca.pem \
>     --cert ~/certs/my-etcd-1.pem \
>     --key ~/certs/my-etcd-1-key.pem \
>     get foo
foo
bar
```

**Comment by fanminshi** [comment] 2017-03-02 19:42
etcd works fine on linux too.

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
```

```
$ bin/etcd --name my-etcd-1 \
>     --listen-client-urls https://127.0.0.1:2379 \
>     --advertise-client-urls https://127.0.0.1:2379 \
>     --cert-file ~/certs/my-etcd-1.pem \
>     --key-file ~/certs/my-etcd-1-key.pem \
>
2017-03-02 19:38:15.795687 I | etcdmain: etcd Version: 3.2.0+git
2017-03-02 19:38:15.795730 I | etcdmain: Git SHA: b9bbfda
2017-03-02 19:38:15.795787 I | etcdmain: Go Version: go1.6.2
2017-03-02 19:38:15.795793 I | etcdmain: Go OS/Arch: linux/amd64
2017-03-02 19:38:15.795799 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2017-03-02 19:38:15.795849 W | etcdmain: no data-dir provided, using default data-dir ./my-etcd-1.etcd
2017-03-02 19:38:15.795886 I | etcdmain: advertising using detected default host "10.240.0.26"
2017-03-02 19:38:15.796018 I | embed: listening for peers on http://localhost:2380
2017-03-02 19:38:15.796050 I | embed: listening for client requests on 127.0.0.1:2379
2017-03-02 19:38:15.799633 I | etcdserver: name = my-etcd-1
2017-03-02 19:38:15.799648 I | etcdserver: data dir = my-etcd-1.etcd
2017-03-02 19:38:15.799662 I | etcdserver: member dir = my-etcd-1.etcd/member
2017-03-02 19:38:15.799668 I | etcdserver: heartbeat = 100ms
2017-03-02 19:38:15.799674 I | etcdserver: election = 1000ms
2017-03-02 19:38:15.799679 I | etcdserver: snapshot count = 100000
2017-03-02 19:38:15.799688 I | etcdserver: advertise client URLs = https://localhost:2379
2017-03-02 19:38:15.799697 I | etcdserver: initial advertise peer URLs = http://10.240.0.26:2380
2017-03-02 19:38:15.799709 I | etcdserver: initial cluster = my-etcd-1=http://10.240.0.26:2380
2017-03-02 19:38:15.803532 I | etcdserver: starting member f7dd2087e0d4ba2a in cluster 75a8fca6388a2173
2017-03-02 19:38:15.803562 I | raft: f7dd2087e0d4ba2a became follower at term 0
2017-03-02 19:38:15.803596 I | raft: newRaft f7dd2087e0d4ba2a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-03-02 19:38:15.803607 I | raft: f7dd2087e0d4ba2a became follower at term 1
2017-03-02 19:38:15.815679 I | etcdserver: starting server... [version: 3.2.0+git, cluster version: to_be_decided]
2017-03-02 19:38:15.815727 I | embed: ClientTLS: cert = /home/fanminshi/certs/my-etcd-1.pem, key = /home/fanminshi/certs/my-etcd-1-key.pem, ca = , trusted-ca = , client-cert-auth = false
2017-03-02 19:38:15.816488 I | etcdserver/membership: added member f7dd2087e0d4ba2a [http://10.240.0.26:2380] to cluster 75a8fca6388a2173
2017-03-02 19:38:16.503894 I | raft: f7dd2087e0d4ba2a is starting a new election at term 1
2017-03-02 19:38:16.503942 I | raft: f7dd2087e0d4ba2a became candidate at term 2
2017-03-02 19:38:16.503956 I | raft: f7dd2087e0d4ba2a received MsgVoteResp from f7dd2087e0d4ba2a at term 2
2017-03-02 19:38:16.503981 I | raft: f7dd2087e0d4ba2a became leader at term 2
2017-03-02 19:38:16.503994 I | raft: raft.node: f7dd2087e0d4ba2a elected leader f7dd2087e0d4ba2a at term 2
2017-03-02 19:38:16.504442 I | etcdserver: published {Name:my-etcd-1 ClientURLs:[https://localhost:2379]} to cluster 75a8fca6388a2173
2017-03-02 19:38:16.504463 I | embed: ready to serve client requests
2017-03-02 19:38:16.504713 I | embed: serving client requests on 127.0.0.1:2379
2017-03-02 19:38:16.504753 E | etcdmain: forgot to set Type=notify in systemd service file?
2017-03-02 19:38:16.504788 I | etcdserver: setting up the initial cluster version to 3.2
2017-03-02 19:38:16.505171 N | etcdserver/membership: set the initial cluster version to 3.2
2017-03-02 19:38:16.505216 I | etcdserver/api: enabled capabilities for version 3.2

# separate window

$ ETCDCTL_API=3 bin/etcdctl \
>     --endpoints https://localhost:2379  \
>     --cacert ~/certs/etcd-root-ca.pem \
>     --cert ~/certs/my-etcd-1.pem \
>     --key ~/certs/my-etcd-1-key.pem \
>     put foo bar
OK

$ ETCDCTL_API=3 bin/etcdctl \
>     --endpoints https://localhost:2379  \
>     --cacert ~/certs/etcd-root-ca.pem \
>     --cert ~/certs/my-etcd-1.pem \
>     --key ~/certs/my-etcd-1-key.pem \
>     get foo
foo
bar
```

**Comment by fanminshi** [comment] 2017-03-02 19:47
@AnjaniKr I couldn't reproduce the issue. Could you try again to make sure that the certs are correctly generated? I followed instruction from  http://play.etcd.io/install to generate certs and it worked for me.

**Comment by xiang90** [comment] 2017-03-02 19:49
@AnjaniKr Actually can you try to compile etcd 3.2 with go 1.7+. We drop the support of 1.6. It should solve your issue. So closing this issue.

**Closed by xiang90** 2017-03-02 19:49 UTC
