### ISSUE TITLE
etcdhttp: unexpected error: etcdserver: request timed out

### ISSUE THREAD

**Issue by wptad** [coreos/etcd#3490] opened 2015-09-11 03:12 UTC
Every several minutes, it will change leader and vote again, which cause all dependences cannot work for several seconds.

* OS info: 

```
NAME=CoreOS
ID=coreos
VERSION=723.3.0
VERSION_ID=723.3.0
BUILD_ID=
PRETTY_NAME="CoreOS 723.3.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

* etcd2 logs: 

```
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [term: 41955] ignored a MsgVote message with lower term from 1cb29d14abb33119 [term: 41954]
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 is starting a new election at term 41955
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 became candidate at term 41956
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 received vote from 172a33b2ad927564 at term 41956
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [logterm: 41953, index: 583600805] sent vote request to 1cb29d14abb33119 at term 41956
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [logterm: 41953, index: 583600805] sent vote request to e27b4c386ba90314 at term 41956
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [term: 41956] ignored a MsgApp message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [term: 41956] ignored a MsgHeartbeat message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 raft: 172a33b2ad927564 [term: 41956] ignored a MsgApp message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:19 central-2-1 etcd2[26376]: 2015/09/11 10:32:19 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 raft: 172a33b2ad927564 [term: 41956] ignored a MsgHeartbeat message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 raft: 172a33b2ad927564 [term: 41956] ignored a MsgApp message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 raft: 172a33b2ad927564 [term: 41956] ignored a MsgHeartbeat message with lower term from e27b4c386ba90314 [term: 41955]
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:20 central-2-1 etcd2[26376]: 2015/09/11 10:32:20 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [term: 41956] received a MsgVote message with higher term from 1cb29d14abb33119 [term: 41957]
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 became follower at term 41957
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600805, vote: 0] voted for 1cb29d14abb33119 [logterm: 41955, index: 583600739] at term 41957
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600739] rejected msgApp [logterm: 41955, index: 583600739] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft.node: 172a33b2ad927564 elected leader 1cb29d14abb33119 at term 41957
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600738] rejected msgApp [logterm: 41955, index: 583600738] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600737] rejected msgApp [logterm: 41955, index: 583600737] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600738] rejected msgApp [logterm: 41955, index: 583600738] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600736] rejected msgApp [logterm: 41955, index: 583600736] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600735] rejected msgApp [logterm: 41955, index: 583600735] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600734] rejected msgApp [logterm: 41955, index: 583600734] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600733] rejected msgApp [logterm: 41955, index: 583600733] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raft: 172a33b2ad927564 [logterm: 41953, index: 583600732] rejected msgApp [logterm: 41955, index: 583600732] from 1cb29d14abb33119
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raftlog: found conflict at index 583600732 [existing term: 41953, conflicting term: 41955]
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 raftlog: replace the unstable entries from index 583600732
Sep 11 10:32:24 central-2-1 etcd2[26376]: 2015/09/11 10:32:24 rafthttp: starting client stream to 1cb29d14abb33119 at term 41957
Sep 11 10:32:25 central-2-1 etcd2[26376]: 2015/09/11 10:32:25 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:32:52 central-2-1 etcd2[26376]: 2015/09/11 10:32:52 etcdserver: start to snapshot (applied: 583604612, lastsnap: 583594291)
Sep 11 10:32:52 central-2-1 etcd2[26376]: 2015/09/11 10:32:52 etcdserver: compacted log at index 583604612
Sep 11 10:32:52 central-2-1 etcd2[26376]: 2015/09/11 10:32:52 wal: segmented wal file /var/lib/etcd2/member/wal/000000000000e32e-0000000022c9198d.wal is created
Sep 11 10:32:52 central-2-1 etcd2[26376]: 2015/09/11 10:32:52 etcdserver: saved snapshot at index 583604612
Sep 11 10:33:05 central-2-1 etcd2[26376]: 2015/09/11 10:33:05 filePurge: successfully removed file /var/lib/etcd2/member/snap/000000000000a3e0-0000000022c853e5.snap
Sep 11 10:33:05 central-2-1 etcd2[26376]: 2015/09/11 10:33:05 filePurge: successfully removed file /var/lib/etcd2/member/wal/000000000000e329-0000000022c853f9.wal
Sep 11 10:34:23 central-2-1 etcd2[26376]: 2015/09/11 10:34:23 etcdserver: start to snapshot (applied: 583614670, lastsnap: 583604612)
Sep 11 10:34:23 central-2-1 etcd2[26376]: 2015/09/11 10:34:23 etcdserver: compacted log at index 583614670
Sep 11 10:34:23 central-2-1 etcd2[26376]: 2015/09/11 10:34:23 wal: segmented wal file /var/lib/etcd2/member/wal/000000000000e32f-0000000022c940d4.wal is created
Sep 11 10:34:23 central-2-1 etcd2[26376]: 2015/09/11 10:34:23 etcdserver: saved snapshot at index 583614670
Sep 11 10:34:35 central-2-1 etcd2[26376]: 2015/09/11 10:34:35 filePurge: successfully removed file /var/lib/etcd2/member/snap/000000000000a3e0-0000000022c87b6f.snap
Sep 11 10:34:35 central-2-1 etcd2[26376]: 2015/09/11 10:34:35 filePurge: successfully removed file /var/lib/etcd2/member/wal/000000000000e32a-0000000022c87b71.wal
Sep 11 10:34:39 central-2-1 etcd2[26376]: 2015/09/11 10:34:39 sender: error posting to 1cb29d14abb33119: dial tcp 10.12.1.29:2380: i/o timeout
Sep 11 10:34:39 central-2-1 etcd2[26376]: 2015/09/11 10:34:39 sender: the connection with 1cb29d14abb33119 became inactive
Sep 11 10:34:40 central-2-1 etcd2[26376]: 2015/09/11 10:34:40 sender: the connection with 1cb29d14abb33119 became active
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out
Sep 11 10:34:44 central-2-1 etcd2[26376]: 2015/09/11 10:34:44 etcdhttp: unexpected error: etcdserver: request timed out

```

* health info

```
etcdctl cluster-health
cluster is healthy
member 172a33b2ad927564 is healthy
member 1cb29d14abb33119 is healthy
member e27b4c386ba90314 is healthy
```

**Comment by xiang90** [comment] 2015-09-11 03:17
@wptad etcd 2.0.x has some network issue under highload. I would suggest you to upgrade it to etcd 2.1 and give etcd more CPUs.

**Comment by xiang90** [comment] 2015-09-11 03:19
To give it more CPUs, see https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#maximum-os-threads.

**Comment by xiang90** [comment] 2015-09-14 17:00
@wptad Can we close this issue?

After talked with @wptad offline and did some analysis together, we found the root cause is that etcd was overload.

**Comment by wptad** [comment] 2015-09-14 17:18
@xiang90 thanks for your help :)

**Closed** 2015-09-14 17:18 UTC
