### ISSUE TITLE
Suspicious I/O timeouts

### ISSUE THREAD

**Issue by ef4** [coreos/etcd#2338] opened 2015-02-18 18:50 UTC
I'm seeing frequent log lines like:

     2015/02/18 16:17:42 sender: error posting to 5a06d97868c04ccf: read tcp 104.236.206.61:2380: i/o timeout 

Is this timeout tunable?

**Comment by ef4** [comment] 2015-02-18 22:46
I tracked this down in the source, both the read and write timeouts are hard-coded to five seconds:

https://github.com/coreos/etcd/blob/88994f9ec8dfb5f7945a7926d1f9ee359dddb5d7/rafthttp/peer.go#L43-L44

Which seems reasonably generous. I'm not sure what's pushing my latency higher than that, it seems suspicious. I have three nodes on a local network, though they are VPSs that may have highly variable disk latency.

**Comment by rrati** [comment] 2015-02-20 19:15
We are seeing the same kind of issue.  We have a 3 node cluster running, and at idle on the peers we are regularly seeing

Feb 20 19:02:04 <peer_hostname> etcd[47582]: 2015/02/20 19:02:04 sender: error posting to c2c815787318259b: read tcp <leader_ip>:7001: i/o timeout

and

Feb 20 19:00:58 <peer_hostname> etcd[47582]: 2015/02/20 19:00:58 sender: error posting to c2c815787318259b: read tcp <leader_ip>:7001: connection reset by peer

And once even

Feb 20 18:53:37 <peer_hostname> etcd[30809]: 2015/02/20 18:53:37 sender: error posting to c2c815787318259b: EOF

**Comment by timothysc** [comment] 2015-02-20 19:16
Also seeing this same issue.

**Comment by xiang90** [comment] 2015-02-20 19:42
@timothysc @rrati The i/o timeout is 5 second. And we do not see a need to change it currently. If  the latency is larger than 5 seconds, raft would be the first thing to start fail.

**Comment by timothysc** [comment] 2015-02-20 19:56
@xiang90 this is on an unloaded setup.

**Comment by ef4** [comment] 2015-02-20 20:18
@xiang90 I think the real issue here is not that we need higher timeouts, it's that it's surprising that timeouts are being hit. I can't find any explanation for where the latency is coming from, and if others are seeing it too there may be a bug in etcd that's causing these connections to stall and timeout.

**Comment by timothysc** [comment] 2015-02-20 20:42
@ef4 - exactly!

**Comment by xiang90** [comment] 2015-02-20 21:19
@ef4 @timothysc 
Yes. I am just wanting to make sure you do not want a tunable timeout. 

We are redoing the related code at https://github.com/coreos/etcd/pull/2323/. 
We will have metrics for recoding, so we can have a better idea of what exactly is going on.

**Comment by kelseyhightower** [comment] 2015-02-27 15:54
@xiang90 I think we can attempt to improve the error message a bit so we have a little context into what is going on. Is this error message related to raft?

**Comment by xiang90** [comment] 2015-02-27 16:02
@kelseyhightower 

The error msg in this issue is generated by go's http standard library. i/o might be just slow for a moment  or raft is slow which might indirectly cause the timeout. 

We do not have a better way to tell which is the root problem at the moment. 

In 2.1.0 we have recored the time spending on i/o and raft separately. So hopefully, we can have a better answer for this issue.

Also we plan to do level logging in the future. Actually this is more like a debugging output.

**Comment by xiang90** [comment] 2015-02-27 16:07
@rrati 


I am pretty sure this is not caused by etcd. This indicates a problem at the link layer most probably.
```
2015/02/20 19:00:58 sender: error posting to c2c815787318259b: read tcp :7001: connection reset by peer
```

**Comment by ef4** [comment] 2015-02-27 21:02
@xiang90 that doesn't follow. That reset message just means the other etcd has closed the socket -- probably in response to the read or write timeout mentioned in the other log lines.

**Comment by timothysc** [comment] 2015-02-28 00:46
@xiang90 I agree with @ef4, this is not a link-layer issue.

**Comment by xiang90** [comment] 2015-03-02 22:48
@ef4 @timothysc By link-layer, I mean the layer under etcd. We have found the root cause after looking into it. As #2323 has merged, we will fix it shortly.

**Comment by kelseyhightower** [comment] 2015-03-03 14:31
@timothysc I've just merged a fixed for this issue, can you please test this on master?

**Comment by kelseyhightower** [comment] 2015-03-03 14:31
@ef4 ^

**Comment by timothysc** [comment] 2015-03-03 15:23
@kelseyhightower we've updated and ran for about an hour with no sign of the timeouts.

**Comment by kelseyhightower** [comment] 2015-03-03 15:26
@timothysc Awesome.

**Comment by kelseyhightower** [comment] 2015-03-03 15:26
I'm going to close this one out. Please feel free to reopen if required.

**Closed by kelseyhightower** 2015-03-03 15:26 UTC

**Comment by cdwertmann** [comment] 2015-06-25 00:35
I had a lot of problems with timeouts in etcd2 until I removed the QoS policy on the Openstack Cinder backend. I was limiting write IOPS, and etcd2 does not like that. Hope this helps anyone with a similar issue.
