### ISSUE TITLE
clientv3: client.Close() blocks forever

### ISSUE THREAD

**Issue by HeavyHorst** [coreos/etcd#6823] opened 2016-11-09 15:03 UTC
If i'm running the following example code and then quit etcd while it is running the cli.Close() will block forever if i try to quit the example.

```go
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/coreos/etcd/clientv3"
)

func main() {
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, syscall.SIGINT, syscall.SIGTERM)

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})

	if err != nil {
		panic(err)
	}

	defer cli.Close()

	rch := cli.Watch(context.Background(), "/", clientv3.WithPrefix())
	for {
		select {
		case s := <-signalChan:
			fmt.Println(fmt.Sprintf("Captured %v. Exiting...", s))
			return
		case wresp := <-rch:
			fmt.Println(wresp)
		}
	}

}
```

**Comment by heyitsanthony** [comment] 2016-11-09 17:57
Confirmed on master.

**Comment by xiang90** [comment] 2016-11-11 01:21
@heyitsanthony How did you reproduce it? I cannot reproduce locally on master.

I build the example code. run etcd, run example code, sleep 5 seconds, kill etcd, kill example.

**Comment by xiang90** [comment] 2016-11-11 01:22
I thought this is fixed by https://github.com/coreos/etcd/commit/510676fea9118f6baf8f0fa74ee1467ffe488df8

**Comment by xiang90** [comment] 2016-11-11 01:23
@gyuho  can you also give this a try?

**Comment by gyuho** [comment] 2016-11-11 01:26
Sure.

**Comment by heyitsanthony** [comment] 2016-11-11 01:27
@xiang90 yeah, seems to work now. Maybe my branch was stale when I tried it yesterday.

**Comment by xiang90** [comment] 2016-11-11 02:13
@heyitsanthony OK. I am closing this.

@HeavyHorst @gyuho Let me know if this is still an issue on the master. We can re-open.

**Closed by xiang90** 2016-11-11 02:13 UTC
Labels: kind/bug

**Comment by gyuho** [comment] 2016-11-11 02:17
@heyitsanthony @xiang90 Yeah works for me

```
go run a.go
^CCaptured interrupt. Exiting...
```
