### ISSUE TITLE
raftlog violates its invariant

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2808] opened 2015-05-11 14:55 UTC
The out-of-date follower is doing its best to catch up the leader(recover snapshot and hopefully the recovery is fast enough), here is the log:

```
2015/05/11 02:03:10 etcdraft: applied incoming snapshot at index 346558870
2015/05/11 02:03:11 etcdserver: publish error: etcdserver: request timed out
gc38(2): 10989+9+121620+10 us, 278 -> 611 MB, 2910650 (48510093-45599443) objects, 254 goroutines, 30801/20346/0 sweeps, 2(237) handoff, 7(302) steal, 39/12/3 yields
2015/05/11 02:03:11 etcdhttp: unexpected error: etcdserver: request timed out
2015/05/11 02:03:11 etcdhttp: unexpected error: etcdserver: request timed out
2015/05/11 02:03:11 INFO: raft: 49d1351238d0e541 [commit: 346565099, lastindex: 346565099, lastterm: 18962] starts to restore snapshot [index: 346569038, term: 18962]
2015/05/11 02:03:11 INFO: raftlog: log [committed=346558871, applied=346565099, unstable.offset=346555053, len(unstable.Entries)=6229] starts to restore snapshot [index: 346569038, term: 18962]
2015/05/11 02:03:11 INFO: raft: 49d1351238d0e541 restored progress of 217e5298f6dfdb33 [next = 346569039, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2015/05/11 02:03:11 INFO: raft: 49d1351238d0e541 restored progress of 49d1351238d0e541 [next = 346569039, match = 346569038, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2015/05/11 02:03:11 INFO: raft: 49d1351238d0e541 restored progress of 7e1d7e3cd441ab75 [next = 346569039, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2015/05/11 02:03:11 INFO: raft: 49d1351238d0e541 [commit: 346565099] restored snapshot [index: 346569038, term: 18962]
```

The log violates the invariant we list:
```
 :   // committed is the highest log position that is known to be in
 :   // stable storage on a quorum of nodes.
 :   // Invariant: committed < unstable
 :   committed uint64
 :   // applied is the highest log position that the application has
 :   // been instructed to apply to its state machine.
 :   // Invariant: applied <= committed
 :   applied uint64
```

**Comment by xiang90** [comment] 2015-05-30 00:03
@yichengq Can you try to reproduce it? I looked through the current raft code, and failed to find the bug by looking at code. :(

**Comment by xiang90** [comment] 2015-05-30 00:14
@yichengq I think it might be caused by https://github.com/coreos/etcd/commit/6b7891c643a1c429b26ae477c67dd29cb3665707

**Comment by xiang90** [comment] 2015-05-30 00:16
@yichengq confirmed it is fixed by the commit i mentioned.

**Closed by xiang90** 2015-05-30 00:16 UTC
