### ISSUE TITLE
Etcd cluster logs about lost leader and takes several seconds to recover

### ISSUE THREAD

**Issue by plwhite** [coreos/etcd#3969] opened 2015-12-08 11:25 UTC
I'm seeing the following error in some but not all of a sequence of load test runs against etcd, and I'd appreciate some pointers as to what might be going on here.

In a typical run, I'm running 7 etcd nodes in a cluster, with 500 clients, each using an etcd proxy. All etcd proxy instances are etcd 2.0.11, but the cluster itself is running 2.2.2. There's a fair amount of read and write load - around 1000 modifications per second, and all 500 clients are watching - but the database size isn't huge, probably a few tens to hundreds of MB. The etcd nodes are very overspecced; using multiple cores of CPU, but less than 50% of the server's cores in each case.

On three occasions during a test run lasting about three minutes, I saw the following set of events. All 7 cluster nodes hit what is apparently the same sequence of logs at the same time. Note that I have run this identical test many times, and seen a similar problem once and clean runs the other times. I have further logs if that would help.

```
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb [term: 2] received a MsgVote message with higher term from ca94987804e7c7a9 [term: 3]
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb became follower at term 3
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb [logterm: 2, index: 134060, vote: 0] voted for ca94987804e7c7a9 [logterm: 2, index: 134060] at term 3
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: raft.node: 252758ea54526bcb lost leader 56c0e9402fe92afd at term 3
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: raft.node: 252758ea54526bcb elected leader ca94987804e7c7a9 at term 3
Dec 07 14:45:29 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb [term: 3] ignored a MsgApp message with lower term from 56c0e9402fe92afd [term: 2]
```

The last log is repeated over and over for about six seconds, after which it turns into this.

```
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb [term: 3] ignored a MsgApp message with lower term from 56c0e9402fe92afd [term: 2]
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:29 raft: 252758ea54526bcb [term: 3] ignored a MsgApp message with lower term from 56c0e9402fe92afd [term: 2]
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:34 etcdhttp: got unexpected response error (etcdserver: request timed out)
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:34 etcdhttp: got unexpected response error (etcdserver: request timed out)
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:34 etcdhttp: got unexpected response error (etcdserver: request timed out)
Dec 07 14:45:36 plw-etcd-06.c.unique-caldron-775.internal etcd2[852]: 2015/12/7 14:45:34 etcdhttp: got unexpected response error (etcdserver: request timed out)
```

Client requests outstanding on the proxy return an `EtcdException`, which I assume just means that the cluster went into a bad state and came back from under the feet of the proxy.

**Comment by xiang90** [comment] 2015-12-08 15:24
> probably a few tens to hundreds of MB

You have to keep db size less than 100MB for etcd2 when you have a lot of small keys. See https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md#data-size-threshold

**Comment by plwhite** [comment] 2015-12-08 16:37
Interesting - thanks. I'd somehow missed this reference. I'll dig around and get a better idea for how much data we actually have in etcd to see if my estimate was right, and if that might be the problem.

**Comment by xiang90** [comment] 2015-12-08 16:59
@plwhite Thanks!

**Comment by plwhite** [comment] 2015-12-08 17:07
@xiang90 Clarifying your last comment, do you think the issue might just be that etcd isn't keeping up because it's run out of resources of some sort?

I think RAM is likely not to be the issue, since we peak at somewhere short of 100K keys by my calculation (I need to run a test and actually check the number to make sure). etcd was using around 1GB virtual, 300MB resident at the point things went wrong, and the servers have 60GB of RAM. I'm rather concerned that we are at 80% disk utilisation, which might be an issue though - I'll have investigate further to see if we are doing something silly there.

**Comment by xiang90** [comment] 2015-12-08 17:10
@plwhite When you have a large amount of data in etcd, each raft log compaction requires writing the entire data set to disk. That costs a lot of resources. We are working on incremental snapshotting to solve it.

**Comment by xiang90** [comment] 2015-12-08 17:11
@plwhite 

> around 1000 modifications per second

Are these writes triggering ALL watchers?

**Comment by plwhite** [comment] 2015-12-08 17:22
We have 500 watchers each of which is triggering on about a third of the changes (same third each time, i.e. they all watch the same subtree). Each watcher is behind its own proxy. Seems like we are hitting etcd about as fast as it seems to go; it might be that we are hitting it so hard that we need to back off.

Worth saying though that this test normally works, in that etcd handles it all, but even in good runs it looks like it cannot keep up with the watchers and they hit the overflow of the watcher index issue (i.e. being 1000 changes behind), even though the CPU isn't crazy and we have a decent amount of memory. Latency accounts for some of the limit on watch performance (we have at least 1 ms round trip time, and turning that into HTTP might mean that we have enough that 300 mods per second is too much).

**Comment by plwhite** [comment] 2015-12-10 16:35
We are unable to repro now running the exact same test. That's going to make diagnosis very hard, so I'm leaving this idle for now.

**Comment by xiang90** [comment] 2015-12-21 23:51
@plwhite I am closing this since we are not able to reproduce it too. Also etcd2 is not suitable for storing large amount of data nor supporting a lot of watchers.

**Closed by xiang90** 2015-12-21 23:51 UTC
