### ISSUE TITLE
etcd 0.4.6 crashes out of memory, then panics on startup with index out of range.

### ISSUE THREAD

**Issue by alex-mohr** [coreos/etcd#2187] opened 2015-01-29 18:40 UTC
Using etcd 0.4.6 -- presumably fix is to move to 2.0?
Commandline: /usr/local/bin/etcd -peer-addr k8s-prod3-master:7001 -name k8s-prod3-master

[etcd] Jan 29 16:40:16.658 INFO      | k8s-prod3-master: snapshot of 10060 events at index 670889 completed
fatal error: runtime: out of memory
<stack trace>

Then for each future startup:
[etcd] Jan 29 17:45:21.732 INFO      | Peer URLs in log:  / k8s-prod3-master ()
[etcd] Jan 29 17:45:21.735 INFO      | etcd server [name k8s-prod3-master, listen on 0.0.0.0:4001, advertised url http://127.0.0.1:4001]
[etcd] Jan 29 17:45:21.736 INFO      | peer server [name k8s-prod3-master, listen on :7001, advertised url http://k8s-prod3-master:7001]
[etcd] Jan 29 17:45:21.736 INFO      | k8s-prod3-master starting in peer mode
[etcd] Jan 29 17:45:21.736 INFO      | k8s-prod3-master: state changed from 'initialized' to 'follower'.
[etcd] Jan 29 17:45:22.106 INFO      | k8s-prod3-master: state changed from 'follower' to 'candidate'.
[etcd] Jan 29 17:45:22.106 INFO      | k8s-prod3-master: state changed from 'candidate' to 'leader'.
[etcd] Jan 29 17:45:22.106 INFO      | k8s-prod3-master: leader changed from '' to 'k8s-prod3-master'.
panic: runtime error: index out of range
<stack trace>

**Comment by xiang90** [comment] 2015-01-29 18:44
@alex-mohr Can you please check how large is the snapshot and log file? Thanks.

**Comment by alex-mohr** [comment] 2015-01-29 22:47
@xiang90 sorry, I don't have the snapshot or log file anymore.   I'll start a repro with a much larger VM (50GB ram instead of 4GB) and see where that ends up.  Took ~12 hours last time.

**Comment by xiang90** [comment] 2015-01-29 22:50
@alex-mohr Besides, do you have any scalability requirement in mind? How many keys do you want to save. What is avg size of keys?

**Comment by alex-mohr** [comment] 2015-01-29 22:57
@xiang90 I only had ~50 keys written at any given time.  The workload was create ~50 keys, wait for that batch to be processed, delete the keys, repeat.  Run with defaults, so 10k events between snapshots, though.

**Comment by yichengq** [comment] 2015-02-01 18:25
@alex-mohr What is the average size of keys?
etcd does put 10k events in the memory, and it is usually fine.

**Comment by xiang90** [comment] 2015-03-01 16:44
@alex-mohr I am closing this due to low activity. You might want to try to reproduce with etcd 2.0.x and report back with more information if there is still some problems.

**Closed by xiang90** 2015-03-01 16:44 UTC
