### ISSUE TITLE
On master, key doesn't be deleted when bound lease expires

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#9006] opened 2017-12-13 03:53 UTC
step:
- `etcdctl lease grant 30`
- `etcdctl put a 123 --lease leaseid`
- `etcdctl lease timetolive leaseid` and got `lease 4289604df903d409 granted with TTL(30s), remaining(-4s)`

Lease expired but it and key still exists. Correct output of expired lease should be `lease 4289604df903d409 granted with TTL(0s), remaining(-1s)`

**Comment by hexfusion** [comment] 2017-12-13 09:12
Hi @zyf0330 I can not replicate this can you post logs? What version of go are you using and what are steps to compile? Thanks!

```
[samb@ob1 etcd]$ bin/etcd --version
etcd Version: 3.2.0+git
Git SHA: c886bda7f
Go Version: go1.9
Go OS/Arch: linux/amd64

$ etcdctl lease grant 30
lease 694d604f1cc13e0f granted with TTL(30s)

$ etcdctl put a 123 --lease 694d604f1cc13e0f
OK

$ etcdctl lease timetolive  694d604f1cc13e0f
lease 694d604f1cc13e0f granted with TTL(30s), remaining(10s)

$ etcdctl lease timetolive  694d604f1cc13e0f
lease 694d604f1cc13e0f granted with TTL(0s), remaining(-1s)
```

**Comment by zyf0330** [comment] 2017-12-13 10:50
```
go version 1.9.2
etcd commit c886bda
```
It seems that only go version is different. But I have problem still.

**Comment by zyf0330** [comment] 2017-12-13 10:51
I have test that at release v3.2.11, this problem doesn't exist.

**Comment by hexfusion** [comment] 2017-12-13 11:03
@zyf0330 I just built 1.9.2 and tested against master. Can you confirm your build process?

```
$ ./build
$ rm -rf default.etcd/
$ bin/etcd&
```

**Comment by zyf0330** [comment] 2017-12-14 01:31
You are right, I test again with deleting old data and no problem.
I use old etcd data dir, so this problem occurs.
So how to solve it?

**Comment by xiang90** [comment] 2017-12-14 01:35
We need a way to reproduce this problem. 

I am not sure what is the `old data`. If you can reproduce it with `old data`, you probably need to upload the `old data` somewhere, and tell us the steps to reproduce the problem.

**Comment by zyf0330** [comment] 2017-12-14 01:36
So do you need data dir or real k/v?

**Comment by xiang90** [comment] 2017-12-14 01:38
We need a way to reproduce it. You should write down the exact steps to reproduce the problem. If any data is needed to reproduce it, it should be uploaded somewhere.

**Comment by zyf0330** [comment] 2017-12-14 01:55
I found it. This is reproduce step.
1. use c886bda7f and build
1. add user root:root and enable auth
1. `grant lease` and `put k v --lease leaseid`
1. wait to see it

**Comment by xiang90** [comment] 2017-12-15 02:54
@gyuho @hexfusion 

are you able to reproduce this? it seems like a bug.

**Comment by gyuho** [comment] 2017-12-15 03:05
@xiang90 Yeah, easily reproducible. Will fix.

```bash
ETCDCTL_API=3 ./bin/etcdctl \
  put abc def

ETCDCTL_API=3 ./bin/etcdctl \
  get abc

ETCDCTL_API=3 ./bin/etcdctl \
  role add root

ETCDCTL_API=3 ./bin/etcdctl \
  role grant-permission root readwrite foo

ETCDCTL_API=3 ./bin/etcdctl \
  role get root

ETCDCTL_API=3 ./bin/etcdctl \
  --interactive=false \
  user add root:123

ETCDCTL_API=3 ./bin/etcdctl \
  user grant-role root root

ETCDCTL_API=3 ./bin/etcdctl \
  user get root

ETCDCTL_API=3 ./bin/etcdctl \
  auth enable

ETCDCTL_API=3 ./bin/etcdctl \
  --user=root:123 \
  put foo bar

ETCDCTL_API=3 ./bin/etcdctl \
  --user=root:123 \
  lease grant 30

ETCDCTL_API=3 ./bin/etcdctl \
  --user=root:123 \
  put foo bar --lease 694d60581f75b714

ETCDCTL_API=3 ./bin/etcdctl \
  --user=root:123 \
  lease timetolive 694d60581f75b714

ETCDCTL_API=3 ./bin/etcdctl \
  --user=root:123 \
  get foo
```

**Comment by gyuho** [comment] 2017-12-15 03:09
Also the `lease timetolive` output is broken.

```
ETCDCTL_API=3 ./bin/etcdctl lease timetolive 694d60581f75b714
lease 694d60581f75b714 granted with TTL(30s), remaining(-4s)
```

Should be

```
lease 694d60581f75b714 granted with TTL(0s), remaining(-4s)
```

**Comment by hexfusion** [comment] 2017-12-15 03:30
@xiang90 added a test for via https://github.com/coreos/etcd/pull/9017 but it was passing for me.

**Comment by gyuho** [comment] 2017-12-15 05:28
This is server-side regression when it upgraded gRPC to v1.4.x (https://github.com/coreos/etcd/pull/7896).
So this affects etcd v3.2.10+ with gRPC v1.7.x.

I have a fix https://github.com/coreos/etcd/pull/9018.
And we need another v3.2 release with this fix.

**Comment by zyf0330** [comment] 2017-12-15 06:40
About format mentioned in (comment)[https://github.com/coreos/etcd/issues/9006#issuecomment-351901333], should it keep being `lease 694d60581f75b714 granted with TTL(0s), remaining(-1s)` after expiring?

**Comment by gyuho** [comment] 2017-12-15 06:44
@zyf0330 Yes, the output should be fixed as well.

```
lease 694d60581f75b714 granted with TTL(0s), remaining(-4s)
```

is the correct format.

**Comment by xiang90** [comment] 2017-12-15 06:46
Why the remaining can be negative?

**Comment by gyuho** [comment] 2017-12-15 06:47
@xiang90 Just found with auth disabled, we print `lease 694d6058ec511804 granted with TTL(0s), remaining(-1s)`. Will fix that output as well in another PR.

**Comment by gyuho** [comment] 2017-12-15 16:57
@xiang90 This is fixed via https://github.com/coreos/etcd/pull/9018. Also the output, we return TTL -1 on lease not found. So `lease 694d60581f75b714 granted with TTL(0s), remaining(-1s)` is the correct output.

**Comment by xiang90** [comment] 2017-12-15 17:00
Is it better to explicitly return lease not found? -1 still seems not
intuitive.

**Comment by gyuho** [comment] 2017-12-15 17:09
@xiang90 The change was made from 3.1 to 3.2. https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_2.md#client-upgrade-checklists-320

Also, just found out this only happens in master since we didn't backport https://github.com/coreos/etcd/pull/8031. No need for another v3.2.12 release.

**Comment by gyuho** [comment] 2017-12-15 17:19
Just backported https://github.com/coreos/etcd/commit/9fb7bbdb2db023f41aba84e7da657b78135d9957 to release-3.2 branch.

**Closed** 2017-12-15 18:08 UTC
Labels: kind/bug
