### ISSUE TITLE
better recovery after failure

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#4012] opened 2015-12-17 02:08 UTC
After power failure on one of three nodes Etcd-2.2.2 failed to start:

~~~~
etcd[1001]: recovered store from snapshot at index 20431266
[...]
etcd[1001]: loaded cluster information from store: <nil>
systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
~~~~

Investigation revealed that most recently modified `000000000000003f-0000000001367007.wal` file is likely to be corrupted. However _etcd_ silently terminated on start without clearly logging nature of the problem.
Removing damaged file did not help and all my attempts to recover node have failed.
In the end I had to remove member and re-create it from scratch.

This incident demonstrate that there is a room for improvements to how Etcd handles such problems. For instance I suppose Etcd could automatically dismiss corrupted file and fall back to earlier snapshot and re-load newer data from peers. Such situation should be recoverable without manual re-creation of member.

**Comment by xiang90** [comment] 2015-12-17 02:11
> For instance I suppose Etcd could automatically dismiss corrupted file and fall back to earlier snapshot and re-load newer data from peers. Such situation should be recoverable without manual re-creation of member.

That is not going to work. If any committed log entries is lost, etcd has to refuse to start. Or you might corrupt the cluster data.

**Comment by xiang90** [comment] 2015-12-17 02:12
Can you please show the full log of etcd? 

> However etcd silently terminated on start without clearly logging nature of the problem.

This is what we need to fix I believe.

**Comment by onlyjob** [comment] 2015-12-17 03:08
> Can you please show the full log of etcd?

I already quoted all meaningful messages. Etcd just terminates after `loaded cluster information from store: <nil>` so there is nothing more to add...

>  If any committed log entries is lost, etcd has to refuse to start. Or you might corrupt the cluster data.

IMHO this is the problem. When other Etcd nodes are up-to-date it is clear that node that fall behind due to corruption should just pull newer data from peers instead of failing.
Anyway this is the only way to recover but manual re-creation of node pulls _all data_ from peers while automatic recovery could probably load data since last valid index point.

Peers should not let outdated node to corrupt cluster data so I don't see why there can't be automatic recovery. If outdated peer can corrupt cluster data then there is a bigger (more serious) problem...

**Comment by xiang90** [comment] 2015-12-17 03:14
>  Etcd just terminates after loaded cluster information from store: <nil> so there is nothing more to add...

I mean the log before it when reading the wal.

> Peers should not let outdated node to corrupt cluster data so I don't see why there can't be automatic recovery.

Your node is not only out of date but also loses meaningful state information about itself. For more information, I would suggest you to read raft paper which we use as our underlying protocol.

**Comment by xiang90** [comment] 2015-12-17 03:28
@onlyjob Also to get full log, you need to do https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service. There is a journald issue.

**Comment by onlyjob** [comment] 2015-12-17 03:46
> I mean the log before it when reading the wal.

Please believe me, Etcd logged nothing useful comparing to normal Etcd start up.
I know how to use `journalctl`. This is exactly one of the problems I'm reporting: Etcd quietly terminates when its data files are corrupted.

> Your node is not only out of date but also loses meaningful state information about itself.

Well, in this case it knows when to re-initialise itself. Why not to do so instead of failing?
Why do I need to remove and re-create member manually?

**Comment by xiang90** [comment] 2015-12-17 04:01
@onlyjob Have you tried https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service? I do not think etcd should silently quit.

> Well, in this case it knows when to re-initialise itself.

etcd does not provide auto reconfiguration intentionally. Check https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#design-of-runtime-reconfiguration. We already provide a flexible enough reconfiguration API. If you want, you can write a script to do it.

**Comment by onlyjob** [comment] 2015-12-17 04:14
> I do not think etcd should silently quit.

This is exactly my point. Yet it seems to quit silently. I've checked logs and I'm not sure how can I convince you that Etcd logged nothing relevant...

> etcd does not provide auto reconfiguration intentionally

Fair enough. Bit IMHO it invalidates the following claim: "_etcd is designed to be resilient to machine failures_" from [admin guide](https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery) as my example demonstrates that Etcd in fact very poorly handles abnormal termination. Re-creation of node is like re-formatting file system after power loss. Journal should be of help in such situation...
I'm not sure whether it is a flaw in implementation or in design of Etcd...

**Comment by xiang90** [comment] 2015-12-17 04:18
> I'm not sure whether it is a flaw in implementation or in design of Etcd...

Well. First etcd handles power failure most the cases. If the last few entries does not contain important data, it can be repaired. Check https://github.com/coreos/etcd/blob/master/wal/repair.go. I am not sure what exactly happened. And you told me it is `likely` happened. I want something for sure.

I cannot really help unless you can reproduce the issue and give me step by step instruction. If we can get the last few log lines it would also be helpful. I do not think etcd CAN quit silently without log. I can double check tomorrow.

**Comment by xiang90** [comment] 2015-12-17 04:24
> etcd is designed to be resilient to machine failures

I have to copy the full paragraph here. Your argument totally misinterprets the whole paragraph.

etcd is designed to be resilient to machine failures. An etcd cluster can automatically recover from any number of temporary failures (for example, machine reboots), and a cluster of N members can tolerate up to (N-1)/2 permanent failures (where a member can no longer access the cluster, due to hardware failure or disk corruption). However, in extreme circumstances, a cluster might permanently lose enough members such that quorum is irrevocably lost. For example, if a three-node cluster suffered two simultaneous and unrecoverable machine failures, it would be normally impossible for the cluster to restore quorum and continue functioning.

What we are trying to say is etcd as a cluster can handle machine failure. And for your exact case, you lose ZERO data at cluster level even if one of your power went down.

**Comment by onlyjob** [comment] 2015-12-17 13:38
It is true that cluster survives single node failure. However instead of self-repairing node just commits suicide which is wrong. Certainly it can be improved.

> I am not sure what exactly happened. And you told me it is likely happened. I want something for sure.

I'm sorry if I wasn't clear enough. I tried though... See below for details.

> I cannot really help

I'm not asking for help but reporting two issues that I recognise as suboptimal: lack of error message and failure to recover.  I hope you might consider this report as opportunity to introduce some improvements.


> unless you can reproduce the issue and give me step by step instruction.

I tried to corrupt last wal file and managed to produce similar failure using the following steps:

  1. stop etcd daemon.
  2. in the data folder  `member/wal` find most recently modified file (e.g. `0000000000000001-00000000013dad08.wal`).
  3. corrupt the file: `head --bytes=4M /dev/zero >>0000000000000001-00000000013dad08.wal`

Now Etcd either fails to start exactly as described (i.e. silently) or with error `read wal error (walpb: crc mismatch) and cannot be repaired` which is close enough. About 4M in the end of the originally corrupted file was empty which makes me think that some data was lost. In the above example I'm appending zeroes instead of overwriting tail of the file for simplicity.
I tried that two times and on one instance Etcd failed to start silently without `read wal error`.


> If we can get the last few log lines it would also be helpful.

Why do you keep insisting on that? I already told you that there was nothing logged, at least not to _syslog_.

> I do not think etcd CAN quit silently without log. 

I have no time to deal with denial and I find it quite discouraging. Perhaps if try to reproduce the issue by overwriting some megs in the end of recent wal file with zeroes you'll see for yourself...

> I can double check tomorrow.

Thanks.

**Comment by xiang90** [comment] 2015-12-17 16:15
@onlyjob Thanks for your last reply with more detailed information. I will try to reproduce it and get back to you soon.

**Comment by xiang90** [comment] 2015-12-28 06:12
@onlyjob 

> Now Etcd either fails to start exactly as described (i.e. silently) or with error read wal error (walpb: crc mismatch) and cannot be repaired which is close enough. 

I tried several times on both linux(ext3/ext4) and osx(hfs+). etcd always fails with `crc mismatch` error. This is expected. etcd might fix short write as long as the metadata of the last entry is written. As long as the broken entry is not a critical one (a state change entry), etcd should be able to repair it. For appending all zeros, etcd cannot identify the metadata so it cannot be repaired. 

I cannot reproduce the silent failure case. After you reproduced the silent failure case, will etcd fail silently every time you restart with the same data dir? Can you share that data dir?

**Comment by onlyjob** [comment] 2016-01-04 07:16
Unfortunately original corrupted data is lost. IMHO silent fail is not too important if it is hard to reproduce but I hope `crc mismatch` error can be re-factored into warning + automatic recovery from peers -- it will make Etcd clusters much more robust and resilient to failures.
Thanks and Happy New Year. :-)

**Comment by xiang90** [comment] 2016-01-04 15:30
> I hope crc mismatch error can be re-factored into warning + automatic recovery from peers 

We cannot do this by default since this is unsafe. Any quorum based system requires the majority to have data written to disk before commit it. Restarting a data loss peer (we do not know if crc mismatch is caused by actual data loss or just a writing during power failure) might break this and also cause inconsistency. To be honest, I understand that data loss happens very rare in reality and most cases it is just a short write. But we still do not want etcd compromise correctness. 

There are ways to make this slightly better though. But it is not a high priority for now. We might consider to do it in the future. I will create an issue for that, so closing this one.

**Closed by xiang90** 2016-01-04 15:30 UTC
Labels: kind/support
