### ISSUE TITLE
Intermittent etcdhttp: got unexpected response error (etcdserver: request timed out)

### ISSUE THREAD

**Issue by apatil** [coreos/etcd#3864] opened 2015-11-13 23:25 UTC
Hi all,

I'm running a single node etcd 2.2.0 (e4561dd) cluster on Ubuntu 14.04 on OpenStack, with options name, listen-client-urls, listen-peer-urls, advertise-client-urls, initial-cluster-master, initial-advertise-peer-urls and data-dir set. 

It's backing a single-node test Kubernetes cluster that has scheduled a couple dozen pods, but isn't changing much. Every few minutes, I see

```
2015-11-13_22:08:10.35486 2015-11-13 22:08:10.354738 E | etcdhttp: got unexpected response error (etcdserver: request timed out)
```

in the logs. Sometimes I see a few in succession, and during those times `etcdctl ls` can fail with

```
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://127.0.0.1:4001 exceeded header timeout
error #1: client: endpoint http://192.168.0.15:2379 exceeded header timeout
error #2: client: endpoint http://127.0.0.1:2379 exceeded header timeout
error #3: client: endpoint http://192.168.0.15:4001 exceeded header timeout
```

I can make it happen more frequently by writing something substantial to etcd in a loop:

```bash
while true
do 
  etcdctl set /blarg $(etcdctl get /registry/pods/default/redis-controller-q4948) > /dev/null
done
```

The machine has plenty of spare memory and cpu. etcd's position in iotop is spiky. It's usually relatively low, but sometimes reaches 99%. The stress-test script above pushes etcd higher in iotop, I usually see 5-7 threads under 5%.

I also have a 292kb strace of the etcd process taken while the stress test was running & etcd was periodically logging the timeout message, and would be happy to grep it for anything that might shed light on the situation.

Thanks,
Anand

**Comment by xiang90** [comment] 2015-11-14 02:27
@apatil Do you have access to any cloud environment? If you can reproduce the issue there, it would be very helpful.

**Comment by apatil** [comment] 2015-11-14 17:39
@xiang90 I do, yes. I'll try to get you a simple repro.

**Comment by xiang90** [comment] 2015-11-14 17:40
@apatil Great. Thanks!

**Comment by apatil** [comment] 2015-11-16 16:45
Is this issue superseded by/redundant with https://github.com/coreos/etcd/issues/3812 ?

**Comment by xiang90** [comment] 2015-11-16 16:48
no they are different. it is important to find out why this happens to a one member cluster with mid load.

**Comment by apatil** [comment] 2015-11-18 15:07
I still haven't managed to come up with a simple repro case, but I have gotten some more information.

In addition to 2.2.0, this happens with versions 2.0.13 and c4672ced3e0a0dc2232af3194d00d869516866f1 . I'm able to convince myself that it's less frequent with c4672ced3e0a0dc2232af3194d00d869516866f1 , but couldn't swear to it.

Also, I took a look at traffic with the new etcd-top tool. In most seconds there are <5 requests, but every 10s there is a spike. The spike is usually 50-60 requests, the most I've seen is 68 requests per second. The breakdown is as follows:

```
Top 10 most popular http requests:
Total Sum  Period Sum Verb Path
     2566      22 GET /v2/keys/registry/pods/default
     1713      16 GET /v2/keys/registry/controllers/default
     1712      16 GET /v2/keys/registry/daemonsets/default
      850       2 GET /v2/keys/environment
      356       0 GET /v2/members
      318       0 GET /v2/keys/registry/minions
      202       0 GET /v2/keys/registry/minions/localhost
      108       0 GET /v2/keys/registry/namespaces/default
```

So most of the traffic seems to be Kubernetes heartbeating. No pods were scheduled and no API objects were changed, created or deleted during this test.

Strangely, the timeout messages don't seem to be correlated with the spikes. The overwhelming majority of the spikes go by without problems, and I have seen timeout messages right in the middle of the cycle, in seconds where there were zero requests.

**Comment by apatil** [comment] 2015-11-18 15:24
Also of interest, it looks like kube-apiserver is using the go-etcd client: https://github.com/kubernetes/kubernetes/blob/54706661ad72d62ea0b494112a74e0467093c9f4/cmd/kube-apiserver/app/server.go#L52 . The default timeout seems to be 1s: https://github.com/coreos/go-etcd/blob/de3514f25635bbfb024fdaf2a8d5f67378492675/etcd/client.go#L79 .

**Comment by xiang90** [comment] 2015-12-24 05:44
@apatil The error comes from server-side, not client-side. Have you managed to reproduce it on a single member etcd cluster? We are aware that this might happen to a multi-member cluster when the cluster is under high load.

**Comment by liggitt** [comment] 2016-01-04 19:16
We're seeing request timeout errors as well and resulting 50x server errors with single-node etcd clusters, from etcd 2.1.2 up to 2.2.2.

On the etcd server side, we see one or more of these logged about 30-60 seconds after server start:
```
2016/01/4 12:55:11 etcdhttp: got unexpected response error (etcdserver: request timed out)
```

As best as I can tell, this isn't at a watch limit boundary (1000) or a snapshot boundary (10000). At the same time that occurs, the etcd client gets a 501 error. It reacts by retrying the request, thinking a leader election was in progress. If the request is one that would fail on a retry (like a delete or a conditional update/create), the request then fails.

Running a loop with curl doing PUTs against etcd alongside the tests:
```
while true; do curl -v -s -X PUT "http://127.0.0.1:44001/v2/keys/_curltest" >> curletcd.log 2>&1; done
```

it looks like the etcd server is stuttering, maybe during a garbage collect? It averages 200 PUTs/second, then hits a 6 second gap, a 500 error, a few more 3-4 second gaps, then is back to 200+ PUTs/second

```
grep -E " 500 |Date:" curletcd.log | awk -f dedup.awk

< Date: Tue, 22 Dec 2015 22:20:37 GMT
... repeated 237 times
< Date: Tue, 22 Dec 2015 22:20:38 GMT
... repeated 191 times
< Date: Tue, 22 Dec 2015 22:20:39 GMT
... repeated 182 times
< Date: Tue, 22 Dec 2015 22:20:40 GMT
... repeated 175 times
< Date: Tue, 22 Dec 2015 22:20:41 GMT
... repeated 301 times
< Date: Tue, 22 Dec 2015 22:20:42 GMT
... repeated 219 times
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< X-Etcd-Cluster-Id: a176fdba55eb9204
< X-Etcd-Index: 0
< Date: Tue, 22 Dec 2015 22:20:48 GMT
< Content-Length: 100
< 
{ [data not shown]
* Connection #0 to host 127.0.0.1 left intact
{"errorCode":300,"message":"Raft Internal Error","cause":"etcdserver: request timed out","index":0}
< Date: Tue, 22 Dec 2015 22:20:48 GMT
< Date: Tue, 22 Dec 2015 22:20:53 GMT
< Date: Tue, 22 Dec 2015 22:20:56 GMT
... repeated 149 times
< Date: Tue, 22 Dec 2015 22:20:57 GMT
... repeated 337 times
< Date: Tue, 22 Dec 2015 22:20:58 GMT
... repeated 334 times
< Date: Tue, 22 Dec 2015 22:20:59 GMT
... repeated 336 times
< Date: Tue, 22 Dec 2015 22:21:00 GMT
... repeated 329 times
```

Related issue/comments:
https://github.com/openshift/origin/issues/6065#issuecomment-166651844

**Comment by gyuho** [comment] 2016-01-28 21:27
@apatil @liggitt 

The server side error that you see in `etcdserver: request timed out` can happen in 2 cases:

- `Propose(ctx, data)` to append log got timed out.
- `ProposeConfChange(ctx, cc)` to propose configuration change got timed out.

I tried in a single node etcd cluster, extensively with verstion `2.1.2`, `2.2.2`,
master branch, but I **couldn't reproduce this error**.

It might have been timed out from gc pause, but we need GC trace to find that out. 

Could you reproduce this reliably in a cloud environment?  If you have simple configs and commands that are reproducible in our side, it would be very helpful.

Thanks,

**Comment by liggitt** [comment] 2016-01-28 21:30
For our issue, we tracked it to the fsync system call and a super-slow disk issue (ec2 blocked the fsync call for 10-30 seconds while silently resizing the supposedly local and supposedly pre-allocated SSD volume).

**Comment by gyuho** [comment] 2016-01-28 21:37
The server side error is not related to disk issue, I think. Did that issue affect the CPU or anything else?

**Comment by xiang90** [comment] 2016-01-28 21:38
@gyuho It is highly related to disk since etcd needs to do fsync before committing. @liggitt Thanks for the update. I feel we can close this actually.

**Comment by gyuho** [comment] 2016-01-28 21:41
@xiang90 is right. Sorry about the wrong information.

The raft implementation calls fsync before committing an entry and if there were disk issues,
the propose operations in raft could have timed out.

**Comment by apatil** [comment] 2016-01-28 22:41
That's good to know. Thanks @liggitt for the info. I agree that this can be closed, will investigate fsync performance on our side and open a different issue if necessary.

**Closed** 2016-01-28 22:42 UTC
Labels: kind/question

**Comment by sukrit007** [comment] 2016-11-21 18:11
We keep seeing these errors in the logs.  What are the current timeouts and is there a way to adjust the timeouts ?  

We are using 3 node cluster in ec2 created using cloudformation template:

https://s3.amazonaws.com/coreos.com/dist/aws/coreos-stable-hvm.template

CoreOS: 1185.3.0

**Comment by heyitsanthony** [comment] 2016-11-28 20:20
From https://github.com/coreos/etcd/blob/master/etcdserver/config.go#L137 it's defined as `return 5*time.Second + 2*time.Duration(c.ElectionTicks)*time.Duration(c.TickMs)*time.Millisecond`. If you want to increase the request timeout that means changing the `--election-timeout` flag passed to etcd.
