### ISSUE TITLE
etcd2 cluster bootstrap failing on Google Compute Engine

### ISSUE THREAD

**Issue by scole-scea** [coreos/etcd#3971] opened 2015-12-08 17:54 UTC
# Etcd2 Initial Cluster Discovery for new Clusters in CoreOS 835.9.0

## The Problem

When trying to create an etcd cluster where some hosts are members and some hosts are proxies, cluster discovery seems to get confused about who is a member and who is a proxy, and then gets stuck, refusing to ever change its mind.

This happens in roughly 8 out of 10 cluster bringups. (The other 2 work fine.)

## Versions
This issue has been found on
* CoreOS Stable: CoreOS 835.9.0; etcd 2.2.0.
* CoreOS Beta: CoreOS 877.1.0; etcd 2.2.2.
* CoreOS Alpha: CoreOS 884.0.0; etcd 2.2.2.

## cloudinit

The initial cloudinit setup files for these hosts looks like the following:

```
#cloud-config
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/b4e8d34f98130cd02a85a507fd99fd2c
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```

That discovery token is regenerated for each new cluster.

## Logs

When a host comes up in failure mode, it's first `etcd2.service` log looks like:

```
Dec 07 23:47:00 trouble-etcd-e systemd[1]: Starting etcd2...
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.240.0.5:2379
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/b86bdd008160b8d7bd352262ce2e0c33
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.240.0.5:2380
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.240.0.5:2380,http://10.240.0.5:7001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_NAME=52f206ffb747382c49bfde7c3d21b5d7
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: etcd Version: 2.2.0
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Git SHA: e4561dd
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Go Version: go1.4.2
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Go OS/Arch: linux/amd64
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for peers on http://10.240.0.5:2380
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for peers on http://10.240.0.5:7001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for client requests on http://0.0.0.0:2379
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:06 trouble-etcd-e etcd2[757]: stopping listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Dec 07 23:47:06 trouble-etcd-e systemd[1]: Failed to start etcd2.
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Unit entered failed state.
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Failed with result 'exit-code'.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: Stopped etcd2.
```

Subsequent restarts are nearly the same:

```
Dec 07 23:47:16 trouble-etcd-e systemd[1]: Starting etcd2...
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.240.0.5:2379
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/b86bdd008160b8d7bd352262ce2e0c33
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.240.0.5:2380
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.240.0.5:2380,http://10.240.0.5:7001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: recognized and used environment variable ETCD_NAME=52f206ffb747382c49bfde7c3d21b5d7
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: etcd Version: 2.2.0
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: Git SHA: e4561dd
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: Go Version: go1.4.2
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: Go OS/Arch: linux/amd64
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: the server is already initialized as member before, starting as etcd member...
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: listening for peers on http://10.240.0.5:2380
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: listening for peers on http://10.240.0.5:7001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: listening for client requests on http://0.0.0.0:2379
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: stopping listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: stopping listening for client requests on http://0.0.0.0:2379
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: stopping listening for peers on http://10.240.0.5:7001
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: stopping listening for peers on http://10.240.0.5:2380
Dec 07 23:47:16 trouble-etcd-e etcd2[956]: discovery: cluster is full
Dec 07 23:47:16 trouble-etcd-e systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Dec 07 23:47:16 trouble-etcd-e systemd[1]: Failed to start etcd2.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: etcd2.service: Unit entered failed state.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: etcd2.service: Failed with result 'exit-code'.
Dec 07 23:47:26 trouble-etcd-e systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Dec 07 23:47:26 trouble-etcd-e systemd[1]: Stopped etcd2.
```

Though we have the noticible difference now of actually getting an error message: `discovery: cluster is full`.

## Workaround

So etcd2 is supposed to have automatic proxy fallback if more hosts than are requested try and join the cluster, but this doesn't seem to be working. It seems that the service is convinced at this point that it must be configured as a member, and not a proxy. The content of the `/var/lib/etcd2` directory at this stage is just an empty directory called `member`.

Fixing the issue is as simple as removing the `member` directory. Then the automatically restarting etcd2 service will  forget that it thinks it should be a member of the cluster and will fall back to being a proxy.

(One caveat, though: it generates both a `member` and a `proxy` directory during this fallback, and if you try to restart the etcd2 service later, you'll get an error about being configured both as a member and as a proxy. Again: just remove the `member` directory, and restarting the service will become possible.)

## The Scripts

There are a pair of scripts that I've checked into GitHub that I use to reproduce the issue. You can find them at https://github.com/scole-scea/etcd2_startup_issue.

**Comment by xiang90** [comment] 2015-12-08 17:57
```
Dec 07 23:47:00 trouble-etcd-e systemd[1]: Starting etcd2...
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.240.0.5:2379
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/b86bdd008160b8d7bd352262ce2e0c33
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.240.0.5:2380
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.240.0.5:2380,http://10.240.0.5:7001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: recognized and used environment variable ETCD_NAME=52f206ffb747382c49bfde7c3d21b5d7
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: etcd Version: 2.2.0
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Git SHA: e4561dd
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Go Version: go1.4.2
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: Go OS/Arch: linux/amd64
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for peers on http://10.240.0.5:2380
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for peers on http://10.240.0.5:7001
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for client requests on http://0.0.0.0:2379
Dec 07 23:47:01 trouble-etcd-e etcd2[757]: listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:06 trouble-etcd-e etcd2[757]: stopping listening for client requests on http://0.0.0.0:4001
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Dec 07 23:47:06 trouble-etcd-e systemd[1]: Failed to start etcd2.
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Unit entered failed state.
Dec 07 23:47:06 trouble-etcd-e systemd[1]: etcd2.service: Failed with result 'exit-code'.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Dec 07 23:47:16 trouble-etcd-e systemd[1]: Stopped etcd2.
```

Can you please provide the full log? I cannot see why it failed for the first time.

You probably need to try https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service

**Comment by scole-scea** [comment] 2015-12-08 18:15
Ah! You need to take the `-f` out of the "get the logs" example on that list. That helps a lot, since I can't turn on follow mode until after the service has failed. 

At any rate: the first couple of failures from the log are:
```
-- Logs begin at Tue 2015-12-08 17:44:06 UTC, end at Tue 2015-12-08 18:12:00 UTC. --
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.240.0.6:2379
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/c519647cd5ed09b20f9038a79d7f6525
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.240.0.6:2380
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.240.0.6:2380,http://10.240.0.6:7001
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: recognized and used environment variable ETCD_NAME=a6453bb639c1fc0fd8d800384efff6a8
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: etcd Version: 2.2.2
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: Git SHA: b4bddf6
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: Go Version: go1.4.3
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: Go OS/Arch: linux/amd64
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: listening for peers on http://10.240.0.6:2380
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: listening for peers on http://10.240.0.6:7001
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: listening for client requests on http://0.0.0.0:2379
Dec 08 17:44:13 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: listening for client requests on http://0.0.0.0:4001
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: stopping listening for client requests on http://0.0.0.0:4001
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: stopping listening for client requests on http://0.0.0.0:2379
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: stopping listening for peers on http://10.240.0.6:7001
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: stopping listening for peers on http://10.240.0.6:2380
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: failed to join discovery cluster (context deadline exceeded)
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: discovery token https://discovery.etcd.io/c519647cd5ed09b20f9038a79d7f6525 was used, but failed to bootstrap the cluster.
Dec 08 17:44:18 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[997]: please generate a new discovery token and try to bootstrap again.
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.240.0.6:2379
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/c519647cd5ed09b20f9038a79d7f6525
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.240.0.6:2380
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.240.0.6:2380,http://10.240.0.6:7001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: recognized and used environment variable ETCD_NAME=a6453bb639c1fc0fd8d800384efff6a8
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: etcd Version: 2.2.2
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: Git SHA: b4bddf6
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: Go Version: go1.4.3
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: Go OS/Arch: linux/amd64
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: the server is already initialized as member before, starting as etcd member...
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: listening for peers on http://10.240.0.6:2380
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: listening for peers on http://10.240.0.6:7001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: listening for client requests on http://0.0.0.0:2379
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: listening for client requests on http://0.0.0.0:4001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: stopping listening for client requests on http://0.0.0.0:4001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: stopping listening for client requests on http://0.0.0.0:2379
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: stopping listening for peers on http://10.240.0.6:7001
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: stopping listening for peers on http://10.240.0.6:2380
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: failed to join discovery cluster (discovery: cluster is full)
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: discovery token https://discovery.etcd.io/c519647cd5ed09b20f9038a79d7f6525 was used, but failed to bootstrap the cluster.
Dec 08 17:44:29 trouble-etcd-c.c.ace-ripsaw-671.internal etcd2[1198]: please generate a new discovery token and try to bootstrap again.
```

So: `context deadline exceeded`.

**Comment by scole-scea** [comment] 2015-12-08 18:32
It also looks like the syslog identifier for etcd isn't in the current CoreOS stable, so that `journalctl -t` trick won't work when I try this there.

**Comment by penguinxr2** [comment] 2015-12-14 02:43
I can confirm this happened to me also with CoreOS 835.9.0. I had to manually delete the /var/lib/etcd2/member folder in order for the etcd2 service to launch correctly as a proxy.

**Comment by xiang90** [comment] 2015-12-21 23:48
@scole-scea Does this happen a lot? The context deadline indicates the etcdserver timed out while sending requests to public discovery service. Can you reliably reproduce this?

**Comment by scole-scea** [comment] 2015-12-22 02:10
When I wrote up the issue two weeks ago, it was every time, which is why I figured out the workaround. The test script I linked to, above, was my testcase. When I next connect to my employer's accounts and network (probably during the next week), I'll give it another shot or to to see if it's still reliably failing.

(The holidays do make that schedule a bit chaotic.)

**Comment by scole-scea** [comment] 2016-01-04 21:40
This happened in my first test run of those scripts I pointed out before, so I'd say it's fairly reproducible.

**Comment by scole-scea** [comment] 2016-01-04 21:57
Interestingly, alpha channel coreOS (899.1.0) starts up ok, but still leaves {{/var/lib/etc2}} with both {{member}} and {{proxy}} directories and doesn't survive {{systemctl restart etcd2.service}}.

**Comment by gyuho** [comment] 2016-01-04 22:07
@scole-scea Sorry for late response. And thanks for the script. I will try to reproduce this behavior
and try to find out the cause. I will keep you updated through this thread.

**Comment by gyuho** [comment] 2016-01-04 23:44
@scole-scea FYI. Your `Workaround` issue should be fixed by this [PR](https://github.com/coreos/etcd/pull/4089). I will investigate more why it fails before.

**Comment by gyuho** [comment] 2016-01-06 07:03
@scole-scea I cannot reproduce this error message using the same configuration.
It seems work fine.

`failed to join discovery cluster (discovery: cluster is full)` message from your log means
you launch nodes more than the discovery size that you set up at the beginning.

You generated discovery token for 3 members here https://github.com/scole-scea/etcd2_startup_issue/blob/master/make_cluster.sh#L32:

```
token=$(curl -s https://discovery.etcd.io/new?size=3)
```

But if you launch 5 nodes using this token (`"#### Making a 5-node cluster on GCE: 3 etcd members, 2 etcd proxies..."`), it will error. Your discovery token https://discovery.etcd.io/b4e8d34f98130cd02a85a507fd99fd2c only shows 3 are registered.

And regarding work-around, I believe it is resolved in our latest etcd version https://github.com/coreos/etcd/pull/4089. So please try it with etcd v2.2.3.

**Comment by gyuho** [comment] 2016-01-06 07:05
Or do you intend to make two extra members fall back to proxy? That case should also be fixed in etcd v2.2.3 https://github.com/coreos/etcd/releases/tag/v2.2.3.

**Comment by scole-scea** [comment] 2016-01-06 17:13
Yeah, the intent was for two of them to fall back. (This is a simplified example of a "quick development cluster" bringup, where we don't run an independent etcd cluster; we just run etcd on all the nodes. Not production worthy, and usually not long-lived.)

etcd 2.2.3 is not yet in a CoreOS release; unless there's an easy way to bring up a CoreOS host with etcd 2.2.3 running, I'll just wait until 2.2.3 hits alpha and retest then.

**Comment by gyuho** [comment] 2016-01-06 17:18
@scole-scea Yes etcd v2.2.3 was released last year. Please try out https://github.com/coreos/etcd/releases/tag/v2.2.3 and let us know if you still have issues.

**Comment by scole-scea** [comment] 2016-01-06 17:22
Well, released 7 days ago, you mean. :smile: I'm a bit more up-to-date than a year behind...

My workaround still needs to be part of our tooling until 2.2.3 hits CoreOS stable, though, so it'll be a while.

**Comment by gyuho** [comment] 2016-01-06 17:23
Yeah just before the new year :)

And we will close this for now, and please let us know when you have any other questions.

Thanks,

**Closed by gyuho** 2016-01-06 17:23 UTC

**Comment by scole-scea** [comment] 2016-01-12 19:57
CoreOS 921.0.0 was released to the alpha channel today, and it contains etcd 2.2.3.

I re-ran my tests, and huzzah! everything seems just fine.

Thanks for your help.

**Comment by gyuho** [comment] 2016-01-12 20:13
That's great! Thanks!
