### ISSUE TITLE
etcd2 cluster goes unhealthy when removing an unhealthy node

### ISSUE THREAD

**Issue by tj-corrigan** [coreos/etcd#2888] opened 2015-05-29 18:27 UTC
I am seeing something similar to #2834. I'm running 3 CoreOS alpha 695 (etcd 2.0.11) machines on AWS. 

If I hard kill etcd on one of the machines, the cluster remains healthy with 1 unhealthy member. At this point I am successfully able to remove the machine from the cluster.

If instead I stop an entire machine, I still see a healthy cluster with 1 unhealthy member. However, if I try to remove the unhealthy node at this point I get ```context deadline exceeded``` if using etcdctl member remove or a  ```{"message":"Internal Server Error"}``` if using the etcd2 endpoint directly. The cluster remains in this state for ~ 5 minutes before it returns back to a healthy state with only 2 nodes as expected. Looking at the leader logs I see:

```
May 29 17:57:29 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:29 sender: error posting to a429f0ef0f2d2a80: dial tcp 10.183.2.42:2380: connection refused
May 29 17:57:29 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:29 sender: the connection with a429f0ef0f2d2a80 became inactive
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 rafthttp: encountered error writing to server log stream: write tcp 10.183.2.42:39814: broken pipe
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 rafthttp: server streaming to a429f0ef0f2d2a80 at term 862 has been stopped
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 stream: error sending message: stopped
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 stream: stopping the stream server...
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 [term: 862] received a MsgVote message with higher term from af20822d7afb109f [term: 863]
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 became follower at term 863
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 863
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft.node: 11b2f73f68ab6ea6 lost leader 11b2f73f68ab6ea6 at term 863
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 [term: 863] received a MsgVote message with higher term from af20822d7afb109f [term: 864]
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 became follower at term 864
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 864
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 [term: 864] received a MsgVote message with higher term from af20822d7afb109f [term: 865]
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 became follower at term 865
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 865
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: error removing node a429f0ef0f2d2a80: etcdserver: request timed out
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: unexpected error: etcdserver: request timed out
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: unexpected error: etcdserver: request timed out
```

**Comment by yichengq** [comment] 2015-05-29 20:58
I confirmed this is a bug in etcd 2.0.11.
The main etcdserver loop is blocked when stopping removed peer in rafthttp. It should cancel in-flight request instead of waiting for requests to finish.

We have refactored rafthttp package, and etcd 2.1-alpha.0 can run well under this case in my environment. Could you double-check that for me?

**Comment by yichengq** [comment] 2015-06-01 21:00
After digging deeper into it with xiang, we find that the problem does still exist in 2.1 but not that severe. Basically peer.pipeline should be stopped without block. We will fix it.

**Comment by tj-corrigan** [comment] 2015-06-01 21:43
I went ahead and tested this against quay.io/coreos/etcd:v2.1.0-alpha.0 . It looks like the problem still exists but resolves itself a lot faster (~30 seconds instead of 5 minutes). Here are the logs in case they are helpful: 

```
Jun 01 21:28:17 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:17 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:17 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:17 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:18 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:18 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:18 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:18 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:20 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:20 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:20 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:20 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:21 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:21 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:21 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:21 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:22 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:22 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:22 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:22 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:23 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:23 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:23 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:23 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft: 288b154d0ea4caa3 is starting a new election at term 7
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft: 288b154d0ea4caa3 became candidate at term 8
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft: 288b154d0ea4caa3 received vote from 288b154d0ea4caa3 at term 8
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to 9500e44c6c674e16 at term 8
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to e49255d3e11729a5 at term 8
Jun 01 21:28:24 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:24 INFO: raft.node: 288b154d0ea4caa3 lost leader e49255d3e11729a5 at term 8
Jun 01 21:28:25 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:25 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:25 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:25 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 INFO: raft: 288b154d0ea4caa3 is starting a new election at term 8
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 INFO: raft: 288b154d0ea4caa3 became candidate at term 9
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 INFO: raft: 288b154d0ea4caa3 received vote from 288b154d0ea4caa3 at term 9
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to e49255d3e11729a5 at term 9
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to 9500e44c6c674e16 at term 9
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:26 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:26 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 INFO: raft: 288b154d0ea4caa3 is starting a new election at term 9
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 INFO: raft: 288b154d0ea4caa3 became candidate at term 10
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 INFO: raft: 288b154d0ea4caa3 received vote from 288b154d0ea4caa3 at term 10
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to 9500e44c6c674e16 at term 10
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to e49255d3e11729a5 at term 10
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:27 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:27 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:28 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:28 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/msgapp/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:28 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:28 rafthttp: roundtripping error: error roundtripping to http://10.183.0.217:2380/raft/stream/message/288b154d0ea4caa3: dial tcp 10.183.0.217:2380: i/o timeout
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 INFO: raft: 288b154d0ea4caa3 is starting a new election at term 10
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 INFO: raft: 288b154d0ea4caa3 became candidate at term 11
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 INFO: raft: 288b154d0ea4caa3 received vote from 288b154d0ea4caa3 at term 11
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to 9500e44c6c674e16 at term 11
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 INFO: raft: 288b154d0ea4caa3 [logterm: 7, index: 1464] sent vote request to e49255d3e11729a5 at term 11
Jun 01 21:28:29 ip-10-183-2-154.ec2.internal sh[1330]: 2015/06/01 21:28:29 etcdhttp: error removing node 9500e44c6c674e16: etcdserver: request timed out
```

**Comment by bmccandless** [comment] 2015-06-03 00:10
I've run into this problem as well.  Do you know what version this will be
fixed in?

 Thanks,
    Brian

**Comment by yichengq** [comment] 2015-06-03 04:48
@bmccandless It will be fixed at 2.1.alpha.1

**Closed** 2015-06-03 15:47 UTC
Labels: bug

**Comment by maximecaron** [comment] 2016-04-12 18:14
Now that this is fixed, should we add logic on ETCD startup to remove and add itself again to the members if it's data folder is empty but other nodes in the cluster have data.

If we have a 3 node cluster with A, B and C
A is leader and replicate to only B but not C and then become partitioned.
then machine B lost its data and restart. 

Having this system in place would make machine B wait for machine A to rejoin the network instead of silently starting with missing data because it cant remove and add itself without contacting node A.

**Comment by xiang90** [comment] 2016-04-12 18:17
@maximecaron No. We will not. All reconfiguration should be done externally.
