### ISSUE TITLE
gRPC error in etcd v3.2.14 HA environment.

### ISSUE THREAD

**Issue by hchenxa** [coreos/etcd#9166] opened 2018-01-18 07:07 UTC
I setup a etcd HA environment with etcd v3.2.14 and here is the etcd server startup parameters:

```
etcd --name=etcd1 --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://9.111.255.45:2380 --listen-peer-urls=https://0.0.0.0:2380 --listen-client-urls=https://0.0.0.0:4001 --advertise-client-urls=https://9.111.255.45:4001 --cert-file=/etc/cfc/conf/etcd/server.pem --key-file=/etc/cfc/conf/etcd/server-key.pem --client-cert-auth --peer-auto-tls --trusted-ca-file=/etc/cfc/conf/etcd/ca.pem --initial-cluster-token=etcd-cluster-1 --initial-cluster=etcd0=https://9.111.255.15:2380,etcd1=https://9.111.255.45:2380,etcd2=https://9.111.255.131:2380 --initial-cluster-state=new
```

when etcd started, I found below messages in etcd logs:
```
2018-01-18 06:50:59.058302 I | mvcc: finished scheduled compaction at 4375 (took 1.299701ms)
2018-01-18 06:54:21.121542 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 21; CANCEL")
2018-01-18 06:54:28.093291 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 19; CANCEL")
2018-01-18 06:54:52.302752 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 15; CANCEL")
2018-01-18 06:55:59.062545 I | mvcc: store.index: compact 4859
```

Does there have any impact about gRPC failed?

**Comment by gyuho** [comment] 2018-01-18 15:35
Seems like server failed to receive watch request on compaction. Was there any error in client side?

**Comment by hchenxa** [comment] 2018-01-19 01:52
@gyuho , I did not see any error from kubernetes apiserver side.

**Comment by xiang90** [comment] 2018-01-19 01:58
@gyuho 

the requests are canceled from the client. we should not log these as warning. i am not sure why they are logged though. i think @spzala put up a PR to get it fixed. maybe we missed something.

**Comment by gyuho** [comment] 2018-01-19 02:00
Yeah it was only handling context cancel errors. Will try reproduce tomorrow.

**Comment by gyuho** [comment] 2018-01-19 06:25
@hchenxa Can you reproduce outside of k8s?

I see similar errors with TLS

> W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = client disconnected")

Which should be at debug level as well (`http2.errClientDisconnected`).

> rpc error: code = Unavailable desc = stream error: stream ID 21; CANCEL

This is from gRPC closing http2 stream with `http2.ErrCodeCancel` which is expected.

Should we change all gRPC errors with `code.Unavailable` to debug level?

**Comment by spzala** [comment] 2018-01-19 15:04
@xiang90 yes I worked on a related PR #9105 @gyuho thanks, I am close to work on load test issue #9121 and hoping to have PR created this weekend. I have couple other issues to work on but if needed I can work on this issue next week. To me, moving expected gRPC error/warning messages to debug level makes sense to not to confuse users. Thanks!

**Closed** 2018-01-19 21:01 UTC

**Comment by motecshine** [comment] 2018-06-08 08:10
`[root@irain217 kube-dashboard]# etcdctl -version
etcdctl version: 3.2.11
API version: 2`

`
Jun 08 15:55:14 irain217 etcd[26005]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 67; CANCEL")
Jun 08 15:55:14 irain217 etcd[26005]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 81; CANCEL")
Jun 08 15:58:46 irain217 etcd[26005]: store.index: compact 8636
Jun 08 15:58:46 irain217 etcd[26005]: finished scheduled compaction at 8636 (took 1.010574ms)
Jun 08 16:02:23 irain217 etcd[26005]: transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:2379->127.0.0.1:49072: read: connection reset by peer
Jun 08 16:03:46 irain217 etcd[26005]: store.index: compact 9087
Jun 08 16:03:46 irain217 etcd[26005]: finished scheduled compaction at 9087 (took 1.00037ms)
Jun 08 16:03:47 irain217 etcd[26005]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 85; CANCEL")
Jun 08 16:03:47 irain217 etcd[26005]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 97; CANCEL")
Jun 08 16:06:01 irain217 etcd[26005]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
`

may be same problems ?

**Comment by johnxiaohe** [comment] 2021-12-11 04:42
This problem is caused by the unsuccessful connection between the client and the server. There is a problem with the current state of the server. For example, the number of connections is full
