### ISSUE TITLE
etcdserver: failed to send out heartbeat on time,etcdserver: server is likely overloaded

### ISSUE THREAD

**Issue by heyujiaan** [coreos/etcd#5154] opened 2016-04-22 03:46 UTC
I have etcd version2.3.0,Construction etcd cluster on three nodes,I've discovered following messages:
2016-04-22 03:04:09.678778 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 185.938874ms)
2016-04-22 03:04:09.680486 W | etcdserver: server is likely overloaded
2016-04-22 03:04:21.816000 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 22.665497ms)
2016-04-22 03:04:21.816044 W | etcdserver: server is likely overloaded
2016-04-22 03:04:21.816054 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 22.738588ms)
2016-04-22 03:04:21.816061 W | etcdserver: server is likely overloaded
2016-04-22 03:04:42.571759 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 79.299038ms)
2016-04-22 03:04:42.571825 W | etcdserver: server is likely overloaded
2016-04-22 03:04:42.574990 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 82.538303ms)
2016-04-22 03:04:42.575017 W | etcdserver: server is likely overloaded
2016-04-22 03:05:10.815591 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 323.228276ms)
2016-04-22 03:05:10.815629 W | etcdserver: server is likely overloaded
2016-04-22 03:05:10.815693 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 323.341784ms)
2016-04-22 03:05:10.815703 W | etcdserver: server is likely overloaded

etcdctl member list:
2fd7dc4a458cf357: name=etcd2 peerURLs=http://127.0.0.1:2280 clientURLs=http://127.0.0.1:2279 isLeader=true
a5d52a3122b11c3e: name=etcd1 peerURLs=http://127.0.0.1:2180 clientURLs=http://127.0.0.1:2179 isLeader=false
c317c2302966e94b: name=etcd3 peerURLs=http://127.0.0.1:2380 clientURLs=http://127.0.0.1:2379 isLeader=false

if this is a problem how do I solve?

**Comment by xiang90** [comment] 2016-04-22 03:47
The problem is as it states, etcd is over loaded. Reduce the number of requests your applicants sent to etcd or give etcd process more resources to run with.

**Comment by xiang90** [comment] 2016-04-28 17:07
Closing this issue due to low activity. Please re-open if you still have the issue or you want to provide more information. Thanks!

**Closed by xiang90** 2016-04-28 17:07 UTC

**Comment by maverick-racheal** [comment] 2016-07-04 09:03
These logs are seen in v2.3.7 when we bring up ETCD along with K8 and create 10 pods. If there is more load on etcd, is there any recommendation on how we can increase the resources which doesnt lead to such overload condition. 
Also i wanted to understand if there are any other implications of these logs or they are just warning level logs

**Comment by v1k0d3n** [comment] 2016-07-06 18:53
@maverick-racheal you may want to tailor your timeout to match your environment. for instance, I'm seeing this while testing v3.0.1 as well (testing with an OSX binary):

```
2016-07-06 14:48:38.562412 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 21.716738ms)
2016-07-06 14:48:38.562430 W | etcdserver: server is likely overloaded
2016-07-06 14:48:40.574099 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 41.41508ms)
2016-07-06 14:48:40.574153 W | etcdserver: server is likely overloaded
2016-07-06 14:48:40.574176 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 41.50738ms)
2016-07-06 14:48:40.574189 W | etcdserver: server is likely overloaded
2016-07-06 14:48:54.045411 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 14.180971ms)
2016-07-06 14:48:54.045456 W | etcdserver: server is likely overloaded
2016-07-06 14:48:54.045475 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 14.264834ms)
2016-07-06 14:48:54.045488 W | etcdserver: server is likely overloaded
2016-07-06 14:49:02.046863 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 15.035952ms)
2016-07-06 14:49:02.046917 W | etcdserver: server is likely overloaded
2016-07-06 14:49:02.046942 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 15.134934ms)
2016-07-06 14:49:02.046957 W | etcdserver: server is likely overloaded
2016-07-06 14:49:03.541690 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 4.89051ms)
2016-07-06 14:49:03.541843 W | etcdserver: server is likely overloaded
2016-07-06 14:49:03.541871 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 5.08316ms)
2016-07-06 14:49:03.541881 W | etcdserver: server is likely overloaded
```

You can change this with the following flag:

```
--heartbeat-interval 250
```

Sure, it's not the ideal, but this will precent me from seeing overload heartbeat W(arning) messages. I'm testing in my use-case after all.

**Comment by FangXiangmeng** [comment] 2017-10-23 09:07
May I ask whether this problem is resolved

**Comment by Markbnj** [comment] 2017-11-20 17:43
Are there any kubernetes-releated edge cases that might cause this? We have an etcd cluster running in kubernetes 1.8 on Google Container Engine. The cluster was created and is maintained by etcd-operator. We were trying to diagnose an error `EtcdEventIndexCleared: The event in requested index is outdated and cleared : the requested history has been cleared ` (I believe it is unrelated but mention it because who knows) and noticed quite a few of these in the logs ```2017-11-20 17:38:03.401446 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 95.177087ms)                                                                                  
2017-11-20 17:38:03.401459 W | etcdserver: server is likely overloaded``` The original cluster was three pods, and we saw that this error occurred on only one of them at a time, and with several days between events. None of the pods showed any restarts or indication of exceeding memory or cpu limits, and in fact the mem/cpu usage per pod seems quite reasonable.

**Comment by prune998** [comment] 2018-03-23 11:45
@Markbnj I have the same issue with EtcD 3.2.17 started using Etcd-Operator on K8s 1.9.4 on GKE.

```
etcd-etcd-zfnp9sstzc etcd 2018-03-23 11:40:26.536843 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 191.128µs)
etcd-etcd-zfnp9sstzc etcd 2018-03-23 11:40:26.537157 W | etcdserver: server is likely overloaded
etcd-etcd-zfnp9sstzc etcd 2018-03-23 11:40:26.537604 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 1.01152ms)
etcd-etcd-zfnp9sstzc etcd 2018-03-23 11:40:26.537713 W | etcdserver: server is likely overloaded
```

The cluster is 3 node and is not hitted (no read or write at this time...)
![image](https://user-images.githubusercontent.com/1110398/37827431-d9176628-2e6d-11e8-9de0-fb968f1bc313.png)
Nodes are globally way underused, so it may not be a problem either.
