### ISSUE TITLE
save snapshot error: no such file or directory

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4552] opened 2016-02-18 04:06 UTC
```
agent1 2016-02-18 01:34:16.226396 I | etcdserver: compacted raft log at 54481933
agent1 2016-02-18 01:34:17.215567 C | etcdserver: save snapshot error: open agent.etcd/member/snap/0000000000000018-00000000033f8f30.snap: no such file or directory
```

And similar thing happens with test logs. Might be something related to archive and rename function? Because sometimes, the failure archive does not have etcd.log files when it should have.

**Comment by xiang90** [comment] 2016-02-18 04:20
I will check this out. Seems like an etcd issue.

**Comment by gyuho** [comment] 2016-02-18 04:23
Ok thanks. I will check the etcd-tester side to check if it does anything wrong.

**Comment by gyuho** [comment] 2016-02-18 09:39
Getting `os.Rename` error:

```
Feb 18 00:40:51 agent1 etcd_agent.log  undefined: | etcd-agent: cleanup etcd
Feb 18 00:40:51 agent1 etcd_agent.log  undefined: | etcd-agent: [IMPORTANT] Rename error rename /home/gyuho/logs/etcd.log failure_archive/2016-02-18T08:40:50Z/home/gyuho/logs/etcd.log: no such file or directory
```

**Comment by heyitsanthony** [comment] 2016-02-18 09:47
The log file has a full path so the code is trying to rename it into a directory that doesn't exist under `failure_archive/2016-02-18T08:40:50Z/`.

If you don't care about the directory structure, try:
agent.go:
```
logBase := path.Base(log)
if err := os.Rename(log, path.Join(dir, logBase)); err != nil {
...
```

**Comment by gyuho** [comment] 2016-02-18 09:52
@heyitsanthony Right! Happened after I started passing full path flag. Will fix. Thanks!

**Comment by xiang90** [comment] 2016-02-18 17:33
> agent1 2016-02-18 01:34:17.215567 C | etcdserver: save snapshot error: open agent.etcd/member/snap/0000000000000018-00000000033f8f30.snap: no such file or directory

This is different one since it prints out from etcdserver not agent.

**Comment by gyuho** [comment] 2016-02-18 17:37
@xiang90 Right. I am trying to reproduce this (because of the rename bug in agent code, I lost the log). Thanks.

**Comment by xiang90** [comment] 2016-02-18 18:21
This error is strange. It comes from https://github.com/coreos/etcd/blob/master/snap/snapshotter.go#L81.

I think the data-dir is removed while etcd is running, which is incorrect. Can you check if it is possible that we remove dir before fully stop etcd?

**Comment by gyuho** [comment] 2016-02-18 18:32
@xiang90 Ok thanks for pointing that out. I will try to see that specific behavior in more detail.

**Comment by xiang90** [comment] 2016-02-23 16:05
Closing this one since it does not appear for a long time. And we think this is probably a operational fault.

**Closed by xiang90** 2016-02-23 16:05 UTC
Labels: area/testing

**Comment by gyuho** [comment] 2016-02-23 17:48
Yeah seems resolved. Will revisit if it happens again.

**Comment by jaricftw** [comment] 2017-07-27 18:49
Just saying we are seeing the error intermittently in test, if we set the snapshot internal to be small (e.g. every 3 entries). 


> 2017-07-27 00:16:53.355221 E | snap: failed to remove broken snapshot file /tmp/raftexample428152788/boulder-raft-1-snap/0000000000000004-000000000000001a.snap
> --- PASS: TestWALReplay (8.75s)
> {"level":"panic","msg":"raft.go:609 open /tmp/raftexample428152788/boulder-raft-1-snap/0000000000000004-000000000000001a.snap: no such file or directory","time":"2017-07-27T00:16:53Z"}
> PASS
> panic: (*logrus.Entry) (0x10268c0,0xc4204374a0)

**Comment by heyitsanthony** [comment] 2017-07-27 19:28
@jaricftw what is `TestWALReplay`? it's not part of etcd...

**Comment by jaricftw** [comment] 2017-07-27 19:45
@heyitsanthony Oh sorry, that's my own unit test. What it does is simply start a three-node raft cluster, propose some requests, stop the cluster, and then restart the cluster to observe WAL replay.

**Comment by jaricftw** [comment] 2017-08-04 17:04
Shall we re-open this? I've seen it multiple times recently.

**Comment by xiang90** [comment] 2017-08-04 17:30
@jaricftw Create a new issue for it with reproduce steps.
