### ISSUE TITLE
etcd2-proxy does not load balance the requests to etcd, leading etcd2 restart

### ISSUE THREAD

**Issue by Vish0007** [coreos/etcd#5458] opened 2016-05-26 00:41 UTC
etcd Version: 2.2.0
curl -L http://127.0.0.1:2379/health
{"health": "true"}
etcd2 cluster size:5 and about 1200 etcd2-proxy nodes.

I observed etcd2 node is running out of file limits (40000) very often.
Further dwelling showed the etcd2 proxy is loading this particular node while there are other etcd2 4 nodes available.

I could verify this as an issue from an etcd2 proxy node.
test@cluster0 ~ $ sudo netstat -nap|grep etcd|grep 10.1.25.1|wc -l
2
test@cluster0 ~ $ sudo netstat -nap|grep etcd|grep 10.2.25.1|wc -l
53
test@cluster0 ~ $ sudo netstat -nap|grep etcd|grep 10.3.25.1|wc -l
26
test@cluster0 ~ $ sudo netstat -nap|grep etcd|grep 10.4.25.1|wc -l
2

As shown above, 10.2.25.1 is loaded while 10.1.25.1 is almost with no load.
The randomizing between the etcd2 cluster nodes does not help load balance the requests via etcd2 proxy.
This situation of loading a node (10.2.25.1) leads to fast consumption of file limits (40000) and frequent restarts of etcd2. The restarts make it still worst as there is one node less to share the load and keeps thrashing the etcd2 cluster.

**Comment by gyuho** [comment] 2016-05-26 01:14
> I observed etcd2 node is running out of file limits (40000) very often.

Do you mean the proxy nodes are using up the file descriptors or etcd nodes?

**Comment by xiang90** [comment] 2016-05-26 01:14
What is the configuration of the proxy?

The randomization is done through a number of proxies. For one proxy, it will try to stick with one etcd member. But for diffrent proxies, they should try to connect to different etcd members.

**Comment by Vish0007** [comment] 2016-05-26 14:43
@gyuho 
its etcd2 node (one of the five nodes involved in consensus and leader selection) and not the etcd2-proxy nodes. As there are many etcd2-proxy nodes hitting the same etcd2 node leading to exhaustion of file handle limit (40000).

@xiang90 
the etcd2-proxy configuration is same across the cluster i.e the initial-cluster parameter is same for all the etcd2-proxy nodes, the initial-cluster is list of etcd2 nodes.

**Comment by xiang90** [comment] 2016-05-26 14:58
@Vish0007 Probably the rand here is unseeded. So the randomization is not effective for your specific case. Are you able to modify some code and redeploy some of the proxies?

**Comment by Vish0007** [comment] 2016-05-26 16:37
Thats not an option for me :)
btw, what changes are you recommending in the etcd proxy?
until we have load balancer functionality this problem can appear with rand.

**Comment by xiang90** [comment] 2016-05-27 17:22
@Vish0007 I set up a 5 members cluster, and 100s of proxies. The 100s proxies do send requests to different members. So I am not sure what exactly happened in your case. Maybe some of your clients are setting consistent-read flag to true which force the requests to be sent to leader?

**Comment by xiang90** [comment] 2016-05-27 17:49
@mwitkow Have you seen this behavior in your environment? I cannot reproduce myself. etcd proxy seems to do the load balancing just fine.

**Comment by Vish0007** [comment] 2016-06-04 22:49
@xiang90 
can you please elaborate this more:
"Maybe some of your clients are setting consistent-read flag to true which force the requests to be sent to leader?"
how can I verify this behavior in my etcd proxy? Any particular configuration?

**Comment by xiang90** [comment] 2016-06-07 18:37
@Vish0007 On the other side, we do have plan to actually balance requests instead of balancing connections per proxy. But it would not happen anytime soon for v2 proxy (which is actually a gateway).

**Comment by xiang90** [comment] 2016-06-21 01:47
I am closing this due to low activity. Reopen if you have any related questions.

**Closed by xiang90** 2016-06-21 01:47 UTC
