### ISSUE TITLE
cluster's slave node start service start failure,but start success with command

### ISSUE THREAD

**Issue by tianhao** [coreos/etcd#4962] opened 2016-04-04 19:10 UTC
```
root@centos130:~/bin# etcd --version
etcd Version: 2.2.2
Git SHA: 6335fdc
Go Version: go1.4.2
Go OS/Arch: linux/amd64
root@centos130:~/bin#
```

```
root@centos130:~# systemctl cat etcd
# /usr/lib/systemd/system/etcd.service
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
# set GOMAXPROCS to number of processors
ExecStart=/bin/bash -c "GOMAXPROCS=$(nproc) /usr/bin/etcd --name=\"${ETCD_NAME}\" --data-dir=\"${ETCD_DATA_DIR}\" --listen-client-urls=\"${ETCD_LISTEN_CLIENT_URLS}\"
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
root@centos130:~#
```

master ip=192.168.0.129
etcd.conf:
```
# [member]
 ETCD_NAME=etcd0
 ETCD_DATA_DIR="/var/lib/etcd/etcd0"
 ETCD_LISTEN_PEER_URLS="http://192.168.0.129:2380"
 ETCD_LISTEN_CLIENT_URLS="http://192.168.0.129:2379,http://127.0.0.1:2379"
 #[cluster]
 ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.0.129:2380"
 ETCD_INITIAL_CLUSTER="etcd0=http://192.168.0.129:2380,etcd1=http://192.168.0.130:2380"
 ETCD_INITIAL_CLUSTER_STATE="new"
 ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
 ETCD_ADVERTISE_CLIENT_URLS="http://192.168.0.129:2379"
```

slave node ip=192.168.0.130
etcd.conf:
```
 # [member]
 ETCD_NAME=etcd1
 ETCD_LISTEN_PEER_URLS="http://192.168.0.130:2380"
 ETCD_LISTEN_CLIENT_URLS="http://192.168.0.130:2379,http://127.0.0.1:2379"
 #[cluster]
 ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.0.130:2380"
 ETCD_INITIAL_CLUSTER="etcd0=http://192.168.0.129:2380,etcd1=http://192.168.0.130:2380"
 ETCD_INITIAL_CLUSTER_STATE="existing"
 ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
 ETCD_ADVERTISE_CLIENT_URLS="http://192.168.0.130:2379"
```

master etcd service start success, but slave start failure:
journalctl -u etcd
```
4月 05 02:28:11 centos130 etcd[1602]: etcd Version: 2.2.2
4月 05 02:28:11 centos130 etcd[1602]: Git SHA: 6335fdc
4月 05 02:28:11 centos130 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
4月 05 02:28:11 centos130 systemd[1]: Failed to start Etcd Server.
4月 05 02:28:11 centos130 systemd[1]: Unit etcd.service entered failed state.
4月 05 02:28:11 centos130 systemd[1]: etcd.service failed.
4月 05 02:28:11 centos130 systemd[1]: etcd.service holdoff time over, scheduling restart.
4月 05 02:28:11 centos130 systemd[1]: Starting Etcd Server...
4月 05 02:28:11 centos130 etcd[1681]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.0.130:2379
4月 05 02:28:11 centos130 etcd[1681]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.0.130:2380
4月 05 02:28:11 centos130 etcd[1681]: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd0=http://192.168.0.129:2380,etcd1=http://192.168.0.130:2380
4月 05 02:28:11 centos130 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
4月 05 02:28:11 centos130 systemd[1]: Failed to start Etcd Server.
4月 05 02:28:11 centos130 systemd[1]: Unit etcd.service entered failed state.
4月 05 02:28:11 centos130 systemd[1]: etcd.service failed.
4月 05 02:28:12 centos130 systemd[1]: etcd.service holdoff time over, scheduling restart.
4月 05 02:28:12 centos130 systemd[1]: Starting Etcd Server...
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.0.130:2379
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.0.130:2380
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd0=http://192.168.0.129:2380,etcd1=http://192.168.0.130:2380
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
4月 05 02:28:12 centos130 etcd[1784]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.0.130:2380
4月 05 02:28:12 centos130 etcd[1784]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag
4月 05 02:28:12 centos130 etcd[1784]: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag
```

I start slave etcd success with command :
```
etcd --name etcd1 --initial-advertise-peer-urls http://192.168.0.130:2380 \
    --listen-peer-urls http://192.168.0.130:2380 \
    --listen-client-urls http://192.168.0.130:2379,http://127.0.0.1:2379 \
    --advertise-client-urls http://192.168.0.130:2379 \
    --initial-cluster-token etcd-cluster \
    --initial-cluster etcd0=http://192.168.0.129:2380,etcd1=http://192.168.0.130:2380\
    --initial-cluster-state existing 2>&1 >> ~/etcd.log &
```
after start it with command, master check it is health:
```
root@centos129:~# etcdctl cluster-health
member ecbcfa8d255c48d4 is healthy: got healthy result from http://192.168.0.130:2379
member f1da3dbb828c6792 is healthy: got healthy result from http://192.168.0.129:2379
cluster is healthy
root@centos129:~#
```

**Comment by xiang90** [comment] 2016-04-04 19:25
> I start slave etcd success with command :

So is this an etcd issue? Or a systemd question?

**Comment by tianhao** [comment] 2016-04-04 22:07
etcd issue with systemd
my os is CentOS7

**Comment by xiang90** [comment] 2016-04-04 22:15
@tianhao I do not really understand. From my understanding based on your original issue, etcd works without systemd, but it does not work when starts with systemd unit file. It seems like the problem is your systemd unit configuration or your environment to start the service. Also journalctl does not show all the logging before etcd exists. Probably try to get all the log first?

**Comment by xiang90** [comment] 2016-04-04 22:16
@tianhao https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service

**Comment by xiang90** [comment] 2016-04-10 18:02
I am closing this due to low activity. If you still have the issue and can provide more information, feel free to reopen. Thanks.

**Closed by xiang90** 2016-04-10 18:02 UTC

**Comment by tianhao** [comment] 2016-04-10 19:54
I rebuild my cluster, and this issue not happen, may be my vm software settings was wrong
