### ISSUE TITLE
etcdctl exec-watch not reliably triggered

### ISSUE THREAD

**Issue by petergardfjall** [coreos/etcd#4287] opened 2016-01-26 14:23 UTC
This issue describes a problem that is likely a duplicate of #2644 and  #1518, both of which have been closed, due to difficulties of reproducing the problem and/or the assumption that the behavior had been fixed in recent versions of etcd.

However, I'm seeing this issue on `CoreOS alpha (935.0.0)`.

I've set up a 3-node cluster in Vagrant following the instructions [here](https://coreos.com/os/docs/latest/booting-on-vagrant.html), running the `stable channel` edition.

Then, I've simply been playing with `etcd` according to the instructions in the [Getting started with etcd](https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html) guide.

On one host (`core-02`) I'm running 

    etcdctl exec-watch --recursive /messages -- sh -c 'echo $ETCD_WATCH_VALUE'

On host `core-01` I'm doing:

    etcdctl set /messages/msg1 '1'
    etcdctl set /messages/msg1 '2'
    etcdctl set /messages/msg1 '3'
    ...
    etcdctl set /messages/msg1 '15'

Although one would expect all numbers from 1 to 15 to be output on `core-02`, it only displays the following:

    7
    13

So, `exec-watch` is triggered somewhat arbitrarily.

This is on etcd2:

    > etcdctl --version
    etcdctl version 2.2.4

Some additional details on my setup:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
$ vagrant -v
Vagrant 1.7.4
$ uname -mrs
Linux 4.2.0-18-generic x86_64
```

**Comment by petergardfjall** [comment] 2016-01-26 14:34
I re-ran the command on `host2` with the `--debug` flag while running the following commands from `host1`

```
etcdctl set /messages/msg1 '1'
etcdctl set /messages/msg1 '2'
etcdctl set /messages/msg1 '3'
...
etcdctl set /messages/msg1 '10'
```

The output on `host2` now looks like this, which actually appears to indicate that the watch is being triggered on every `set` command, but the command output isn't always visible. Could this be some issue related to not properly flushing the output of the `exec-watch` command?

```
$ etcdctl --debug exec-watch --recursive /messages -- sh -c 'echo $ETCD_WATCH_VALUE'
start to sync cluster using endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://172.17.8.101:2379,http://172.17.8.102:2379,http://172.17.8.103:2379) after sync
Cluster-Endpoints: http://172.17.8.101:2379, http://172.17.8.102:2379, http://172.17.8.103:2379
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=0

cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3355
1
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3357
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3359
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3360
4
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3362
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3364
6
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3365
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3367
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3369
cURL Command: curl -X GET http://172.17.8.101:2379/v2/keys/messages?recursive=true&wait=true&waitIndex=3374

**Comment by gyuho** [comment] 2016-01-26 21:35
@petergardfjall  Thanks for detailed report. I will investigate this as soon as possible.

**Comment by gyuho** [comment] 2016-01-27 07:30
This does not happen in master branch, neither in 2.2.4 version that you are using.
I just double-checked that `exec-watch` command works properly. Could you try `goreman`
to set up local cluster? Link is here https://github.com/coreos/etcd#running-local-etcd-cluster.

I don't think this is an etcd issue. Maybe Vagrant is being too slow to respond.

**Comment by petergardfjall** [comment] 2016-01-27 08:21
@gyuho 

I am seeing the same problem when running via `goreman`, although the issue does not surface quite as often as in the Vagrant case. So, I followed the instructions in the aforementioned [link](https://github.com/coreos/etcd#running-local-etcd-cluster).

Then I set up an `exec-watch` listener as follows:

```
etcdctl --endpoint http://127.0.0.1:22379 exec-watch --recursive /messages -- sh -c 'echo -n "$ETCD_WATCH_VALUE\t"'
```
(the tab after each entry is just to make output line up to allow me to easily spot differences between different executions).

And after this, I execute the following script a couple of times:

```
for i in $(seq 1 100); do etcdctl --endpoint http://127.0.0.1:12379 set /messages/msg1 $i; done
```

In my setup, I'm seeing different output from the `exec-watch` script on almost all executions (one or a few numbers missing in the expected sequence -- `0..100`).

**Comment by gyuho** [comment] 2016-01-27 08:23
@petergardfjall Thanks! I will take a look again shortly.

**Comment by petergardfjall** [comment] 2016-01-27 08:25
Again, if i turn on debug output on the `exec-watch` command via `--debug`, I can see the 
```
cURL Command: curl -X GET http://127.0.0.1:22379/v2/keys/messages?recursive=true&wait=true&waitIndex=XXXX`
```
line for each `set` call, but in a few cases the output from the `exec-watch` command is missing.

**Comment by gyuho** [comment] 2016-01-27 09:01
@petergardfjall Sorry, I cannot reproduce it. For me, I get every single notification from the `set` command. I even ran `for i 1000`.

I see `exec-watch` command launches another goroutine in the background to copy the command output back to the Stdout. But even if I set command output directly to stdout without copying, I still get the same result. 

So could you try this code https://github.com/coreos/etcd/pull/4301? And let me know if it still misses? I will look into more tomorrow.

**Comment by gyuho** [comment] 2016-01-28 00:05
Kindly ping @petergardfjall. https://github.com/coreos/etcd/pull/4301 is merged. Can you try again with master branch? Hope it helps reduce the delays in your environment.

**Comment by petergardfjall** [comment] 2016-01-28 07:11
@gyuho 
I've been somewhat delayed by other pressing matters. I'll try to get back to you during the day though.

**Comment by petergardfjall** [comment] 2016-01-28 12:45
@gyuho 
I've tried out the patch and I am no longer able to reproduce the problem. Nice work.
Case closed?

**Comment by xiang90** [comment] 2016-01-28 15:59
@petergardfjall Thanks!

**Closed** 2016-01-28 15:59 UTC

**Comment by gyuho** [comment] 2016-01-28 18:44
@petergardfjall That's great. Thanks for report!
