### ISSUE TITLE
Watch with index (waitIndex) does not work

### ISSUE THREAD

**Issue by gradywang** [coreos/etcd#5276] opened 2016-05-05 00:20 UTC
Hi guys,

I deployed the etcd cluster with 3 nodes under docker, append my cluster information as below:
```
# curl -L http://9.111.255.50:2379/version | python -m json.tool
{
    "etcdcluster": "2.3.0",
    "etcdserver": "2.3.2"
}

# etcdctl -C http://9.111.254.41:2379,http://9.111.255.10:2379,http://9.111.255.50:2379 member list
4a2c4ac424ea87c2: name=etcd1 peerURLs=http://9.111.254.41:2380 clientURLs=http://9.111.254.41:2379,http://9.111.254.41:4001 isLeader=false
9f564d76c2326b1a: name=etcd0 peerURLs=http://9.111.255.10:2380 clientURLs=http://9.111.255.10:2379,http://9.111.255.10:4001 isLeader=true
f45d70d240a351bc: name=etcd2 peerURLs=http://9.111.255.50:2380 clientURLs=http://9.111.255.50:2379,http://9.111.255.50:4001 isLeader=false

# etcdctl -C http://9.111.254.41:2379,http://9.111.255.10:2379,http://9.111.255.50:2379 cluster-health
member 4a2c4ac424ea87c2 is healthy: got healthy result from http://9.111.254.41:2379
member 9f564d76c2326b1a is healthy: got healthy result from http://9.111.255.10:2379
member f45d70d240a351bc is healthy: got healthy result from http://9.111.255.50:2379
```

I want to watch a key to get its modification in the past, but I found it does not work, my test steps as below:

Step1: Put the key-value pair which I will watch:
```
# curl http://9.111.255.50:2379/v2/keys/key -XPUT -d value="Hello world" | python -m json.tool
{
    "action": "set",
    "node": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 99,
        "value": "Hello world"
    }
}
```

Step2: Watch it one terminal:
```
# curl  http://9.111.255.50:2379/v2/keys/key?wait=true   // It work well, after doing step3, it returned.
{"action":"update","node":{"key":"/key","value":"Hello world","modifiedIndex":100,"createdIndex":99},"prevNode":{"key":"/key","value":"Hello world","modifiedIndex":99,"createdIndex":99}}
```

Step3: Update this key in another terminal:
```
# curl http://9.111.255.50:2379/v2/keys/key -XPUT -d value="Hello world" -d prevExist=true | python -m json.tool
{
    "action": "update",
    "node": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 100,
        "value": "Hello world"
    },
    "prevNode": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 99,
        "value": "Hello world"
    }
}
```

Step4: Update this key again:
```
curl http://9.111.255.50:2379/v2/keys/key -XPUT -d value="Hello world" -d prevExist=true | python -m json.tool
{
    "action": "update",
    "node": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 101,
        "value": "Hello world"
    },
    "prevNode": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 100,
        "value": "Hello world"
    }
}
```

Step5: Watch this key to get the modification with index 101:
```
# curl 'http://9.111.255.50:2379/v2/keys/key?wait=true&waitIndex=101'
curl: (52) Empty reply from server
```

I think the watched value of step5 should be:
```
{
    "action": "update",
    "node": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 101,
        "value": "Hello world"
    },
    "prevNode": {
        "createdIndex": 99,
        "key": "/key",
        "modifiedIndex": 100,
        "value": "Hello world"
    }
}
```
But it returned an empty reply. Can some one help me on this issue? Maybe I was wrong in somewhere.

**Comment by gradywang** [comment] 2016-05-05 00:21
In addition, I deployed the etcd cluster with the official docker image:
```
docker run -d \
 -v /usr/share/ca-certificates/:/etc/ssl/certs \
 -p 4001:4001 -p 2380:2380 -p 2379:2379 \
 --name etcd quay.io/coreos/etcd \
 -name etcd0 \
 -advertise-client-urls http://${HostIP0}:2379,http://${HostIP0}:4001 \
 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
 -initial-advertise-peer-urls http://${HostIP0}:2380 \
 -listen-peer-urls http://0.0.0.0:2380 \
 -initial-cluster-token etcd-cluster-1 \
 -initial-cluster etcd0=http://${HostIP0}:2380,etcd1=http://${HostIP1}:2380,etcd2=http://${HostIP2}:2380 \
 -initial-cluster-state new
```

**Comment by gradywang** [comment] 2016-05-05 00:31
May be this is a bug for this version, I have tried with another version:
```
# curl -L http://9.111.255.50:2379/version | python -m json.tool
{
    "etcdcluster": "2.2.0",
    "etcdserver": "2.2.5"
}
```

Watch with index (waitIndex) works well.

**Comment by xiang90** [comment] 2016-05-05 01:40
@gradywang I tried on 2.3.2 and current master and could not reproduce it.

/cc @heyitsanthony @gyuho Can you give it a try?

**Comment by heyitsanthony** [comment] 2016-05-05 02:31
Tried it on 2.3.2, 2.3.3, and 2.2.5. All seem to work.

**Comment by gyuho** [comment] 2016-05-05 02:45
Yeah I tried and can't reproduce. @gradywang What version has this behavior?

**Comment by gradywang** [comment] 2016-05-05 04:08
I pull the official image `quay.io/coreos/etcd` directly to deploy my etcd cluster under docker:
# curl -L http://9.111.255.50:2379/version | python -m json.tool
{
    "etcdcluster": "2.3.0",
    "etcdserver": "2.3.2"
}

**Comment by xiang90** [comment] 2016-05-05 13:51
@gradywang I tried `2.3.2`, but failed to reproduce? Can you try to reproduce from a fresh cluster? In the example you provided, there are 100 events already happened. I am not what they are so I cannot reproduce the exact case you did.

**Comment by gradywang** [comment] 2016-05-06 00:13
@xiang90, thank you very much. I will try later.

**Comment by xiang90** [comment] 2016-05-07 02:08
Closing. Reopen if you can reproduce it.

**Closed by xiang90** 2016-05-07 02:08 UTC
