### ISSUE TITLE
TTLs expire prematurely - appears related to etcd elections

### ISSUE THREAD

**Issue by onsi** [coreos/etcd#2508] opened 2015-03-13 20:32 UTC
We are seeing keys with TTLs expire prematurely (e.g. ~10 seconds too soon).  We managed to isolate two of these incidents and compare logs from our various components with etcd's logs. 

### Incident 1:

 We get the following timeline of events (unfortunately etcd's logs only have second-level granularity - we've verified that all our machines are within ~100ms of each other so we don't think clock-drift obscures this picture dramatically):

What etcd logs indicate:
11:26:58 : a new etcd term (term 33) begins, an election is attempted but appears to fail
11:26:59 : another etcd term (term 34) begins, this time a leader is elected

What our logs indicate:
11:26:58.7: one of our components (let's call it `A`) attempts to CAS a key with a TTL
11:26:59.4: `A`'s CAS **succeeds** the new key should have a TTL of 10s
11:26:59.9: a component watching the key is notified that the key has expired
11:26:63: `A` attempts another CAS - this time it fails (the key does not exist)

Here are the etcd output logs for this event:
https://drive.google.com/file/d/0B55cOnKV7PrQNkhxbHRwVGR6Zkk/view?usp=sharing

I can try to fetch the wal/snapshots if you need them.

---

### Incident 2:

In the second incident we see the following:

16:23:07: one of our components (let's call it `A`) attempts to CAS a key with a TTL
16:23:09: an etcd election begins then ends within this one second
16:23:12: a component watching the key is notified that the key has expired (this actually makes sense, there would have only been 5 seconds left on the TTL when `A` attempts the CAS.
16:23:13: `A` reports that the CAS failed

---

These two incidents are quite different - both share one feature in common: an etcd election occurs and we end up failing to maintain the presence of a key with a TTL.

**Comment by xiang90** [comment] 2015-03-13 20:38
@onsi 
The clock on the machines are not perfectly synced? The TTL keys are managed by the leader. So if the clock is not synced, the new leader might remove the key "early" in the view of clients.

At etcd side, we should probably refresh all TTL keys if there is a leader election.

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:40
Some additional information:

- Our etcd cluster is 3 nodes
- We don't see any indication as to why one of the nodes tries to initiate an election in the first place for both incidents.  Over the course of ~24hrs these are the only two times when there are elections.
- In the first incident, there is only one candidate in term 33, the other two nodes are followers, but they both reject the vote request.
- about ~5s after each successful election, we see a bunch of etcd server request timeouts in the logs of all the nodes -- two of the nodes have one log line with the server timeout, and the other node has tens of them

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:43
@xiang90 There's phyically no way to know whether any two clocks are every perfectly synced, but as far as we can tell we can upper bound on the skew is at most 100ms, probably quite less.  The TTLs on the nodes that are disappearing are 10s, so several orders of magnitude greater than our upper bound on the time skew.

**Comment by xiang90** [comment] 2015-03-13 20:45
> In the first incident, there is only one candidate in term 33, the other two nodes are followers, but they both reject the vote request.

This is normal. A follower can deny a candidate if the candidate is not suitable to be a leader (ensure by raft)

> about ~5s after each successful election

We are aware of this issue. etcd does not resend proposals internally. It should be solved soon (we actually have fixed it in current master, but have not tested it).

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:47
@xiang90 any idea why an election would be held in the first place?  We don't see anything in the logs prior to initiation of the new term indicating a missed heartbeat or anything like that.

**Comment by xiang90** [comment] 2015-03-13 20:47
> There's phyically no way to know whether any two clocks are every perfectly synced.

I mean within 1 second. Sorry for the confusion. I added it to my original comment later, but you still beat me.

> The TTLs on the nodes that are disappearing are 10s

10 second or tens of second? If it is 10 second, I highly suspect that the removal of key is simply caused by the failure of proposals (the request timeout you saw above).

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:47
Exactly 10s.

**Comment by xiang90** [comment] 2015-03-13 20:48
>  any idea why an election would be held in the first place?  We don't see anything in the logs prior to initiation of the new term indicating a missed heartbeat or anything like that.

etcd does not log that out in etcd 2.0.x. We should improve that for sure.

**Comment by xiang90** [comment] 2015-03-13 20:50
@onsi @Amit-PivotalLabs I think I have enough context. I will try to reproduce it myself and look into the log you provided. If you can reliably reproduce it, it would also be a great help.

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:52
Can you please confirm that if a client request a CAS of a node and then receives a successful response, then this update has been replicated across the cluster, rather than just acknowledged by the server handling the request?  Assuming a successful response means replication, I don't understand the following:

11:26:59.4: A's CAS succeeds the new key should have a TTL of 10s
11:26:59.9: a component watching the key is notified that the key has expired
11:26:63: A attempts another CAS - this time it fails (the key does not exist)

At 59.4 the CAS succeeds and updates the TTL, so it should have 10s to live, but at 59.9 (half second later) the key is gone.

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 20:52
Yes, we'll try to reproduce it.

**Comment by Amit-PivotalLabs** [comment] 2015-03-13 23:10
Do you know some way to trigger some node to start an election in a running cluster?  We saw the issue where you guys added a fake time provider for testing purposes, but we'd like to trigger this against a "real" running cluster.

**Comment by Amit-PivotalLabs** [comment] 2015-03-14 00:00
To reproduce:

We have an etcd cluster running locally inside Linux containers (inside a VM), with the following startup commands:

1. `etcd --name etcd_z1-0 --data-dir /var/vcap/store/etcd --heartbeat-interval 50 --election-timeout 1000 --listen-peer-urls http://0.0.0.0:7001 --listen-client-urls http://0.0.0.0:4001 --initial-advertise-peer-urls http://10.244.16.10:7001 --advertise-client-urls http://10.244.16.10:4001 --initial-cluster etcd_z1-0=http://10.244.16.10:7001 --initial-cluster-state new`
2. `etcd --name etcd_z1-1 --data-dir /var/vcap/store/etcd --heartbeat-interval 50 --election-timeout 1000 --listen-peer-urls http://0.0.0.0:7001 --listen-client-urls http://0.0.0.0:4001 --initial-advertise-peer-urls http://10.244.16.14:7001 --advertise-client-urls http://10.244.16.14:4001 --initial-cluster etcd_z1-0=http://10.244.16.10:7001,etcd_z1-1=http://10.244.16.14:7001,etcd_z1-2=http://10.244.16.18:7001 --initial-cluster-state existing`
3. `etcd --name etcd_z1-2 --data-dir /var/vcap/store/etcd --heartbeat-interval 50 --election-timeout 1000 --listen-peer-urls http://0.0.0.0:7001 --listen-client-urls http://0.0.0.0:4001 --initial-advertise-peer-urls http://10.244.16.18:7001 --advertise-client-urls http://10.244.16.18:4001 --initial-cluster etcd_z1-0=http://10.244.16.10:7001,etcd_z1-1=http://10.244.16.14:7001,etcd_z1-2=http://10.244.16.18:7001 --initial-cluster-state existing`

with the appropriate `etcdctl member add`s in between.

We then have a heartbeater updating a node every 2 seconds and setting the TTL to 4 second, as well as a watcher continually watching that node.  Finally, we set iptable rules to block incoming and outgoing tcp traffic to the peer port on the leader, and then remove the rules as soon as we see indication in the etcd server logs that something has happened (we're tailing logs from all three nodes while all this is happening).  We see blank lines in the watcher output, indicating a removal of the watched node.

heartbeater.sh
```
ETCD_CLUSTER='http://10.244.16.10:4001,http://10.244.16.14:4001,http://10.244.16.18:4001'

while true; do
  sleep 2
  etcdctl -C $ETCD_CLUSTER set foo/bar "`date`" --ttl 4
done
```

watcher.sh
```
ETCD_CLUSTER='http://10.244.16.10:4001,http://10.244.16.14:4001,http://10.244.16.18:4001'

while true; do
  etcdctl -C $ETCD_CLUSTER watch foo/bar
done
```

iptable commands
```
iptables -D OUTPUT  -p tcp --destination-port 7001 -j DROP && iptables -D INPUT -i wihkqso5v4dp-1 -p tcp --destination-port 7001 -j DROP
```

heartbeater output
```
Fri Mar 13 16:58:19 PDT 2015
Fri Mar 13 16:58:21 PDT 2015
Fri Mar 13 16:58:23 PDT 2015
Fri Mar 13 16:58:25 PDT 2015
Fri Mar 13 16:58:27 PDT 2015
Fri Mar 13 16:58:29 PDT 2015
Fri Mar 13 16:58:31 PDT 2015
Fri Mar 13 16:58:37 PDT 2015
Fri Mar 13 16:58:39 PDT 2015
Fri Mar 13 16:58:41 PDT 2015
Fri Mar 13 16:58:44 PDT 2015
```

watcher output
```
Fri Mar 13 16:58:19 PDT 2015
Fri Mar 13 16:58:21 PDT 2015
Fri Mar 13 16:58:23 PDT 2015
Fri Mar 13 16:58:25 PDT 2015
Fri Mar 13 16:58:27 PDT 2015
Fri Mar 13 16:58:29 PDT 2015

Fri Mar 13 16:58:31 PDT 2015

Fri Mar 13 16:58:37 PDT 2015
Fri Mar 13 16:58:39 PDT 2015
Fri Mar 13 16:58:41 PDT 2015
Fri Mar 13 16:58:44 PDT 2015
```

**Comment by xiang90** [comment] 2015-03-14 00:05
@Amit-PivotalLabs 

> Do you know some way to trigger some node to start an election in a running cluster?

We are working on a function-tester for etcd at https://github.com/coreos/etcd/tree/master/tools/functional-tester.

You can write simulation case very easy in the future:
https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-tester/failure.go#L72-L94

> To reproduce:

Thanks! I will look into this very soon.

**Comment by xiang90** [comment] 2015-03-15 16:32
@Amit-PivotalLabs I have reproduced the issue: `To reproduce:`

I think it is "normal" and let me explain what actually happened. 

Here is what I observed, just as what you have observed: 

heartbeat.sh
```
Sun Mar 15 09:02:58 PDT 2015
Sun Mar 15 09:03:01 PDT 2015
Sun Mar 15 09:03:03 PDT 2015
Sun Mar 15 09:03:11 PDT 2015
Sun Mar 15 09:03:13 PDT 2015
``` 

wait.sh
```
Sun Mar 15 09:03:01 PDT 2015

Sun Mar 15 09:03:03 PDT 2015
Sun Mar 15 09:03:11 PDT 2015
```

I forced a leader election right before real time `Sun Mar 15 09:03:03 PDT 2015`, and we "observed" a expiration between the value "Sun Mar 15 09:03:01 PDT 2015" and value "Sun Mar 15 09:03:03 PDT 2015". It seems to be wired since we successfully did two heartbeat with value "Sun Mar 15 09:03:01 PDT 2015" and  "Sun Mar 15 09:03:03 PDT 2015".

But let's see what exactly in etcd's wal:
```
4	       205	norm	method=PUT path="/1/foo/bar" val="Sun Mar 15 09:03:01 PDT 2015"
   4	       206	norm	method=SYNC time="2015-03-15 09:03:01.555054135 -0700 PDT"
   4	       207	norm	method=SYNC time="2015-03-15 09:03:02.056672395 -0700 PDT"
   5	       208	norm	noop
   5	       209	norm	method=SYNC time="2015-03-15 09:03:03.222095535 -0700 PDT"
   5	       210	norm	method=SYNC time="2015-03-15 09:03:03.513440272 -0700 PDT"
   5	       211	norm	method=SYNC time="2015-03-15 09:03:04.012585615 -0700 PDT"
   5	       212	norm	method=SYNC time="2015-03-15 09:03:04.51346819 -0700 PDT"
   5	       213	norm	method=SYNC time="2015-03-15 09:03:05.012538535 -0700 PDT"
   5	       214	norm	method=SYNC time="2015-03-15 09:03:05.51347099 -0700 PDT"
   5	       215	norm	method=SYNC time="2015-03-15 09:03:06.013273784 -0700 PDT"
   5	       216	norm	method=SYNC time="2015-03-15 09:03:06.513621244 -0700 PDT"
   5	       217	norm	method=SYNC time="2015-03-15 09:03:07.013515464 -0700 PDT"
   5	       218	norm	method=SYNC time="2015-03-15 09:03:07.513484484 -0700 PDT"
   5	       219	norm	method=SYNC time="2015-03-15 09:03:08.01283611 -0700 PDT"
   5	       220	norm	method=SYNC time="2015-03-15 09:03:08.512866964 -0700 PDT"
   5	       221	norm	method=SYNC time="2015-03-15 09:03:09.013412372 -0700 PDT"
   5	       222	norm	method=PUT path="/1/foo/bar" val="Sun Mar 15 09:03:03 PDT 2015"
   5	       223	norm	method=SYNC time="2015-03-15 09:03:09.513464149 -0700 PDT"
```

The `noop` indicates a new leader elected between `09:03:02.056672395` and `2015-03-15 09:03:03.222095535`. The actual `Update TTL` succeed between `09:03:09.013412372` and `09:03:09.513464149`. Before the `Update TTL` arrived, the key has been expired. I prefixed the output with real time when it finished and confirmed it again.

What happened internally inside `go-etcd` is: 
1. there is a `Update TTL` issued during the leader election.
2. the `Update TTL` blocked for 5 second and failed. (here is what etcd should improve. unblock all immediately when there is an leader election) During this 5 seconds, the key has been expired.
3. the `Update TTL` is retried by `go-etcd` and succeed with output `Sun Mar 15 09:03:03 PDT 2015`.

**Comment by xiang90** [comment] 2015-03-15 16:39
@onsi @Amit-PivotalLabs 

This is actually still quite different from `incident1`. 

In `incident1`, you actually observed: 
`11:26:59.4: A's CAS succeeds the new key should have a TTL of 10s`. 

And I assume `11:26:59.4` is the realtime when it succeed rather than when it is issued. And the key was expired 0.5 second after that.

I have tried to reproduce `incident1` but failed. :( 

@onsi Can you try to get the wal files of that incident? The wal files may contain that piece of information, if you stopped the cluster right after `incident1`.

**Comment by xiang90** [comment] 2015-03-15 17:15
@onsi 

Another thing I would like to add

```
What etcd logs indicate:
11:26:58 : a new etcd term (term 33) begins, an election is attempted but appears to fail
11:26:59 : another etcd term (term 34) begins, this time a leader is elected

What our logs indicate:
11:26:58.7: one of our components (let's call it A) attempts to CAS a key with a TTL
11:26:59.4: A's CAS succeeds the new key should have a TTL of 10s
11:26:59.9: a component watching the key is notified that the key has expired
```

Fact: etcd cluster dropped all proposals and could not commit for at least one second (for term 33, which lasted at least 1 second), since there were two continuous leader election. (we should improve this at etcd side)

Term 33 might begin between `11:26:58` and `11:26:59`. If term 33 began at `11:26:58`, then nothing should happen between `11:26:58.00` to `11:26:59.00`. If term 33 begin at `12:26:59`, the nothing should happen between `11:26:59.00` to `11:27:00.00`. And I high suspect that the leader election term33 began around `11:26:58.500`. (in 8b357's log, it received two heartbeats in term33 at 11:26:58, which toke around 200ms). So nothing should happen from `11:26:58.500` to `11:26:59.500`.

But you observed a proposal issued after `11:26:58.7` was accepted and committed before `11:26:59.4`. This seems to be conflicting with my observation that term 33 was just around this time and nothing should happen (even take 200ms clock-drift into consideration).

**Comment by amitkgupta** [comment] 2015-03-16 06:28
@xiang90, I think we've identified a few things in this issue:

- etcd should have improved logging for the cause of an election when an election is triggered
- etcd should fast-fail requests made while the cluster is busy electing (I assume this is what you're suggesting when you say "unblock all immediately when there is a leader election")
- it is normal for a request to potentially fail, and require a retry to succeed, if made during a leader election; empirically this can take upwards of 6s so we need to set our TTLs higher
- it would be nice if etcd server logs had more precise timestamps like the wal's nanosecond precision

It's still not clear how a CAS containing a TTL update can succeed at `11:26:59.4` but at `11:26:59.9` a component watching the key is notified that the key has expired; we have not reproduced this and there's no chance of recovering the wals at this point.  We saw this behaviour regularly (every few hours) in both experiments we've run so far, I strongly suspect we'll see it again in the next run unless we change something about the system (e.g. increase TTLs) before then.  In case we do see it again we now know where to look.

**Comment by xiang90** [comment] 2015-03-16 06:39
We will definitely make the improvement. 

For something like `incident2` and the issue you just reproduced, I recommend you to set a higher TTL for now to deal with the potential proposal blocking caused by leader election.

> It's still not clear how a CAS containing a TTL update can succeed at 11:26:59.4 but at 11:26:59.9 a component watching the key is notified that the key has expired;

I am more concerned with this one too. Before the CAS succeed at `11:26:59.4`, the key should still have around 5 second TTL (assume you update the key every 5 second). The CAS with TTL update even made the TTL shorter. And this makes no sense to me. 

I have looked through the related code and tried to reproduce it, but I still cannot locate the problem. 

> We saw this behavior regularly (every few hours) in both experiments we've run so far

If it is possible, can you please keep the WAL, snap file and all related log (etcd and your application side)? So we can try to dig into the problem?

**Comment by amitkgupta** [comment] 2015-03-16 06:56
> If it is possible, can you please keep the WAL, snap file and all related log (etcd and your application side)? So we can try to dig into the problem?

Will do.  To clarify, the behaviour we saw regularly was TTLs expiring apparently prematurely, can't say how often they were like Incident 1, Incident 2, or something else.

Anything we need to know about getting all the logs/files you mentioned?  The last couple times this has happened, it happens over night and we don't notice til perhaps 12+ hrs later.  Will this make it difficult to retrieve any of the required info?

**Comment by xiang90** [comment] 2015-03-16 14:48
> Anything we need to know about getting all the logs/files you mentioned?

Yes. You can set max-snap and max-wal to a large enough number.

**Comment by xiang90** [comment] 2015-04-01 16:52
@onsi @Amit-PivotalLabs Any luck to get this reproduced?

**Comment by amitkgupta** [comment] 2015-04-02 03:56
@xiang90 not yet, we've been making changes to our system before our next set of stress tests, it may be less likely to happen with our new changes.  Feel free to close this issue; if by some chance it still manifests in some form we will re-open.

**Comment by popsikle** [comment] 2015-04-02 04:14
Hmm, I have seen this happen once or twice, but never really thought anything of it because of other factors that I figured caused my issues.  Im my situation my network interfaces were > 75%  utilized (due to a docker pull of a > 1.5GB container) and heartbeat traffic in and out of etcd was delayed.  This only happened in dev as I was running etcd on my container hosts.  My exp is probably irrelevant to this conversation, but JIC...

**Comment by xiang90** [comment] 2015-04-13 02:24
Covered in https://github.com/coreos/etcd/issues/2660.

**Closed by xiang90** 2015-04-13 02:24 UTC
Labels: waiting for reply
