### ISSUE TITLE
when etcd version is 3.0 and api version is 2.0, disaster recovery v2 key is failed, but use v3 method is ok. I am very confused.

### ISSUE THREAD

**Issue by strugglingyouth** [coreos/etcd#7218] opened 2017-01-23 09:47 UTC
when etcd version is 3.0 and api version is 2.0, disaster recovery v2 key is failed, but use v3 method is ok. I am very confused.Whether version 3.0 is not use api 2.0 method?

use api 2.0 method ， the error is as follows：

> 2017-01-23 15:36:24.203213 C | etcdmain: database file (/tmp/etcd_backup/member/snap/db index 0) does not match with snapshot (index 2980298).

I would also like to know if there is a way to recover from heat, without rebuilding the new cluster。

**Comment by gyuho** [comment] 2017-01-23 17:44
I tested setting up v3.0 cluster and wrote v2 keys. And tried recovery and works for me? Do you have exact step to reproduce?

v3.0, v3.1 support v2 API by the way

**Comment by strugglingyouth** [comment] 2017-01-24 02:16
@gyuho 

I follow this tutorial：

https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#disaster-recovery

![etcd-png](https://cloud.githubusercontent.com/assets/10249666/22231360/15596340-e21e-11e6-867a-9f173d08c047.png)

**Comment by xiang90** [comment] 2017-01-24 02:18
@strugglingyouth Can you please provide a step by step example for us to reproduce your problem?

**Comment by strugglingyouth** [comment] 2017-01-24 07:02
I use etcd version is 3.0 and api version is 2.0,And use api 2.0 backup tool (etcdctl backup --data-dir /home/etcd/ --backup-dir /tmp/etcd_backup),but no db files are displayed during recovery.I did not see DB files in the backup directory.The complete error is:
>2017-01-24 15:02:06.074253 I | etcdmain: etcd Version: 3.0.4
2017-01-24 15:02:06.074449 I | etcdmain: Git SHA: d53923c
2017-01-24 15:02:06.074488 I | etcdmain: Go Version: go1.6.3
2017-01-24 15:02:06.074536 I | etcdmain: Go OS/Arch: linux/amd64
2017-01-24 15:02:06.074598 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-01-24 15:02:06.074821 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-01-24 15:02:06.078284 I | etcdmain: listening for peers on http://localhost:2380
2017-01-24 15:02:06.081160 I | etcdmain: listening for client requests on localhost:2379
2017-01-24 15:02:06.234469 I | etcdserver: recovered store from snapshot at index 200020
2017-01-24 15:02:06.234822 I | etcdserver: name = default
2017-01-24 15:02:06.235058 I | etcdserver: force new cluster
2017-01-24 15:02:06.235344 I | etcdserver: data dir = /home/etcd_backup/
2017-01-24 15:02:06.235488 I | etcdserver: member dir = /home/etcd_backup/member
2017-01-24 15:02:06.235617 I | etcdserver: heartbeat = 100ms
2017-01-24 15:02:06.235740 I | etcdserver: election = 1000ms
2017-01-24 15:02:06.235899 I | etcdserver: snapshot count = 10000
2017-01-24 15:02:06.236073 I | etcdserver: advertise client URLs = http://localhost:2379
2017-01-24 15:02:06.294417 I | etcdserver: discarding 2 uncommitted WAL entries 
2017-01-24 15:02:06.297847 I | etcdserver: forcing restart of member 59cf35eecf01 in cluster 59cf35eecf02 at commit index 205335
2017-01-24 15:02:06.300836 I | raft: 59cf35eecf01 became follower at term 20
2017-01-24 15:02:06.301136 I | raft: newRaft 59cf35eecf01 [peers: [e4c1981a5360013e], term: 20, commit: 205335, applied: 200020, lastindex: 205335, lastterm: 20]
2017-01-24 15:02:06.301885 I | api: enabled capabilities for version 3.0
2017-01-24 15:02:06.302141 I | membership: added member e4c1981a5360013e [http://10.94.107.113:2380] to cluster 59cf35eecf02 from store
2017-01-24 15:02:06.302363 I | membership: set the cluster version to 3.0 from store
2017-01-24 15:02:06.321449 I | etcdmain: stopping listening for client requests on localhost:2379
2017-01-24 15:02:06.321827 I | etcdmain: stopping listening for peers on http://localhost:2380
2017-01-24 15:02:06.322113 C | etcdmain: database file (/home/etcd_backup/member/snap/db) of the backend is missing


Operation as shown in the picture above.

**Comment by xiang90** [comment] 2017-01-24 07:33
@strugglingyouth Can you try with 3.0.17 or 3.1.0 release?

**Comment by strugglingyouth** [comment] 2017-01-25 02:17
@xiang90 

I used 3.0.4 version.

But now I have found the problem. My systems store v2 and v3 data at once ,so use v2's backup method is failed, use v3's backup method is ok. And i delete all data, only use v2's data test ,it is successful.

**Comment by xiang90** [comment] 2017-01-25 02:19
v2 backup only backups v2 data, not v3. I would still suggest you try etcd 3.0.17.

I am closing this since the problem is resolved.

**Closed by xiang90** 2017-01-25 02:19 UTC
