### ISSUE TITLE
Got panic in raft.go

### ISSUE THREAD

**Issue by allencloud** [coreos/etcd#6787] opened 2016-11-02 12:45 UTC
Hi, All, 

Today my colleague ran into a panic of docker daemon.

Here is the log message of docker daemon:
```
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: panic: runtime error: index out of range
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: goroutine 3396 [running]:
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: panic(0x1a90660, 0xc82000e020)
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: github.com/coreos/etcd/raft.(raft).maybeCommit(0xc821e28240, 0xc822018990)
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:382 +0x302
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: github.com/coreos/etcd/raft.(raft).removeNode(0xc821e28240, 0x49b7a3e5811c3b72)
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:842 +0x59
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: github.com/coreos/etcd/raft.(*node).run(0xc821f1a550, 0xc821e28240)
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:330 +0xca4
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: created by github.com/coreos/etcd/raft.RestartNode
Nov 02 19:04:52 10-10-237-29 dockerd[28586]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
```

maybe it is related with raft. Here is my thought:
```
func (r *raft) maybeCommit() bool {
	// TODO(bmizerany): optimize.. Currently naive
	mis := make(uint64Slice, 0, len(r.prs))
	for id := range r.prs {
		mis = append(mis, r.prs[id].Match)
	}
	sort.Sort(sort.Reverse(mis))
	mci := mis[r.quorum()-1]
	return r.raftLog.maybeCommit(mci, r.Term)
}
```
when len(r.prs) == 0, then `mis[r.quorum()-1]` got panic.

related to https://github.com/docker/swarmkit/issues/1727

**Comment by gyuho** [comment] 2016-11-02 17:30
What version of raft does it use? Seems duplicate of https://github.com/coreos/etcd/issues/5482

/cc @xiang90

**Comment by xiang90** [comment] 2016-11-02 17:33
This should already be fixed on etcd/raft side as @gyuho mentioned. I guess you should wait for swarmkit's reply on this.

**Closed by xiang90** 2016-11-02 17:33 UTC
