### ISSUE TITLE
etcd3.0 OOM

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6352] opened 2016-09-05 14:28 UTC
When client operations were executed continuously, the size of snapshot was rising all the time and got OOM at last.
Does the db file have upper limit value?
What laws are there during the generation of the db file? 

Another question：
If the speed of client request is 7k/s, How long will the etcd works normally?

Thanks!

**Comment by xiang90** [comment] 2016-09-05 14:36
OOM is not caused by etcd, it is because your machine does not have enough memory. v3 has a default 2GB size limit. Normally 2GB is more than enough for storing all your metadata even if you have a really large cluster. There are other factors that can contribute to your memory usage. You need to monitor your usage closely yourself.

For your specific case, we need to know more to help. For example, what is your workload looks like? What is the key size? What is the value size? Do you overwrite one key? Do you use v3 or v2 API?

**Comment by shuqilou** [comment] 2016-09-06 13:38
Thanks for your reply! 
Our runtime log is as follows:

    2016-09-06 00:06:02.945457 I | fileutil: purged file member1/member/wal/0000000000000006-    00000000003a62a8.wal successfully
    2016-09-06 00:06:03.260689 I | etcdserver: start to snapshot (applied: 7257994, lastsnap: 7247972)
    2016-09-06 00:06:03.264649 I | etcdserver: saved snapshot at index 7257994
    2016-09-06 00:06:03.264824 I | etcdserver: compacted raft log at 7252994
    2016-09-06 00:06:03.899567 I | rafthttp: receiving database snapshot [index:7274746, from d8f1cd487ed7cf9d] ...
    2016-09-06 00:06:05.439160 I | snap: saved database snapshot to disk [total bytes: 614359040]
    2016-09-06 00:06:05.439231 I | rafthttp: received and saved database snapshot [index: 7274746, from: d8f1cd487ed7cf9d] successfully
    2016-09-06 00:06:05.439377 I | raft: fd565958b082af1f [commit: 7261274, lastindex: 7261274, lastterm: 20] starts to restore snapshot [index: 7274746, term: 20]
    2016-09-06 00:06:05.439441 I | raft: log [committed=7261274, applied=7261274, unstable.offset=7261275, len(unstable.Entries)=0] starts to restore snapshot [index: 7274746, term: 20]
    2016-09-06 00:06:05.439490 I | raft: fd565958b082af1f restored progress of 16e5d3bac81bd492 [next = 7274747, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
    2016-09-06 00:06:05.439518 I | raft: fd565958b082af1f restored progress of d8f1cd487ed7cf9d [next = 7274747, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
    2016-09-06 00:06:05.439537 I | raft: fd565958b082af1f restored progress of fd565958b082af1f [next = 7274747, match = 7274746, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
    2016-09-06 00:06:05.439559 I | raft: fd565958b082af1f [commit: 7274746] restored snapshot [index: 7274746, term: 20]
    2016-09-06 00:06:05.439816 I | etcdserver: applying snapshot at index 7257994...
    2016-09-06 00:06:05.440034 C | backend: cannot open database at member1/member/snap/db (cannot allocate memory)
    2016-09-06 00:06:05.440051 I | etcdserver: finished applying incoming snapshot at index 7257994
    2016-09-06 00:06:05.440342 I | etcdserver: raft applied incoming snapshot at index 7274746
    panic: cannot open database at member1/member/snap/db (cannot allocate memory)
    goroutine 162 [running]:
    panic(0xd46e00, 0xc82cbc1120)
    /tools/go/src/runtime/panic.go:481 +0x3e6
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc8201d08c0, 0x11e1a40, 0x1f, 0xc86e75b4d0, 0x2, 0x2)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x191
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend(0xc84deec6e0, 0x16, 0x5f5e100, 0x2710, 0x0)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:106 +0x1ee
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.NewDefaultBackend(0xc84deec6e0, 0x16, 0x0, 0x0)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:100 +0x53
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applySnapshot(0xc8200b8240, 0xc865202080, 0xc8200ee580)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:663 +0x7af
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc8200b8240, 0xc865202080, 0xc8200ee580)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:616 +0x60
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func2(0x7fcf054db360, 0xc865202040)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:597 +0x32
    github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc8651f61e0)
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:160 +0x323
    created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
    /root/h00273181/etcd-release-3.0.1/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x27d
The size of snap file is small while the size of db file is huge which increases all the time. The Key size is 30Byte and the Value size is 40Byte.

**Comment by xiang90** [comment] 2016-09-06 19:38
> The size of snap file is small while the size of db file is huge which increases all the time. The Key size is 30Byte and the Value size is 40Byte.

How many keys have you put into etcd? You should expect the db size to grow as you put more keys. The size would roughly be (30+40) * N bytes.

**Comment by xiang90** [comment] 2016-09-06 19:39
Also is your machine running 32bit or 64bit?

**Comment by shuqilou** [comment] 2016-09-07 15:12
Our machine is 64bit and we keep on putting keys into etcd and then keep on deleting keys and cycle the processing. Normally speaking, when we delete keys in the etcd, the size of db file should decrease and when we end the process above, our keys in etcd are not so many while the db file is very big. It really confuses me a lot.
We set InitialMmapSize equals to 5G, 3 million times put and delete operations just exhausts our storage space. Can you help us to explain this phenomenon?

**Comment by xiang90** [comment] 2016-09-07 15:14
>  when we delete keys in the etcd, the size of db file should decrease and when we end the process above,

This is incorrect. etcd keeps all versions of your key by default. You need to compact your keyspace. Also the panic is probably due to the modification of mmap size. We do not really can help you debug the modified version of etcd.

**Comment by nekto0n** [comment] 2016-09-12 20:51
I think adding `--auto-compaction-retention` option to etcd should help (as well as issuing compaction requests manually).

**Comment by xiang90** [comment] 2016-09-14 04:33
I am going to close this issue. I think the root cause is clear. Let's know if you have any further questions.

**Closed by xiang90** 2016-09-14 04:33 UTC
