### ISSUE TITLE
Always "Internal Server Error"

### ISSUE THREAD

**Issue by snowdreamist** [coreos/etcd#2266] opened 2015-02-10 03:39 UTC
I'm using etcd 2.0 release version and set up a 5 instances cluster by DNS record discovery.
My services use etcd to do server discovery and heartbeating, about 20 instances sending requests to etcd every 5s.
Each time the request the service sending are:
1. PUT new values with ttl to two files (In different directory)
2. Update ttl to an existed directory
And each service watching for a directory to get notified when change happened. TTL update changes are filtered by client.

That's all my scenarios, and I'm keeping receive "Internal Service Error" From etcd when PUT new value or update ttl with no X-Etcd-Index header and no related logs I found in etcd log. The interval between each errors could be smaller than 1s or larger than 10 hour.

I just cannot figured out what's happening, could you guys take a look at this?

More details, the put/update path looks like:

__Dir__: /v2/keys/service/mongodb/cluster/bj/instance/mongo0
__File__: /v2/keys/service/mongodb/cluster/bj/instance/mongo0/registry
__File__:/v2/keys/routing/mongo0-bj
Both of these nodes has a ttl equals 15s. The value of registry is quite small, just { "host": "1234xxx" }

And all 5 etcd instances are in one local network connected through 1000Mbps ethernet network, the ping latency among these instances is smaller than 1ms.

Any response is appreciated.

**Comment by xiang90** [comment] 2015-02-10 04:17
@snowdreamist Can you please provide etcd log? Are you seeing raft term increase? Did leader election happen? 

Can you try to reproduce the problem with a simple setup. We can help you debug the problem with log or more detailed information.

**Comment by snowdreamist** [comment] 2015-02-10 05:02
of course, I'll record related info in 1 or 2 days. @xiang90

**Comment by snowdreamist** [comment] 2015-02-10 12:19
OK, I got a piece of log may related to this error:
2015/02/10 19:45:17 raft: b3cf14a3ff886f6e [term: 7] received a MsgVote message with higher term from 4d18ffbde916ed55 [term: 8]
2015/02/10 19:45:17 raft: b3cf14a3ff886f6e became follower at term 8
2015/02/10 19:45:17 raft: b3cf14a3ff886f6e [logterm: 7, index: 610357, vote: 0] voted for 4d18ffbde916ed55 [logterm: 7, index: 610357] at term 8
2015/02/10 19:45:17 raft.node: b3cf14a3ff886f6e lost leader a607f655c64595cc at term 8
2015/02/10 19:45:17 raft.node: b3cf14a3ff886f6e elected leader 4d18ffbde916ed55 at term 8
2015/02/10 19:45:17 sender: the connection with a607f655c64595cc becomes active
2015/02/10 19:45:17 rafthttp: starting client stream to 4d18ffbde916ed55 at term 8
2015/02/10 19:45:22 etcdhttp: unexpected __error__: etcdserver: request timed out
2015/02/10 19:45:23 etcdhttp: unexpected __error__: etcdserver: request timed out
2015/02/10 19:45:23 etcdhttp: unexpected __error__: etcdserver: request timed out
2015/02/10 20:07:39 etcdserver: start to snapshot (applied: 620132, lastsnap: 610127)
2015/02/10 20:07:39 etcdserver: compacted log at index 620132
2015/02/10 20:07:39 etcdserver: saved snapshot at index 620132
2015/02/10 20:07:52 filePurge: successfully removed file /var/lib/etcd/default.etcd/wal/0000000000000039-000000000008b307.wal
2015/02/10 20:07:52 filePurge: successfully removed file /var/lib/etcd/default.etcd/snap/0000000000000007-000000000008b306.snap

And the ts exactly match the error log of our service log's ts.
@xiang90

**Comment by xiang90** [comment] 2015-02-11 05:56
@snowdreamist 
```
2015/02/10 19:45:17 rafthttp: starting client stream to 4d18ffbde916ed55 at term 8
```
There is a leader election happened at 19:45:17.

```
2015/02/10 19:45:22 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:45:23 etcdhttp: unexpected error: etcdserver: request timed out
2015/02/10 19:45:23 etcdhttp: unexpected error: etcdserver: request timed out
```

There are three timeout happened after around 5 seconds.

There might be proposal during leader election. And the proposal waiting timeout is around 5 seconds.

I highly suspect that the timeout is caused by the leader lost. 
So you need to find out if the leader election is expected. Was the leader machine down for a while? Was there a network problem? Or the leader machine was slow for a while?

**Comment by xiang90** [comment] 2015-02-11 05:59
@snowdreamist In the future, we might improve this by buffering proposals and trying to resend them if they are lost due to leader lost.

**Comment by snowdreamist** [comment] 2015-02-11 08:12
Thanks for reply! I'll take a look at the server log.
By the way, I found our DNS server (bind9) is somehow unstable, and I use domain name instead of IP address in the SRV record for setting up etcd cluster. Will it affect etcd?
And when will an etcd node notice that the leader is lost? Heart beat timed out?
@xiang90

**Comment by AdoHe** [comment] 2015-02-11 08:23
@snowdreamist In Raft Protocol, the leader must send heartbeats(empty AppendEntries RPCs) to maintain the authority, if the `electionTimeout` elapses with no RPCs, the follower will assume that the leader crashes. Hope this will help you...

**Comment by xiang90** [comment] 2015-02-11 19:50
@snowdreamist I am closing this. Reopen if you have any follow up.

**Closed by xiang90** 2015-02-11 19:50 UTC
Labels: wontfix

**Comment by snowdreamist** [comment] 2015-02-16 11:10
I haven't found why internal error still always happened, I can't be sure if it is a network issue or not. Bug the connections between services and mongodb instances is pretty stable.
And I found another issue, if the internal server error happened, etcd may __block__ the connection forever.

**Comment by xiang90** [comment] 2015-02-16 16:27
>  etcd may block the connection forever.

We are solving this.

/cc @yichengq

**Comment by yichengq** [comment] 2015-02-16 22:31
@snowdreamist Do you have more detailed context, or TCP status at that time, or log for the block issue?
From your description, I think it is more reasonable to say that the block of the connection causes the internal server error.
