### ISSUE TITLE
e2e: too many goroutines error

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#6785] opened 2016-11-02 03:44 UTC
I saw the below error during `TestCtlV3EndpointHealthWithAuth` of e2e test:

```
Too many goroutines running after all test(s).
1 instances of:
syscall.Syscall(...)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(...)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(...)
        /usr/local/go/src/os/file_unix.go:140 +0x86
FAIL    github.com/coreos/etcd/e2e      4.204s
PASS
Too many goroutines running after all test(s).
1 instances of:
os.(*Process).Release(...)
```

It happens almost once or twice in 10 times testing.

**Comment by xiang90** [comment] 2016-11-03 16:04
@gyuho Can you take a look? Thanks!

**Comment by gyuho** [comment] 2016-11-03 16:04
Sure will try to reproduce.

**Comment by gyuho** [comment] 2016-11-03 18:21
@mitake Can you get the full trace when you hit this issue again? I can't reproduce in my side.
My guess is that file descriptor was not closed properly or reused by another process.

Thanks!

**Comment by mitake** [comment] 2016-11-08 01:29
@gyuho sure, I'll share the trace maybe next week (I'm attending to KubeCon this week)

**Comment by mitake** [comment] 2016-11-15 15:47
@gyuho I changed the sleeping interval here: https://github.com/coreos/etcd/blob/master/pkg/testutil/leak.go#L94 from 50ms to 500ms, and the problem disappeared. Maybe enshorting the value will increase the probability of reproduction on your nevironment?

BTW, is the leaked goroutine check important for e2e? The e2e test itself just invokes etcd and etcdctl, so I feel leaking in the test code doesn't mean serious bugs in etcd itself.

**Comment by xiang90** [comment] 2016-11-15 15:49
@mitake Probably `os.(*Process).Release(...)` did not finish within 300ms? I agree this is probably not a serious problem. But it would be nice if we can locate the problem and fix it if easy to do.

**Comment by mitake** [comment] 2016-11-15 15:56
@xiang90 Yes, some goroutines seems to be struggling at closing fd in the interval. I'm repeating the test several times but the part of `os.(*Process).Release(...)` disappeared. Only reproducible is
```
Too many goroutines running after all test(s).
1 instances of:
syscall.Syscall(...)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(...)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(...)
        /usr/local/go/src/os/file_unix.go:140 +0x61
FAIL    github.com/coreos/etcd/e2e      3.762s
```

Anyway, I'll dig the problem deeper tomorrow.

**Comment by mitake** [comment] 2016-11-16 13:13
I'm trying to reproduce with `-trace` flag of `go test`, but it seems that the flag makes the probability of reproduction lower...

**Comment by xiang90** [comment] 2016-11-16 15:51
I do not think we should spend too much time on this. If we know this is not related to etcd and the possibility to reproduce is so low, let's close (or forget about this and move this out of 3.1) this for now. /cc @heyitsanthony

**Comment by heyitsanthony** [comment] 2016-11-16 17:32
I can't reproduce this.

**Comment by xiang90** [comment] 2016-11-16 17:34
OK. @mitake I am closing this out. Let's reopen if this happens more frequently.

**Closed by xiang90** 2016-11-16 17:34 UTC
Labels: area/testing

**Comment by mitake** [comment] 2016-11-17 02:24
@xiang90 @heyitsanthony I agree, let's close this for now.
