### ISSUE TITLE
BUG:etcd cluster reliability

### ISSUE THREAD

**Issue by ffbin** [coreos/etcd#6406] opened 2016-09-12 09:03 UTC
I use 3 machines(A/B/C) to set up etcd cluster. 
Machine A create temp node A on etcd cluster and update TTL every 300ms.
Machine B create temp node B on etcd cluster and update TTL every 300ms.
Machine c create temp node C on etcd cluster and update TTL every 300ms.
Then reboot machine A, machine B update node B TTL failed, httpcode is 404, machine C update node C TTL failed, httpcode is 404.

**Comment by ffbin** [comment] 2016-09-12 11:36
@xiang90 ,hi, my etcd version is etcd-2.2.4. I will write a simple script to reproduce the issue i described later. 
If machine A is not the leader, we can update the key?

**Comment by xiang90** [comment] 2016-09-12 11:56
@ffbin 

> If machine A is not the leader, we can update the key?

It should.

**Comment by ffbin** [comment] 2016-09-13 13:08
[103_log.txt](https://github.com/coreos/etcd/files/469828/103_log.txt)
[176_log.txt](https://github.com/coreos/etcd/files/469831/176_log.txt)
[177_log.txt](https://github.com/coreos/etcd/files/469832/177_log.txt)


@xiang90 .Hi, I create etcd cluster with machine 103/176/177, start command is "nohup ./etcd --initial-advertise-peer-urls http://${LOCAL_DSS_ADDR}:${DSS_LEAD_PORT} --initial-cluster default=http://${LOCAL_DSS_ADDR}:${DSS_LEAD_PORT} --advertise-client-urls http://${LOCAL_DSS_ADDR}:${DSS_LISTEN_PORT} --listen-peer-urls http://${LOCAL_DSS_ADDR}:${DSS_LEAD_PORT} --listen-client-urls http://${LOCAL_DSS_ADDR}:${DSS_LISTEN_PORT} >> log.out".
Then machine 103/176/177 create tmp node on  etcd cluster and update TTL every 300ms.
I use command "curl -L http://10.120.185.176:4001/v2/stats/leader" to find leader is machine 176.
This is result:
{"leader":"36e86ab78717bf20","followers":{"26830401b52980be":{"latency":{"current":0.001846,"average":0.0036024973302822205,"standardDeviation":0.0019507177054984759,"minimum":0.000844,"maximum":0.043545},"counts":{"fail":2,"success":3933}},"7658919be10a9cbd":{"latency":{"current":0.002288,"average":0.0033704399999999967,"standardDeviation":0.001743021193018436,"minimum":0.000804,"maximum":0.02294},"counts":{"fail":0,"success":3950}}}}

Then i reboot machine 103, machine 177/176 update tmp node TTL failed, httpcode is 404.

**Comment by xiang90** [comment] 2016-09-13 13:14
```
2016-09-13 20:38:43.695456 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.708373022s > 1s]
2016-09-13 20:39:13.689414 W | rafthttp: the clock difference against peer 36e86ab78717bf20 is too high [7.186010049s > 1s]
2016-09-13 20:39:13.695635 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.709596053s > 1s]
2016-09-13 20:39:43.690531 W | rafthttp: the clock difference against peer 36e86ab78717bf20 is too high [7.18504036s > 1s]
2016-09-13 20:39:43.695772 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.710260094s > 1s]
2016-09-13 20:40:13.690751 W | rafthttp: the clock difference against peer 36e86ab78717bf20 is too high [7.184552696s > 1s]
2016-09-13 20:40:13.695927 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.710672614s > 1s]
2016-09-13 20:40:43.690942 W | rafthttp: the clock difference against peer 36e86ab78717bf20 is too high [7.184582131s > 1s]
2016-09-13 20:40:43.696097 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.710553353s > 1s]
2016-09-13 20:41:13.691130 W | rafthttp: the clock difference against peer 36e86ab78717bf20 is too high [7.184457263s > 1s]
2016-09-13 20:41:13.696192 W | rafthttp: the clock difference against peer 7658919be10a9cbd is too high [10.710938898s > 1s]
```

etcd printed out quite a few warnings. Please fix your clock (using ntp for example) and try again. I believe the clock difference is the root cause. Closing this issue.

**Closed by xiang90** 2016-09-13 13:14 UTC

**Comment by ffbin** [comment] 2016-09-14 07:43
@xiang90 ,i fix my  clock using ntp and have a try.
Machine 103/176/177, 176 is the leader.
Before i reboot 103, i use command "curl -L http://10.120.185.176:4001/v2/keys/master" on machine 176 can get the message:
{"action":"get","node":{"key":"/master","value":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000e\u00001\u00000\u0000.\u00001\u00007\u00007\u0000.\u00001\u00001\u00002\u0000.\u00001\u00007\u00007\u0000\u001\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000e\u00001\u00000\u0000.\u00001\u00007\u00007\u0000.\u00001\u00001\u00002\u0000.\u00001\u00007\u00007\u0000\u001\u0002","expiration":"2016-09-14T06:41:39.127717195Z","ttl":1,"modifiedIndex":622,"createdIndex":11}}
After i reboot 103, i use command "curl -L http://10.120.185.176:4001/v2/keys/master" on machine 176 can get the message:{"errorCode":100,"message":"Key not found","cause":"/master","index":645}.

Update tmp node TTL failed is failed, httpcode is 404.

[103_log.txt](https://github.com/coreos/etcd/files/471509/103_log.txt)
[176_log.txt](https://github.com/coreos/etcd/files/471510/176_log.txt)
[177_log.txt](https://github.com/coreos/etcd/files/471511/177_log.txt)

**Comment by xiang90** [comment] 2016-09-14 07:51
Try with 5 seconds TTL with 1 second update time. Let me know if the problem still exists.

**Comment by ffbin** [comment] 2016-09-18 11:03
@xiang90 , I have try with 5 seconds TTL with 1 second update time, the problem still exists.

[103_log.txt](https://github.com/coreos/etcd/files/478649/103_log.txt)
[176_log.txt](https://github.com/coreos/etcd/files/478650/176_log.txt)
[177_log.txt](https://github.com/coreos/etcd/files/478651/177_log.txt)

**Comment by xiang90** [comment] 2016-09-19 09:44
I cannot reproduce this. I created a 3 member clusters. Setting TTL keys, keep on updating it, and kill random member periodically, but everything seems to be fine.

Can you please provide a script that I can run to reproduce your issue on any local machine?

I should be able to do ./reproduce.sh to reproduce the issue you see.

**Comment by ffbin** [comment] 2016-09-19 12:11
@xiang90 , Can you share me your code about created a 3 member clusters and set TTL keys and keep on updating it. I want to compare your code and my code to find the difference. And I will provide reproduce.sh later.

**Comment by xiang90** [comment] 2016-09-19 12:28
@ffbin 

Well. Ideally you should provide the reproduce script as I mentioned before. Since you did not, we have to guess what you did. I have no idea why you would like to compare them, I hope you can share us what you had at hand.

But anyway, here is my simple script:

on one member's machine:
```bash
./etcdctl set foo bar -ttl=5
for i in `seq 1 100000`;
        do
                ETCDCTL_API=2 ./etcdctl update foo bar -ttl=5
		sleep 1
        done
```

Kill the other members randomly, and expect the script always succeeds.

It works for me.

**Comment by ffbin** [comment] 2016-09-20 13:45
@xiang90 , my code is like this: 
SPS_INT32 WriteToString
(
    const SPS_CHAR *pcData,
    SPS_SIZE_T   size_tSize,
    SPS_SIZE_T   size_tLen,
    std::string *pstrReturn
)
{
    if (SPS_NULL_PTR != pstrReturn)
    {
        pstrReturn->append(pcData, size_tSize * size_tLen);
        SPS_RET_VAL(size_tSize * size_tLen);
    }
    else
    {
        SPS_RET_VAL(0);
    }
}

typedef signed int              SPS_INT32;
typedef long                    SPS_LONG;

int main()
{
    while (1)
    {
        CURL *pCurl;
        curl_global_init(CURL_GLOBAL_ALL);
        pCurl = curl_easy_init();

        std::string strUrl("10.177.112.177:4001/v2/keys/master");
        std::string strBuffer;
        curl_easy_reset(pCurl);
        curl_easy_setopt(pCurl, CURLOPT_URL, strUrl.c_str());
        curl_easy_setopt(pCurl, CURLOPT_WRITEFUNCTION, &WriteToString);
        curl_easy_setopt(pCurl, CURLOPT_WRITEDATA, &strBuffer);
        curl_easy_setopt(pCurl, CURLOPT_TIMEOUT, 2L);

        SPS_LONG  i64HttpCode;
        SPS_INT32 i32CurlCode = curl_easy_perform(pCurl);
        if (CURLE_OK == i32CurlCode)
        {
            printf("curl_easy_perform success.\n");
            SPS_INT32 i32Ret;

            i32Ret = curl_easy_getinfo(pCurl, CURLINFO_RESPONSE_CODE, &i64HttpCode);
            rapidjson::Document jsonDocReturn;
            jsonDocReturn.Parse(strBuffer.c_str());
            if (i64HttpCode / 10 == 20)
            {
                printf("Curl get success.\n");

                /* update ttl */
				....
            }
            else
            {
                printf("Curl get failed.\n");
            }
        }
        else
        {
            printf("curl_easy_perform failed.\n");
        }
    }

    return 0;
}

I get node content first, if success, then update ttl.But if i reboot one machine, get node content will failed.If my use mode is error?

**Comment by xiang90** [comment] 2016-09-20 15:27
Can you provide a simple script that I can use to reproduce the issue? 

There might be a bug in your user code. I would suggest you to use etcdctl to reproduce it.
