### ISSUE TITLE
etcd doesn't start after crash

### ISSUE THREAD

**Issue by zaytsevfuu** [coreos/etcd#7477] opened 2017-03-10 17:34 UTC
```
etcd --version
etcd Version: 3.0.15
Git SHA: fc00305
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

```
etcd[3867]: the server is already initialized as member before, starting as etcd member...
etcd[3867]: listening for peers on http://localhost:2380
etcd[3867]: listening for client requests on localhost:2379
etcd[3867]: recovered store from snapshot at index 1250125
etcd[3867]: name = default
etcd[3867]: data dir = /var/etcd/data
etcd[3867]: member dir = /var/etcd/data/member
etcd[3867]: heartbeat = 100ms
etcd[3867]: election = 1000ms
etcd[3867]: snapshot count = 10000
etcd[3867]: advertise client URLs = http://localhost:2379
etcd[3867]: ignored file 0000000000000000-0000000000000000.wal.broken in wal
etcd[3867]: ignored file 0000000000000003-00000000000632f6.wal.broken in wal
etcd[3867]: ignored file 0000000000000009-0000000000119e78.wal.broken in wal
etcd[3867]: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 1209069
etcd[3867]: 8e9e05c52164694d state.commit 1209069 is out of range [1250125, 1250125]
etcd[3867]: panic: 8e9e05c52164694d state.commit 1209069 is out of range [1250125, 1250125]
etcd[3867]: goroutine 1 [running]:
etcd[3867]: panic(0xd450a0, 0xc82000f200)
etcd[3867]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc8201beb80, 0x12375a0, 0x2b, 0xc820042140, 0x4, 0x4)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x191
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc8201b4270, 0x10, 0x8e9e05c52164694d, 0x1272ed, 0x0, 0x0, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:942 +0x2a2
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.newRaft(0xc8201378d8, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:225 +0x8ff
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode(0xc8201378d8, 0x0, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:213 +0x45
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.restartNode(0xc820218420, 0xc8201a6630, 0x29, 0xc820137d78, 0x0, 0x0, 0x0, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/raft.go:369 +0x7c7
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc820218420, 0x0, 0x0, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:348 +0x430e
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc820202000, 0x0, 0x0, 0x0)
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:374 +0x245f
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x2101
etcd[3867]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x21e
systemd[1]: kube-etcd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
etcd[3867]: main.main()
etcd[3867]:         /home/gyuho/go/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
systemd[1]: Failed to start Kubernetes etcd cluster.
systemd[1]: kube-etcd.service: Unit entered failed state.
systemd[1]: kube-etcd.service: Failed with result 'exit-code'.
```

**Comment by gyuho** [comment] 2017-03-10 17:53
> server is already initialized as member before, starting as etcd member...

This says the machine had etcd before. What version of etcd were you running?

Could be duplicate of https://github.com/coreos/etcd/issues/5664#issuecomment-229844849.

Thanks.

**Comment by gyuho** [comment] 2017-03-14 16:13
ping?

**Comment by gyuho** [comment] 2017-03-23 20:35
@zaytsevfuu I am closing this due to low activity. Please check out https://github.com/coreos/etcd/issues/5664. If it's not the same issue, please create a new issue.

**Closed by gyuho** 2017-03-23 20:35 UTC
