### ISSUE TITLE
TestMetricDbSizeDefrag fails in proxy test mode

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#9302] opened 2018-02-08 15:12 UTC
```
--- FAIL: TestMetricDbSizeDefrag (2.51s)
	metrics_test.go:84: when db size is growing, db size (196608) and db size in use (192512) is expected to be equal
```

https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/4091/console

in proxy tests

**Comment by yudai** [comment] 2018-02-08 21:27
@gyuho Can I see the detail of the test case? (Can I run the test locally?)

**Comment by gyuho** [comment] 2018-02-08 21:33
@yudai Sorry, don't have much details, another failure

```
=== RUN   TestMetricDbSizeDefrag
WARNING: 2018/02/08 18:05:00 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing context canceled"; Reconnecting to {localhost:77032179972776892950 0  <nil>}
WARNING: 2018/02/08 18:05:00 grpc: addrConn.transportMonitor exits due to: context canceled
--- FAIL: TestMetricDbSizeDefrag (2.60s)
	metrics_test.go:84: when db size is growing, db size (200704) and db size in use (196608) is expected to be equal
```

Seems machine-specific, can't reproduce either in my local machine:

```go
go test -v -tags cluster_proxy -run TestMetricDbSizeDefrag
```

**Comment by yudai** [comment] 2018-02-08 21:56
@gyuho Thanks for the info.

From the log, apparently the db size varies every time.
If I understand correctly, even when `+build cluster_proxy`,  it replaces just `toGRPC`
I guess that there are concurrent test cases running at the same time, or the  db is not cleaned up when the test case starts. Getting those two metrics are not an atomic operation, so it can be not equal when there are other requests from the out side of the test case.

**Comment by yudai** [comment] 2018-02-08 23:49
I think I succeeded to reproduce the test failure without the tag.

The test case issues 25 put requests. When they are handled by a single `batchTX` in the backend, that's fine. However, when there are some slow requests (maybe because the machine is just slow?), `unsefePut()` calls for those requests are committed by multiple transactions. In this case, boltdb shows a bit inefficient behavior that leaves some free pages.

I think, it turned out that  "when db size is growing, db size and db size in use is expected to be equal" is not always true, so we can simply remove this check from the test case.

**Closed** 2018-02-12 17:46 UTC
