### ISSUE TITLE
no logs in the journal when running with rkt

### ISSUE THREAD

**Issue by f0** [coreos/etcd#5779] opened 2016-06-27 16:46 UTC
Hi,

if i run etcd with rkt (the official provided aci) and systemd, i do not see the etcd logs.
Is there a way to get the logs into the journal?

regards f0

**Comment by gyuho** [comment] 2016-06-27 16:48
Seems related to https://github.com/coreos/etcd/issues/5449.

**Comment by f0** [comment] 2016-06-27 16:50
@gyuho  maybe, but i see no logs on stdout and no logs in the journal... etcd version is 2.3.6

**Comment by gyuho** [comment] 2016-06-27 16:51
You should be able to get logs from journald... Can you give us a way to reproduce? Like how you run etcd with rkt? I will take a look.

**Comment by f0** [comment] 2016-06-27 16:57
systemd file
https://gist.github.com/f0/7aa9b9ac70ef4331b1fdc9ac3ee4953e

journal output
https://gist.github.com/f0/0d7410e72cc95953bf3c612e1bb289a4

rkt version
'''
rkt Version: 1.7.0
appc Version: 0.8.4
Go Version: go1.6.1
Go OS/Arch: linux/amd64
Features: -TPM
'''

**Comment by f0** [comment] 2016-06-27 17:03
also testet with the latest rkt version (1.9.1) no change

**Comment by gyuho** [comment] 2016-06-27 23:45
@f0 Think with newer rkt, I see the same problem. 

```bash
# RKT_VERSION=1.9.1
sudo ./rkt trust --prefix coreos.com/etcd
sudo ./rkt --debug run --volume data-dir,kind=host,source=/tmp --mds-register=false coreos.com/etcd:v3.0.0-beta.0

sudo ./rkt trust --prefix coreos.com/etcd
sudo ./rkt --debug run --stage1-name=coreos.com/rkt/stage1-coreos:1.3.0 coreos.com/etcd:v3.0.0-beta.0

<<COMMENT
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.3.0
image: using image from local store for image name coreos.com/etcd:v3.0.0-beta.0
stage0: Preparing stage1
stage0: Writing image manifest
stage0: Loading image sha512-2bdba926abef05d7397e4977a9acb33ddddd9b60d9a168186763ac1b12e5293b
stage0: Writing image manifest
stage0: Writing pod manifest
run: group "rkt" not found, will use default gid when rendering images
stage0: Setting up stage1
stage0: Wrote filesystem to /var/lib/rkt/pods/run/8f1296c4-38ac-46f8-a0ed-7abc0230b752
stage0: Pivoting to filesystem /var/lib/rkt/pods/run/8f1296c4-38ac-46f8-a0ed-7abc0230b752
stage0: Execing /init
networking: loading networks from /etc/rkt/net.d
networking: loading network default with type ptp
stage1: warning: error setting journal ACLs, you'll need root to read the pod journal
  └─group "rkt" not found
stage1: warning: no volume specified for mount point "data-dir", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
stage1: creating an empty volume folder for sharing: "sharedVolumes/etcd-data-dir"
Spawning container rkt-8f1296c4-38ac-46f8-a0ed-7abc0230b752 on /var/lib/rkt/pods/run/8f1296c4-38ac-46f8-a0ed-7abc0230b752/stage1/rootfs.
Press ^] three times within 1s to kill container.
Failed to create directory /var/lib/rkt/pods/run/8f1296c4-38ac-46f8-a0ed-7abc0230b752/stage1/rootfs/sys/fs/selinux: Read-only file system
Failed to create directory /var/lib/rkt/pods/run/8f1296c4-38ac-46f8-a0ed-7abc0230b752/stage1/rootfs/sys/fs/selinux: Read-only file system
/etc/localtime is not a symlink, not updating container timezone.
systemd 225 running in system mode. (-PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Linux!

Set hostname to <rkt-8f1296c4-38ac-46f8-a0ed-7abc0230b752>.
Initializing machine ID from container UUID.
Failed to install release agent, ignoring: File exists
[  OK  ] Created slice -.slice.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket.
[  OK  ] Created slice system.slice.
[  OK  ] Created slice system-prepare\x2dapp.slice.
[  OK  ] Started Pod shutdown.
[  OK  ] Started etcd Reaper.
         Starting Journal Service...
[  OK  ] Started Journal Service.
         Starting Prepare minimum e...chrooted applications...
[  OK  ] Started Prepare minimum en...r chrooted applications.
[  OK  ] Started Application=etcd Image=coreos.com/etcd.
[  OK  ] Reached target rkt apps target.
COMMENT
```
```
journalctl
```
```
Jun 27 16:40:04 gyuho sudo[4333]:    gyuho : TTY=pts/2 ; PWD=/home/gyuho/rkt-v1.9.1 ; USER=root 
Jun 27 16:40:04 gyuho sudo[4333]: pam_unix(sudo:session): session opened for user root by gyuho(
Jun 27 16:40:05 gyuho kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Jun 27 16:40:05 gyuho NetworkManager[710]: <warn>  [1467070805.5145] device (vethc8359a35): fail
Jun 27 16:40:05 gyuho systemd-udevd[4364]: Could not generate persistent MAC address for vethc83
Jun 27 16:40:05 gyuho avahi-daemon[753]: Joining mDNS multicast group on interface vethc8359a35.
Jun 27 16:40:05 gyuho avahi-daemon[753]: New relevant interface vethc8359a35.IPv4 for mDNS.
Jun 27 16:40:05 gyuho avahi-daemon[753]: Registering new address record for 172.16.28.1 on vethc
Jun 27 16:40:05 gyuho kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Jun 27 16:40:05 gyuho NetworkManager[710]: <info>  [1467070805.5183] manager: (vethc8359a35): ne
Jun 27 16:40:05 gyuho NetworkManager[710]: <info>  [1467070805.5204] device (vethc8359a35): link
Jun 27 16:40:05 gyuho NetworkManager[710]: <info>  [1467070805.5228] devices added (path: /sys/d
Jun 27 16:40:05 gyuho NetworkManager[710]: <info>  [1467070805.5228] device added (path: /sys/de
Jun 27 16:40:06 gyuho avahi-daemon[753]: Joining mDNS multicast group on interface vethc8359a35.
Jun 27 16:40:06 gyuho avahi-daemon[753]: New relevant interface vethc8359a35.IPv6 for mDNS.
Jun 27 16:40:06 gyuho avahi-daemon[753]: Registering new address record for fe80::a4e9:fcff:fe3f
Jun 27 16:40:08 gyuho ntpd[2049]: Listen normally on 13 vethc8359a35 [fe80::a4e9:fcff:fe3f:3b18%
Jun 27 16:40:08 gyuho ntpd[2049]: new interface(s) found: waking up resolver

# no etcd logs...
```

@jonboulle 

Could anybody in `rkt` team help on this? Maybe I am using it wrong.

Thanks!

**Comment by f0** [comment] 2016-06-28 16:17
any news here?

**Comment by yifan-gu** [comment] 2016-06-29 01:31
what's the systemd version?

**Comment by f0** [comment] 2016-06-29 06:04
```
systemctl --version      
systemd 225
-PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
$ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by lucab** [comment] 2016-06-29 08:26
I think this may be a request for #5449. I just tried and can confirm that etcd is directly shipping its logs to journald. @f0: you should be able to see them with `sudo journalctl -M rkt-$UUID` as shown [in rkt doc](https://github.com/coreos/rkt/blob/master/Documentation/commands.md#accessing-logs-via-journalctl). You can also inspect logs merged from multiple containers with journactl `-m` switch.

**Comment by f0** [comment] 2016-06-29 10:59
@lucab   hm i assumed i can see the logs for my systemd unit..... why does etcd log directly to the journal and not to stdout.
Now i need to find the uuid, and thats not easy with multiple etcd containers running..... (hopfully rkt supports names in the near future)

**Comment by lucab** [comment] 2016-06-29 13:26
> Now i need to find the uuid, and thats not easy with multiple etcd containers running..... (hopefully rkt supports names in the near future)

How do you run those multiple containers? rkt already supports custom annotation (that's what kubernetes uses to distinguish pods) but in this case you would need something that systemd-* understand too.

I think the cleanest way is to use a service template in conjunction with `--uuid-file-save=`. That way you directly know which service is associated to a specific uuid.

**Comment by f0** [comment] 2016-06-29 15:23
@lucab  i run them with system units 
I take a look at --uuid-file-save=

**Comment by f0** [comment] 2016-06-29 15:33
@lucab   hm i do not see how this helps?

**Comment by lucab** [comment] 2016-06-29 20:51
@f0 sorry if I was unclear. [This](https://gist.github.com/lucab/a7c18e0795aac654e89c380294950d85) is an updated version of your etcd service unit. Once installed you can use the following to access journals from different services/pods:

```
$ sudo systemctl start etcd@0
$ sudo systemctl start etcd@1
$ machinectl
MACHINE                                  CLASS     SERVICE
rkt-7cce2fd6-3c3c-4104-a03f-8b4cee01887c container rkt    
rkt-a1ea1c35-c830-4292-85d5-d9b745f98f37 container rkt 

# log from instance/pod 0
$ sudo journalctl -M rkt-`cat /var/run/rkt-etcd-0.uuid`

# log from instance/pod 1
$ sudo journalctl -M rkt-`cat /var/run/rkt-etcd-1.uuid`
```

**Comment by f0** [comment] 2016-06-30 05:31
@lucab  thank you for the further explanation. Yor first explanation was clear, i understand the workaround.

But i do not understand the reason for this...

If you run etcd (without any container) on the commandline, you see logs on stdout
if you run etcd inside a rkt container in interactiv mode (--exec /bin/bash) you see logs on stdout
if you run etcd in a rkt container in non interactive mode you see no logs on stdout <-- why does this differ?

If you run things with systemd the expectation is you can use journalctl -u $unit and see all logs 
If you take a look at other projects e.g prometheus, this works without problems.

So the main question is, why does etcd does this in a different way?

regards f0

**Comment by jonboulle** [comment] 2016-06-30 10:50
@f0 it's basically a capnslog problem - https://github.com/coreos/etcd/issues/5449#issuecomment-221884482

**Comment by xiang90** [comment] 2016-06-30 17:06
This turns out a "dup" with https://github.com/coreos/etcd/issues/5449. We will resolve this in https://github.com/coreos/etcd/issues/5449.

**Closed by xiang90** 2016-06-30 17:06 UTC
