### ISSUE TITLE
Discussion about single etcd performance 

### ISSUE THREAD

**Issue by keithtobin** [coreos/etcd#2238] opened 2015-02-05 16:19 UTC
I got the latest clone of etcd and did a quick (see below), what was interesting was it take about 37 sec to complete.  

client := etcd.NewClient([]string{"http://127.0.0.1:4001"})
startTime := time.Now()
	for i := 0; i < 1000; i++ {
		key := strconv.Itoa(i)
		_, err := client.Set(key, key, 0)
		if err != nil {
			log.Error(err)
		}
	}

endTime := time.Now()
fmt.Println(endTime.Sub(startTime))

**Comment by yichengq** [comment] 2015-02-06 04:08
It is caused by current rafthttp implementation. We are improving it now.

**Comment by keithtobin** [comment] 2015-02-07 13:48
Thanks for the info,

**Comment by pyKun** [comment] 2015-03-04 08:07
Has this performance issue been fixed? I found the referred #2323 has been merged.

**Comment by xiang90** [comment] 2015-03-04 15:23
@keithtobin @pyKun It now takes less than 1 second.

```
boom -m PUT -d value="bar" -n 1000 -c 1 http://127.0.0.1:4001/v2/keys/bench
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	0.4817 secs.
  Slowest:	0.0103 secs.
  Fastest:	0.0003 secs.
  Average:	0.0005 secs.
  Requests/sec:	2075.8388
  Total Data Received:	173000 bytes.
  Response Size per Request:	173 bytes.

Status code distribution:
  [200]	1000 responses

Response time histogram:
  0.000 [1]	|
  0.001 [990]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.002 [6]	|
  0.003 [2]	|
  0.004 [0]	|
  0.005 [0]	|
  0.006 [0]	|
  0.007 [0]	|
  0.008 [0]	|
  0.009 [0]	|
  0.010 [1]	|

Latency distribution:
  10% in 0.0003 secs.
  25% in 0.0004 secs.
  50% in 0.0005 secs.
  75% in 0.0005 secs.
  90% in 0.0006 secs.
  95% in 0.0006 secs.
  99% in 0.0012 secs.
```

**Comment by pyKun** [comment] 2015-03-05 03:11
seems good:) I would recheck later

**Comment by yichengq** [comment] 2015-03-09 16:49
@keithtobin This issue has been kind of solved. We will keep improving the performance.

**Closed by yichengq** 2015-03-09 16:50 UTC
