### ISSUE TITLE
Member panics when adding a new member on first start.

### ISSUE THREAD

**Issue by zbindenren** [coreos/etcd#7182] opened 2017-01-18 14:26 UTC
1. Remove a member from cluster
2. Delete data directory
3. Start the member with initial_cluster_state=existing

This leads to a panic for the newly added cluster:

```
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: established a TCP streaming connection with peer e27543f3820bc6d9 (stream Message reader)
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: established a TCP streaming connection with peer d3b04b5071b4a6c1 (stream Message writer)
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: established a TCP streaming connection with peer e27543f3820bc6d9 (stream MsgApp v2 writer)
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: established a TCP streaming connection with peer d3b04b5071b4a6c1 (stream MsgApp v2 writer)
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: established a TCP streaming connection with peer e27543f3820bc6d9 (stream Message writer)
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: panic: assignment to entry in nil map
Jan 18 15:13:09 p1-linux-mlsu006 etcd[19080]: goroutine 193 [running]:
Jan 18 15:13:09 p1-linux-mlsu006 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 18 15:13:09 p1-linux-mlsu006 systemd[1]: Unit etcd.service entered failed state.
Jan 18 15:13:09 p1-linux-mlsu006 systemd[1]: etcd.service failed.
```

If we start the member again, everything works.

**Comment by gyuho** [comment] 2017-01-18 15:46
Could you share your environment (etcd version, OS, ...)? Thanks.

**Comment by zbindenren** [comment] 2017-01-19 12:30
Sorry, it is on and RHEL7.2 x86_64 with etcd-3.1-rc1.

**Comment by heyitsanthony** [comment] 2017-01-20 23:38
Can you give more specific steps to reproduce?

I tried to reproduce this with 3.1-rc1 using the etcd Procfile:
```sh
# boot fresh cluster with processes etcd1, etcd2, etcd3
rm -rf infra*/*
goreman start
# take down member "etcd2"
goreman run stop etcd2
# remove member from cluster
ETCDCTL_API=3 ./bin/etcdctl member remove `ETCDCTL_API=3 ./bin/etcdctl member list | grep infra2 | cut -f1 -d','`
# delete data directory
rm -rf infra2.etcd/*
# start with "existing"
./bin/etcd --name infra2 --listen-client-urls http://127.0.0.1:22379 --advertise-client-urls http://127.0.0.1:22379 --listen-peer-urls http://127.0.0.1:22380 --initial-advertise-peer-urls http://127.0.0.1:22380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state existing
```

etcd1 and etcd3 give:
```
15:35:43 etcd2 | Terminating etcd2
15:35:44 etcd1 | 2017-01-20 15:35:44.163040 W | rafthttp: lost the TCP streaming connection with peer 91bc3c398fb3c146 (stream Message writer)
15:35:44 etcd1 | 2017-01-20 15:35:44.257916 W | etcdserver: failed to reach the peerURL(http://127.0.0.1:22380) of member 91bc3c398fb3c146 (Get http://127.0.0.1:22380/version: dial tcp 127.0.0.1:22380: getsockopt: connection refused)
15:35:44 etcd1 | 2017-01-20 15:35:44.257948 W | etcdserver: cannot get the version of member 91bc3c398fb3c146 (Get http://127.0.0.1:22380/version: dial tcp 127.0.0.1:22380: getsockopt: connection refused)
15:35:44 etcd1 | 2017-01-20 15:35:44.806842 W | rafthttp: lost the TCP streaming connection with peer 91bc3c398fb3c146 (stream MsgApp v2 writer)
15:35:48 etcd1 | 2017-01-20 15:35:48.263965 W | etcdserver: failed to reach the peerURL(http://127.0.0.1:22380) of member 91bc3c398fb3c146 (Get http://127.0.0.1:22380/version: dial tcp 127.0.0.1:22380: getsockopt: connection refused)
15:35:48 etcd1 | 2017-01-20 15:35:48.263995 W | etcdserver: cannot get the version of member 91bc3c398fb3c146 (Get http://127.0.0.1:22380/version: dial tcp 127.0.0.1:22380: getsockopt: connection refused)
15:35:49 etcd3 | 2017-01-20 15:35:49.170606 W | rafthttp: lost the TCP streaming connection with peer 91bc3c398fb3c146 (stream MsgApp v2 writer)
15:35:49 etcd3 | 2017-01-20 15:35:49.171566 W | rafthttp: lost the TCP streaming connection with peer 91bc3c398fb3c146 (stream Message writer)
15:35:50 etcd1 | 2017-01-20 15:35:50.861187 I | etcdserver/membership: removed member 91bc3c398fb3c146 from cluster ef37ad9dc622a7c4
15:35:50 etcd1 | 2017-01-20 15:35:50.861216 I | rafthttp: stopping peer 91bc3c398fb3c146...
15:35:50 etcd1 | 2017-01-20 15:35:50.861236 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (writer)
15:35:50 etcd1 | 2017-01-20 15:35:50.861250 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (writer)
15:35:50 etcd1 | 2017-01-20 15:35:50.861274 I | rafthttp: stopped HTTP pipelining with peer 91bc3c398fb3c146
15:35:50 etcd1 | 2017-01-20 15:35:50.861306 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (stream MsgApp v2 reader)
15:35:50 etcd1 | 2017-01-20 15:35:50.861324 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (stream Message reader)
15:35:50 etcd1 | 2017-01-20 15:35:50.861335 I | rafthttp: stopped peer 91bc3c398fb3c146
15:35:50 etcd1 | 2017-01-20 15:35:50.861350 I | rafthttp: removed peer 91bc3c398fb3c146
15:35:50 etcd3 | 2017-01-20 15:35:50.862386 I | etcdserver/membership: removed member 91bc3c398fb3c146 from cluster ef37ad9dc622a7c4
15:35:50 etcd3 | 2017-01-20 15:35:50.862407 I | rafthttp: stopping peer 91bc3c398fb3c146...
15:35:50 etcd3 | 2017-01-20 15:35:50.862429 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (writer)
15:35:50 etcd3 | 2017-01-20 15:35:50.862444 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (writer)
15:35:50 etcd3 | 2017-01-20 15:35:50.862468 I | rafthttp: stopped HTTP pipelining with peer 91bc3c398fb3c146
15:35:50 etcd3 | 2017-01-20 15:35:50.862488 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (stream MsgApp v2 reader)
15:35:50 etcd3 | 2017-01-20 15:35:50.862503 I | rafthttp: stopped streaming with peer 91bc3c398fb3c146 (stream Message reader)
15:35:50 etcd3 | 2017-01-20 15:35:50.862514 I | rafthttp: stopped peer 91bc3c398fb3c146
15:35:50 etcd3 | 2017-01-20 15:35:50.862528 I | rafthttp: removed peer 91bc3c398fb3c146
```

etcd2 gives:
```
2017-01-20 15:36:04.912713 I | etcdmain: etcd Version: 3.1.0-rc.1
2017-01-20 15:36:04.912806 I | etcdmain: Git SHA: 3d5ba43
2017-01-20 15:36:04.912812 I | etcdmain: Go Version: go1.7.3
2017-01-20 15:36:04.912814 I | etcdmain: Go OS/Arch: darwin/amd64
2017-01-20 15:36:04.912817 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2017-01-20 15:36:04.912825 W | etcdmain: no data-dir provided, using default data-dir ./infra2.etcd
2017-01-20 15:36:04.913305 I | embed: listening for peers on http://127.0.0.1:22380
2017-01-20 15:36:04.913339 I | embed: listening for client requests on 127.0.0.1:22379
2017-01-20 15:36:04.917720 C | etcdmain: error validating peerURLs {ClusterID:ef37ad9dc622a7c4 Members:[&{ID:fd422379fda50e48 RaftAttributes:{PeerURLs:[http://127.0.0.1:32380]} Attributes:{Name:infra3 ClientURLs:[http://127.0.0.1:32379]}} &{ID:8211f1d0f64f3269 RaftAttributes:{PeerURLs:[http://127.0.0.1:12380]} Attributes:{Name:infra1 ClientURLs:[http://127.0.0.1:2379]}}] RemovedMemberIDs:[]}: member count is unequal
```

**Comment by xiang90** [comment] 2017-01-27 00:05
@zbindenren kindly ping. we cannot reproduce.

Also you should not really restart a member that you know it lost its data dir.

**Comment by xiang90** [comment] 2017-02-14 15:36
I am going to close this due to low activity. Please reopen with more informations if this is still a problem for you. Thanks for reporting!

**Closed by xiang90** 2017-02-14 15:36 UTC
Labels: reviewed/needs more information
