### ISSUE TITLE
Can't delete a node with prevValue=""

### ISSUE THREAD

**Issue by gfxmonk** [coreos/etcd#1619] opened 2014-11-05 23:46 UTC
I have some keys which I want to be present, but sometimes their values are conceptually null. I'm using an empty string for this, since that would never be a valid value.

Periodically (on process restart) I'm clearing out old keys. So I'm enumerating this directory, and deleting all keys whose value is "". To be concurrent-safe (just in case another process is setting the key to a non-empty value), I'm including `prevValue`. But I get:

    $ curl -X DELETE 'http://localhost:4001/v2/keys/app/endpoint/339078d8/d1baa5dc?prevValue='
    {"errorCode":209,"message":"Invalid field","cause":"\"prevValue\" cannot be empty","index":0}

This is on 0.5.0-alpha1. On 0.4.6 I have the same problem, but it's reported with a different error message:

    {"errorCode":201,"message":"PrevValue is Required in POST form","cause":"CompareAndDelete","index":33531}

It seems buggy that a node's value can legitimately be "", but that it's impossible to use `prevValue` to safely delete this key.

**Comment by yichengq** [comment] 2015-07-23 22:25
The root cause of this issue is that v2 Store treats empty-string prevValue as unset prevValue. It cannot compare prevValue to empty string in v2 store. So this behavior is expected and helps users to know its restriction. Remove this restriction is an enhancement instead of a bug.

If we want to remove this restriction, it needs to change v2 Store interface. Because v2 store is frozen and the problem could be resolved by not setting empty value, i don't want to make the change to improve it.

The error message in etcd v2 is accurate and better than 0.4, so i will keep it.

/cc @xiang90

**Comment by xiang90** [comment] 2015-07-24 01:33
@yichengq Agreed. I am closing this since we are not going to change v2 API.

**Closed by xiang90** 2015-07-24 01:33 UTC
