### ISSUE TITLE
etcdctl v3 not working with enviornment variables  on host machine but works on VM

### ISSUE THREAD

**Issue by AnjaniKr** [coreos/etcd#8560] opened 2017-09-14 05:25 UTC
Description : When running etcdctl v3 with enviornment variables set doesn't works on physical host but works on VM. Following variables are set in bashrc  ETCDCTL_ENDPOINTS=https://hostip:2379, ETCDCTL_CACERT=cert file, ETCDCTL_API=3

Following is etcd service status : 
 etcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-09-08 02:04:16 PDT; 6 days ago
     Docs: https://github.com/coreos/etcd
           man:etcd
 Main PID: 2372 (etcd)
    Tasks: 10
   Memory: 7.2M
      CPU: 32min 59.364s
   CGroup: /system.slice/etcd.service
           └─2372 /usr/bin/etcd

Sep 08 02:04:16 xxx etcd[2372]: enabled capabilities for version 3.2
Sep 08 02:04:16 xxx etcd[2372]: ce2a822cea30bfca is starting a new election at term 4
Sep 08 02:04:16 xxx etcd[2372]: ce2a822cea30bfca became candidate at term 5
Sep 08 02:04:16 xxx etcd[2372]: ce2a822cea30bfca received MsgVoteResp from ce2a822cea30bfca at term 5
Sep 08 02:04:16 xxx etcd[2372]: ce2a822cea30bfca became leader at term 5
Sep 08 02:04:16 xxx etcd[2372]: raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 5
Sep 08 02:04:16 xxx etcd[2372]: published {Name:infra1 ClientURLs:[https://localhost:2379]} to cluster 7e27652122e8b2ae
Sep 08 02:04:16 xxx etcd[2372]: ready to serve client requests
Sep 08 02:04:16 xxx etcd[2372]: serving client requests on xxx:2379
Sep 08 02:04:16 xxx4 systemd[1]: Started etcd - highly-available key value store.

If all the params are given in command line like below it is working : 
ETCDCTL_API=3 etcdctl get / --prefix --keys-only --cacert certpath --endpoints https://xxx:2379

but after setting enviornment variables as above and running below command fails : 
etcdctl get / --prefix 
**Error:  grpc: timed out when dialing**

**Comment by zyf0330** [comment] 2017-09-14 06:11
You should export environment variable in .bashrc.

**Comment by AnjaniKr** [comment] 2017-09-14 06:37
ya we exported all three in .bashrc
ETCDCTL_ENDPOINTS=https://xxx:2379, ETCDCTL_CACERT=certpath, ETCDCTL_API=3

**Comment by zyf0330** [comment] 2017-09-14 06:43
notice:
* `export ETCDCTL_ENDPOINTS=...`
* write in .profile not .bashrc

**Comment by heyitsanthony** [comment] 2017-09-14 07:18
@AnjaniKr what does `env` show before running `etcdctl get / --prefix`?

**Comment by AnjaniKr** [comment] 2017-09-14 07:22
@zyf0330 even after adding to .bashrc it doesn't work

**Comment by AnjaniKr** [comment] 2017-09-14 07:23
@heyitsanthony following are env before running etcdctl get --prefix
ETCDCTL_ENDPOINTS=https://x.x.x.x:2379
ETCDCTL_CACERT=certpath
ETCDCTL_API=3

**Comment by zyf0330** [comment] 2017-09-14 07:55
If these are output from `env` command, then I don't know why it doesn't work.

**Comment by heyitsanthony** [comment] 2017-09-14 08:00
@AnjaniKr I need the full output of `env`.

**Comment by heyitsanthony** [comment] 2017-09-14 08:19
also, is there a difference in output between the two when calling etcdctl with `--debug`?

**Comment by AnjaniKr** [comment] 2017-09-15 06:28
@heyitsanthony its saying there is no --debug arguments, I got the issue there was etcd-gateway also running on the same host and that was wrongly configured so whenever we were trying to execute etcdctl it was referring to etcd-gateway's envs

**Comment by AnjaniKr** [comment] 2017-09-15 06:29
@zyf0330 thanks for you valuable time to debug this 👍 
@heyitsanthony thanks 👍

**Comment by zyf0330** [comment] 2017-09-15 06:37
I never see etcd-gateway in my process list.

**Comment by AnjaniKr** [comment] 2017-09-15 07:08
@zyf0330 it will not be shown in process list, just a executable link in some path with set of envs

**Comment by zyf0330** [comment] 2017-09-15 07:11
Didn't you mean `etcd gateway`?

**Comment by AnjaniKr** [comment] 2017-09-15 08:51
yes

**Comment by zyf0330** [comment] 2017-09-15 10:20
Oh, I mean too. I never use it, so cannot help you. I thought you connected to etcd directly.

**Comment by gyuho** [comment] 2017-09-16 05:46
@AnjaniKr I don't think adding to bashrc would work if you run etcd with systemd.

See https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html.

**Comment by zyf0330** [comment] 2017-09-16 07:29
@gyuho I think you understand wrongly. He is using `etcdctl` with environments set.

**Comment by gyuho** [comment] 2017-09-16 08:28
Right, nvm.

Thanks.

**Comment by heyitsanthony** [comment] 2017-09-18 01:01
Closing; root cause was misconfiguration

**Closed by heyitsanthony** 2017-09-18 01:01 UTC
Labels: kind/support

**Comment by zyf0330** [comment] 2017-09-19 08:03
No more explanation?

**Comment by heyitsanthony** [comment] 2017-09-19 08:10
@zyf0330 the environment variables were misconfigured; what more explanation do you need?

**Comment by zyf0330** [comment] 2017-09-19 08:12
Do you mean that he misconfigured env vars?

**Comment by gyuho** [comment] 2017-09-20 13:19
@zyf0330 Most likely from misconfiguration in his etcd gateway. Or wrong cert issues.

Please reopen/create a new issue if you still think it's an etcd bug.
We need reproducible steps to debug issues like this.

Thanks!
