### ISSUE TITLE
seeing etcdserver: too many requests on a single node etcd cluster

### ISSUE THREAD

**Issue by yvdinesh** [coreos/etcd#8576] opened 2017-09-19 18:57 UTC
I have a single node etcd cluster and periodically see `etcdserver: too many requests`. Doing a watch on the key space reports that there are approximately 5 writes coming in to etcd. The error occurs when there is a drift between etcd's applied and commit index. But not sure what is causing etcd to lag behind. I have checked the resource utilization on the box and everything seems to be normal. Looks like there is an upper limit on this gap and that is currently at 5000:
```
// However, if the committed entries are very heavy to apply, the gap might grow.
// We should stop accepting new proposals if the gap growing to a certain point.
maxGapBetweenApplyAndCommitIndex = 5000
```
What constitutes a "heavy" commit? Is there anything else I can do to diagnose the issue here?

**Comment by xiang90** [comment] 2017-09-19 19:52
any logging from etcd server?

**Comment by yvdinesh** [comment] 2017-09-19 20:29
```
2017-09-18 23:00:56.200185 W | etcdserver: apply entries took too long [223.489001ms for 2 entries]
2017-09-18 23:00:56.200210 W | etcdserver: avoid queries with large range/delete range!
2017-09-19 00:57:34.638942 I | etcdserver: start to snapshot (applied: 132302922, lastsnap: 132292921)
2017-09-19 00:57:34.853652 I | etcdserver: saved snapshot at index 132302922
2017-09-19 00:57:34.854029 I | etcdserver: compacted raft log at 132297922
2017-09-19 00:57:58.104912 I | pkg/fileutil: purged file /member/snap/0000000000000090-0000000007e204f5.snap successfully
```

**Comment by xiang90** [comment] 2017-09-19 20:34
> 2017-09-18 23:00:56.200185 W | etcdserver: apply entries took too long [223.489001ms for 2 entries]

Probably you need to figure out what the expensive operators are by querying metrics.

**Comment by jpbetz** [comment] 2017-09-19 23:02
It might be a expensive read requests, not writes.

**Comment by yvdinesh** [comment] 2017-09-19 23:06
Interesting. @jpbetz why do you think reads cause the drift between applied and committed index.

**Comment by xiang90** [comment] 2017-09-19 23:09
@yvdinesh what is the version of your etcd server? read might block writes in the early release of etcd3. i think that is what @jpbetz hints. write is normally inexpensive, but huge range query can be.

**Comment by yvdinesh** [comment] 2017-09-19 23:10
@xiang90 etcd version is 3.1.4.

**Comment by xiang90** [comment] 2017-09-19 23:14
@yvdinesh Probably try to get metrics on requests type to confirm. you can try 3.2 or master to see if things improve too.

**Comment by yvdinesh** [comment] 2017-09-19 23:17
will get the metrics. To confirm @xiang90 , in etcd 3.1.*, reads can block writes, which can cause the drift right?

**Comment by xiang90** [comment] 2017-09-19 23:19
> in etcd 3.1.*, reads can block writes, which can cause the drift right?

if range query is huge, then yes. you really need to confirm that by yourself. i cannot say anything for sure with the limited information you provided.

**Comment by yvdinesh** [comment] 2017-09-21 17:10
@xiang90 I see this in the metrics:
```
etcd_debugging_store_reads_total{action="get"} 15961
etcd_debugging_store_reads_total{action="getRecursive"} 2
etcd_debugging_store_writes_total{action="set"} 1
```
Looks like the reads are causing the writes to be processed slowly.

**Comment by xiang90** [comment] 2017-09-21 17:18
are you using v2 or v3?

**Comment by yvdinesh** [comment] 2017-09-21 17:26
v3

**Comment by gyuho** [comment] 2017-09-21 21:44
@yvdinesh `etcd_debugging_store_reads_total` is v2 metrics.

**Comment by yvdinesh** [comment] 2017-09-21 21:48
@gyuho is there a different endpoint for v3 metrics? If not, should I be looking at different metrics?

**Comment by gyuho** [comment] 2017-09-21 21:51
Can you provide full output of `[your-client-endpoint]/metrics`?

**Comment by yvdinesh** [comment] 2017-09-21 22:27
Uploaded the metrics here:
https://gist.github.com/yvdinesh/4f7c014be3945c5a9b791bf190a0072d

**Comment by gyuho** [comment] 2017-09-21 22:35
```
grpc_server_handled_total{grpc_code="OK",grpc_method="Range",grpc_service="etcdserverpb.KV",grpc_type="unary"} 2.3311891e+07

# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 60
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 3758
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 4711
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 4772
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 4800
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 4803
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 4804
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 4805
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 4805
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 4805
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 4805
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 4805
etcd_disk_backend_commit_duration_seconds_sum 67.79001204900013
etcd_disk_backend_commit_duration_seconds_count 4805
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 6938
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 12620
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 16509
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 19203
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 21756
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 22143
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 22180
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 22213
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 22222
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 22231
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 22231
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 22231
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 22231
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 22231
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 22231
etcd_disk_wal_fsync_duration_seconds_sum 86.39272394800041
etcd_disk_wal_fsync_duration_seconds_count 22231
```

I see high disk I/O latencies and lots of read requests. See related FAQ https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-failed-to-send-out-heartbeat-on-time-mean.

**Comment by xiang90** [comment] 2017-09-22 21:24
closing. the problems are identified.

**Closed by xiang90** 2017-09-22 21:24 UTC

**Comment by iponnam** [comment] 2018-04-11 19:11
@xiang90  Could you please provide the details on the root cause you identified and steps to resolve the issue.
