### ISSUE TITLE
machine power off , etcd is not working

### ISSUE THREAD

**Issue by zhuwenjie11** [coreos/etcd#8381] opened 2017-08-09 06:46 UTC
# etcd not working

 etcd running in docker , images version : gcr.io/google_containers/etcd-amd64:3.0.17

**Problem:**

**machine power off, restart etcd , etcd is not working**

**The logs are as follows**

```
2017-08-09 06:14:38.244635 I | etcdmain: etcd Version: 3.0.17
2017-08-09 06:14:38.244821 I | etcdmain: Git SHA: cc198e2
2017-08-09 06:14:38.244835 I | etcdmain: Go Version: go1.6.4
2017-08-09 06:14:38.244847 I | etcdmain: Go OS/Arch: linux/amd64
2017-08-09 06:14:38.244860 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-08-09 06:14:38.244980 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-08-09 06:14:38.245817 I | etcdmain: listening for peers on http://localhost:2380
2017-08-09 06:14:38.246028 I | etcdmain: listening for client requests on 127.0.0.1:2379
2017-08-09 06:14:38.254683 I | etcdserver: recovered store from snapshot at index 11791179
2017-08-09 06:14:38.254724 I | etcdserver: name = default
2017-08-09 06:14:38.254737 I | etcdserver: data dir = /var/lib/etcd
2017-08-09 06:14:38.254751 I | etcdserver: member dir = /var/lib/etcd/member
2017-08-09 06:14:38.254763 I | etcdserver: heartbeat = 100ms
2017-08-09 06:14:38.254774 I | etcdserver: election = 1000ms
2017-08-09 06:14:38.254785 I | etcdserver: snapshot count = 10000
2017-08-09 06:14:38.254811 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2017-08-09 06:14:38.255065 W | wal: ignored file 0000000000000089-0000000000b31b03.wal.broken in wal
2017-08-09 06:14:39.132965 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 11793719
2017-08-09 06:14:39.135620 I | raft: 8e9e05c52164694d became follower at term 4
2017-08-09 06:14:39.135880 I | raft: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 4, commit: 11793719, applied: 11791179, lastindex: 11793719, lastterm: 4]
2017-08-09 06:14:39.136378 I | api: enabled capabilities for version 3.0
2017-08-09 06:14:39.136443 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
2017-08-09 06:14:39.136673 I | membership: set the cluster version to 3.0 from store
panic: failed to unmarshal lease proto item

goroutine 1 [running]:
panic(0xd460a0, 0xc8201f7160)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc82004ea20)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:432 +0x55c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.newLessor(0x7fc7598287b8, 0xc82020eba0, 0x2, 0x7fc7597f1b90)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:169 +0x182
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.NewLessor(0x7fc7598287b8, 0xc82020eba0, 0x2, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:156 +0x45
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc8200738c0, 0xc82006e240, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:403 +0x1c59
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc820023800, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:374 +0x245f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x2101
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x21e
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
```

**When I delete /var/lib/etcd ,and then restart etcd container，etcd is working , but The configuration data is missing**

**# Is there a way to fix the data?**

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by heyitsanthony** [comment] 2017-08-09 07:11
@zhuwenjie11 what are the flags being used to start etcd in docker? are there steps to easily reproduce this?

**Comment by zhuwenjie11** [comment] 2017-08-09 07:21
@heyitsanthony   i use kubeadm 1.7.0 install kubernetes ， etcd installed at the same time 。
etcd.yaml : 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=http://127.0.0.1:2379
    - --data-dir=/var/lib/etcd
    - --listen-client-urls=http://127.0.0.1:2379
    image: gcr.io/google_containers/etcd-amd64:3.0.17
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /var/lib/etcd
      name: etcd
    - mountPath: /etc/kubernetes
      name: k8s
      readOnly: true
  hostNetwork: true
  securityContext:
    seLinuxOptions:
      type: spc_t
  volumes:
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /var/lib/etcd
    name: etcd
  - hostPath:
      path: /etc/kubernetes
    name: k8s
status: {}
```

**Comment by gyuho** [comment] 2017-08-09 15:35
> the server is already initialized as member before, starting as etcd member...

Did you start etcd before? etcd is loading from previous data directory. What was the version of previous etcd run? We need a way to reproduce.

**Comment by zhuwenjie11** [comment] 2017-08-09 16:54
I ran only one ETCD service at a single node, version is 3.0.17 . Since the machine has been powered off, etcd service is down has restored the power, the machine has started normally, but when I started the ETCD service, I got the problem .
I upload an attachment to the data directory. 


Can you fix these data files? thank you
 









朱文杰

软件工程师

杭州东方通信软件技术有限公司/广东研发部



13751856530

杭州市文三路398号东方通信大厦9楼




 
 
 
------------------ Original ------------------

**Comment by heyitsanthony** [comment] 2017-08-30 04:59
@zhuwenjie11 the backend is corrupted according to `bolt check etcd_bak/member/snap/db`:
```
page 166: multiple references
page 205: reachable freed
page 959: multiple references
page 1050: multiple references
...
734 errors found
ERROR: invalid value
```

This doesn't look easy to reproduce, but it's probably a boltdb bug. 3.0.17 is using bolt 1.3.0 and there haven't been any corruption fixes since so this may affect the master branch. etcd 3.3 will detect this corruption earlier in the boot stage, at least.

The corruption may either be from pulling the plug but not syncing properly or on-going corruption (broken delete path?) that wasn't detected until reboot; it's not clear from the data.

**Comment by heyitsanthony** [comment] 2017-08-30 22:31
Also, just to rule out the storage layer, what was the filesystem / disk set up for the etcd member directory?

**Comment by xiang90** [comment] 2017-09-28 20:30
this issue is not active. also it seems like a bboltdb problem. so closing at etcd side.

**Closed by xiang90** 2017-09-28 20:30 UTC
