### ISSUE TITLE
Golang client returns empty node for non-existing path

### ISSUE THREAD

**Issue by bestofmukul** [coreos/etcd#5264] opened 2016-05-03 23:01 UTC
I have a method that fetches value from etcd and returns the default value if it does not exist. I am relying on error: ErrorCodeKeyNotFound for this functionality. Golang client is returning me an empty node struct for a non-existing path(e.g. /random-string).

Although etcdctl is returning the correct response:  Error: 100: Key not found

**Comment by heyitsanthony** [comment] 2016-05-03 23:15
@bestofmukul `etcdctl`uses the golang client (see https://github.com/coreos/etcd/blob/master/etcdctl/ctlv2/command/get_command.go#L53)  so there shouldn't be any functional difference. Is your method checking `err != nil` before looking at the response?

**Comment by bestofmukul** [comment] 2016-05-04 00:54
This is how my test code looks like

`opts := &etcdclient.GetOptions{Quorum: true}`
`res, err := ec.keysAPI.Get(context.Background(), path, opts)`
`if err != nil {`
		`return nil, err`
	`}`

`return res.Node, nil`

**Comment by heyitsanthony** [comment] 2016-05-05 06:18
@bestofmukul that code does basically the same thing as `etcdctl get` so it's not clear to me what the problem is here. How are you running `etcdctl`? What path is passed into your method? How is the client initialized?

**Comment by bestofmukul** [comment] 2016-05-06 04:01
@heyitsanthony I tried to do this differently and found a bug in my code related to closures. The api is returning correct error code for non-existing keys, however, the empty node is being returned for path="". Not sure if its intended. I was expecting either key not found error or response containing root nodes.

P.S. We can close this issue. I don't think accessing empty path is very common.

**Comment by heyitsanthony** [comment] 2016-05-06 04:14
OK. Closing.

**Closed by heyitsanthony** 2016-05-06 04:14 UTC
