### ISSUE TITLE
wait request does not return all events

### ISSUE THREAD

**Issue by pphaneuf** [coreos/etcd#2686] opened 2015-04-15 11:36 UTC
etcd creates missing directory entries as necessary when creating a key, for example (assuming a fresh, empty etcd) creating ```/foo/bar``` will implicitly create a ```/foo``` directory. If you have a non-recursive watch on ```/foo```, this will **not** return that directory node.

This doesn't seem to be an issue for directory nodes created explicitly (if I created ```/foo``` with ```dir=true``` instead of ```/foo/bar```), so it seems like it's related to the implicit nature of the event, rather than because it is a directory.

I can even get this rather interesting behaviour:

```
$ curl -v 'http://127.0.0.1:4001/v2/keys/foo' | pretty_json 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> GET /v2/keys/foo HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 1781
< X-Raft-Index: 3567335
< X-Raft-Term: 4
< Date: Wed, 15 Apr 2015 11:28:57 GMT
< Content-Length: 176
< 
{ [data not shown]
100   176  100   176    0     0  47058      0 --:--:-- --:--:-- --:--:-- 58666
* Connection #0 to host 127.0.0.1 left intact
{
   "action" : "get",
   "node" : {
      "createdIndex" : 1781,
      "dir" : true,
      "key" : "/foo",
      "modifiedIndex" : 1781,
      "nodes" : [
         {
            "createdIndex" : 1781,
            "key" : "/foo/bar",
            "modifiedIndex" : 1781,
            "value" : "blah"
         }
      ]
   }
}
```

If I run ```curl -v 'http://127.0.0.1:4001/v2/keys/foo?wait=true&waitIndex=1781'``` immediately after, it hangs, which is somewhat surprising. But then, doing this:

```
$ curl -v 'http://127.0.0.1:4001/v2/keys/foo?recursive=true' -X DELETE | pretty_json 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> DELETE /v2/keys/foo?recursive=true HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 1782
< X-Raft-Index: 3567666
< X-Raft-Term: 4
< Date: Wed, 15 Apr 2015 11:31:41 GMT
< Content-Length: 172
< 
{ [data not shown]
100   172  100   172    0     0   5193      0 --:--:-- --:--:-- --:--:--  5375
* Connection #0 to host 127.0.0.1 left intact
{
   "action" : "delete",
   "node" : {
      "createdIndex" : 1781,
      "dir" : true,
      "key" : "/foo",
      "modifiedIndex" : 1782
   },
   "prevNode" : {
      "createdIndex" : 1781,
      "dir" : true,
      "key" : "/foo",
      "modifiedIndex" : 1781
   }
}
$ curl -v 'http://127.0.0.1:4001/v2/keys/foo' -X PUT -d dir=true | pretty_json 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> PUT /v2/keys/foo HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4001
> Accept: */*
> Content-Length: 8
> Content-Type: application/x-www-form-urlencoded
> 
} [data not shown]
* upload completely sent off: 8 out of 8 bytes
< HTTP/1.1 201 Created
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 1783
< X-Raft-Index: 3567725
< X-Raft-Term: 4
< Date: Wed, 15 Apr 2015 11:32:10 GMT
< Content-Length: 91
< 
{ [data not shown]
100    99  100    91  100     8   2541    223 --:--:-- --:--:-- --:--:--  2600
* Connection #0 to host 127.0.0.1 left intact
{
   "action" : "set",
   "node" : {
      "createdIndex" : 1783,
      "dir" : true,
      "key" : "/foo",
      "modifiedIndex" : 1783
   }
}
$ time curl -v 'http://127.0.0.1:4001/v2/keys/foo?wait=true&waitIndex=1783' | pretty_json 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> GET /v2/keys/foo?wait=true&waitIndex=1783 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 1783
< X-Raft-Index: 3567814
< X-Raft-Term: 4
< Date: Wed, 15 Apr 2015 11:32:54 GMT
< Transfer-Encoding: chunked
< 
{ [data not shown]
100    91    0    91    0     0  49564      0 --:--:-- --:--:-- --:--:-- 91000
* Connection #0 to host 127.0.0.1 left intact
{
   "action" : "set",
   "node" : {
      "createdIndex" : 1783,
      "dir" : true,
      "key" : "/foo",
      "modifiedIndex" : 1783
   }
}

real	0m0.037s
user	0m0.038s
sys	0m0.008s
```

As you can see, in that case, the wait request returns immediately with the expected information.

**Comment by xiang90** [comment] 2015-04-15 14:38
@pphaneuf 
Creating the `dir` is a side effect of creating the `key`. Only the actual event can be watched. This is by designed. 

Does that create any problem in practical?

**Comment by xiang90** [comment] 2015-04-23 22:50
@pphaneuf Closing due to low activity. Feel free to reopen if you have a follow-up.

**Closed by xiang90** 2015-04-23 22:50 UTC
