### ISSUE TITLE
Unexpected benchmark result

### ISSUE THREAD

**Issue by cw9** [coreos/etcd#6954] opened 2016-12-06 21:42 UTC
I'm running some performance test agains a 3 node etcd cluster with the following version
```
etcd --version
etcd Version: 3.0.12
Git SHA: 2d1e2e8
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

The Put benchmark looks reasonable but I'm getting some weird result from range benchmarks that the throughput of serializable reads is smaller than throughput of linearizable reads
e.g:
```
./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 range "key1" --total=100000 --consistency=l
bench with linearizable range
Summary:
  Total:	1.3565 secs.
  Slowest:	0.0929 secs.
  Fastest:	0.0009 secs.
  Average:	0.0132 secs.
  Stddev:	0.0140 secs.
  Requests/sec:	73716.7697

 ./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 range "key1" --total=100000 --consistency=s
bench with serializable range
Summary:
  Total:	1.6822 secs.
  Slowest:	0.2442 secs.
  Fastest:	0.0002 secs.
  Average:	0.0166 secs.
  Stddev:	0.0213 secs.
  Requests/sec:	59445.1270
```

If I use only one endpoint rather than all three boxes, I got this result:
```
./main --conns=100 --clients=1000 --endpoints=ip1 range "key1" --total=100000 --consistency=s
bench with serializable range
Summary:
  Total:	4.9861 secs.
  Slowest:	0.7711 secs.
  Fastest:	0.0002 secs.
  Average:	0.0494 secs.
  Stddev:	0.0678 secs.
  Requests/sec:	20055.8663

 ./main --conns=100 --clients=1000 --endpoints=ip1 range "key1" --total=100000 --consistency=l
bench with linearizable range
Summary:
  Total:	1.5002 secs.
  Slowest:	0.0386 secs.
  Fastest:	0.0018 secs.
  Average:	0.0146 secs.
  Stddev:	0.0048 secs.
  Requests/sec:	66659.7614
```

I'm trying to understand the result here because I'm expecting the linearizable reads to be slower than serializable ones, did I miss anything in the benchmark commands?

Thanks

**Comment by xiang90** [comment] 2016-12-06 21:47
What is your machine spec? What is the config you started etcd?

Also can you try 1 client/ 1 conn case to see if s read is faster than l read?

L read does not necessarily affect throughput, it affects latency due to additional disk write. When your cluster is under heavy load, CPU might dominate. Also we have noticed some strange things around go runtime scheduling understand heavy load.

**Comment by gyuho** [comment] 2016-12-06 21:48
Yeah seriazable read is slow due to Go runtime, we believe.

https://github.com/coreos/etcd/issues/6876

**Comment by xiang90** [comment] 2016-12-06 21:53
@cw9 

Also looking at the stats, the slowest query for s read seems very bad:

```
  Slowest:	0.2442 secs.
```

Not sure what happened there. We could help to look into this if you can provide more info so that we can reproduce.

**Comment by cw9** [comment] 2016-12-06 22:29
result with 1 client 1 conn looks much more sane 
```

./main --conns=1 --clients=1 --endpoints=ip2 range "key1" --total=10000 --consistency=l
bench with linearizable range
Summary:
  Total:	7.4256 secs.
  Slowest:	0.0183 secs.
  Fastest:	0.0006 secs.
  Average:	0.0007 secs.
  Stddev:	0.0003 secs.
  Requests/sec:	1346.6996

./main --conns=1 --clients=1 --endpoints=ip1 range "key1" --total=10000 --consistency=s
bench with serializable range
Summary:
  Total:	2.6003 secs.
  Slowest:	0.0017 secs.
  Fastest:	0.0002 secs.
  Average:	0.0003 secs.
  Stddev:	0.0000 secs.
  Requests/sec:	3845.6569
```
I'm getting similar results when running the commands with all 3 hosts in the --endpoints argument as well.


I'm running on HDD machines with 48G memory. I was expecting slower results than the one you posted due to slower disk, but for puts I'm getting slightly better throughput
```

./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 put --key-size=8 --sequential-keys --total=100000 --val-size=256 --key-space-size=100000
Summary:
  Total:	2.5904 secs.
  Slowest:	0.1554 secs.
  Fastest:	0.0012 secs.
  Average:	0.0256 secs.
  Stddev:	0.0120 secs.
  Requests/sec:	38604.3884
```

**Comment by cw9** [comment] 2016-12-06 22:33
The config in /etc/etcd/etcd.conf
```
ETCD_NAME=ip1
ETCD_DATA_DIR=/var/lib/etcd
#ETCD_SNAPSHOT_COUNTER="10000"
#ETCD_HEARTBEAT_INTERVAL="100"
#ETCD_ELECTION_TIMEOUT="1000"
#ETCD_MAX_SNAPSHOTS="5"
#ETCD_MAX_WALS="5"
#ETCD_CORS=""

#[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.30.7.37:2380
ETCD_INITIAL_CLUSTER=ip1=http://10.30.7.37:2380,ip2=http://10.30.18.24:2380,ip3=http://10.30.17.30:2380
ETCD_INITIAL_CLUSTER_STATE=new
ETCD_INITIAL_CLUSTER_TOKEN=etcd-k8-cluster
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_SRV=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""

ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380

ETCD_ADVERTISE_CLIENT_URLS=http://10.30.7.37:2379
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"

#[proxy]
ETCD_PROXY="off"

#[security]
```

**Comment by xiang90** [comment] 2016-12-06 22:34
> I'm running on HDD machines 

It affects only latency. Actually HDD might generate similar throughput compared with SDD in some cases due to better internal batching. In the heave load case, CPU is dominate.

>   Average:	0.0007 secs.

The avg latency result for l-read for 1client case does not seems reasonable for HDD. It is less than 1ms. It is more like a SDD. Can you try to use iostats to see if l-read actually hits your correct disk?

**Comment by xiang90** [comment] 2016-12-06 22:40
@cw9 

For write path:

1. batch a bunch writes, then do a seq write into WAL
2. apply committed writes to in-memory db
3. return the result to client
4. checkpoint the delta writes into on-disk btree

So you might not notice huge difference between HDD, SDD on write path under heavyload. But the on-disk merging part can be slow once the btree grows. Random seek is slow on HDD.

**Comment by cw9** [comment] 2016-12-06 22:44
got it, when would random seek happen/ what does read path look like? Was it served from the in-memory db as well?

**Comment by xiang90** [comment] 2016-12-06 22:47
@cw9 

random seeks happens at step 4 i mentioned above. it happens every 100ms or every 10000 writes. it might invoke a few seeks for 1M keys. it might pause operations for 10s of ms on HDD. We might make this non-pausing later on.

read serves from memory. l-read would hit disk for the version you tested. l-read would not hit disk after 3.1 release.

**Comment by xiang90** [comment] 2016-12-06 22:47
@cw9 I am curious what is your use case.

**Comment by cw9** [comment] 2016-12-06 23:00
@xiang90 I want to use it as a KV store, just trying to understand the performance limit here. I'm not too concerned with the latency, more on the throughput side, and the results from S reads and L reads kinda suprised me. BTW just checked, I don't have any SSD on those etcd servers.

**Comment by cw9** [comment] 2016-12-06 23:02
lscpu
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz
Stepping:              4
CPU MHz:               1250.927
CPU max MHz:           2700.0000
CPU min MHz:           1200.0000
BogoMIPS:              4402.34
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23
```

**Comment by xiang90** [comment] 2016-12-06 23:05
@cw9 

I am not sure. l-read hits disk on my test. Probably you can try iostats to see what is going on there.

For the s-read vs l-read under heavyload, we will investigate more after the go runtime thing @gyuho mentioned early got resolved.

**Comment by cw9** [comment] 2016-12-06 23:09
@xiang90 got it, thanks for the help! I'll keep an eye on it.

**Comment by xiang90** [comment] 2016-12-28 21:17
I am closing this out. The bench result is explained. We will solve the read performance issue soon.

**Closed by xiang90** 2016-12-28 21:17 UTC
