### ISSUE TITLE
when etcd v3 compact, the client get error: context deadline exceeded

### ISSUE THREAD

**Issue by lijianweia** [coreos/etcd#7971] opened 2017-05-23 02:43 UTC
I use  etcd 3.0.15, there is a long time running.
The clients put a key per second, and I set compact per hour.
I found the client always get error " context deadline exceded" ,and in the same time etcd is compacting.
I guess the performance cause the problem.
Is there any suggestion?

**Comment by xiang90** [comment] 2017-05-23 03:10
Can you reproduce this with a simulated workload generator?

**Comment by lijianweia** [comment] 2017-05-23 03:22
Yes, but maybe a long time. Do you need the log?

**Comment by xiang90** [comment] 2017-05-23 03:33
Yes. We need the log and a simple way to reproduce it.

**Comment by xiang90** [comment] 2017-05-31 16:27
@lijianweia kindly ping.

**Comment by xiang90** [comment] 2017-06-14 22:59
I am going to close this due to low activity. reopen if you still feel this issue is useful.

**Closed by xiang90** 2017-06-14 22:59 UTC
