### ISSUE TITLE
Member can be removed without authentication even when auth is enabled.

### ISSUE THREAD

**Issue by zbindenren** [coreos/etcd#7181] opened 2017-01-18 14:20 UTC
If authentication is enabled, removing a member from the cluster should not be possible.

We tested this with 3.1-rc1.

**Comment by mitake** [comment] 2017-01-18 14:40
@zbindenren thanks for your report. The issue is solved in this PR: https://github.com/coreos/etcd/pull/6903
It is in the master branch but not backported to v3.1. Is it possible to backport the commits to the stable release? @gyuho

**Comment by gyuho** [comment] 2017-01-18 15:50
@mitake https://github.com/coreos/etcd/pull/6903 is already in `release-3.1` branch?
We will release 3.1 this week. Thanks.

**Comment by mitake** [comment] 2017-01-18 16:02
@gyuho Ah sorry, I checked the commit in v3.1-rc1 tag. @zbindenren could you try the `release-3.1` branch?

**Comment by xiang90** [comment] 2017-01-20 04:27
I believe this is fixed in 3.1 branch. So closing.

**Closed by xiang90** 2017-01-20 04:27 UTC
