### ISSUE TITLE
0.2: watch returns different events depending on before or after

### ISSUE THREAD

**Issue by philips** [coreos/etcd#284] opened 2013-10-31 23:28 UTC
If I watch for a future index watch returns on either index-1 or index if I retry the watch after the index it return index+1:

```
$ curl -L -G '127.0.0.1:4001/v2/keys/fasdf2' -d wait=true -d recursive=true -d waitIndex=10
{"action":"create","key":"/fasdf2/9","value":"bar","index":9,"term":0}
$ curl -L -G '127.0.0.1:4001/v2/keys/fasdf2' -d wait=true -d recursive=true -d waitIndex=10
{"action":"create","key":"/fasdf2/10","value":"bar","index":10,"term":0}
$ curl -L -G '127.0.0.1:4001/v2/keys/fasdf2' -d wait=true -d recursive=true -d waitIndex=10
{"action":"create","key":"/fasdf2/11","value":"bar","index":11,"term":0}
```

**Comment by yichengq** [comment] 2015-04-10 23:32
I cannot reproduce it and belive that it has been fixed in 2.0

**Closed by yichengq** 2015-04-10 23:32 UTC
Labels: bug
