### ISSUE TITLE
cluster locks up if two members with same name

### ISSUE THREAD

**Issue by llamahunter** [coreos/etcd#5244] opened 2016-05-02 03:13 UTC
I am not 100% sure what's going on, but I think there's a bug somewhere in etcd2 where it does not treat different members with the same name very well.  It seems to miscount them.

I started with three nodes in my cluster.  I then added a 4th node, but typo'd the name such that it had the same name as an existing node, though it was assigned a unique member id.

When I went to manually bring up this node in the cluster using the new ETCD_INITIAL_CLUSTER that listed 4 nodes, it would not come up, claiming
```error validating peerURLs ...: member count is unequal```

I suspect somewhere deep in etcd2, it is putting members listed in ETCD_INITIAL_CLUSTER into a hash table based on their name rather their member id, and so it comes up with 3 nodes, but when consulting the cluster member list organized by member id, it sees 4.

Along the way, one of the nodes died, so, now I have 2 nodes running in a 4 node cluster. But, I can't restart either the failed node or the new node because of the 'member count unequal' problem.  And I can't remove the typo'd duplicate node name via 'etcdctl member remove' (with a unique id) because the cluster is now considered 'unhealthy' due to lack of quorum.

Any help in getting either of the duplicately named nodes without having to lose the entire cluster and restart from scratch?

**Comment by xiang90** [comment] 2016-05-02 03:16
What is the version of the etcd binary?

Can you please provide step by step instruction to reproduce?

**Comment by llamahunter** [comment] 2016-05-02 03:23
step by step instructions are more or less above, no?  I have not tried to reproduce it, as I'm currently trying to get my cluster back.

* create 3 node cluster
* 'member add'  a 4th node with same name as existing node but different peer url
* kill the node with the same name as the one just added
* try to start either of the nodes that have a duplicate name, but fail due to 'member count is unequal'
* try to 'member remove' duplicate named node, but fail due to 'etcd cluster is unavailable or misconfigured'

> % etcd -version
etcd version 0.4.9

**Comment by xiang90** [comment] 2016-05-02 03:32
@llamahunter 

I mean we need more specific and detailed steps. 

Here are my questions:
Are you using etcd 0.4.9 or etcd 2.2.3? What are the configuration/command do you use to create the 3 nodes cluster? What exact command do you use to add the 4th node? How do you kill the node? How do you restart the node? What is the exact log output? What argument you give to `member remove`?

**Comment by llamahunter** [comment] 2016-05-02 03:45
Per initial description, etcd2, which, I believe, is 2.2.3.

Initial cluster was created launching three etcd2 instances with a discovery url. One of the nodes was then replaced manually using a more intelligible name.  No problems with this so far.

4th node is added using 'etcdctl member add <node name> <peer url>'

the running node with the duplicate name had it's etcd2 instance SIGTERM'd

attempt to start new nodes is via the standard way.... using the ETCD_* variables that come out of the 'member add' and running etcd2 from the command line, listing the various peer/advertise/listen urls

the exact log output is 
<pre>
root# etcd2 -data-dir /var/lib/etcd2 -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://10.243.228.246:2379  -listen-peer-urls http://10.243.228.246:2380 -initial-advertise-peer-urls http://10.243.228.246:2380
2016-05-02 03:39:55.154548 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=core01.teab1.tivo.com=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
2016-05-02 03:39:55.154598 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2016-05-02 03:39:55.154618 I | flags: recognized and used environment variable ETCD_NAME=core01.teab1.tivo.com
2016-05-02 03:39:55.154702 I | etcdmain: etcd Version: 2.2.3
2016-05-02 03:39:55.154719 I | etcdmain: Git SHA: 05b564a
2016-05-02 03:39:55.154727 I | etcdmain: Go Version: go1.4.3
2016-05-02 03:39:55.154734 I | etcdmain: Go OS/Arch: linux/amd64
2016-05-02 03:39:55.154742 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
2016-05-02 03:39:55.154826 I | etcdmain: listening for peers on http://10.243.228.246:2380
2016-05-02 03:39:55.154868 I | etcdmain: listening for client requests on http://0.0.0.0:2379
2016-05-02 03:39:55.158348 I | etcdmain: stopping listening for client requests on http://0.0.0.0:2379
2016-05-02 03:39:55.158377 I | etcdmain: stopping listening for peers on http://10.243.228.246:2380
2016-05-02 03:39:55.158391 C | etcdmain: error validating peerURLs {ClusterID:1b0a52aed542d6b0 Members:[&{ID:149291bba7d50725 RaftAttributes:{PeerURLs:[http://10.243.228.246:2380]} Attributes:{Name:core01.teab1.tivo.com ClientURLs:[http://10.243.228.246:2379]}} &{ID:32124f388b63682a RaftAttributes:{PeerURLs:[http://core01.teab1.tivo.com:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:80c09bc33831bc4e RaftAttributes:{PeerURLs:[http://10.243.50.139:2380]} Attributes:{Name:15b5345d69494950900fdc08f25e730e ClientURLs:[http://10.243.50.139:2379]}} &{ID:eb06a5b3b0c7ca07 RaftAttributes:{PeerURLs:[http://10.243.128.162:2380]} Attributes:{Name:980e80e760d44f6a8e91bd68471928d5 ClientURLs:[http://10.243.128.162:2379]}}] RemovedMemberIDs:[]}: member count is unequal
</pre>

Attempts to `member remove` are using the id of the node listed via `member list`

**Comment by xiang90** [comment] 2016-05-02 03:49
> attempt to start new nodes is via the standard way.... using the ETCD_* variables that come out of the 'member add' and running etcd2 from the command line, listing the various peer/advertise/listen urls

What are the value of these environment variables?

From the log, it seems that the environment variables were bad.

**Comment by xiang90** [comment] 2016-05-02 03:51
It has nothing to do with the duplicate names from what I can see in the log at least.

**Comment by llamahunter** [comment] 2016-05-02 03:53
They're listed above...
<pre>
ETCD_INITIAL_CLUSTER=core01.teab1.tivo.com=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_NAME=core01.teab1.tivo.com
</pre>

I tried editing one of the names to be slightly different, and it gets past the immediate count check error (but then encounters much different errors later due to the member mismatch).  So, I'm pretty sure something is collapsing the two identically named values into a single hash entry.

**Comment by xiang90** [comment] 2016-05-02 04:00
@llamahunter 

Oh. OK. etcd does not use member name internally.

Here is the problem:
```
ETCD_INITIAL_CLUSTER=core01.teab1.tivo.com=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
```

For flags, each etcd member can take multiple addresses, so this list contains three etcd members, not four. You can change the name for the newly added member by modifying the environment variable to `XXX` for example. Then everything should be find.

```
ETCD_INITIAL_CLUSTER=XXX=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_NAME=XXX
```

**Comment by xiang90** [comment] 2016-05-02 04:05
> But, I can't restart either the failed node 

What do you mean by failed node? Does it still have pervious data dir? If yes, it should just restart without even checking the cluster membership since it already has the information. If not, then it means the actually lost its identity and you should just remove it from the cluster instead of trying to restart it.

**Comment by llamahunter** [comment] 2016-05-02 04:07
So, I sort of tried that already, but it fails spectacularly:
<pre>
# etcd2 -data-dir /var/lib/etcd2 -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://10.243.228.246:2379  -listen-peer-urls http://10.243.228.246:2380 -initial-advertise-peer-urls http://10.243.228.246:2380
2016-05-02 04:03:52.306751 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=XXX=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
2016-05-02 04:03:52.306788 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2016-05-02 04:03:52.306803 I | flags: recognized and used environment variable ETCD_NAME=XXX
2016-05-02 04:03:52.306872 I | etcdmain: etcd Version: 2.2.3
2016-05-02 04:03:52.306877 I | etcdmain: Git SHA: 05b564a
2016-05-02 04:03:52.306881 I | etcdmain: Go Version: go1.4.3
2016-05-02 04:03:52.306885 I | etcdmain: Go OS/Arch: linux/amd64
2016-05-02 04:03:52.306890 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
2016-05-02 04:03:52.306977 I | etcdmain: listening for peers on http://10.243.228.246:2380
2016-05-02 04:03:52.307006 I | etcdmain: listening for client requests on http://0.0.0.0:2379
2016-05-02 04:03:52.310493 I | netutil: resolving core01.teab1.tivo.com:2380 to 10.243.228.246:2380
2016-05-02 04:03:52.310555 I | netutil: resolving core01.teab1.tivo.com:2380 to 10.243.228.246:2380
2016-05-02 04:03:57.311119 W | etcdserver: failed to reach the peerURL(http://core01.teab1.tivo.com:2380) of member 32124f388b63682a (Get http://core01.teab1.tivo.com:2380/version: read tcp 10.243.228.246:2380: i/o timeout)
2016-05-02 04:03:57.311166 W | etcdserver: cannot get the version of member 32124f388b63682a (Get http://core01.teab1.tivo.com:2380/version: read tcp 10.243.228.246:2380: i/o timeout)
2016-05-02 04:03:57.315504 I | etcdserver: name = XXX
2016-05-02 04:03:57.315517 I | etcdserver: data dir = /var/lib/etcd2
2016-05-02 04:03:57.315524 I | etcdserver: member dir = /var/lib/etcd2/member
2016-05-02 04:03:57.315529 I | etcdserver: heartbeat = 100ms
2016-05-02 04:03:57.315538 I | etcdserver: election = 1000ms
2016-05-02 04:03:57.315543 I | etcdserver: snapshot count = 10000
2016-05-02 04:03:57.315550 I | etcdserver: advertise client URLs = http://10.243.228.246:2379
2016-05-02 04:03:57.323968 I | etcdserver: starting member 149291bba7d50725 in cluster 1b0a52aed542d6b0
2016-05-02 04:03:57.324018 I | raft: 149291bba7d50725 became follower at term 0
2016-05-02 04:03:57.324035 I | raft: newRaft 149291bba7d50725 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-05-02 04:03:57.324050 I | raft: 149291bba7d50725 became follower at term 1
2016-05-02 04:03:57.333377 I | etcdserver: starting server... [version: 2.2.3, cluster version: to_be_decided]
2016-05-02 04:03:57.334909 E | etcdmain: failed to notify systemd for readiness: No socket
2016-05-02 04:03:57.334937 E | etcdmain: forgot to set Type=notify in systemd service file?
2016-05-02 04:03:57.336149 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336294 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336405 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336550 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.338299 I | raft: 149291bba7d50725 [term: 1] received a MsgHeartbeat message with higher term from 80c09bc33831bc4e [term: 183]
2016-05-02 04:03:57.338336 I | raft: 149291bba7d50725 became follower at term 183
2016-05-02 04:03:57.338386 C | raft: tocommit(31449002) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(31449002) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

... lots and lots of go exception stuff elided ...
</pre>

**Comment by llamahunter** [comment] 2016-05-02 04:10
It lost it's data dir.  I would remove nodes from the cluster, but I can't due to the quorum issue due to the duplicate member name typo.

<pre>
core@core02 ~ $ etcdctl member list
149291bba7d50725: name=core01.teab1.tivo.com peerURLs=http://10.243.228.246:2380 clientURLs=http://10.243.228.246:2379
32124f388b63682a[unstarted]: peerURLs=http://core01.teab1.tivo.com:2380
80c09bc33831bc4e: name=15b5345d69494950900fdc08f25e730e peerURLs=http://10.243.50.139:2380 clientURLs=http://10.243.50.139:2379
eb06a5b3b0c7ca07: name=980e80e760d44f6a8e91bd68471928d5 peerURLs=http://10.243.128.162:2380 clientURLs=http://10.243.128.162:2379

core@core02 ~ $ etcdctl member remove 32124f388b63682a
Recieved an error trying to remove member 32124f388b63682a: client: etcd cluster is unavailable or misconfigured

core@core02 ~ $ etcdctl cluster-health
failed to check the health of member 149291bba7d50725 on http://10.243.228.246:2379: Get http://10.243.228.246:2379/health: dial tcp 10.243.228.246:2379: connection refused
member 149291bba7d50725 is unreachable: [http://10.243.228.246:2379] are all unreachable
member 32124f388b63682a is unreachable: no available published client urls
member 80c09bc33831bc4e is unhealthy: got unhealthy result from http://10.243.50.139:2379
member eb06a5b3b0c7ca07 is unhealthy: got unhealthy result from http://10.243.128.162:2379
cluster is unhealthy

core@core02 ~ $ etcdctl ls /coreos.com
/coreos.com/updateengine
</pre>

**Comment by xiang90** [comment] 2016-05-02 04:12
@llamahunter Two of your members have the exact same peer urls. It confuses etcd cluster to send the correct request to correct member. That is a fatal operational error.

```
XXX=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380
```

http://core01.teab1.tivo.com is resolved to 10.243.228.246:2380, which is XXX's addr.

That is why XXX got

```
2016-05-02 04:03:57.336149 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336294 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336405 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
2016-05-02 04:03:57.336550 E | rafthttp: streaming request ignored (ID mismatch got 32124f388b63682a want 149291bba7d50725)
```

**Comment by llamahunter** [comment] 2016-05-02 04:13
they both have the same name and the same peer url, then, so why is there a problem?

**Comment by xiang90** [comment] 2016-05-02 04:16
@llamahunter As I said, etcd does not care about name internally. They are different members. If you use same peer urls to add them, etcd will compliant about duplicate peer urls for different members. Also as you mentioned, you want to add a new member rather than replacing the old member. What etcd did does match your expectation. The problem is that you gave the two members "same" ip:port which confused etcd later.

**Comment by llamahunter** [comment] 2016-05-02 04:17
So, if you give them the same name and url, etcd2 gets confused, and if you give them different names, it  also gets confused?  Is there any way to unconfuse etcd2?  Seems fragile...

**Comment by xiang90** [comment] 2016-05-02 04:18
To fix the problem, you probably need to point `core01.teab1.tivo.com` to some other ip and then start the newly add one. Then you can remove the dead one.

**Comment by llamahunter** [comment] 2016-05-02 04:19
hmmm... could I add a 5th node, obtain a quorum, then remove the two duplicate nodes?  Or will things simply not start up anymore in the current configuration?

**Comment by xiang90** [comment] 2016-05-02 04:19
@llamahunter As I said, you SHOULD NOT give assign same addr:ip to different etcd members. You do not really understand what I said it seems...

**Comment by llamahunter** [comment] 2016-05-02 04:20
Again, this was not intentional.  It was a typo.  It is unfortunate that there is no easy recovery path.

**Comment by xiang90** [comment] 2016-05-02 04:24
> Or will things simply not start up anymore in the current configuration?

I have provided a solution in my previous reply for you to try (change dns temporarily). etcd does try its best to check duplicate peer urls for different members. It is impossible to make it 100% accurate when you give one ip:port and another one dns.

> It is unfortunate that there is no easy recovery path.

Yes. Typically, you need to be careful when doing re-configuration. You lost a member during a re-configuration, which is a disaster.

**Comment by xiang90** [comment] 2016-05-02 04:32
@llamahunter Or you can try https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#disaster-recovery.

**Comment by llamahunter** [comment] 2016-05-02 04:35
Ok, so changed the DNS of core01.teab1.tivo.com, but still having trouble.  Ignores the unreachable core01.teab1.tivo.com, and seems to connect to the two other 'healthy'-ish members, but then immediately has trouble.

I'm guessing snapshotting the other two members and bringing up an entirely new cluster is the only real way forward?

<pre>
# etcd2 -data-dir /var/lib/etcd2 -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://10.243.228.246:2379  -listen-peer-urls http://10.243.228.246:2380 -initial-advertise-peer-urls http://10.243.228.246:2380
2016-05-02 04:29:47.988076 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=XXX=http://10.243.228.246:2380,core01.teab1.tivo.com=http://core01.teab1.tivo.com:2380,15b5345d69494950900fdc08f25e730e=http://10.243.50.139:2380,980e80e760d44f6a8e91bd68471928d5=http://10.243.128.162:2380
2016-05-02 04:29:47.988126 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2016-05-02 04:29:47.988146 I | flags: recognized and used environment variable ETCD_NAME=XXX
2016-05-02 04:29:47.988220 I | etcdmain: etcd Version: 2.2.3
2016-05-02 04:29:47.988236 I | etcdmain: Git SHA: 05b564a
2016-05-02 04:29:47.988244 I | etcdmain: Go Version: go1.4.3
2016-05-02 04:29:47.988252 I | etcdmain: Go OS/Arch: linux/amd64
2016-05-02 04:29:47.988261 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
2016-05-02 04:29:47.988356 I | etcdmain: listening for peers on http://10.243.228.246:2380
2016-05-02 04:29:47.988399 I | etcdmain: listening for client requests on http://0.0.0.0:2379
2016-05-02 04:29:47.992033 I | netutil: resolving core01.teab1.tivo.com:2380 to 10.243.228.247:2380
2016-05-02 04:29:47.992138 I | netutil: resolving core01.teab1.tivo.com:2380 to 10.243.228.247:2380
2016-05-02 04:29:49.192513 W | etcdserver: failed to reach the peerURL(http://core01.teab1.tivo.com:2380) of member 32124f388b63682a (Get http://core01.teab1.tivo.com:2380/version: dial tcp 10.243.228.247:2380: i/o timeout)
2016-05-02 04:29:49.192557 W | etcdserver: cannot get the version of member 32124f388b63682a (Get http://core01.teab1.tivo.com:2380/version: dial tcp 10.243.228.247:2380: i/o timeout)
2016-05-02 04:29:49.196868 I | etcdserver: name = XXX
2016-05-02 04:29:49.196894 I | etcdserver: data dir = /var/lib/etcd2
2016-05-02 04:29:49.196906 I | etcdserver: member dir = /var/lib/etcd2/member
2016-05-02 04:29:49.196915 I | etcdserver: heartbeat = 100ms
2016-05-02 04:29:49.196922 I | etcdserver: election = 1000ms
2016-05-02 04:29:49.196953 I | etcdserver: snapshot count = 10000
2016-05-02 04:29:49.197002 I | etcdserver: advertise client URLs = http://10.243.228.246:2379
2016-05-02 04:29:49.203929 I | etcdserver: starting member 149291bba7d50725 in cluster 1b0a52aed542d6b0
2016-05-02 04:29:49.203977 I | raft: 149291bba7d50725 became follower at term 0
2016-05-02 04:29:49.203999 I | raft: newRaft 149291bba7d50725 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-05-02 04:29:49.204017 I | raft: 149291bba7d50725 became follower at term 1
2016-05-02 04:29:49.212969 I | etcdserver: starting server... [version: 2.2.3, cluster version: to_be_decided]
2016-05-02 04:29:49.214693 E | etcdmain: failed to notify systemd for readiness: No socket
2016-05-02 04:29:49.214721 E | etcdmain: forgot to set Type=notify in systemd service file?
2016-05-02 04:29:49.215765 I | rafthttp: the connection with 80c09bc33831bc4e became active
2016-05-02 04:29:49.224225 I | rafthttp: the connection with eb06a5b3b0c7ca07 became active
2016-05-02 04:29:49.224379 I | raft: 149291bba7d50725 [term: 1] received a MsgHeartbeat message with higher term from 80c09bc33831bc4e [term: 183]
2016-05-02 04:29:49.224407 I | raft: 149291bba7d50725 became follower at term 183
2016-05-02 04:29:49.224444 C | raft: tocommit(31449002) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(31449002) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
</pre>

**Comment by xiang90** [comment] 2016-05-02 04:39
@llamahunter 

So we need to do another thing to fix this... What happened is that the previous dead node was pretending to be the newly added node (since the message sent to the newly added one was delivered to it due to the same ip:port.), and increase the commit index. The commit index fails due to a safety checking.

If you can ssh into the other two members, try to simply restart them and then start the newly added one again. The commit index is kept in memory.

**Comment by llamahunter** [comment] 2016-05-02 04:49
ah... ok... well, good to know. I tried that, and it *looked* like it worked.  The failing node was able to rejoin, but then, a short time later, all three nodes went down simultaneously due to

<pre>
May 02 04:42:19 core03.teab1.tivo.com etcd2[10967]: nodeToMember should never fail: raftAttributes key doesn't exist
May 02 04:42:20 core03.teab1.tivo.com etcd2[10967]: failed to write 32124f388b63682a on pipeline (net/http: request canceled while waiting for connection)
May 02 04:42:20 core03.teab1.tivo.com systemd[1]: etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 04:42:20 core03.teab1.tivo.com systemd[1]: etcd2.service: Unit entered failed state.
May 02 04:42:20 core03.teab1.tivo.com systemd[1]: etcd2.service: Failed with result 'exit-code'.
</pre>

So, now I am definitely in disaster recovery mode, as there are no longer *any* members running.  Fortunately, I took an etcd2 backup before doing this, so I'm off to learn about rebuilding a cluster from a backup now.

Thanks for the help.

**Comment by xiang90** [comment] 2016-05-02 04:56
@llamahunter 

> May 02 04:42:19 core03.teab1.tivo.com etcd2[10967]: nodeToMember should never fail: raftAttributes key doesn't exist

This seems like a real bug that I do not understand. All the following restart will result the same panic? Do you still have the data dir available? Can you share it somehow?

Honestly, I do not know what can happen if two members have the same ip:port in the same cluster. We try to avoid that compare ip:port directly when adding a new member. Probably we will try to resolve dns to make it more robust. Also for the output of etcdctl, we probably need to improve. So it will not generate bad env variables for users to copy.

**Comment by xiang90** [comment] 2016-05-02 05:06
@llamahunter never mind... That is actually fixed by https://github.com/coreos/etcd/pull/3657/files. But the fix is not included in 2.2.3. Sorry about that!

**Comment by llamahunter** [comment] 2016-05-02 05:15
Good to hear. Well, I will be more cautious from now on when touching etcd2. I think I've recovered one of the nodes from the backup.  Moving on to adding the other nodes back into the (new) cluster now.

**Closed** 2016-05-02 05:15 UTC

**Comment by xvuudao** [comment] 2018-05-24 09:18
I'm using etcd Version: 3.1.4 and got the same issue. Was the fix applied to this version ?

> 2018-05-24 10:47:02.709018 I | etcdmain: etcd Version: 3.1.4
> 2018-05-24 10:47:02.709603 I | etcdmain: Git SHA: 41e52eb
> 2018-05-24 10:47:02.709627 I | etcdmain: Go Version: go1.7.5
> 2018-05-24 10:47:02.709637 I | etcdmain: Go OS/Arch: linux/amd64
> 2018-05-24 10:47:02.709647 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
> 2018-05-24 10:47:02.709660 N | etcdmain: failed to detect default host (could not find default route)
> 2018-05-24 10:47:02.711243 I | embed: listening for peers on http://192.168.86.3:2380
> 2018-05-24 10:47:02.711296 I | embed: listening for client requests on 192.168.86.3:2379
> 2018-05-24 10:47:02.750765 C | etcdmain: error validating peerURLs {ClusterID:2509c3574ea27a58 Members:[&{ID:1ca3d1651894e812 RaftAttributes:{PeerURLs:[http://192.168.86.6:2380]} Attributes:{Name:PL-2-6 ClientURLs:[http://192.168.86.6:2379]}} &{ID:6fbf7111d9b203f0 RaftAttributes:{PeerURLs:[http://192.168.86.5:2380]} Attributes:{Name:PL-2-5 ClientURLs:[http://192.168.86.5:2379]}} &{ID:8e1463045967bc12 RaftAttributes:{PeerURLs:[http://192.168.86.1:2380]} Attributes:{Name:SC-2-1 ClientURLs:[http://192.168.86.1:2379]}} &{ID:f012f8443d609988 RaftAttributes:{PeerURLs:[http://192.168.86.2:2380]} Attributes:{Name:SC-2-2 ClientURLs:[http://192.168.86.2:2379]}} &{ID:f37d311373e86af9 RaftAttributes:{PeerURLs:[http://192.168.86.3:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:120c51d2d69cf717 RaftAttributes:{PeerURLs:[http://192.168.86.4:2380]} Attributes:{Name:PL-2-4 ClientURLs:[http://192.168.86.4:2379]}}] RemovedMemberIDs:[]}: member count is unequal
