### ISSUE TITLE
Add "recursive = true", auth failed

### ISSUE THREAD

**Issue by sipt** [coreos/etcd#5673] opened 2016-06-15 06:52 UTC
If i add "recursive = true", will return "The request requires user authentication".
```
[wxy@localhost ~]$ etcdctl -u root:123123 role get myrole
Role: myrole
KV Read:
	/queue
	/queue/
	/queue/*
	/queue/**
KV Write:
	/queue
	/queue/
	/queue/*
	/queue/**
[wxy@localhost ~]$ etcdctl -u root:123123 user get test
User: test
Roles:  myrole
[wxy@localhost ~]$ curl 'http://192.168.0.235:2379/v2/keys/queue?recursive=true&sorted=true' -H "Authorization:Basic dGVzdDoxMjMxMjM="
2016-06-15 00:51:22.115372 W | etcdhttp: auth: invalid access for user test on key /queue.
{
    "errorCode": 110,
    "message": "The request requires user authentication",
    "cause": "Insufficient credentials",
    "index": 0
}
[wxy@localhost ~]$ curl 'http://192.168.0.235:2379/v2/keys/queue?sorted=true' -H "Authorization:Basic dGVzdDoxMjMxMjM="
{
    "action": "get",
    "node": {
        "key": "/queue",
        "dir": true,
        "nodes": [
            {
                "key": "/queue/00000000000000000348",
                "value": "test auth",
                "modifiedIndex": 348,
                "createdIndex": 348
            },
            {
                "key": "/queue/00000000000000000349",
                "value": "test auth",
                "modifiedIndex": 349,
                "createdIndex": 349
            }
        ],
        "modifiedIndex": 60,
        "createdIndex": 60
    }
}
[wxy@localhost ~]$
```

**Comment by heyitsanthony** [comment] 2016-06-20 22:17
@sipt 
This is expected behavior according to the docs-- https://github.com/coreos/etcd/blob/master/Documentation/v2/auth_api.md#key-value-resources

`/queue/*` will give access to `/queue/`'s immediate children-- `/queue/348` and `/queue/349` are accessible but not a deeper path like `/queue/a/b`. Since `recursive` may try to access deeper paths, auth will reject it even if no deeper paths exist.

If you need `recursive`, granting permissions on `/queue*` will give access to all of `/queue/`'s subdirectories (but will also grant access to other keys that match the prefix like `/queueX`).

**Comment by xiang90** [comment] 2016-06-20 23:39
Closing since this works as intended.

**Closed by xiang90** 2016-06-20 23:39 UTC
