### ISSUE TITLE
etcd client missing a watch update.

### ISSUE THREAD

**Issue by adityadani** [coreos/etcd#9107] opened 2018-01-06 02:27 UTC
Env info:

```
etcd (client and server) version: 3.2.2
etcd server cluster size: 3
```

I have 3 etcd clients configured with all the 3 etcd server endpoints.

Expectation: 
I am testing a scenario where one of the etcd server endpoints goes down, but the etcd clients should still get the watch updates.  

Outcome: 
One of the 3 clients does not get an update for 30 seconds. While other 2 clients get the update instantly.

The key put operation was done at timestamp `2018-01-05T10:05:13`. We expect a watch update within 30 seconds.

Here are the etcd server logs 
[etcd-server-169](https://gist.github.com/adityadani/abcad7299f17bd44232c714db5ad6226)
[etcd-server-170](https://gist.github.com/adityadani/a887329a1e86749b0d5ada0f382e292a) - Node which was stopped
[etcd-server-171](https://gist.github.com/adityadani/47f8f04e9537c667c43548d8fc6a6ebb)

In order to debug this issue I had added a debug statement in etcd clientv3's balancer code to print the last pinned etcd server address. 
Two clients were pinned to etcd server 169 while the one client which did not get the update was pinned to etcd server 171.

An interesting log line I found on 169 was this
```
2018-01-05 10:05:13.815332 W | etcdserver: timed out waiting for read index response
```
The above timestamp lies within our 30 seconds timeout where we expect the update. 
I have referred to #7970 which suggests that the fsync durations are high causing leader elections. But could that lead to a client which is connected to another etcd server to miss an update?

Any help will be much appreciated.

**Comment by xiang90** [comment] 2018-01-06 02:39
can you provide detailed steps or a simple script to reproduce the problem you hit?

**Comment by adityadani** [comment] 2018-01-06 02:50
I am not able to reproduce this issue consistently, may be 2 out of 10 times.
I dont have a script as such as this test case is a part of a bigger test effort. 
But essentially it does this in a loop

```
On the server side:
1. Select one node randomly from the etcd cluster and stop it.
2. Start the node back and let it join the cluster.

Setup 3 clients to talk to the 3 etcd server
On the client side:
1. Continuously put keys into etcd and expect watch updates within 30 seconds.
```

**Comment by xiang90** [comment] 2018-01-06 02:54
> I dont have a script as such as this test case is a part of a bigger test effort.
But essentially it does this in a loop

can you please put some effort to create a script that we can run to reproduce it?

**Comment by adityadani** [comment] 2018-01-06 02:57
@xiang90 Sure. Let me do that.

On a side note, can high fsync latency on a node cause such missed watch updates? Or are they completely unrelated

**Comment by xiang90** [comment] 2018-01-06 03:05
No. It should not be related. Also I should suggest you try latest 3.2.13
release.

**Comment by wgw335363240** [comment] 2018-01-15 13:35
I met same problem and etcd version is 3.2.9.   And the same with 3.3.0.rc

**Comment by xiang90** [comment] 2018-01-15 19:32
@wgw335363240 

can you reproduce it?

**Comment by wgw335363240** [comment] 2018-01-17 05:54
A new envionment does not have the problem.

**Comment by xiang90** [comment] 2018-01-17 06:09
@wgw335363240 

there is no way for us to help unless you tell us how to reproduce the problem.

**Comment by xiang90** [comment] 2018-01-24 21:41
i am going to close this due to low activity. please reopen if anyone can reproduce it or can prove this is an real issue.

**Closed by xiang90** 2018-01-24 21:41 UTC
