### ISSUE TITLE
TestTLSGRPCRejectInsecureClient fail

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4679] opened 2016-03-04 03:27 UTC
https://semaphoreci.com/coreos/etcd/branches/pull-request-4678/builds/12

```
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:31 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:31 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
...
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:38 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:33 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x73679f]

goroutine 18552 [running]:
github.com/coreos/etcd/contrib/recipes.(*DoubleBarrier).Leave(0xc821727f40, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/contrib/recipes/double_barrier.go:77 +0x1af
github.com/coreos/etcd/contrib/recipes.(*DoubleBarrier).Leave(0xc821727f40, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/contrib/recipes/double_barrier.go:130 +0x70c
github.com/coreos/etcd/integration.TestDoubleBarrierFailover.func2(0xc8232f77a0, 0xa, 0xc820178c60, 0xc82b73e540)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:109 +0x2b1
created by github.com/coreos/etcd/integration.TestDoubleBarrierFailover
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:111 +0x1a6

```

**Comment by xiang90** [comment] 2016-03-04 03:29
> github.com/coreos/etcd/contrib/recipes.(*DoubleBarrier).Leave(0xc821727f40, 0x0, 0x0)/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/contrib/recipes/double_barrier.go:77 +0x1af

@heyitsanthony seems like there is also a routine leak?

**Comment by heyitsanthony** [comment] 2016-03-04 08:26
Source of leak is probably:
```
--- FAIL: TestDoubleBarrierFailover (10.25s)
	v3_double_barrier_test.go:119: timed out waiting for enter, 9
```

**Comment by gyuho** [comment] 2016-03-04 18:19
@heyitsanthony I think this is fixed by https://github.com/coreos/etcd/pull/4683?
I don't see it anymore after your patch.

**Comment by heyitsanthony** [comment] 2016-03-04 18:24
I don't think that patch fixes the problem; there would have been a panic in the test log if it was hitting that path.

**Comment by xiang90** [comment] 2016-03-05 00:51
The root cause is #4688. Closing this one in favor of #4688.

**Comment by gyuho** [comment] 2016-03-05 21:26
We got one more. This time `TestTLSGRPCRejectInsecureClient` times out after 15m.

Looks like remote address causes grpc to error:

```
=== RUN   TestTLSGRPCRejectInsecureClient
2016/03/05 21:04:52 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/05 21:04:52 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```

https://github.com/grpc/grpc-go/blob/master/server.go#L273

**Closed** 2016-03-07 22:02 UTC
Labels: area/testing
