### ISSUE TITLE
etcdctl v3 environment variables

### ISSUE THREAD

**Issue by bhouse** [coreos/etcd#6645] opened 2016-10-13 17:19 UTC
Hi!

This is just a question, I'm wondering if the same environment variables for `etcdctl` from v2 are supported in v3? Specifically the TLS related ones [here](https://github.com/coreos/etcd/blob/master/etcdctl/ctlv2/command/util.go#L158-L168). I couldn't find a reference for them in the v3 code, and they don't appear to work in my tests.

Thanks!

**Comment by gyuho** [comment] 2016-10-13 17:36
It's not supported now.

/cc @xiang90 @heyitsanthony  Should we add those to v3?

**Comment by bhouse** [comment] 2016-10-13 22:21
It would be awesome if you could add them!

Currently our etcd client certs require root permissions to read them for etcdctl, so I'm using env vars to point to them, and allowing the env vars to pass through sudo (via `env_keep`). This makes the user experience intuitive for using client cert auth.

```
[bhouse@ip-10-0-222-205 ~]$ cat /etc/profile.d/etcdctl.sh
export ETCDCTL_CA_FILE='/srv/etcd/etcd-ca.crt'
export ETCDCTL_CERT_FILE='/srv/etcd/etcd-client.crt'
export ETCDCTL_KEY_FILE='/srv/etcd/etcd-client.key'
export ETCDCTL_ENDPOINTS='https://127.0.0.1:2379'
[bhouse@ip-10-0-222-205 ~]$ sudo cat /etc/sudoers.d/etcdctl
Defaults    env_keep += "ETCDCTL_CA_FILE"
Defaults    env_keep += "ETCDCTL_CERT_FILE"
Defaults    env_keep += "ETCDCTL_ENDPOINTS"
Defaults    env_keep += "ETCDCTL_KEY_FILE"
```

```
[bhouse@ip-10-0-222-205 ~]$ etcdctl member list
open /srv/etcd/etcd-client.crt: permission denied
[bhouse@ip-10-0-222-205 ~]$ env | grep ETCDCTL
ETCDCTL_ENDPOINTS=https://127.0.0.1:2379
ETCDCTL_CA_FILE=/srv/etcd/etcd-ca.crt
ETCDCTL_KEY_FILE=/srv/etcd/etcd-client.key
ETCDCTL_CERT_FILE=/srv/etcd/etcd-client.crt
[bhouse@ip-10-0-222-205 ~]$ sudo env | grep ETCDCTL
[sudo] password for bhouse:
ETCDCTL_ENDPOINTS=https://127.0.0.1:2379
ETCDCTL_CA_FILE=/srv/etcd/etcd-ca.crt
ETCDCTL_KEY_FILE=/srv/etcd/etcd-client.key
ETCDCTL_CERT_FILE=/srv/etcd/etcd-client.crt
[bhouse@ip-10-0-222-205 ~]$ sudo etcdctl member list
a5389351e34ce31: name=member3 peerURLs=https://10.0.222.13:2380 clientURLs=https://10.0.222.20:2379 isLeader=true
...
```

**Comment by gyuho** [comment] 2016-10-13 22:34
We have something similar `flags.SetPflagsFromEnv("ETCDCTL", cmd.InheritedFlags())` in etcdctl v3, but apparently it's not working. I will double-check and get back to you.

Thanks for reporting.

**Comment by gyuho** [comment] 2016-10-14 19:17
@bhouse Confirmed that it's already supported in v3. You just need to pass different env vars

```
ETCDCTL_CACERT=/tmp/ca.pem
ETCDCTL_CERT=/tmp/cert.pem
ETCDCTL_KEY=/tmp/key.pem
```

since we change our flag strings in v3.

Please let me know if you have more questions.

Closing via https://github.com/coreos/etcd/pull/6650

**Closed by gyuho** 2016-10-14 19:17 UTC
Labels: kind/enhancement

**Comment by bhouse** [comment] 2016-10-14 20:46
Thanks @gyuho for the doc fix and quick responses! 👍  🎉

**Comment by joedborg** [comment] 2019-11-12 16:15
@gyuho has the `ETCDCTL_ENDPOINT` var changed as well?

```
ETCDCTL_ENDPOINT=https://172.31.29.136:2379 ETCDCTL_API=3 etcd.etcdctl alarm list
2019-11-12 16:12:34.380364 W | pkg/flags: unrecognized environment variable ETCDCTL_ENDPOINT=https://172.31.29.136:2379
{"level":"warn","ts":"2019-11-12T16:12:39.380Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-94f07616-208e-48a3-93ca-375e82d5e4f0/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 172.31.11.86, 172.31.29.136, 172.31.37.38, 252.29.136.1, 54.157.232.230, not 127.0.0.1\""}
```

**Comment by jingyih** [comment] 2019-11-12 18:33
@joedborg Please refer to [1] for all the supported env variables.

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md

**Comment by Peakchen** [comment] 2022-05-11 08:03
> @joedborg Please refer to [1] for all the supported env variables.
> 
> [1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md

it can not open？
