### ISSUE TITLE
Snapshot restored cluster not sync-ing up

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#6361] opened 2016-09-06 17:52 UTC
# Problem

Three members etcd cluster that were restored from snapshot couldn't sync up and end up serving different result.

# How to reproduce

ETCD_VERSION=(master tip)

Assumed I have a cluster that has key "foo=bar". Now I'm taking the snapshot by doing:
```
$ ETCDCTL_API=3 etcdctl snapshot save latest.backup
```

After shutting down the cluster, restore the snapshot:
```
$ ETCDCTL_API=3 etcdctl snapshot restore latest.backup \
  --name infra1 \
  --initial-cluster infra1=http://127.0.0.1:12380 \
  --initial-cluster-token etcd-cluster-2 \
  --initial-advertise-peer-urls http://127.0.0.1:12380 \
  --data-dir data.etcd1
```

Then start one member etcd:
```
$ etcd --name infra1 \
  --listen-client-urls http://127.0.0.1:2379 \
  --advertise-client-urls http://127.0.0.1:2379 \
  --listen-peer-urls http://127.0.0.1:12380 \
  --initial-advertise-peer-urls http://127.0.0.1:12380 \
  --initial-cluster-token etcd-cluster-2 \
  --initial-cluster infra1=http://127.0.0.1:12380 \
  --initial-cluster-state new \
  --data-dir data.etcd1
```

I can verify that the data is correct:
```
$ ETCDCTL_API=3 etcdctl get foo
foo
bar
```

Then add a second member:
```
$ etcdctl member add infra2 http://127.0.0.1:22380
$ etcd --name infra2 \
  --listen-client-urls http://127.0.0.1:22379 \
  --advertise-client-urls http://127.0.0.1:22379 \
  --listen-peer-urls http://127.0.0.1:22380 \
  --initial-advertise-peer-urls http://127.0.0.1:22380 \
  --initial-cluster "infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380" \
  --initial-cluster-state existing \
  --data-dir data.etcd2
```

Wait after cluster gets stable, I get different results:
```
$ ETCDCTL_API=3 etcdctl get foo -w json
{"header":{"cluster_id":9938042548879139131,"member_id":9938617409493207853,"revision":2,"raft_term":7},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":2,"version":1,"value":"YmFy"}],"count":1}
$ ETCDCTL_API=3 etcdctl --endpoints http://127.0.0.1:22379 get foo -w json
{"header":{"cluster_id":9938042548879139131,"member_id":7821991461170905411,"revision":1,"raft_term":7}}
```
No value returns from the newly added endpoint "infra2".

Note that they have the same member list:
```
$ etcdctl member list
6c8d4bca8f3b0143: name=infra2 peerURLs=http://127.0.0.1:22380 clientURLs=http://127.0.0.1:22379 isLeader=false
89ed0fe07b5b0b2d: name=infra1 peerURLs=http://127.0.0.1:12380 clientURLs=http://127.0.0.1:2379 isLeader=true
$ etcdctl --endpoints http://127.0.0.1:22379 member list
6c8d4bca8f3b0143: name=infra2 peerURLs=http://127.0.0.1:22380 clientURLs=http://127.0.0.1:22379 isLeader=false
89ed0fe07b5b0b2d: name=infra1 peerURLs=http://127.0.0.1:12380 clientURLs=http://127.0.0.1:2379 isLeader=true
```

**Comment by xiang90** [comment] 2016-09-06 20:09
@heyitsanthony @hongchaodeng 

I looked at the code, and found the root cause.
For restore, we create a new WAL and a new DB. This works well for restored member. However, if we add a new member before any snapshot is taken, there will be an issue. The restored member will send over the WAL files but not DB files to the newly add member.

We should force the restored member to have a snapshot that matches the DB file in the restore case. So he restored member will always send snapshot to other members.

**Comment by xiang90** [comment] 2016-09-06 22:19
I am fixing this. I can finish this probably in two days. If anyone is in urgent, probably you can go ahead to fix it on your own.

**Comment by xiang90** [comment] 2016-09-08 20:21
fixed by https://github.com/coreos/etcd/pull/6370

**Closed by xiang90** 2016-09-08 20:21 UTC
Labels: kind/bug, priority/P1
