### ISSUE TITLE
new random election timeout on every tick

### ISSUE THREAD

**Issue by ongardie** [coreos/etcd#4887] opened 2016-03-29 03:23 UTC
I was browsing around with @superfell earlier, and I think this code https://github.com/coreos/etcd/blob/v2.3.0/raft/raft.go#L874 compares against a new random election timeout every time tickElection() is called. If the new random value is ever smaller than the ticks elapsed, it'll start a new election. This is really different from choosing a random election timeout, then waiting for it to elapse. The more you call the tickElection function, the shorter your effective election timeout will be. I didn't measure it, but I'd expect this to cause a higher split vote rate than necessary.

**Comment by xiang90** [comment] 2016-03-29 03:45
@ongardie 

I am aware this. We did the first simple implementation (without remembering the first choice) and did some test around this: https://github.com/coreos/etcd/blob/master/raft/raft_paper_test.go#L350-L384

The ideal value should be around 30%, which is (A10,5)/(10^5).

With the current implementation, it grows up to 35%-40%. 

I am not sure there is a real effect in practical with such small number. But yes, we should make this better.

**Comment by xiang90** [comment] 2016-03-29 03:55
@ongardie Btw, thanks for bringing this up. We will get a fix soon.

**Comment by ongardie** [comment] 2016-03-29 06:16
@xiang90 your test looks like it only checks if servers time out at the exact same tick. That's not the same as a split vote rate, where two servers timing out at nearly the same time can still cause a split vote.

What's (A10,5)/(10^5) mean? I don't think I get the syntax.

How frequent are ticks? What's a typical election timeout set to?

**Comment by xiang90** [comment] 2016-03-29 06:33
I mentioned "But this calculation is not exactly effective since raft votes only conflicts when the number conflicts happens with the smallest chosen number."

So you are right. That is an approximation to compare the ideal one and the current one. I feel the actual difference should be smaller.

> What's (A10,5)/(10^5) mean

Sorry. It seems like America calls this P 10,5, which is short for Permutations. No idea why we call this A in China...

> How frequent are ticks? What's a typical election timeout set to?

A tick is usually larger than expected RTT (heartbeat per tick; and election timeout is 10*ticks by default). So if different servers timeout at different tick, we can expect no split votes. But yea... There might be other cases when RTTs between different machines can vary a lot.

**Comment by ongardie** [comment] 2016-03-29 17:50
I see. Ticks are less frequent than I imagined, which lessens the severity of this randomness problem. Still, if ticks are too infrequent (say you only had 1 per election timeout), you'd expect to see a high split vote rate. I'm wondering whether 10 is enough.

How frequent are ticks typically in milliseconds? And how long is a typical one-way latency (half RTT) in milliseconds?

**Comment by xiang90** [comment] 2016-03-29 17:57
> How frequent are ticks typically in milliseconds? And how long is a typical one-way latency (half RTT) in milliseconds?

You mean the default, right? For the default setup in etcd, we assume the machines are in one DC. We assume the one-way latency is usually well under 10ms (<1ms for most of the time).

The default heartbeat tick is around 100ms and election timeout is 10 ticks (1s). Sometimes, we suggest to set to 10ms, 300ms for faster recovery (higher false positive rate though... GC, high load can lead to higher latency to start sending heartbeat).

**Comment by ongardie** [comment] 2016-03-29 18:19
Thanks.

I think this might make a good detour in my CoreOS Fest talk, along with hashicorp/raft#109. I'm working on a tool that includes a visualization component like RaftScope but also a simulator and model checker. It might be fun to talk through Raft's randomized timeout algorithm and these two variations, and show some graphs from simulations of how they compare. Those default/typical values are good for plugging into the simulation.

I'd be picking on you guys a little, but my take-aways would be:
 - Raft, including its randomized election timeouts, can be a little subtle.
 - On the other hand, randomness can be forgiving.
 - A tool like what I'm building can be useful to better understand the behavior of different designs.

Of course, I'll be happy to mention that you guys are working on this or have already changed it by then. :)

Do you have a sense for whether different servers will be ticking at similar times or offset from another? Does it depend on whether a leader just sent out heartbeats? I didn't get to looking at this part of the code (is it somewhere in raft/node.go?).

**Comment by xiang90** [comment] 2016-03-29 18:25
> Do you have a sense for whether different servers will be ticking at similar times or offset from another? Does it depend on whether a leader just sent out heartbeats? I didn't get to looking at this part of the code (is it somewhere in raft/node.go?).

The ticking is not synced. Actually I can get some real world data for you. We are injecting failures into etcd consistently on GCE (http://dash.etcd.io/dashboard/db/functional-tests). We have the data of split votes :). We did observe some long election, but most of them are caused by the bad buffer/batching mechanism used by upper layer.

**Comment by ongardie** [comment] 2016-03-29 18:35
Cool, I'd love to have the real-world data for comparison.


> The ticking is not synced.

What if I were to boot the servers at the same time?

**Comment by xiang90** [comment] 2016-03-29 19:14
> What if I were to boot the servers at the same time?

By not synced, I mean we do not sync the ticker intentionally.

**Comment by xiang90** [comment] 2016-04-01 19:36
Fixed by https://github.com/coreos/etcd/pull/4929.

**Closed by xiang90** 2016-04-01 19:36 UTC
Labels: component/raft
