### ISSUE TITLE
Multi-raft documentation

### ISSUE THREAD

**Issue by Iulian7** [coreos/etcd#8562] opened 2017-09-14 10:09 UTC
I saw some issues open from last year about this (#4932, #5107) however I could not find any more documentation about this. Is there any more documentation about using raft for multiple consensus groups (multi-raft)? Any documentation/examples for rawnode?

**Comment by heyitsanthony** [comment] 2017-09-14 12:56
No, that's why the issue is still open. Duplicates #4932; closing.

**Closed by heyitsanthony** 2017-09-14 12:56 UTC
Labels: component/raft, kind/documentation
