### ISSUE TITLE
2-node cluster with TLS peering stops making progress after a few seconds

### ISSUE THREAD

**Issue by danderson** [coreos/etcd#3095] opened 2015-07-04 21:23 UTC
I'm creating a 1-node etcd cluster with static bootstrapping, then expanding to 2 nodes with runtime reconfiguration. TLS is enabled for peer communication. When the second replica starts, writes start succeeding (albeit with multi-second latency) for a few seconds. After that, writes start to hang, and both etcd replicas start complaining continuously that their message queue to their peer is full, causing message discards.

The setup is two KVM VMs running on the same physical host, connected via a bridge interface on the host. Both nodes are running coreos stable (681.2.0) and etcd2 2.0.10.

Github won't let me attach non-image files, but I've collected a bunch of files at https://drive.google.com/folderview?id=0B45M0RJpnb64fnhzY0lsRnh5LUxHVF9OR2IxVmpSZDFJbjd4SGhMUEZWZHdvdmFQazBFOVk&usp=sharing :
* Cluster build logs. I'm using Fabric to set up the two etcd nodes, and the log contains all the commands being run, as well as some etcdctl output at various stages, and `systemctl cat` of the etcd2 units on both nodes.
* etcd2 logs for both nodes
* Drop-in systemd unit configuration for both nodes
* Peering and client certs/keys for both nodes (these keys and CAs are playground CAs, not sensitive)
* Both peering and client CAs for the cluster

Lemme know if there's any other data I can usefully provide to reproduce.

**Comment by philips** [comment] 2015-07-04 21:42
I believe this is related to or a duplicate of #2539.

**Comment by philips** [comment] 2015-07-04 21:56
This fully reproduces the issue and requires an etcd v2.0.* binary be dropped into bin/

https://github.com/philips/hacks/tree/master/etcd-tls-2.0

**Comment by philips** [comment] 2015-07-04 22:29
@danderson Fixed via a documentation entry: https://github.com/coreos/etcd/pull/3097

**Closed by philips** 2015-07-04 22:29 UTC
