### ISSUE TITLE
clientv3: Multiple watchers on a key using same etcd v3 client doesn’t work

### ISSUE THREAD

**Issue by shilpamayanna** [coreos/etcd#7290] opened 2017-02-08 03:12 UTC
Created multiple watchers in separate go routines. All of them use the same etcd v3 client and watch on same key. Watch doesn’t receive  events after sometime. No indication of any errors or watch failures.
Go routines are blocked waiting for the response from watch channel. 
Tried with 10 go routines.

**Comment by heyitsanthony** [comment] 2017-02-08 05:57
What version of etcd? Example code to trigger this?

**Comment by shilpamayanna** [comment] 2017-02-08 16:57
I tried with version 3.0.7 and 3.1.0. Both have same behavior.
It is easily reproducible by restarting etcd server while watching. Some of the go routines stop receiving response.
Here is the example code.

package main

import (
	"fmt"
	"os"
	"strconv"
	"time"

	etcd "github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
)

const (
	testDir     = "/test/"
	dialTimeout = 5 * time.Second
)

func main() {
	// Config options for etcd client
	cfg := etcd.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: dialTimeout,
	}

	client, err := etcd.New(cfg)
	if err != nil {
		fmt.Printf("Etcd client connection failed with error %+v", err)
		os.Exit(1)
	}

	if len(os.Args) < 3 {
		fmt.Println("Insufficient command line arguments")
		fmt.Println("Usage: etcdtest <num-watchers> <duration-in-minutes>")
		os.Exit(1)
	}

	fmt.Println("Start watch testing on etcd")

	count, _ := strconv.Atoi(os.Args[1])
	for idx := 0; idx < count; idx++ {
		WatchEtcd(idx, client)
	}

	timeVal, _ := strconv.Atoi(os.Args[2])
	time.Sleep(time.Duration(timeVal) * time.Minute)
	fmt.Println("Stopping test")
	os.Exit(0)
}

func WatchEtcd(id int, client *etcd.Client) {
	go func() {
		fmt.Println("Start go routine ", id)
		opts := []etcd.OpOption{etcd.WithPrefix()}

		watchChan := client.Watch(context.Background(), testDir, opts...)
		go func() {
			for {
				resp, ok := <-watchChan
				if !ok || resp.Err() != nil {
					if ok {
						fmt.Printf("Watch channel returned err %v", resp.Err())
						return
					}
					fmt.Printf("Watch channel closed")
					return
				}
				fmt.Printf("Watch response received for %d\n", id)
			}
		}()
	}()
}

**Comment by shilpamayanna** [comment] 2017-02-08 16:57
I tried with version 3.0.7 and 3.1.0. Both have same behavior.
It is easily reproducible by restarting etcd server while watching. Some of the go routines stop receiving response.
Here is the example code.

package main

import (
	"fmt"
	"os"
	"strconv"
	"time"

	etcd "github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
)

const (
	testDir     = "/test/"
	dialTimeout = 5 * time.Second
)

func main() {
	// Config options for etcd client
	cfg := etcd.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: dialTimeout,
	}

	client, err := etcd.New(cfg)
	if err != nil {
		fmt.Printf("Etcd client connection failed with error %+v", err)
		os.Exit(1)
	}

	if len(os.Args) < 3 {
		fmt.Println("Insufficient command line arguments")
		fmt.Println("Usage: etcdtest <num-watchers> <duration-in-minutes>")
		os.Exit(1)
	}

	fmt.Println("Start watch testing on etcd")

	count, _ := strconv.Atoi(os.Args[1])
	for idx := 0; idx < count; idx++ {
		WatchEtcd(idx, client)
	}

	timeVal, _ := strconv.Atoi(os.Args[2])
	time.Sleep(time.Duration(timeVal) * time.Minute)
	fmt.Println("Stopping test")
	os.Exit(0)
}

func WatchEtcd(id int, client *etcd.Client) {
	go func() {
		fmt.Println("Start go routine ", id)
		opts := []etcd.OpOption{etcd.WithPrefix()}

		watchChan := client.Watch(context.Background(), testDir, opts...)
		go func() {
			for {
				resp, ok := <-watchChan
				if !ok || resp.Err() != nil {
					if ok {
						fmt.Printf("Watch channel returned err %v", resp.Err())
						return
					}
					fmt.Printf("Watch channel closed")
					return
				}
				fmt.Printf("Watch response received for %d\n", id)
			}
		}()

	}()
}

**Comment by heyitsanthony** [comment] 2017-02-08 17:07
@shilpamayanna how are the writes being issued?

**Comment by shilpamayanna** [comment] 2017-02-08 17:15
@heyitsanthony Writes with etcdctl command

**Comment by heyitsanthony** [comment] 2017-02-08 19:29
> 3.0.7 

There were some watch client bugs fixed since 3.0.7 (in particular, 3.0.11). Try the latest 3.0.x?

Is the watch binary being compiled against the 3.1.0 client code? I can not reproduce this...

**Comment by xiang90** [comment] 2017-02-09 02:36
@shilpamayanna Can you provide a program that I can simply compile and run to reproduce the issue?

something like

```
./etcd-3.1.0&
go run produce.go
wow... no watch events for 10 second!!!
```

**Comment by shilpamayanna** [comment] 2017-02-09 07:29
@heyitsanthony @xiang90, I tried with 3.0.17. Couldn't reproduce the issue.

**Comment by xiang90** [comment] 2017-02-10 07:11
> I tried with 3.0.17. Couldn't reproduce the issue.

Awesome. But you also mentioned that 3.1.0 does not work? 3.1.0 should include all bug fixes in 3.0.17. I still want to figure that part out before we can close this issue. Thank you!

**Comment by xiang90** [comment] 2017-02-14 15:34
@shilpamayanna kindly ping.

**Comment by shilpamayanna** [comment] 2017-02-14 16:18
@xiang90 I couldn't reproduce this bug on 3.1.0 anymore. With earlier experiments, this issue happened once on 3.1.0 where watcher stopped receiving notifications completely after restarting etcd server couple of times.

**Comment by heyitsanthony** [comment] 2017-02-14 19:13
Looks like a 3.0.7 issue and is fixed now. Thanks for reporting! Closing.

**Closed by heyitsanthony** 2017-02-14 19:13 UTC
