### ISSUE TITLE
Upgrading etcd from 2.0.3 to 2.0.5 - members succeed & start, proxies won't start

### ISSUE THREAD

**Issue by wsimmonds** [coreos/etcd#2530] opened 2015-03-18 13:47 UTC
As part of investigating #2529 and attempting to see if the latest release might resolve the issue (it didn't). The proxies are unable to start up. However the error is different in this scenario:

Mar 18 13:38:20 ip-10-0-1-113.ec2.internal systemd[1]: Started etcd container.
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: listening for peers on http://0.0.0.0:2380
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: listening for peers on http://0.0.0.0:7001
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: listening for client requests on http://0.0.0.0:2379
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: listening for client requests on http://0.0.0.0:4001
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 datadir is valid for the 2.0.1 format
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: stopping listening for client requests on http://0.0.0.0:4001
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: stopping listening for client requests on http://0.0.0.0:2379
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: stopping listening for peers on http://0.0.0.0:7001
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: stopping listening for peers on http://0.0.0.0:2380
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal writer_process[3907]: 2015/03/18 13:38:20 etcd: cannot write to member directory: open /opt/etcd/member/.touch: no such file or directory
Mar 18 13:38:20 ip-10-0-1-113.ec2.internal systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE

This only affects proxies (upgrading my cluster members was successful) and similarly to #2529 it can be resolved by deleting the proxy folder.

**Comment by xiang90** [comment] 2015-03-18 14:40
This should be fixed by #2526. Next release will include this fix.

**Comment by wsimmonds** [comment] 2015-03-18 16:29
@xiang90 That's brilliant. Once the build is passing, I'm happy to download and test this and #2529 and confirm they have been resolved.

**Comment by yichengq** [comment] 2015-03-19 20:33
@wsimmonds The build and test are passing. Could you help to confirm the problem is resolved?

**Comment by wsimmonds** [comment] 2015-03-20 13:15
@yichengq Happy to report for both #2529 and #2530, the issues have been resolved and it's working perfectly from my perspective.

Thanks for the great work! Once I learn a bit more Go, hope to be able to contribute.

**Comment by xiang90** [comment] 2015-03-20 14:42
@wsimmonds Thanks! Looking forward to your contribution.

**Closed by xiang90** 2015-03-20 14:42 UTC
