### ISSUE TITLE
raftexample restart without leader

### ISSUE THREAD

**Issue by izouxv** [coreos/etcd#4474] opened 2016-02-10 03:22 UTC
single raft cluster. First start can vote a leader, but restart cannot vote leader. It always follower

**Comment by xiang90** [comment] 2016-02-10 03:26
@izouxv Can you please provide the necessary start command line and logging?

**Comment by izouxv** [comment] 2016-02-10 03:59
First start and second. I use the same command : ./raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380 
First can vote leader,second cannot vote leader

**Comment by izouxv** [comment] 2016-02-10 04:01
I used goraft and it's too long time to maintain , I want to use etcd raft to replace goraft

**Comment by xiang90** [comment] 2016-02-10 04:17
@izouxv Sure. I think @heyitsanthony will have an answer for you shortly.

**Comment by heyitsanthony** [comment] 2016-02-10 05:02
Fix is in #4476

Started a new cluster, put data in it, killed node:
```
rm -rf raftexample-1/
./raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380 &
curl 127.0.0.1:12380/my-key -XPUT -d'abc'
killall raftexample
```

Started node again, confirmed data still present, confirmed cluster accepting writes:
```
./raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380`
curl 127.0.0.1:12380/my-key
curl 127.0.0.1:12380/my-key -XPUT -d'def'
```

**Comment by izouxv** [comment] 2016-02-10 05:26
I test it again. But not success. First I start raftexample ,I can set and get data .but I kill all raftexample and run it again ,set data ,but get data it notice "failed to get"

**Comment by heyitsanthony** [comment] 2016-02-10 05:50
@izouxv are you using my branch? did you run the exact steps I provided? If yes to both, I'll need to see the logs since I can't reproduce your problem with the pending fix.

**Comment by izouxv** [comment] 2016-02-10 05:50
first set & get key1, ok
Second set & get key2, faild

**Comment by izouxv** [comment] 2016-02-10 05:51
I use master branch to test it, what branch need I test?

**Comment by heyitsanthony** [comment] 2016-02-10 05:55
The branch for the PR is https://github.com/heyitsanthony/etcd/tree/fix-raftexample-restart

Also, your copy of master is a day or two out of date. Right now the code on master crashes on restart.

**Comment by izouxv** [comment] 2016-02-10 05:56
i test it follow your command step by step on master branch ,I can post my screen snapshot to you shortly

**Comment by heyitsanthony** [comment] 2016-02-10 05:58
@izouxv master branch won't work; the fix isn't committed yet

**Comment by izouxv** [comment] 2016-02-10 07:47
i use https://github.com/heyitsanthony/etcd/tree/fix-raftexample-restart branch, and test..., crash .

**Comment by izouxv** [comment] 2016-02-10 07:47
zouxu:raftexample zouxu$ ./raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380
raft2016/02/10 15:45:17 INFO: 1 became follower at term 0
raft2016/02/10 15:45:17 INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/02/10 15:45:17 INFO: 1 became follower at term 1
raft2016/02/10 15:45:18 INFO: 1 is starting a new election at term 1
raft2016/02/10 15:45:18 INFO: 1 became candidate at term 2
raft2016/02/10 15:45:18 INFO: 1 received vote from 1 at term 2
raft2016/02/10 15:45:18 INFO: 1 became leader at term 2
raft2016/02/10 15:45:18 INFO: raft.node: 1 elected leader 1 at term 2
killall raftexample
^Czouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ 
zouxu:raftexample zouxu$ ./raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5144]

goroutine 14 [running]:
main.(*raftNode).publishEntries(0xc820092c80, 0xc8200c4240, 0x3, 0x4, 0x0)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/raft.go:107 +0x354
main.(*raftNode).replayWAL(0xc820092c80, 0xd)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/raft.go:157 +0x1dc
main.(*raftNode).startRaft(0xc820092c80)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/raft.go:173 +0x67
created by main.newRaftNode
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/raft.go:82 +0x450

goroutine 1 [chan receive]:
main.(*kvstore).readCommits(0xc8200c2fc0, 0xc820018a20, 0xc820018a80)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/kvstore.go:61 +0x6e
main.newKVStore(0xc820018960, 0xc820018a20, 0xc820018a80, 0xc820063dc8)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/kvstore.go:39 +0xd4
main.serveHttpKVAPI(0x305c, 0xc820018960, 0xc8200189c0, 0xc820018a20, 0xc820018a80)
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/httpapi.go:110 +0x92
main.main()
	/Users/zouxu/.golang/gopath/src/fish.red/zouxu/goall/other/raftexample/main.go:40 +0x28f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 9 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8200ccbc0)
	/Users/zouxu/.golang/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/Users/zouxu/.golang/gopath/src/git

**Closed** 2016-02-10 21:00 UTC
Labels: component/raftexample
