### ISSUE TITLE
etcd3.0.0: etcdctl and curl

### ISSUE THREAD

**Issue by heyujiaan** [coreos/etcd#6164] opened 2016-08-12 10:01 UTC
If I use curl to store a KV, and then through the tool etcdct to get the KV, found that there is no the KV,The opposite is also the result.
1../etcd 启动etcd
2.curl http://127.0.0.1:2379/v2/keys/a -XPUT -d value="bbbbbbbbbbbbb"
3../etcdctl get --endpoints=127.0.0.1:2379  a
you will find  that you have nothing to get,why?

**Comment by heyitsanthony** [comment] 2016-08-12 16:11
> `../etcd 启动etcd`

That's not a valid flag; etcd should refuse to start. What version of etcd are you running? What is the `curl` output?

This is the output using the master branch:
```sh
$ bin/etcd
$ curl http://127.0.0.1:2379/v2/keys/a -XPUT -d value="bbbbbbbbbbbbb"
{"action":"set","node":{"key":"/a","value":"bbbbbbbbbbbbb","modifiedIndex":4,"createdIndex":4}}
$ bin/etcdctl  --endpoints=127.0.0.1:2379 get a
bbbbbbbbbbbbb
```

**Comment by xiang90** [comment] 2016-08-12 19:29
I cannot reproduce this either. So closing. Please report back with more information if this problem still exists. (like what is the output of curl, what is the output of etcdctl?)

**Closed by xiang90** 2016-08-12 19:29 UTC

**Comment by armstrongli** [comment] 2016-11-28 06:59
I got this issue when I migrated the etcd from etcd2 to etcd3. The values put into were stored in etcd2's store.

```shell
$ curl http://127.0.0.1:2379/v2/keys/a -XPUT -d value="bbbbbbbbbbbbb"
$ etcdctl ls
/a
$ export ETCDCTL_API=3
$ etcdctl get a
# nothing shown
```

@heyujiaan Please migrate the data or use etcdctl(v3) do the key/value put.
