### ISSUE TITLE
mvcc: cannot detach lease not found

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#6093] opened 2016-08-03 21:33 UTC
Hi!
Just encountered a very unexpected issue. I'm using latest etcd and had a key which was used as a lock, i.e. lease attached to it. For some reason lease was there even if I stopped all clients for a while. I decided to remove the key using `etcdctl del`. After running this command whole cluster (5 nodes) went down with error:
```
mvcc: cannot detach lease not found
```
I had to patch `etcd` to ignore this error, after that cluster went back to live.

Not quite sure, how I managed to get there (have stale lease), but I think you may be interested. Maybe there was a bug a while ago which is now fixed, but lurked in my installation and revealed itself only now.

**Comment by xiang90** [comment] 2016-08-03 21:38
is your deployment upgraded from a pre-release version of etcd3?

**Comment by nekto0n** [comment] 2016-08-03 21:45
Not sure, but that's quite possible, yes.

**Comment by xiang90** [comment] 2016-08-03 21:50
If you have time, probably you can help to reproduce? Set up same lock logic and let lease expire. At the meantime, I will take a look at the lease logic sometime this week.

**Comment by nekto0n** [comment] 2016-08-03 21:59
Thanks for such a prompt response!
I am quite sure I have another etcd ensemble with same issue right now.

**Comment by xiang90** [comment] 2016-08-04 03:47
@nekto0n It would be really helpful if you can somehow reproduce it from a fresh cluster.

**Comment by xiang90** [comment] 2016-08-04 04:02
@nekto0n I think I found the bug. I will try to get a fix soon. It would be great if you can provide me the full etcd log? Is there a snapshot sending/receiving event happened?

**Comment by nekto0n** [comment] 2016-08-04 06:39
@xiang90 I tried to, but I failed to reproduce the bug on fresh/testing installations.

> It would be great if you can provide me the full etcd log? Is there a snapshot sending/receiving event happened?

You'd like to look at logs during `etcdctl del` call? Seems like I miss them =(

**Comment by nekto0n** [comment] 2016-08-04 06:41
But as I said, I'm pretty sure I have at least another one cluster, which has similar state and I can issue `etcdctl del` and grab all info you need :)

**Comment by xiang90** [comment] 2016-08-04 14:46
@nekto0n In the pre-release, there was a bug that if one lease attached with multiple keys, only the first key will be removed. In your case, have you attached multiple keys to one lease?

**Comment by nekto0n** [comment] 2016-08-04 15:21
@xiang90 No, I don't think so.

**Comment by xiang90** [comment] 2016-08-05 04:10
@nekto0n 

We made a couple of fixes here: https://github.com/coreos/etcd/pull/6098. 

Most of them are on recovery path. Previously, etcd might mess up lease items during crash recovery.

If you can throw some workload onto the patched etcd, it would be great...

**Comment by nekto0n** [comment] 2016-08-05 09:36
Sure thing! I'll give it a spin during weekend.

**Comment by xiang90** [comment] 2016-08-06 23:22
> No, I don't think so.

Did you implement your own lock? Or you were using our lock implementation? If you were using ours, we actually attach all lock keys onto one lease.

**Comment by nekto0n** [comment] 2016-08-08 04:05
I used your `Session` implementation. Couldn't use `Lock` because I found no way to stop worker, when lease expires. Either way, at the moment I use only one lock per process.

**Comment by xiang90** [comment] 2016-08-08 04:11
Can you please create an issue for the lock thing? We can improve it. I cannot really figure out where was the bug... We changed quite a lot stuff since 2.3.x to 3.0. I think we can close this for now. Let us know if it happens again. It would be great if you can reproduce.

**Closed by xiang90** 2016-08-08 04:11 UTC

**Comment by nekto0n** [comment] 2016-08-08 04:24
Yeah, sure. Just thought it tried to look like `sync.Mutex`, which cannot be unlocked behind your back :)

**Comment by nekto0n** [comment] 2016-08-08 04:25
BTW, I built and installed etcd from master and still something is holding lock file. Can I now remove it with `etcdctl` without shutting down whole ensemble?

**Comment by heyitsanthony** [comment] 2016-08-08 04:46
@nekto0n what do you mean by lock file?

If `etcd` is refusing to start, then an etcd process is still running on the target member directory and needs to be stopped before running the new version of etcd. It can be done one-by-one so the cluster stays up.

If the mutex is still held, you could try revoking the lease on the mutex key with the lowest create revision which will abort the holder's session.

**Comment by nekto0n** [comment] 2016-08-08 04:48
Sorry for being vague. By lock file I meant "file with attached lease". I confirm, that issue is fixed, after removing file with stale lease I got an error `E | mvcc: cannot detach lease not found`, not panic.

**Comment by xiang90** [comment] 2016-08-08 05:07
@nekto0n If you start with a fresh cluster, even that error should not ever appear. Or there is still a bug some where.

**Comment by nekto0n** [comment] 2016-08-08 05:25
@xiang90 Right, I failed to reproduce this with a fresh cluster. Thanks a lot for your help!
