### ISSUE TITLE
panic during etcdctl backup

### ISSUE THREAD

**Issue by gmarek** [coreos/etcd#7150] opened 2017-01-13 10:46 UTC
We've run into a problem while doing etcd backup while testing head kubernetes with etcd 3.0.14 image.

Stacktrace attached:
```
2017-01-13 10:13:41.306689 W | wal: ignored file 0.tmp in wal
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/coreos/etcd/wal.(*decoder).decode(0xc820153470, 0xc8200da068, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc820166680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/wal.go:238 +0x442
github.com/coreos/etcd/etcdctl/command.handleBackup(0xc82010e9a0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/backup_command.go:74 +0x9ce
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0xc27418, 0x6, 0x0, 0x0, 0xcc5ae0, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xdbc
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc820168000, 0xc82000a140, 0x4, 0x4, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:125 +0xa9f
main.main()
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/main.go:67 +0x1dfa

goroutine 6 [runnable]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0x1023a20)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:878
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init.1
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 13 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

cc @mml @hongchaodeng @xiang90 @wojtek-t @smarterclayton @lavalamp @roberthbailey

**Comment by xiang90** [comment] 2017-01-13 16:02
@gmarek What is the version of etcdctl are you using?

**Comment by gmarek** [comment] 2017-01-13 16:14
3.0.14 AFAICT

**Comment by xiang90** [comment] 2017-01-13 16:29
Example data dir?

I guess this is because the data dir still contains some 2.3.7 wal data. etcdctl tries to open it up with a later version of wal pkg, and it panics. But we probably need more information to confirm.

/cc @heyitsanthony

**Comment by heyitsanthony** [comment] 2017-01-13 16:56
@xiang90 3.0 wal can read 2.3 wal, otherwise upgrade wouldn't work. This is etcdctl from 2.3.x:

2.3 decoder.go:55,
```go
data := make([]byte, l)
```

3.0 decoder.go:55,
```go
defer d.mu.Unlock()
```

**Comment by xiang90** [comment] 2017-01-13 17:11
@heyitsanthony It should. But I suspect that there might be a bug somewhere. But I double checked the code as you did, and I agree with you now.

@gmarek Can you double check you are using etcdctl 3.0.14? From the panic logging, you use etcdctl 2.3.x.

**Comment by gmarek** [comment] 2017-01-13 17:34
Yup:
gcr.io/google_containers/etcd                      3.0.14-alpha.1
          f7f5b1969fb5        3 weeks ago         175 MB

**Comment by lavalamp** [comment] 2017-01-13 18:21
@wojtek-t or @mml can confirm, but I believe we build multiple versions of
etcd into that container and run the one corresponding to the data on the
disk. So it could well be 2.3.7 etcd?

**Comment by wojtek-t** [comment] 2017-01-16 09:30
I'm pretty sure the issue is purely on our side.
I'm 99% sure that the reason of it is that:
- we are using 3.0.14 etcd server
- but for backups in GKE we are still using 2.*.* etcdctl. The mechanism for fixing it was already in GKE, but we reverted it due to other problems. The internal cl to fix it is already in-flight. So let's close it for now - will reopen if we know that this is a real issue.

**Closed** 2017-01-16 16:33 UTC
