### ISSUE TITLE
etcd2 fail to start with CoreOS 835.10

### ISSUE THREAD

**Issue by bchanan03** [coreos/etcd#4251] opened 2016-01-21 12:34 UTC
I have just created a new CoreOS 835.10 cluster with 5 nodes using Vagrant + VirtualBox
The cluster fail to start causing flannel and docker to fail too.

- Issue found after locksmith upgraded the nodes after reboot moving from CoreOS 766.4 to CoreOS 835.9
- I created a new virtualbox cluster using Vagrant and CoreOS 835.10 same issue appeared again.
- Issue did not appear when running CoreOS 766.4

Attached is a log created by journal showing the problem.
[log.txt](https://github.com/coreos/etcd/files/99114/log.txt)

**Comment by xiang90** [comment] 2016-01-25 22:11
@bchanan03 The log is unreadable to me. Can you try to make this an independent etcd issue? 

What are the steps to reproduce this issue with etcd itself? (for example, CoreOS 766.4 ships with etcd 2.1.2, can you reproduce with etcd 2.1.2 without doing CoreOS updates since that also involves other changing variables)

Also there are missing logs. Can you please follow the doc (https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md) here to make the bug report a little bit better?

**Comment by xiang90** [comment] 2016-02-06 05:07
Closing due to low activity. Please reopen if this is still an issue.

**Closed by xiang90** 2016-02-06 05:07 UTC
Labels: reviewed/needs more information
