### ISSUE TITLE
JSON gateway is not usable on grpc proxy node

### ISSUE THREAD

**Issue by bra-fsn** [coreos/etcd#9104] opened 2018-01-05 14:54 UTC
I start two nodes:
$ ./etcd --name test --auto-compaction-retention 1 --initial-cluster-token test --initial-cluster-state new
$ etcd grpc-proxy start --endpoints=localhost:2379 --listen-addr=127.0.0.1:23791 --advertise-client-url=127.0.0.1:23791

Setting a key with the REST API works on the etcd master node:
$ curl http://localhost:2379/v3beta/kv/range -X POST -d '{"key": "YQ=="}'
{"header":{"cluster_id":"284846713903947703","member_id":"8658500760918457051","revision":"1","raft_term":"3"}}

but it doesn't on the grpc-proxy node:
curl http://localhost:23791/v3beta/kv/range -X POST -d '{"key": "YQ=="}'
404 page not found

According to the docs:
"This gateway serves a RESTful proxy that translates HTTP/JSON requests into gRPC messages."
So it seems pretty logical (and may be easy?) to support REST queries on a grpc proxy node, it has all the capabilities to do so.

**Comment by gyuho** [comment] 2018-01-05 16:22
Currently, it's not supported. Do you want to contribute for this feature?

**Comment by xiang90** [comment] 2018-01-05 16:23
as it suggests gRPC proxy is for proxying gRPC requests only, not http based json request.

**Comment by bra-fsn** [comment] 2018-01-06 11:07
@xiang90 OK, that's clear. But do I assume it wrong if the JSON proxy uses gRPC underneath, it would be trivial to run it on a gRPC proxy? Basically you would only have to use the local node, it already does everything needed.
Running etcd on a hundred nodes is not benefical. While the current setup of having 3-5-7 nodes and let the other machines use gRPC proxy is still not perfect, it's much better than a simple TCP load balancer, which is unaware of the underlying protocol.
So what's recommended for anyone who wishes to run a large number of "client" nodes?

**Comment by xiang90** [comment] 2018-01-06 16:45
> So what's recommended for anyone who wishes to run a large number of "client" nodes?

Why do you want to do this? 

This is probably what you want to use: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/gateway.md#etcd-gateway.

**Comment by bra-fsn** [comment] 2018-01-08 09:50
@xiang90: I have nodes, which may leave or come back on demand. This elasticity doesn't seem to be a good fit for the cluster.
Yes, gateway may be good, but gRPC proxy knows more, it would be good to be able to use its capabilities.

**Comment by xiang90** [comment] 2018-01-09 02:15
> I have nodes, which may leave or come back on demand. This elasticity doesn't seem to be a good fit for the cluster.

then you do not put etcd on them. there is no reason to run etcd on every nodes.

for your use case, you should either use etcd gateway or just do not run etcd on all your nodes. i am closing this since the grpc proxy wont expose http json for the reason i mentioned above.

**Closed by xiang90** 2018-01-09 02:15 UTC

**Comment by neiljerram** [comment] 2018-01-14 18:22
@bra-fsn @xiang90 @gyuho Do you know if a similar scenario with `etcd --proxy on ...` instead of `etcd grpc-proxy` is also not supported?  In other words, if `etcd --proxy on` supports the JSON gateway and proxies JSON gateway requests to the etcd cluster?

(Empirically, I see that a http://<proxy>:2379/v3beta/kv/range request does not get any response.  So I think the answer is that this is not supported, but would appreciate having that officially confirmed or denied.)
