### ISSUE TITLE
New member not working after joined to existing cluster

### ISSUE THREAD

**Issue by mindaugasrukas** [coreos/etcd#2838] opened 2015-05-15 14:26 UTC
etcd 2.1.0-alpha.0

I've tried to join a clean new member to existing cluster, but it is not working correctly. On that instance etcd shows that cluster is unhealthy, until I restarted etcd service.

On other members etcd shows that cluster is healthy.

Log output and executed commands: https://gist.github.com/mindaugasrukas/3089a6dc17583ddf77ab

**Comment by xiang90** [comment] 2015-05-15 14:54
@mindaugasrukas Can you provide more information? For example, first I did A. Then I did B. Here is what I expected. Here is the unexpected output. 

I cannot quite follow what happened to your cluster. And it is too hard for me to look every line of the log you shared here.

**Comment by mariusgrigaitis** [comment] 2015-05-15 15:22
@xiang90 
1. Start a cluster of 4 nodes
2. Join the node to cluster (run etcd, specifying initial-cluster nodes)

Expected cluster health to be fully healthy
Expected clientURLS to be filled correctly (since all nodes are equal, just different IP).

Strange thing happens, that just after join clientURLs shows as = empty. Also sometimes from the node that just joined etcdctl cluster-health returns unhealthy, but other nodes show the node as healthy and cluster healthy.

Somehow restarting etcd helps.

**Comment by xiang90** [comment] 2015-05-18 20:26
> Strange thing happens, that just after join clientURLs shows as = empty.

This is expected. When you run etcdctl, it should show as the new member unstarted. The etcd member will publish the client url when it starts. So it updates at starting time, not joining time.

> joined etcdctl cluster-health returns unhealthy

It needs some time to catch up with the cluster. If you have a small data set, it takes several seconds.

**Comment by yichengq** [comment] 2015-05-26 21:47
@mindaugasrukas @mariusgrigaitis Any updates?

**Comment by mindaugasrukas** [comment] 2015-05-27 11:36
> This is expected. When you run etcdctl, it should show as the new member unstarted. The etcd member will publish the client url when it starts. So it updates at starting time, not joining time.

It is not showing as unstarted, but just empty ClientURLs values:

```
etcdctl member list
3e40a6f7dbc20a75: name=ip-10-128-1-33 peerURLs=http://10.128.1.33:2380 clientURLs=http://10.128.1.33:2379,http://10.128.1.33:4001
69e5eeba42a3e4cb: name=ip-10-128-1-156 peerURLs=http://10.128.1.156:2380 clientURLs=
750600a2b52a8ab4: name=soad-cluster-node1 peerURLs=http://172.21.3.1:2380 clientURLs=http://172.21.3.1:2379,http://172.21.3.1:4001
7f6b262dd7767f30: name=ip-10-128-1-153 peerURLs=http://10.128.1.153:2380 clientURLs=
89f14c2ba6df79a3: name=ip-10-128-1-203 peerURLs=http://10.128.1.203:2380 clientURLs=http://10.128.1.203:2379,http://10.128.1.203:4001
```

And it is not changed after some time of waiting. Just until etcd restart.

> It needs some time to catch up with the cluster. If you have a small data set, it takes several seconds.

We've waited tens of  minutes but nothing has changed.

Maybe worth to mention, that we are trying to use etcd not on CoreOS but on Debian machine.

**Comment by xiang90** [comment] 2015-05-27 14:55
@mindaugasrukas What version of etcd are you running? Can you please provide more log information?

The log output you gave seems OK. I did not find anything bad.

> We've waited tens of minutes but nothing has changed.

Did you start the joined node? The cluster will become healthy after you starting the two new nodes.

**Comment by mindaugasrukas** [comment] 2015-06-01 13:49
We have tested with etcd v2.0.10 and 2.1.0-alpha.0.  
I'll try with v2.0.11 and provide full log.

**Comment by xiang90** [comment] 2015-07-03 16:21
@mindaugasrukas Any update? I cannot reproduce this issue myself. :(

**Comment by xiang90** [comment] 2015-07-09 19:22
@mindaugasrukas I am closing this due to low activity. Feel free to reopen if you still have the issue.

**Closed by xiang90** 2015-07-09 19:22 UTC
