### ISSUE TITLE
leader switches easily when sending v3 snapshot on GCE using HDD

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3777] opened 2015-10-29 21:10 UTC
Background:
1. use standard persistent disk in GCE as both data-dir and wal-dir
2. 3-member cluster
3. leader is sending ~1G v3 snapshot to one follower

The leader calls disk reads heavily to load snapshot and send it out, and calls disk writes to write log entry into WAL at the same time. In the given background, it may take several seconds for one disk write request on WAL to finish, which affects heartbeat mechanism between leader and other followers, so the cluster may switch leader easily and become unstable. The worst case is that leader is always changed before one snapshot is sent out, and the cluster becomes totally unstable.

from #2370

**Comment by xiang90** [comment] 2015-11-02 17:55
I want to close this since the root cause is  https://github.com/coreos/etcd/issues/3788

**Closed by xiang90** 2015-11-02 17:55 UTC
