### ISSUE TITLE
txn error: there is no address available

### ISSUE THREAD

**Issue by soyking** [coreos/etcd#6795] opened 2016-11-03 13:51 UTC
I ran a local cluster by the `goreman` in the project. 

Then I ran `ETCDCTL_API=3 etcdctl auth enable` to enable auth.

But when I ran this program:

```go
package main

import (
	"github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
	"log"
)

func main() {
	clt, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:2379", "127.0.0.1:22379", "127.0.0.1:32379"},
		Username:  "root",
		Password:  "root",
	})
	if err != nil {
		log.Fatal(err)
	}

	key := "abc"

	txn := clt.Txn(context.TODO())
	txn.If(
		clientv3.Compare(
			clientv3.Value(key),
			"=",
			"some_special",
		),
	).Then(
		clientv3.OpDelete(key),
	)

	_, err = txn.Commit()
	if err != nil {
		log.Fatal(err)
	}
}
```

I got this error: rpc error: code = 2 desc = there is no address available. And it worked when `clt.Delete(context.TODO(),key)`. So it is strange for me, is there any explanation or a correct way to use it ?

etcd version: 3.1.0-rc.0+git
etcd log:

```
21:43:20 etcd1 | 2016-11-03 21:43:20.550847 I | auth: authorized root, token is UKmrKCtpIkWSPqSK.26939
21:43:20 etcd3 | 2016-11-03 21:43:20.551234 I | auth: authorized root, token is UKmrKCtpIkWSPqSK.26939
21:43:20 etcd2 | 2016-11-03 21:43:20.551234 I | auth: authorized root, token is UKmrKCtpIkWSPqSK.26939
```

**Comment by xiang90** [comment] 2016-11-03 17:39
@soyking It works for me. I cannot reproduce this on master at least.

/cc @gyuho @mitake Give this a try?

**Comment by gyuho** [comment] 2016-11-03 17:45
Works fine with no error?

```
2016-11-03 10:43:35.376952 N | auth: Role root is created
2016-11-03 10:43:59.187722 N | auth: granted role root to user root
2016-11-03 10:44:02.884906 N | auth: Authentication enabled
2016-11-03 10:44:08.065697 I | auth: authorized root, token is gGzYUGEjMhWYGYek.350
2016-11-03 10:44:20.305991 I | auth: authorized root, token is kyVzZwbYXwvIaFuZ.376
2016-11-03 10:45:11.102405 I | auth: authorized root, token is ahNIGaTgYGSMOVpB.481
2016-11-03 10:45:14.695114 I | auth: authorized root, token is ILIlZjYKIVpyJKtw.489
2016-11-03 10:45:17.863060 I | auth: authorized root, token is iKrNgNcPuDWSQFXL.497
2016-11-03 10:45:21.653076 I | auth: authorized root, token is pLhiWJZqAhONomCF.506
```

**Comment by xiang90** [comment] 2016-11-03 17:47
@soyking I am closing this out. We cannot reproduce this with your script and setup. Please try with current master, reopen if the problem still exist and you find a reliable way to reproduce it.

**Closed by xiang90** 2016-11-03 17:47 UTC

**Comment by mitake** [comment] 2016-11-04 02:31
@soyking I also tested and couldn't find the reported problem. Did you tried on the latest master?

**Comment by soyking** [comment] 2016-11-04 03:27
@xiang90 @gyuho @mitake 

I pulled the newest code in master branch and build it. And it worked. Thank you.
