### ISSUE TITLE
metrics: rename v3 metrics

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3833] opened 2015-11-07 23:00 UTC
today the v2 metrics exposed from `/metrics` are called "store" and the v3 metrics are called "storage". For example etcd_store_writes_total and etcd_storage_put_total.

Lets remove the storage metrics and call them `etcd_store_v3_...` and add `etcd_store_v2_...` metrics  that are just duplicates of the others to maintain compatibility.

Thoughts?

**Comment by mischief** [comment] 2015-11-08 04:13
why include a version? why not simply merge storage into store?

**Comment by philips** [comment] 2015-11-08 06:42
@mischief The two stores are separate: keys in v2 can't be accessed via v3 and vice-versa and the two stores have different verbs like multi-key transactions and range gets.

**Comment by ajityagaty** [comment] 2016-03-07 04:18
Or should the v2 metrics' names be left as they are? The reason being that if we duplicate then we would also need to keep the newer counters up to date. Although the code changes to update the newer counters can be contained within store/metrics.go file.

Also, just renaming "storage" to "store_v3" will be in line with the way "clientv3" and "etcdctlv3" are named.

I am attempting to make the changes. Please let me know which approach to take.

**Comment by philips** [comment] 2016-03-08 02:26
I think storev3 makes sense but will leave that up to Xiang

**Comment by xiang90** [comment] 2016-03-08 02:39
> "clientv3" and "etcdctlv3" are named.

We will probably rename them to etcdctl/client when we release etcd3. It might confuse people since I could image people will think etcdctl/client is the most updated one while the one with versioned suffix is the out-of-date one or experimental one.

So same for the metrics. We probably want to keep everything versioned if we want to version the newest one. Or we should keep the old one versioned and leave the current one un-versioned.

/cc @heyitsanthony @gyuho Opinions?

**Comment by gyuho** [comment] 2016-03-08 02:58
I agree with @xiang90 keeping current ones un-versioned. I think metrics should be changed
at v3 release, because all metrics are experimental anyway, according to this doc https://github.com/coreos/etcd/blob/master/Documentation/metrics.md#metrics.

**Comment by xiang90** [comment] 2016-03-08 03:00
@gyuho I am not saying we have to keep the newest one unversioned. But if we version it, we need to ensure we also version old ones.

**Comment by gyuho** [comment] 2016-03-08 03:03
Ah makes sense. That sounds good. I don't have strong opinions. Keeping v3 ones un-versioned and v2 one versioned sounds good.

**Comment by ajityagaty** [comment] 2016-03-08 03:18
Thanks for the inputs !
I shall version the v2 ones and keep the v3 ones un-versioned.

**Comment by philips** [comment] 2016-03-14 15:04
I think we should version both. I don't understand why we wouldn't. It lets people clearly map their usage of one API vs the other. Who knows if we will add a v4 API at some point in the future.

**Comment by xiang90** [comment] 2016-04-22 19:16
@philips 

> Lets remove the storage metrics and call them etcd_store_v3_... and add etcd_store_v2_... metrics that are just duplicates of the others to maintain compatibility.

Talked with people that are familiar with prometheus (or metrics in general). Their suggestion is to keep the metrics name as same as package name, since it is the metrics for that specific package. If we need to differentiate version, we could create higher level metrics to capture it. https://github.com/coreos/etcd/pull/4713#issuecomment-209997165

So I think we should keep the storage metrics name as it is.

I think the root cause of this issue is that the two pkgs names (store vs storage) are too similar and confusing from external point of view. If we really want to solve it, we have to give a better name to storage. And I do not have one really... /cc @gyuho @heyitsanthony

**Comment by gyuho** [comment] 2016-04-22 19:24
Yeah agree that having similar name `store` and `storage` is confusing, but can't think of a better name. We can't change `store` to `storagev2` though, right?

**Comment by xiang90** [comment] 2016-04-26 17:27
closed by https://github.com/coreos/etcd/pull/5190

**Closed by xiang90** 2016-04-26 17:27 UTC
Labels: component/etcdserver/store, component/storage, low hanging fruit, priority/P1
