### ISSUE TITLE
[question] invoke service by balance

### ISSUE THREAD

**Issue by tfzxyinhao** [coreos/etcd#7821] opened 2017-04-26 11:30 UTC
**env**

```
etcd Version: 3.2.0+git
Git SHA: 35dff4cb
Go Version: go1.8.1
Go OS/Arch: linux/amd64
```

I am beginner for etcd
my purpose is the follow
1.service register itself after service start
2.client find service and invoke service

## the follow code show test how to find service and invoke it

```
func ClientTestService() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{endpoint},
		DialTimeout: time.Second * 5,
	})

	if err != nil {
		log.Println("connect etcd err:", err.Error())
		return
	}

	defer cli.Close()
	r := &naming.GRPCResolver{Client: cli}
	b := grpc.RoundRobin(r)

	conn, err := grpc.Dial(service_name, grpc.WithBalancer(b), grpc.WithInsecure())
	if err != nil {
		log.Println("dial err:", err.Error())
		return
	}

	defer conn.Close()
	c := calc.NewCalcClient(conn)
	req := calc.CalcRequest{IResult: 1, SResult: "req"}
	resp, err := c.CalcResult(context.Background(), &req)
	if err != nil {
		log.Println("calc err:", err)
		return
	}
	log.Println(resp.IResult, resp.SResult)
}
```
console output "calc err: rpc error: code = Unavailable desc = there is no address available"  after execute `resp, err := c.CalcResult(context.Background(), &req)`
it means that resolver can't find the address of service from the service name
i guess there have two possible
1. call service need start etcd "proxy service"  or "gateway" first
2. need to get service address from service name by manual

## the follow code show register service 
```
func RegisterService(w *sync.WaitGroup) {
	w.Add(1)
	defer func() {
		w.Done()
	}()

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{endpoint},
		DialTimeout: time.Second * 5,
	})

	if err != nil {
		log.Println("etcd err:", err)
		return
	}

	cli.Delete(cli.Ctx(), service_name)
	r := &naming.GRPCResolver{Client: cli}
	for _, addr := range GetLocalAddrs() {
		service_node := addr + ":" + strconv.Itoa(port)
		err = r.Update(cli.Ctx(), service_name, gn.Update{Op: gn.Add, Addr: service_node})
		log.Println("register node :", service_name, service_node, err)
	}
}
```
code parts from this [link](https://coreos.com/etcd/docs/latest/dev-guide/grpc_naming.html)

My understanding is that function "ClientTestService" connect etcd server and resolve the service name to service address and invoke service by balance
but when i debug this code and then find it just invoke etcd by balance,
is there function in etcd for my need ?

**Comment by tfzxyinhao** [comment] 2017-04-26 16:08
my etcd server just only one node

**Comment by fanminshi** [comment] 2017-04-26 17:25
taking a look.

**Comment by fanminshi** [comment] 2017-04-26 18:40
```go
conn, err := grpc.Dial(service_name, grpc.WithBalancer(b), grpc.WithInsecure())
	if err != nil {
		log.Println("dial err:", err.Error())
		return
	}
```
If this doesn't return an error, it means that the grpc is able to establish an connection with one of the register service's endpoint. 

```go
c := calc.NewCalcClient(conn)
	req := calc.CalcRequest{IResult: 1, SResult: "req"}
	resp, err := c.CalcResult(context.Background(), &req)
	if err != nil {
		log.Println("calc err:", err)
		return
	}
```
I am unsure why the above code return an error.

Are there any grpc related errors/warnings from the program output? e.g `grpc: addrConn.resetTransport failed to create client transport..`

`1. call service need start etcd "proxy service" or "gateway" first`
no need to start gateway for GRPCResolver to work . if you meant "proxy service" as grpc-proxy, you don't need that for GRPCResolver to work. Just start an etcd node and  call `RegisterService()` first should be good.

`2. need to get service address from service name by manual`
No need to get service address manually. That defeats the purpose of using `naming.GRPCResolver` to get service addresses for you.

**Comment by tfzxyinhao** [comment] 2017-04-27 02:30
![image](https://cloud.githubusercontent.com/assets/444814/25465282/d95a57a0-2b33-11e7-8866-aa3ce17c1c23.png)
thanks for your answer, the error comes from the red arrow mark on the map
I need to read more code of etcd to solve it

**Comment by fanminshi** [comment] 2017-04-27 17:01
I don't think the error is returned by the line [`return grpc.Address{Addr: ""}, nil, ErrNoAddrAvilable`](https://github.com/coreos/etcd/blob/master/clientv3/balancer.go#L272)  because the `Get()` call is blocking in this case and [`if !opts.BlockingWait`](https://github.com/coreos/etcd/blob/master/clientv3/balancer.go#L263 ) evaluates to false.

The body of the `If` won't execute.
```go
if !opts.BlockingWait {
               // doesn't execute
		b.mu.RLock()
		closed = b.closed
		addr = b.pinAddr
		b.mu.RUnlock()
		if closed {
			return grpc.Address{Addr: ""}, nil, grpc.ErrClientConnClosing
		}
		if addr == "" {
			return grpc.Address{Addr: ""}, nil, ErrNoAddrAvilable
		}
		return grpc.Address{Addr: addr}, func() {}, nil
	}
```

I think the error is returned by round robin balancer at https://github.com/grpc/grpc-go/blob/master/balancer.go#L319.

From the source code the error is returned only if `!opts.BlockingWait` is true.
```go
if !opts.BlockingWait {
		if len(rr.addrs) == 0 {
			rr.mu.Unlock()
			err = Errorf(codes.Unavailable, "there is no address available")
			return
		}
		// Returns the next addr on rr.addrs for failfast RPCs.
		addr = rr.addrs[rr.next].addr
		rr.next++
		rr.mu.Unlock()
		return
	}
```
https://github.com/grpc/grpc-go/blob/master/balancer.go#L316-L327

`!opts.BlockingWait` is true only if `!c.failFast` is false which means `c.failFast` must be true.
```go
gopts := BalancerGetOptions{
		BlockingWait: !c.failFast,
}
t, put, err = cc.getTransport(ctx, gopts) // calls balancer.Get()
```
https://github.com/grpc/grpc-go/blob/master/call.go#L229

To update `c.failFast`, grpc takes an option `grpc.FailFast(bool)`. Do you have `grpc.FailFast(true)` anywhere in the implementation of `resp, err := c.CalcResult(context.Background(), &req)`?

**Comment by tfzxyinhao** [comment] 2017-05-02 14:14
@fanminshi 
I have never call "grpc.FailFast(true)"

**Comment by heyitsanthony** [comment] 2017-05-02 21:31
@tfzxyinhao I tried to reproduce your problem here:
https://github.com/heyitsanthony/scraps/blob/master/calc/main_test.go

I started an etcd server on localhost:2379 and ran the test:
```sh
$ GOPATH=~/etcd-gopath/ go test -v
=== RUN   TestClientTestService
2017/05/02 14:29:26 register node : the-service localhost:9999 <nil>
2017/05/02 14:29:26 z:2 
--- PASS: TestClientTestService (0.01s)
PASS
ok      _/home/anthony/go/src/github.com/heyitsanthony/scraps/calc      0.019s
```

So it looks OK. What's the test missing that's causing the failure?

**Comment by fanminshi** [comment] 2017-05-02 21:35
@tfzxyinhao  can you share the internal code for `calc.NewCalcClient(conn)`?

**Comment by tfzxyinhao** [comment] 2017-05-03 03:45
@fanminshi 
thanks very much for your help
my test code [https://github.com/tfzxyinhao/rpc](https://github.com/tfzxyinhao/rpc)

**Comment by tfzxyinhao** [comment] 2017-05-03 10:57
![image](https://cloud.githubusercontent.com/assets/444814/25657820/4b65d5b0-3032-11e7-8628-46030dfe6b5b.png)

**Comment by tfzxyinhao** [comment] 2017-05-05 16:01
@fanminshi 
new-found that, the error was return by `google.golang.org/grpc.invoke at call.go:230`

![image](https://cloud.githubusercontent.com/assets/444814/25753661/fdbf70dc-31ee-11e7-84da-9e66bdf02aed.png)
![image](https://cloud.githubusercontent.com/assets/444814/25753689/18db0778-31ef-11e7-9adb-6d85c67da845.png)

**Comment by fanminshi** [comment] 2017-05-05 22:56
@tfzxyinhao what's the error msg?

**Comment by tfzxyinhao** [comment] 2017-05-06 02:05
"rpc error: code = Unavailable desc = there is no address available"

**Comment by tfzxyinhao** [comment] 2017-05-13 09:52
@heyitsanthony 
your code has the same problem in my machine
```
etcd Version: 3.2.0-rc.0
Git SHA: 7e6d876
Go Version: go1.8.1
Go OS/Arch: windows/amd64
```

**Comment by heyitsanthony** [comment] 2017-05-14 01:54
@tfzxyinhao the test uses localhost for the service address, not 192.168.0.45. That isn't the same code.

 I tried it using a windows 7 vm with etcd's vendored dependencies copied into the gopath:
```
anthony@win7-vm /cygdrive/c/users/anthony/go/src/github.com/coreos/etcd/calc
$ go test -v
=== RUN   TestClientTestService
2017/05/13 18:39:50 register node : the-service localhost:9999 
2017/05/13 18:39:52 z:2
--- PASS: TestClientTestService (3.25s)
PASS
ok      github.com/coreos/etcd/calc     3.300s
```

**Comment by tfzxyinhao** [comment] 2017-05-14 15:04
@heyitsanthony 
change my etcd server config from 192.168.0.45 to localhost get the same error
can you show your etcd config?

**Comment by heyitsanthony** [comment] 2017-05-15 16:52
@tfzxyinhao it's the default configuration:
```sh
anthony@win7-vm /cygdrive/c/users/anthony/go/src/github.com/coreos/etcd/bin
$  ./etcd
```

Are there errors in the etcd server logs?

**Comment by tfzxyinhao** [comment] 2017-05-16 10:08
@heyitsanthony 
the result of running your code on my machine

![etcd server](https://cloud.githubusercontent.com/assets/444814/26100985/268d333e-3a62-11e7-9037-d5c36745e8f4.png)

![image](https://cloud.githubusercontent.com/assets/444814/26101007/409affcc-3a62-11e7-8680-cd56291ffef4.png)

**Comment by heyitsanthony** [comment] 2017-05-16 16:44
OK, the etcd server looks fine. How are the go libraries being vendored for building the test?

**Comment by tfzxyinhao** [comment] 2017-05-17 02:15
@heyitsanthony 

### thanks for so enthusiastic helping me to find the answer!

**library vendor**
![image](https://cloud.githubusercontent.com/assets/444814/26135624/50ceb9d8-3ae9-11e7-9d2e-8d87fdf265da.png)

**Comment by tfzxyinhao** [comment] 2017-05-17 07:04
```
package: prize
import:
- package: github.com/dgrijalva/jwt-go
  version: ~3.0.0
- package: github.com/valyala/fasthttp
  version: 9ffce8c687bb1f181032a667206d248058cd445a
- package: gopkg.in/mgo.v2
  subpackages:
  - bson
```

**Comment by heyitsanthony** [comment] 2017-05-17 16:52
My only guess at this point is it could be from vendoring v1.3.0 grpc instead of v1.2.1 like etcd...

**Comment by xiang90** [comment] 2017-07-27 00:03
none of use can reproduce this. and it does not seem like an etcd issue. so closing.

**Closed by xiang90** 2017-07-27 00:03 UTC
Labels: area/windows

**Comment by koko990** [comment] 2017-10-16 11:35
need a block in  grpc.Dial() https://github.com/coreos/etcd/issues/8701

**Comment by tfzxyinhao** [comment] 2017-10-16 16:06
@koko990 your solution can solve it
