### ISSUE TITLE
repetitive execution of the test file

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6329] opened 2016-09-01 13:00 UTC
Question:
After installing the source code of etcd-3.0.1, I want to excute the test file, which can generate the gopath folder and bin folder, and then the problem is coming. The first time I excuted the test file, everything was ok, and I could get the correct result which proved that the environment of my machine was available. The second time when I excuted the test file, I just got the wrong result. It said that:
`2016-09-01 20:29:21.052054 E | etcdserver: publish error: etcdserver: request timed out`
`2016-09-01 20:29:21.052280 E | etcdserver: publish error: etcdserver: request timed out`
`2016-09-01 20:29:21.052344 I | etcdserver: aborting publish because server is stopped`
`2016-09-01 20:29:21.052583 I | etcdserver: setting up the initial cluster version to 2.0`
`FAIL`
`coverage: 30.2% of statements`
`FAIL	github.com/coreos/etcd/etcdserver	6.139s`
And then I modified nothing, just reexecuted the test file, and I got the correct result again. It confused me a lot. 
I really appreciate it if someone can explain the phenomenon to me.

**Comment by heyitsanthony** [comment] 2016-09-01 16:10
Which test is failing? Does this happen with 3.0.7?

**Comment by xiang90** [comment] 2016-09-06 20:10
kindly ping on this @shuqilou

**Comment by xiang90** [comment] 2016-09-08 20:09
I am going to close this out. I cannot reproduce locally. Probably you met some flaky tests. If you can reliably reproduce a test failure, please open an issue for that test.

**Closed by xiang90** 2016-09-08 20:09 UTC
