### ISSUE TITLE
default value of auto-compaction in 3.2.x

### ISSUE THREAD

**Issue by shsjshentao** [coreos/etcd#9456] opened 2018-03-19 06:50 UTC
In document,  i find the default value of auto-compaction is 0. It seems to mean no compact.
But in fact, i find etcd will compact every 5 minutes if i do not set this flag.
Is it a bug in 3.2?
Is it related to #8098?

**Comment by hexfusion** [comment] 2018-03-19 15:20
> In document, i find the default value of auto-compaction is 0.

HI @shsjshentao which document are you referring to?

**Comment by gyuho** [comment] 2018-03-19 16:21
> etcd will compact every 5 minutes

How do you know? Do you have server logs?

**Comment by hexfusion** [comment] 2018-03-19 17:48
Not to hijack the issue but I do see this constant. How does this fit into the picture?

https://github.com/coreos/etcd/blob/5b9741e804a44990f67b5eeab686b7141a801346/compactor/compactor.go#L32

**Comment by yudai** [comment] 2018-03-19 17:58
The value @hexfusion pointed out is used here to set timeout in the loop:

https://github.com/coreos/etcd/blob/5b9741e804a44990f67b5eeab686b7141a801346/compactor/periodic.go#L72

and as mentioned in #9443, `last` is not updated at all, so this condition is pass through;

https://github.com/coreos/etcd/blob/5b9741e804a44990f67b5eeab686b7141a801346/compactor/periodic.go#L80

Eventually, every 5 minutes, auto compaction happens without checking the last execution time.

**Comment by hexfusion** [comment] 2018-03-19 18:02
@shsjshentao after @yudai explanation I feel this is a duplicate of  https://github.com/coreos/etcd/pull/9443. Please track this issue for updates.

**Closed by hexfusion** 2018-03-19 18:02 UTC

**Comment by gyuho** [comment] 2018-03-20 20:09
@shsjshentao If you set auto compaction 0, compactor wouldn't even run. What's the server log?

**Comment by yudai** [comment] 2018-03-20 21:47
Oh that's true. I think I jumped into a wrong way.
