### ISSUE TITLE
HEARTBEAT-INTERVAL > 1000 crashes

### ISSUE THREAD

**Issue by mighq** [coreos/etcd#2566] opened 2015-03-23 23:11 UTC
When I set heartbeat > 1000 ms, for example 1001, it causes a crash.

    panic: runtime error: integer divide by zero
    [signal 0x8 code=0x1 addr=0x5f3ebd pc=0x5f3ebd]

> goroutine 21 [running]:
> runtime.panic(0x7dbb20, 0xa5f628)
>         /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
> github.com/coreos/etcd/raft.(*raft).isElectionTimeout(0xc20803c4d0, 0xc20807a2d0)
>         /root/rpmbuild/BUILD/etcd-2.0.5/src/github.com/coreos/etcd/raft/raft.go:696 +0x6d
> github.com/coreos/etcd/raft.(*raft).tickElection(0xc20803c4d0)
>         /root/rpmbuild/BUILD/etcd-2.0.5/src/github.com/coreos/etcd/raft/raft.go:343 +0x9a
> github.com/coreos/etcd/raft.*raft.(github.com/coreos/etcd/raft.tickElection)·fm()
>         /root/rpmbuild/BUILD/etcd-2.0.5/src/github.com/coreos/etcd/raft/raft.go:361 +0x26
> github.com/coreos/etcd/raft.(*node).run(0xc2080a68c0, 0xc20803c4d0)
>         /root/rpmbuild/BUILD/etcd-2.0.5/src/github.com/coreos/etcd/raft/node.go:306 +0x8f1
> created by github.com/coreos/etcd/raft.RestartNode
>         /root/rpmbuild/BUILD/etcd-2.0.5/src/github.com/coreos/etcd/raft/node.go:180 +0xff

Affected version **v2.0.5**.

**Comment by yichengq** [comment] 2015-03-23 23:12
this is a duplicate of https://github.com/coreos/etcd/issues/2487.
It is fixed in master and v2.0.6

**Comment by yichengq** [comment] 2015-03-23 23:12
Thanks for reporting!

**Closed by yichengq** 2015-03-23 23:12 UTC
