### ISSUE TITLE
TestSendMessage test fails on CI

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4417] opened 2016-02-04 17:43 UTC
Note: the `rafthttp: failed to write 1 on stream Message (blah)` message is complaining about data from another unit test for some reason.

via https://semaphoreci.com/coreos/etcd/branches/master/builds/399
```
--- FAIL: TestSendMessage (1.10s)
	functional_test.go:62: stream from 1 to 2 is not in work as expected
2016-02-03 23:56:25.719130 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:25.719143 I | rafthttp: the connection with 2 became active
2016-02-03 23:56:25.723274 E | rafthttp: failed to read 2 on stream MsgApp v2 (unexpected EOF)
2016-02-03 23:56:25.723290 I | rafthttp: the connection with 2 became inactive
2016-02-03 23:56:25.723368 E | rafthttp: failed to read 1 on stream Message (unexpected EOF)
2016-02-03 23:56:25.723378 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:25.728178 I | rafthttp: the connection with 2 became active
2016-02-03 23:56:25.728390 E | rafthttp: failed to read raft message (some error)
2016-02-03 23:56:25.728409 E | rafthttp: failed to unmarshal raft message (unexpected EOF)
2016-02-03 23:56:25.728429 E | rafthttp: request cluster ID mismatch (got 1 want 0)
2016-02-03 23:56:25.728449 W | rafthttp: failed to process raft message (blah)
2016-02-03 23:56:25.728553 E | rafthttp: failed to find member 2 in cluster 1
2016-02-03 23:56:25.728565 W | rafthttp: rejected the stream from peer 5 since it was removed
2016-02-03 23:56:25.728576 E | rafthttp: request cluster ID mismatch (got 2 want 1)
2016-02-03 23:56:25.728587 E | rafthttp: streaming request ignored (ID mismatch got 2 want 1)
2016-02-03 23:56:25.728989 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.446389 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.469373 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.592222 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.592264 E | rafthttp: failed to write 1 on stream Message (blah)
2016-02-03 23:56:26.592271 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:26.605079 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.605124 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.607947 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.608041 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.609651 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.613600 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.614522 E | rafthttp: failed to read 1 on stream MsgApp v2 (net/http: request canceled)
2016-02-03 23:56:26.614530 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:26.614724 E | rafthttp: failed to read 1 on stream Message (net/http: request canceled)
2016-02-03 23:56:26.614730 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:26.653565 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.655072 I | rafthttp: the connection with 2 became active
2016-02-03 23:56:26.670771 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:26.670845 I | rafthttp: the connection with 2 became active
2016-02-03 23:56:26.674981 E | rafthttp: failed to read 1 on stream Message (unexpected EOF)
2016-02-03 23:56:26.675002 E | rafthttp: failed to read 2 on stream Message (unexpected EOF)
2016-02-03 23:56:26.675021 I | rafthttp: the connection with 2 became inactive
2016-02-03 23:56:26.675032 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:26.679923 I | rafthttp: the connection with 2 became active
2016-02-03 23:56:26.681716 E | rafthttp: failed to read raft message (some error)
2016-02-03 23:56:26.681763 E | rafthttp: failed to unmarshal raft message (unexpected EOF)
2016-02-03 23:56:26.681792 E | rafthttp: request cluster ID mismatch (got 1 want 0)
2016-02-03 23:56:26.681853 W | rafthttp: failed to process raft message (blah)
2016-02-03 23:56:26.682106 E | rafthttp: failed to find member 2 in cluster 1
2016-02-03 23:56:26.682141 W | rafthttp: rejected the stream from peer 5 since it was removed
2016-02-03 23:56:26.682171 E | rafthttp: request cluster ID mismatch (got 2 want 1)
2016-02-03 23:56:26.682191 E | rafthttp: streaming request ignored (ID mismatch got 2 want 1)
2016-02-03 23:56:26.682977 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.400488 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.421261 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.544115 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.544152 E | rafthttp: failed to write 1 on stream Message (blah)
2016-02-03 23:56:27.544157 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:27.557157 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.557177 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.559500 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.559554 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.561563 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.562661 I | rafthttp: the connection with 1 became active
2016-02-03 23:56:27.564887 E | rafthttp: failed to read 1 on stream Message (net/http: request canceled)
2016-02-03 23:56:27.564898 I | rafthttp: the connection with 1 became inactive
2016-02-03 23:56:27.565193 E | rafthttp: failed to read 1 on stream Message (net/http: request canceled)
2016-02-03 23:56:27.565207 I | rafthttp: the connection with 1 became inactive
FAIL
```

**Comment by AkihiroSuda** [comment] 2016-02-05 04:52
`TestSendMessageWhenStreamIsBroken-2` also failed with very similar error string.
https://travis-ci.org/coreos/etcd/jobs/107159682

**Comment by xiang90** [comment] 2016-02-05 05:13
@heyitsanthony @AkihiroSuda The transportation layer is pretty broken now. I am trying to find a way to fix it... Not sure if it is caused by @heyitsanthony's recent fix though.

**Comment by heyitsanthony** [comment] 2016-02-05 05:16
I think I found the issue while debugging the clientv3 logic-- appears to be giving the wrong URLs in `X-Server-Peers`

**Comment by AkihiroSuda** [comment] 2016-02-05 06:32
https://github.com/coreos/etcd/blob/b61eaf33356f7485f4b65d3a4aea8ac5d38ccd72/rafthttp/functional_test.go#L61-L63
 https://github.com/coreos/etcd/blob/b61eaf33356f7485f4b65d3a4aea8ac5d38ccd72/rafthttp/functional_test.go#L148

```go
func waitStreamWorking(p *peer) bool {
	for i := 0; i < 1000; i++ {
		time.Sleep(time.Millisecond)
		if _, ok := p.msgAppV2Writer.writec(); !ok {
			continue
		}
		if _, ok := p.writer.writec(); !ok {
			continue
		}
		return true
	}
	return false
}
```

`waitStreamWorking` has only 1,000 msecs timeout value, which can be too short for slow machines.

I suggest increasing the timeout to an extremely long value. (related discussion: #4121)

**Comment by xiang90** [comment] 2016-02-06 05:04
This is fixed by https://github.com/coreos/etcd/pull/4431 I believe.

**Closed by xiang90** 2016-02-06 05:04 UTC
Labels: area/testing
