### ISSUE TITLE
etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by coozy** [coreos/etcd#5130] opened 2016-04-20 02:36 UTC
I occasionally get the error "etcd cluster is unavailable or misconfigured" from the etcd client library. The etcd server is up and reachable and a retry solves the problem. From the etcd logs this appears to happen when an etcd snapshot is in progress.

My problem is that if this happens for an update operation where PrevExist==client.PrevNoExist, the client returns an error but the key is actually created in the server. Retry operation obviously fails.

How do I handle this - How can I retry an operation, something akin to a TCP retransmit?

---
Single Etcd server: /usr/bin/etcd -version
etcd version 2.0.9

Etcd client library:
   version: "v2.3.0-92-g92a73e7",
  "Rev": "92a73e727b28de00cf9ebb5a40204901f927663b"

**Comment by gyuho** [comment] 2016-04-20 03:05
Do you have logs? Was there any leader election?

**Comment by coozy** [comment] 2016-04-20 18:11
This is a single node etcd deployment; no leader election. I have all the logs, I am just including a small snippet, lemme know if you want it in its entirety. This is not a one time occurrence so I can even enable any debug you need.

The log has this repeated many many times (note, this instance of etcd has stayed up > 6 months with constant use: kudos!)

```
Apr 20 16:48:51 ip-172-31-29-80 etcd[778]: 2016/04/20 16:48:51 filePurge: successfully removed file /var/lib/etcd/default.etcd/member/wal/0000000000001b6d-00000000042f6d40.wal
Apr 20 16:48:53 ip-172-31-29-80 etcd[778]: 2016/04/20 16:48:53 filePurge: successfully removed file /var/lib/etcd/default.etcd/member/snap/0000000000000003-00000000042f6d3f.snap
Apr 20 17:55:07 ip-172-31-29-80 etcd[778]: 2016/04/20 17:55:07 etcdserver: start to snapshot (applied: 70277029, lastsnap: 70267028)
Apr 20 17:55:11 ip-172-31-29-80 etcd[778]: 2016/04/20 17:55:11 etcdserver: compacted log at index 70277029
Apr 20 17:55:16 ip-172-31-29-80 etcd[778]: 2016/04/20 17:55:16 etcdserver: saved snapshot at index 70277029

```

**Comment by xiang90** [comment] 2016-04-20 18:14
@coozy The log seems right. etcd was doing internal snapshotting. It seems like the problem is the client-server communication part. Can you try to get the detail of the error?

``` go
if cerr, ok := err.(*client.ClusterError); ok {
   log(cerr.Detail())
}
```

**Comment by coozy** [comment] 2016-04-20 18:50
I added that and ran a test that just does update in a loop. That caused the server to oom destroying the 6 month uptime! You might have a memory leak somewhere. So the 'Detail' I got was EOF which I suspect isn't useful. 

Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: fatal error: runtime: out of memory
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: runtime stack:
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: runtime.SysMap(0xc293770000, 0x127d0000, 0xc208001900, 0xa564f8)
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: /usr/lib/golang/src/runtime/mem_linux.c:149 +0x98
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: runtime.MHeap_SysAlloc(0xa5bbe0, 0x127d0000, 0x42c782)
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: /usr/lib/golang/src/runtime/malloc.c:284 +0x124
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: runtime.MHeap_Alloc(0xa5bbe0, 0x93e2, 0x10100000000, 0x0)
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: /usr/lib/golang/src/runtime/mheap.c:240 +0x66
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: goroutine 8 [running]:
Apr 20 18:32:05 ip-172-31-29-80 etcd[778]: runtime.switchtoM()

**Comment by xiang90** [comment] 2016-04-20 18:54
@coozy Can you try to upgrade your etcd cluster to 2.3? We fixed tons of bugs in these 6 months.

**Comment by coozy** [comment] 2016-04-20 18:59
we do have a cluster that runs that. I was trying to avoid doing that because that means we need to tell everyone that we can't work with etcd 2.0. 

Also this problem happens over time and I am suspecting data. If you look at the amount of time it took to snapshot it is in the order of 10s of seconds. That's a lot. 

Is the system available when it's taking a snapshot?

**Comment by xiang90** [comment] 2016-04-20 19:07
> Is the system available when it's taking a snapshot?

It is not for 2.0.9. We improved it since 2.1. You probably have to upgrade to get the new features.

**Comment by xiang90** [comment] 2016-04-25 23:18
I think we can close this now. The best solution here is to upgrade your etcd cluster.

**Closed by xiang90** 2016-04-25 23:18 UTC
