### ISSUE TITLE
etcd client paralel usage socket error

### ISSUE THREAD

**Issue by martende** [coreos/etcd#3653] opened 2015-10-08 08:01 UTC
Hello , I am using single etcd client paralel in goroutines for Get requests code looks like

```go
import 	etcd "github.com/coreos/etcd/client"
import	"github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context"


config := etcd.Config{
		Endpoints:servers,
		Transport:etcd.DefaultTransport,
		HeaderTimeoutPerRequest:time.Second,
}
client,_ = etcd.New(config)
kapi = etcd.NewKeysAPI(client)
...
func ParalelUsedGet(key) {
v,err := kapi.Get(context.Background(),key)
...
if ( err != nil ) {
		this.log.Printf("Key '%s' not found. Error: %s", value,err)
		err2 := err.(*etcd.ClusterError)
		if (err2 != nil ) {
			this.log.Printf("Details %s",err2.Detail())
		}
}

}

... 
// Some paralel usage pseudocode
for i:=0; i < N ; i++ {
go ParalelUsedGet(someVal)
}
```

and somtimes i am receiving err from kapi.Get with details:

EtcdBackend 2015/10/08 09:45:26 Details error #0: dial tcp 127.0.0.1:2379: conne
ctex: Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Ans
chluss) nur jeweils einmal verwendet werden.

it looks like socket connect error on already connected socket. 
seems that I should organize connection pool to etcd myself but as I look to the context code looks like it also makes this work for me. 

I don't know is it actually a bug or i am making something wrong in configuration or I should build connection pool myself.

**Comment by philips** [comment] 2015-10-08 12:32
@martende Could you set your locale to english so we can read the error?

**Comment by martende** [comment] 2015-10-08 14:18
socket.error error: [Errno 10048]: Address already in use. Only one usage of each socket address (protocol/IP address/port) is normally permitted

**Comment by yichengq** [comment] 2015-10-09 01:25
@martende Could you reproduce it reliably?

I have tested this at my side:
```
package main

import (
	"log"
	"time"

	"github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context"
	etcd "github.com/coreos/etcd/client"
)

func main() {
	config := etcd.Config{
		Endpoints:               []string{"http://127.0.0.1:2379"},
		Transport:               etcd.DefaultTransport,
		HeaderTimeoutPerRequest: time.Second,
	}
	client, err := etcd.New(config)
	if err != nil {
		log.Print(err)
	}
	kapi := etcd.NewKeysAPI(client)

	for i := 0; i < 100; i++ {
		go func(key string) {
			v, err := kapi.Get(context.Background(), key, nil)
			if err != nil {
				log.Printf("Key '%s' not found. Error: %s", key, err)
			} else {
				log.Printf("get key success: %v", v)
			}
		}("foo")
	}
	time.Sleep(time.Minute)
}
```
and it works fine.

**Comment by martende** [comment] 2015-10-09 07:18
This code can stable reproduce this error.

```
package main

import (
    "log"
    "time"

    "github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context"
    etcd "github.com/coreos/etcd/client"
)

func main() {
    config := etcd.Config{
        Endpoints:               []string{"http://127.0.0.1:2379"},
        Transport:               etcd.DefaultTransport,
        HeaderTimeoutPerRequest: time.Second,
    }
    client, err := etcd.New(config)
    if err != nil {
        log.Print(err)
    }
    kapi := etcd.NewKeysAPI(client)

    log.Println("Start")
    for i := 0; i < 100; i++ {
        go func(key string) {
    for {            _, err := kapi.Get(context.Background(), key,nil)
            if err != nil {
                log.Printf("Key '%s' not found. Error: %s", key, err.(*etcd.ClusterError).Detail())
            } else {
                //log.Printf("get key success: %v", v)
            }
}
        }("product1/v/1")
    }
    time.Sleep(time.Minute)
}
```

**Comment by yichengq** [comment] 2015-10-11 17:31
@martende 
We have no expert on windows, so I could only help to narrow down this problem.

For etcd client, it does normal http request, and should do nothing special. Could you check to see whether normal HTTP requests causes this problem?

something like this:
```
	for i := 0; i < 100; i++ {
		go func(key string) {
			for {
				req, err := http.NewRequest("GET", "http://127.0.0.1:2379/v2/keys/foo", nil)
				if err != nil {
					log.Fatal(err)
				}
				resp, err := http.DefaultTransport.RoundTrip(req)
				if err != nil {
					log.Fatal(err)
				}
				b, err := ioutil.ReadAll(resp.Body)
				if err != nil {
					log.Fatal(err)
				}
				resp.Body.Close()
				log.Printf("get key success: %s", b)
			}
		}("foo")
	}
```

**Comment by xiang90** [comment] 2015-11-18 03:38
@martende As @yichengq mentioned, we are not familiar with windows. And this seems not to be an etcd specific issue. It would be great, if you can try the script @yichengq provided.

I am going to close this issue due to its low activity. Please reopen it if you can provide more information.

**Closed by xiang90** 2015-11-18 03:38 UTC
