### ISSUE TITLE
Getting "cluster ID mismatch:" When Starting A New Cluster

### ISSUE THREAD

**Issue by spirrello** [coreos/etcd#5139] opened 2016-04-20 12:42 UTC
Hi,

Every time I start a new cluster from systemctl, the Etcd process starts but the cluster never "connects".  The following error message keep flooding the logs and I can't seem to understand why this is happening.  Can someone point me in the right direction?  I'm running etcd on Centos 7.

**Error messages from both servers:**
 sudo systemctl status etcd
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-04-20 08:20:02 EDT; 7s ago
 Main PID: 3052 (etcd)
   Memory: 4.4M
   CGroup: /system.slice/etcd.service
           └─3052 /usr/bin/etcd

Apr 20 08:20:09 StefanoC7-2 etcd[3052]: request sent was ignored (cluster ID mismatch: remote[d02e4310f63aca8f]=337bbf...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: publish error: etcdserver: request timed out
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: streaming request ignored (cluster ID mismatch got 337bbf1d89b93fd5 want d0527...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: streaming request ignored (cluster ID mismatch got 337bbf1d89b93fd5 want d0527...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: request sent was ignored (cluster ID mismatch: remote[d02e4310f63aca8f]=337bbf...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: request sent was ignored (cluster ID mismatch: remote[d02e4310f63aca8f]=337bbf...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: streaming request ignored (cluster ID mismatch got 337bbf1d89b93fd5 want d0527...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: streaming request ignored (cluster ID mismatch got 337bbf1d89b93fd5 want d0527...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: request sent was ignored (cluster ID mismatch: remote[d02e4310f63aca8f]=337bbf...29778)
Apr 20 08:20:09 StefanoC7-2 etcd[3052]: request sent was ignored (cluster ID mismatch: remote[d02e4310f63aca8f]=337bbf...29778)
Hint: Some lines were ellipsized, use -l to show in full.

**Here's my config on both servers:**
sudo cat /usr/lib/systemd/system/etcd.service
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
# set GOMAXPROCS to number of processors
ExecStart=/usr/bin/etcd
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

**Server 1**
sudo cat /etc/etcd/etcd.conf
[cluster]
ETCD_NAME=StefanoC7-1
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.10.16.61:2380"
ETCD_LISTEN_PEER_URLS="http://10.10.16.61:2380"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_CLIENT_URLS="http://10.10.16.61:2379,http://127.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://10.10.16.61:2379"
ETCD_INITIAL_CLUSTER_TOKEN="843c4abe-4e8f-4add-8c70-516206dae53b" #Need to dynamically generate this in the future.
ETCD_INITIAL_CLUSTER="StefanoC7-1=http://10.10.16.61:2380,StefanoC7-2=http://10.10.16.62:2380" #Need to research how to build this dynamically
ETCD_INITIAL_CLUSTER_STATE="new"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_SRV=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""[stefano@StefanoC7-1 Calico]

**Server 2**
sudo cat /etc/etcd/etcd.conf
[cluster]
ETCD_NAME=StefanoC7-2
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.10.16.62:2380"
ETCD_LISTEN_PEER_URLS="http://10.10.16.62:2380"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_CLIENT_URLS="http://10.10.16.62:2379,http://127.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://10.10.16.62:2379"
ETCD_INITIAL_CLUSTER_TOKEN="843c4abe-4e8f-4add-8c70-516206dae53b" #Need to dynamically generate this in the future.
ETCD_INITIAL_CLUSTER="StefanoC7-2=http://10.10.16.62:2380,StefanoC7-1=http://10.10.16.61:2380" #Need to research how to build this dynamically
ETCD_INITIAL_CLUSTER_STATE="new"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_SRV=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""

**Comment by gyuho** [comment] 2016-04-20 16:04
Do you have other etcd cluster running in the same machine or reuse `ETCD_INITIAL_CLUSTER_TOKEN`?

**Comment by spirrello** [comment] 2016-04-20 18:48
No this is the only cluster I have running.  I am using the same token
configured in "ETCD_INITIAL_CLUSTER_TOKEN" for each machine in the cluster.

**Comment by gyuho** [comment] 2016-04-20 18:57
Or did you restart the node before? Trying to understand where the other cluster ID `d0527...` might have come from...

**Comment by spirrello** [comment] 2016-04-20 19:33
What's interesting is if I run etcd with the same parameters via exec etcd,
they clusters run fine.  See below for my example:

 exec etcd --name "StefanoC7-1" \
  --data-dir "/var/lib/etcd/" \
  --initial-advertise-peer-urls "http://10.10.16.61:2380" \
  --listen-peer-urls "http://10.10.16.61:2380" \
  --listen-client-urls "http://10.10.16.61:2379,http://127.0.0.1:2379" \
  --advertise-client-urls "http://10.10.16.61:2379" \
  --initial-cluster-token "843c4abe-4e8f-4add-8c70-516206dae53b" \
  --initial-cluster "StefanoC7-1=http://10.10.16.61:2380,StefanoC7-2=
http://10.10.16.62:2380" \
  --initial-cluster-state "new"



Node:2

 exec etcd --name "StefanoC7-2" \
  --data-dir "/var/lib/etcd/" \
  --initial-advertise-peer-urls "http://10.10.16.62:2380" \
  --listen-peer-urls "http://10.10.16.62:2380" \
  --listen-client-urls "http://10.10.16.62:2379,http://127.0.0.1:2379" \
  --advertise-client-urls "http://10.10.16.62:2379" \
  --initial-cluster-token "843c4abe-4e8f-4add-8c70-516206dae53b" \
  --initial-cluster "StefanoC7-1=http://10.10.16.61:2380,StefanoC7-2=
http://10.10.16.62:2380" \
  --initial-cluster-state "new"

**Comment by gyuho** [comment] 2016-04-20 19:36
Yeah it should because I can't find anything wrong in your configuration.

Might be systemd specific issue?

**Comment by spirrello** [comment] 2016-04-20 19:44
How could it be systemd specific if it's loading the same parameters?  Do
you have any other recommendations for a daemon manager?  The docs
recommended systemd so that's what I used.

**Comment by gyuho** [comment] 2016-04-20 19:50
@spirrello Sorry, I am not a systemd expert. Could you clean up the data directory after you back up and restart the cluster? The new configuration will be ignored if data directory exists.

**Comment by heyitsanthony** [comment] 2016-04-20 20:22
@spirrello @gyuho I can reproduce this locally.

For server2, I think the unit file should match server1's `ETCD_INITIAL_CLUSTER`:
```
ETCD_INITIAL_CLUSTER="StefanoC7-1=http://10.10.16.61:2380,StefanoC7-2=http://10.10.16.62:2380"
```
(the manual launch had this order for both nodes, which is probably why it worked)

The upshot is etcd seems to be generating different cluster ids based on the ordering (it shouldn't afaik). Will investigate.

**Comment by heyitsanthony** [comment] 2016-04-20 20:24
Or not... it seems I had a stale data directory left over from an old cluster. Back to the drawing board.

**Comment by spirrello** [comment] 2016-04-20 21:28
Finally got it working.  I did two things:

- removed the comments that were listed for the cluster token and initial
cluster
- I then changed the token to something more simple.  Not sure if this
helped but I'll continue testing.

Thanks for the quick responses.

**Comment by gyuho** [comment] 2016-04-20 21:30
Glad that it worked. Please let us know if you still have the same issue.

**Comment by spirrello** [comment] 2016-04-20 21:37
Will do and again thanks for the help today.

**Comment by xiang90** [comment] 2016-04-20 22:16
@spirrello Closing this issue since it works now!

**Closed by xiang90** 2016-04-20 22:16 UTC
