### ISSUE TITLE
etcdctl backup doesn't restore data

### ISSUE THREAD

**Issue by holser** [coreos/etcd#7570] opened 2017-03-22 14:09 UTC
# Bug reporting

etcd cannot assemble cluster using 'backup' data.

Here is a setup:

node1: 10.90.0.2
node2: 10.90.0.3
node3: 10.90.0.4

## etcd version
```
./etcd --version
etcd Version: 3.1.3
Git SHA: 21fdcc6
Go Version: go1.7.5
Go OS/Arch: linux/amd64
```

## How to reproduce a bug?
1. Let's start etcd on node1
```
./etcd --name=etcd1 --listen-peer-urls=http://10.90.0.2:12380 --listen-client-urls=http://10.90.0.2:12379 --initial-cluster=etcd1=http://10.90.0.2:12380 --advertise-client-urls=http://10.90.0.2:12379 --initial-advertise-peer-urls=http://10.90.0.2:12380 --initial-cluster-token=cluster --initial-cluster-state=new
```
2. Let's add node2 to cluster
```
curl http://10.90.0.2:12379/v2/members -XPOST -H "Content-Type: application/json" -d '{"peerURLs":["http://10.90.0.3:12380"]}'
```
3. Let's start etcd on node2
```
./etcd --name=etcd2 --listen-peer-urls=http://10.90.0.3:12380 --listen-client-urls=http://10.90.0.3:12379 --initial-cluster=etcd1=http://10.90.0.2:12380,etcd2=http://10.90.0.3:12380 --advertise-client-urls=http://10.90.0.3:12379 --initial-advertise-peer-urls=http://10.90.0.3:12380 --initial-cluster-token=cluster --initial-cluster-state=existing
```
4. Let's add node3 to cluster
```
curl http://10.90.0.3:12379/v2/members -XPOST -H "Content-Type: application/json" -d '{"peerURLs":["http://10.90.0.4:12380"]}'
```
5. Let's start etcd on node3
```
./etcd --name=etcd3 --listen-peer-urls=http://10.90.0.4:12380 --listen-client-urls=http://10.90.0.4:12379 --initial-cluster=etcd1=http://10.90.0.2:12380,etcd2=http://10.90.0.3:12380,etcd3=http://10.90.0.4:12380 --advertise-client-urls=http://10.90.0.4:12379 --initial-advertise-peer-urls=http://10.90.0.4:12380 --initial-cluster-token=cluster --initial-cluster-state=existing
```
6. Let's populate data from any node
```
for i in `seq 1 100`; do curl http://10.90.0.2:12379/v2/keys/message$i -XPUT -d value="Hello world"; done
```
7. Let's backup data on node1
```
etcdctl backup --data-dir etcd1.etcd/ --backup-dir /tmp/etcddata
```
8. Let's stop cluster on all nodes
9. Let's start forget data about members of cluster
```
./etcd --data-dir /tmp/etcddata/ --force-new-cluster
```
10. Let's start etcd on node1 using 'backup' data
```
./etcd --name=etcd1 --listen-peer-urls=http://10.90.0.2:12380 --listen-client-urls=http://10.90.0.2:12379 --initial-cluster=etcd1=http://10.90.0.2:12380 --advertise-client-urls=http://10.90.0.2:12379 --initial-advertise-peer-urls=http://10.90.0.2:12380 --initial-cluster-token=cluster --initial-cluster-state=new --data-dir /tmp/etcddata/
```
I see the following
```
2017-03-22 15:04:49.905932 I | etcdserver/membership: added member 5af647cb0c01 [http://localhost:2380] to cluster 5af647cb0c02
```
or
```
curl -L http://10.90.0.2:12379/v2/members
{"members":[{"id":"5af647cb0c01","name":"etcd1","peerURLs":["http://localhost:2380"],"clientURLs":["http://10.90.0.2:12379"]}]}
```
## Expected
```
2017-03-22 15:06:29.471420 I | etcdserver: published {Name:etcd1 ClientURLs:[http://10.90.0.2:12379]} to cluster d825fe558110f498
```
or
```
curl -L http://10.90.0.2:12379/v2/members
{"members":[{"id":"8ba468ac385845c","name":"etcd1","peerURLs":["http://10.90.0.2:12380"],"clientURLs":["http://10.90.0.2:12379"]}]}
```

## Conclusion

This bug doesn't allow to assemble cluster anymore using backup data as node2 cannot validate membership
```
2017-03-22 15:09:20.897218 C | etcdmain: error validating peerURLs {ClusterID:5af647cb0c02 Members:[&{ID:5af647cb0c01 RaftAttributes:{PeerURLs:[http://localhost:2380]} Attributes:{Name:etcd1 ClientURLs:[http://10.90.0.2:12379]}} &{ID:cd0f4a1f228e3023 RaftAttributes:{PeerURLs:[http://10.90.0.3:12380]} Attributes:{Name: ClientURLs:[]}}] RemovedMemberIDs:[]}: unmatched member while checking PeerURLs
```

However, when I use original data ` --force-new-cluster` works as expected.

This bug makes backup feature completely broken as data is not restorable...

**Comment by xiang90** [comment] 2017-03-22 15:25
I do not understand how you come to the conclusion that data is not restored.

Your expect this to happen

```
2017-03-22 15:06:29.471420 I | etcdserver: published {Name:etcd1 ClientURLs:[http://10.90.0.2:12379]} to cluster d825fe558110f498
```
.

And it has **nothing** to do with the data you put into etcd.

**Comment by xiang90** [comment] 2017-03-22 15:27
This https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#restoring-the-cluster might help you understand why you see `localhost` in member URLs.

**Comment by holser** [comment] 2017-03-22 16:37
You misread the bug

```
2017-03-22 15:06:29.471420 I | etcdserver: published {Name:etcd1 ClientURLs:[http://10.90.0.2:12379]} to cluster d825fe558110f498
```
is expected. However, I get

```
2017-03-22 15:04:49.905932 I | etcdserver/membership: added member 5af647cb0c01 [http://localhost:2380] to cluster 5af647cb0c02
```

**Comment by holser** [comment] 2017-03-22 16:40
See step 9 and 10 (where --advertise-client-urls is set to http://10.90.0.2:12379 but `etcd` sets `localhost` instead)

**Comment by heyitsanthony** [comment] 2017-03-22 16:45
@holser this is by design, per the docs "--force-new-cluster option has set the peer URL to the default listening on localhost.". The membership is reset because it's restore creates a new cluster; its membership / advertise addresses can't make any assumptions. The new cluster won't reuse the old peer address until it's told to do so through `etcdctl member update`

**Comment by mattymo** [comment] 2017-03-22 16:53
@heyitsanthony that definitely seems like a foolish reason to ignore an explicit option. Why ever would I want to advertise localhost as my peer URL? Why should it be convoluted to restore when initial setup is intuitive?

**Comment by holser** [comment] 2017-03-22 16:57
After '--force-new-cluster'. I am trying to assemble a new cluster, so as a parameter I set '--listen-peer-urls=http://10.90.0.2:12380'. Moreover if I reset original data `etcd1.etcd` with '--force-new-cluster' I was able to start cluster.

I gave step by step instructions. In nutshell when I do 9,10 with `/tmp/etcddata` etcd doesn't set proper peer url when I do with `./etcd1.etcd` it sets it correctly.

**Comment by heyitsanthony** [comment] 2017-03-22 17:18
@holster `--initial-advertise-urls` is for bootstrapping. Since it's forced a cluster, it's already been bootstrapped and the peer advertise url is already registered as localhost. etcd won't use the `--initial-advertise-urls` flag to override known membership configuration.

A reason for doing it this way: consider a cluster of A, B, C with initial advertise URLs a, b, c. Let B move to b' and C move to c' and reboot A. Also, assume that `--initial-advertise-urls` is attached to the etcd command, even when resuming. If `--initial-advertise-urls` overrides the membership configuration from the raft layer, A will not be able to find B or C (since it expects peers on b and c) and it will not be able to participate in the cluster. The downside to this approach is if A is down for b->b' and c->c', it will not be able to find the raft cluster without an override, but this both operationally rare and simple to workaround (remove/add the member).

There might be an argument for `--initial-advertise-urls` to have an effect on `--force-new-cluster`. But ultimately, restore is for backing up key data, not cluster configuration.

**Comment by mattymo** [comment] 2017-03-22 17:25
There are good arguments here, but etcd is often run in a container with an env file. Obfuscating the ability to set advertise address after restore places an undue and unnecessary burden on the deployer. Why not enable some extra flag to update member name? Generally --force-* options serve this function.

**Comment by xiang90** [comment] 2017-03-22 17:55
@mattymo It already happened for etcd3: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster.

We have no interest in adding this for v2, which can pollute etcd flag set. If you want, you can submit a patch to etcdctlv2 to enable similar things.

This is a limitation as it is. It works exactly as documented. I do not feel it is a bug.

@holser 

I do not understand your reply still. As @heyitsanthony and I mentioned, configuration is not data. If you insist that your data is not restored, show us. Or I am going to close this issue.

**Comment by heyitsanthony** [comment] 2017-03-22 18:00
@mattymo like I said, it could be done when --initial-advertise-urls is given with --force-new-cluster, but it's not supported now.

Having the server update the advertise peer address on boot is do-able, but seems like a way to fall into a configuration that will deadlock the cluster. Suppose each member forces its advertise peer URL; this works if individual members reboot now and then. However, suppose the entire cluster reboots. Since the peer publish must go through consensus, since there's no quorum to accept the peer publish the cluster can't make forward progress / boot.

**Comment by holser** [comment] 2017-03-24 21:56
@heyitsanthony Thank you very much for `etcdctl member update`. It did a trick.

However, one question still remains. Why does **--force-new-cluster** work differently with original data? Why do I need to do `member update` for restored data?

I have recorded a debug session. I hope it will be more clear to understand my confusion from it.

[debug session](http://asciinema.org/a/6lk8rila6fuy97pzqf20wrkwn)

Thank you very much for your patience.

**Comment by heyitsanthony** [comment] 2017-03-24 22:19
@holser differently from what? 

Running this command will force the WAL file to have a member configuration of one member with a localhost advertise peer url:
`./etcd --data-dir /tmp/etcddata/ --force-new-cluster`

Running this command will not overwrite the member configuration, since has already been set by `--force-new-cluster`:
`./etcd --name=etcd1 --listen-peer-urls=http://10.90.0.2:12380 --listen-client-urls=http://10.90.0.2:12379 --initial-cluster=etcd1=http://10.90.0.2:12380 --advertise-client-urls=http://10.90.0.2:12379 --initial-advertise-peer-urls=http://10.90.0.2:12380 --initial-cluster-token=cluster --initial-cluster-state=new --data-dir /tmp/etcddata/`

Once the membership is initialized, all member changes go through raft to avoid membership split-brain. The command line here could possibly reconfigure the membership on noticing it's different from what the WAL file has, but again, this can lead to cluster boot deadlock where all members have a circular dependency between reconfiguring and participating in consensus.

**Comment by heyitsanthony** [comment] 2017-03-28 19:12
The v2 restore path isn't too great regardless. Since v2 is in maintenance and all active development is going into v3, it's unlikely this behavior will ever change in the future.

On the other hand, the v3 restore path supports setting up an initial cluster (see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster) as part of its restore process.

Closing.

**Closed by heyitsanthony** 2017-03-28 19:12 UTC
