### ISSUE TITLE
Rotating through servers on the client, or possibly blacklisting after failed attempts.

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2677] opened 2015-04-14 13:32 UTC
When testing etcd daemon failures in kubernetes, we had discovered that it would not cycle through it's clients list regularly: 

https://github.com/GoogleCloudPlatform/kubernetes/issues/6559 

This becomes an issue when testing failure conditions such as a hard kill, or net-split: 
https://github.com/GoogleCloudPlatform/kubernetes/issues/5589 

because it will be stuck trying to contact the failed server. 

/cc @rrati, @xiang90

**Comment by xiang90** [comment] 2015-04-15 03:23
@timothysc @rrati Can you please tell me what is the version of etcd/etcdclint are you using?

**Comment by xiang90** [comment] 2015-04-15 03:24
It seems like https://github.com/GoogleCloudPlatform/kubernetes/pull/6422 this the root cause. Not etcd-client. But I can look into the issue if you can provide me the version of etcd and client.

**Comment by timothysc** [comment] 2015-04-15 13:21
@xiang90 sha:  f480a8b051591a6b053bd9ad643fed5787b3acb0 

Re: #6422, we use our own etcd cluster and configs on bare metal, no default configs from upstream.

**Comment by xiang90** [comment] 2015-04-15 16:09
@timothysc OK.

I cannot reproduce the problem you described with etcd. I need some of your help.

Here is what I have done:

1. set up a 3 members cluster
2. use a small tool I wrote for k8s to simulate the situation [https://github.com/xiang90/etcdk8s-stress]
3. simulate the node failure by killing etcd process
4. see the output of the small tool

##etcd setup

```
etcd1: bin/etcd -name infra1 -listen-client-urls http://localhost:4001 -advertise-client-urls http://localhost:4001 -listen-peer-urls http://localhost:7001 -initial-advertise-peer-urls http://localhost:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new

etcd2: bin/etcd -name infra2 -listen-client-urls http://localhost:4002 -advertise-client-urls http://localhost:4002 -listen-peer-urls http://localhost:7002 -initial-advertise-peer-urls http://localhost:7002 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new

etcd3: bin/etcd -name infra3 -listen-client-urls http://localhost:4003 -advertise-client-urls http://localhost:4003 -listen-peer-urls http://localhost:7003 -initial-advertise-peer-urls http://localhost:7003 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
```

## run small tool

```
./etcdk8s-stress -action "switch" -end-points "http://127.0.0.1:4001,http://127.0.0.1:4002,http://127.0.0.1:4003"
go-etcd2015/04/15 09:00:24 DEBUG: put 0, 0, ttl: 0, [http://127.0.0.1:4001]
go-etcd2015/04/15 09:00:24 DEBUG: Connecting to etcd: attempt 1 for keys/0
go-etcd2015/04/15 09:00:24 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/0 | method PUT
go-etcd2015/04/15 09:00:24 DEBUG: recv.response.from http://127.0.0.1:4001/v2/keys/0
go-etcd2015/04/15 09:00:24 DEBUG: recv.success http://127.0.0.1:4001/v2/keys/0
go-etcd2015/04/15 09:00:25 DEBUG: put 1, 1, ttl: 0, [http://127.0.0.1:4001]
go-etcd2015/04/15 09:00:25 DEBUG: Connecting to etcd: attempt 1 for keys/1
```

## kill member 4001, which is go-etcd talks to.

## expect a failure due to leader election and then rotates to the new leader

```
go-etcd2015/04/15 09:00:32 DEBUG: network error: Put http://127.0.0.1:4001/v2/keys/8: dial tcp 127.0.0.1:4001: connection refused
go-etcd2015/04/15 09:00:32 WARNING: bad response status code0
go-etcd2015/04/15 09:00:32 DEBUG: switch.leader[from http://127.0.0.1:4001 to http://127.0.0.1:4002]
go-etcd2015/04/15 09:00:32 DEBUG: Connecting to etcd: attempt 3 for keys/8
go-etcd2015/04/15 09:00:32 DEBUG: send.request.to http://127.0.0.1:4002/v2/keys/8 | method PUT
go-etcd2015/04/15 09:00:38 DEBUG: recv.response.from http://127.0.0.1:4002/v2/keys/8
** go-etcd2015/04/15 09:00:38 WARNING: bad response status code500 ** // leader election
go-etcd2015/04/15 09:00:38 DEBUG: Connecting to etcd: attempt 4 for keys/8
go-etcd2015/04/15 09:00:38 DEBUG: send.request.to http://127.0.0.1:4002/v2/keys/8 | method PUT
go-etcd2015/04/15 09:00:38 DEBUG: recv.response.from http://127.0.0.1:4002/v2/keys/8
** go-etcd2015/04/15 09:00:38 DEBUG: recv.success http://127.0.0.1:4002/v2/keys/8 ** switched
go-etcd2015/04/15 09:00:39 DEBUG: put 9, 9, ttl: 0, [http://127.0.0.1:4002]
```

Can you try this out?

**Comment by xiang90** [comment] 2015-04-16 21:18
@timothysc Ping

**Comment by timothysc** [comment] 2015-04-16 21:35
@xiang90 sorry I haven't had a chance to circle back.  I'll be sure to respond by tomorrow.

**Comment by xiang90** [comment] 2015-04-21 18:37
@timothysc Ping

**Comment by timothysc** [comment] 2015-04-24 20:22
@xiang90 sorry for my delay... I've recreated the issue using a modified version of your test program which simulates the k8's issue. 

https://github.com/timothysc/etcdk8s-stress
https://github.com/timothysc/etcdk8s-stress/blob/master/writer_stress.go 

@ghodss ^ FYI.

**Comment by xiang90** [comment] 2015-04-24 20:23
@timothysc Thanks. I will give it a try.

**Comment by xiang90** [comment] 2015-04-27 04:13
@timothysc Can you please tell me how did you run the modified version of my test? What is the expected output/behavior.  And why you think it is a problem? Thanks.

**Comment by timothysc** [comment] 2015-04-27 13:01
@xiang90 I updated the writer to use the existing client connection similar to k8's, and all operations are through a single server.  In your example it (prior to mods), it would rotate through the servers but it would also constantly be creating a new client connection.  Forcing the client to call NewClient on every single operation is onerous, and imho the responsibility of connection management and rotation should be on the library itself. 

to verify - `lsof -p <pid_of_prog>`

**Comment by xiang90** [comment] 2015-04-27 14:23
@timothysc 

Actually I still cannot follow you. 

See https://github.com/coreos/etcd/issues/2677#issuecomment-93465774 again.

I used `switch` action, not `write`. You changed `write` action in your branch, so I am confused how would that help.

> it would rotate through the servers but it would also constantly be creating a new client connection.

This is also not true on `switch`.

**Comment by timothysc** [comment] 2015-04-27 14:51
I modified the writer, and up'd the concurrency as a test case. 

Prior to the modification, you would have an equal number of connections to each endpoint.  This was because your tests constantly created a new client for ever operations.

// was inside the for loop
client := etcd.NewClient(endpoints) 

With the current modifications to the writer, which is how kubernetes uses the client library, all connections go through a single endpoint.  

// outside the for loop.
client := etcd.NewClient(endpoints) 

The idea that every single operation requires creating a new client is onerous to anyone using the library, and unexpected.

@dchen1107, @kelseyhightower - FYI^

**Comment by xiang90** [comment] 2015-04-27 14:56
@timothysc 

As I said before,
```
I used switch action, not write. You changed write action in your branch, so I am confused how would that help.
```

The code is like
``` go
func stressSwitch(endpoints []string) {
	client := etcd.NewClient(endpoints)
	etcd.SetLogger(log.New(os.Stderr, "go-etcd", log.LstdFlags))
	client.OpenCURL()
	for i := 0; i < 10000; i++ {
		key := fmt.Sprintf("%d", i)
		_, err := client.Set(key, key, 0)
		if err != nil {
			log.Printf("error setting key %s", key)
			time.Sleep(time.Second)
			continue
		}
		time.Sleep(time.Second)
	}
}
```
https://github.com/xiang90/etcdk8s-stress/blob/master/switch_member.go#L13-L25

As I said, 

```
// was inside the for loop
client := etcd.NewClient(endpoints)

With the current modifications to the writer, which is how kubernetes uses the client library, all connections go through a single endpoint.

// outside the for loop.
client := etcd.NewClient(endpoints)
```

This is not true. You used and modified the wrong action.

**Comment by xiang90** [comment] 2015-04-27 15:01
> The idea that every single operation requires creating a new client is onerous to anyone using the library, and unexpected.

`write` tests create one client for each concurrent write, not for each operation. You need to read the code again. 

This is exact what you should do in your application. go-etcd is not thread-safe.

**Comment by timothysc** [comment] 2015-04-27 15:18
> This is exact what you should do in your application. go-etcd is not thread-safe. 

That is the root of the problem...

**Comment by xiang90** [comment] 2015-04-27 15:21
this has nothing to do with your original issue imo

**Comment by timothysc** [comment] 2015-04-27 15:57
I don't think it is.  K8's has only a single open client and upwards of 400 concurrent operations going on.  

Also, FWIW `etcdk8s-stress --action="switch"` only hits one server.

**Comment by xiang90** [comment] 2015-04-27 16:25
@timothysc 

`switch` only uses one client. It has three endpoints. And after I killed one, it rotates to use another one. It tries to reproduce the case you described in your original issue.

I am not sure about what do you mean by 

> only hits one server.

**Comment by yichengq** [comment] 2015-04-27 20:36
@timothysc @xiang90 
The discussion goes into several problems now:

1. @timothysc you said that go-etcd doesn't rotate through server on the client. I read xiang's switchStress code and it does switch to another member when one member is killed. Any more thoughts on your failure case? I think either changing switchStress code or giving instruments on how to do it is helpful. I tried your write stress code and cannot reproduce the case that `it would not cycle through it's clients list regularly`.

2. go-etcd is not thread-safe, and it may have some problem if it is called concurrently. If k8s is using that way, we will dig into it and either fix it here or in k8s. Could you point out how k8s uses etcd client today?

**Comment by timothysc** [comment] 2015-04-27 21:18
@yichengq 

re:1 - To reproduce the issue on with 'switch', you can navigate to the server which it is communicating with, and call `kill -STOP $(pgrep etcd)` to simulate a net-split, and the etcdk8s-stress test will completely lock.

IMHO every client set/get operation should round-robin through the servers, to prevent this.   

re: 2 - k8's only has 1 client for upwards of 400 concurrent operations.  It would be easy to change if there were a client weight mechanism to create a new client from an existing one.  (Clone/Copy...)

**Comment by xiang90** [comment] 2015-04-27 21:25
@timothysc 

>  To reproduce the issue with 'switch', you can navigate to the server which it is communicating with, and call kill -STOP $(pgrep etcd) to simulate a net-split, and the etcdk8s-stress test will completely lock.

This is what I have done at https://github.com/coreos/etcd/issues/2677#issuecomment-93465774. And I did not see a lock down. @yichengq Can you try to verify?

**Comment by yichengq** [comment] 2015-04-27 21:56
@timothysc I did the reproduction but failed:
1. start a local etcd cluster listen on 4001-4003
2. `./etcdk8s-stress -action="switch" -end-points="http://127.0.0.1:4001,http://127.0.0.1:4002,http://127.0.0.1:4003"`
3. I find it connects to 4002 for requests, so i killed machine2 that listens on 4002
4.
```
go-etcd2015/04/27 14:41:57 DEBUG: put 411, 411, ttl: 0, [http://127.0.0.1:4002]
go-etcd2015/04/27 14:41:57 DEBUG: Connecting to etcd: attempt 1 for keys/411
go-etcd2015/04/27 14:41:57 DEBUG: send.request.to http://127.0.0.1:4002/v2/keys/411 | method PUT
go-etcd2015/04/27 14:41:57 DEBUG: network error: Put http://127.0.0.1:4002/v2/keys/411: dial tcp 127.0.0.1:4002: connection refused
go-etcd2015/04/27 14:41:57 DEBUG: Connecting to etcd: attempt 2 for keys/411
go-etcd2015/04/27 14:41:57 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/411 | method PUT
go-etcd2015/04/27 14:41:57 DEBUG: recv.response.from
go-etcd2015/04/27 14:41:57 DEBUG: recv.success
```
It does switch to 4001 port. I have tested this in GCE etcd cluster, and it still works.

I think go-etcd DOES round-robin today. Could you write detailed instructions or shell script for reproduction?


re: 2 - One single client can handle that with lock, and there is no bother to clone client. I am not familiar with k8s code base. Do you know where the shared client is?

**Comment by timothysc** [comment] 2015-04-28 13:26
I have 4 separate machines on bare metal that span 2 switches.

* running from master: be6f49ba3251cd9d8f8a5aff1aa95b04b7ead3b3
* 3 etcd servers (http://host01-rack10:2379,http://host02-rack10:2379,http://host17-rack11:2379)  I've verified that their configs are correct.
* 1 client (host18-rack11) 

Step 1: 
On host18-rack11 run 'etcdk8s-stress -action="switch"' with the endpoints hard-coded in the program

go-etcd2015/04/27 21:01:43 DEBUG: put 0, 0, ttl: 0, [http://host02-rack10:2379]
go-etcd2015/04/27 21:01:43 DEBUG: Connecting to etcd: attempt 1 for keys/0
go-etcd2015/04/27 21:01:43 DEBUG: send.request.to http://host02-rack10:2379/v2/keys/0 | method PUT
go-etcd2015/04/27 21:01:43 DEBUG: recv.response.from 
go-etcd2015/04/27 21:01:43 DEBUG: recv.success
...

Step 2: 
ssh into host2-rack10 and execute the following: 
# ps aux | grep etcd
root      3832 10.4  0.0  91620 63884 ?        Ssl  01:27 122:33 /mnt/build/bin/etcd
# kill -STOP 3832

Step 3: 
Check output of etcdk8s-stress : 

'LOCKED, no recovery'

**Comment by yichengq** [comment] 2015-04-28 19:07
@timothysc I did the exact same thing as you mentioned, but it worked well. Here is my log when the member is killed:
```
go-etcd2015/04/28 19:03:00 DEBUG: put 26, 26, ttl: 0, [http://10.240.134.131:2379]
go-etcd2015/04/28 19:03:00 DEBUG: Connecting to etcd: attempt 1 for keys/26
go-etcd2015/04/28 19:03:00 DEBUG: send.request.to http://10.240.134.131:2379/v2/keys/26 | method PUT
go-etcd2015/04/28 19:03:00 DEBUG: network error: Put http://10.240.134.131:2379/v2/keys/26: dial tcp 10.240.134.131:2379: connection refused
go-etcd2015/04/28 19:03:00 DEBUG: Connecting to etcd: attempt 2 for keys/26
go-etcd2015/04/28 19:03:00 DEBUG: send.request.to http://10.240.142.94:2379/v2/keys/26 | method PUT
go-etcd2015/04/28 19:03:00 DEBUG: recv.response.from
go-etcd2015/04/28 19:03:00 DEBUG: recv.success
go-etcd2015/04/28 19:03:01 DEBUG: put 27, 27, ttl: 0, [http://10.240.142.94:2379]
go-etcd2015/04/28 19:03:01 DEBUG: Connecting to etcd: attempt 1 for keys/27
go-etcd2015/04/28 19:03:01 DEBUG: send.request.to http://10.240.142.94:2379/v2/keys/27 | method PUT
go-etcd2015/04/28 19:03:01 DEBUG: recv.response.from
go-etcd2015/04/28 19:03:01 DEBUG: recv.success
```

the go-etcd version I am using for etcdk8s-stress is https://github.com/coreos/go-etcd/commit/0424b5f86ef0ca57a5309c599f74bbb3e97ecd9d
Could you give it a try?

Could you SIGQUIT etcdk8s-stress when it stalls and have no output? Maybe we can find something out from the stack trace.

**Comment by timothysc** [comment] 2015-04-28 20:39
In summary from irc-chat: `systemd stop != kill -STOP`

**Comment by yichengq** [comment] 2015-04-28 21:54
Based on discussion on IRC, here are some summary for this issue:

1. hard kill rotation works fine. If the member that go-etcd connects to is hard killed, go-etcd will fail on the first attempt with the killed member, and succeed on the second attempt with another member.

2. `kill -STOP` etcd will let go-etcd stuck on `httpClient.Do` function call. the default transport in go-etcd does have DialTimeout, but that doesn't help in this case.
@timothysc I am not convinced that `kill -STOP` could happen in real life. I think a normal net-split should return error 'connection refused' or 'dial error'.
One workable way is to set transport: http://godoc.org/github.com/coreos/go-etcd/etcd#Client.SetTransport .

3. go-etcd doesn't rotate through etcd members when the connected member works well, and this behavior is intentional. It saves socket resources, and improves efficiency based on the experience that the member works well last time.

**Comment by timothysc** [comment] 2015-04-29 03:18
`kill -STOP` is a standard practice for simulation of net-splits, and is adopted by many distributed systems.  It was also the reason why it was chosen as a test route by others looking at Kubernetes.  

Do you know if TCP keepalive is set on the underlying socket?

**Comment by xiang90** [comment] 2015-04-29 03:39
@timothysc 

The default transport does not set tcp keepalive. 

As yicheng mentioned, the user can set it themselves. Even if you set tcp keepalive, it takes o(minutes) to detect a broken link or at least second if you set it very low. 

And as yicheng mentioned, the client stuck on dial. The connection is not even set up properly. 

This seems a transport issue, not a client lib issue. 

Are you suggesting the default transport should handle this for you?

**Comment by timothysc** [comment] 2015-04-29 14:38
From a client perspective, it should handle this network situation gracefully but currently it does not.   Providing well documented tuning options would be great, but this situation should be handled under any tuning configuration.

As a user, I don't care about the internal implementation semantics in either the client or server.  I want to use etcd as a service, and have the client and server handle fail over for various scenarios.

**Comment by xiang90** [comment] 2015-04-29 14:56
@timothysc 

I agree with you we need to do better documentation around the default transport in go-etcd and the fact you can change the default one. We should probably set a dial timeout by default.

> I want to use etcd as a service, and have the client and server handle fail over for various scenarios.

You probably want to know the guarantees. No service in the world can handle all kinds of fail over for you.

Moreover, this thread ended up with a different issue with the one you originally posted. Form your original post and its reference, I saw a shutdown not "sigstop". And the client did not stuck but report 501 error without rotating to another etcd server. We are always trying to reproduce your original issue.

Here is what you have done and I cannot reproduce with etcd cluster itself

https://github.com/GoogleCloudPlatform/kubernetes/issues/6559#issuecomment-93399344
```
Setup a etcd 3-node cluster
Startup the apiserver with proper args for etcd
netstat to determine which server the apiserver appears to have chosen
kill that etcd server
apiserver is now hosed, and it doesn't chose any of the other clients that have been provided to the etcd client. Toast!
```

Here is what you saw and I cannot reproduce.
```
Error: Get http://:2379/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp :2379: connection refused
```

Since we are not able to reproduce the original one, I have to close this issue.

I will create another issue for the transport documentation in go-etcd repo.

Thanks for reporting.

**Closed by xiang90** 2015-04-29 14:56 UTC

**Comment by yichengq** [comment] 2015-04-29 20:20
@timothysc 
The default transport of go-etcd uses 1s dialTimeout, and uses 1s TCP keepAlive period.

If the remote is dead, or net-split, client will detect that through TCP keepalive messages in a few seconds, and rotates to another member.
It doesn't detect that server is `kill -STOP` because the tcp connections on suspended process are kept alive by linux. Based on this, i think `kill -STOP` is not a good way to simulate network partition, and you should down the interface or use iptables to do it.

I will add the note about the default transport that go-etcd is using. But we don't have simple ways to detect etcd suspend, and it is not our priority to tackle this problem now because we don't see a solid real life possibilities for it. Sound good?

**Comment by xiang90** [comment] 2015-04-29 20:22
@yichengq We still need to document it in go-etcd readme.
