### ISSUE TITLE
Public Service Discovery Bugs?

### ISSUE THREAD

**Issue by spontaneous01** [coreos/etcd#2207] opened 2015-02-02 17:37 UTC
Hi, 
I am using etcd v2.0.0 and I fill in trouble.

Info:
```
Version: 2.0.0
Cloud Platform: Microsoft Azure
Distribution: Ubuntu 14.10
```

I use `public service discovery` . I have three node. Always one of them can't join the cluster.
Logs:
```
2015/02/02 17:32:26 etcd: stopping listening for client requests on http://localhost:4001
2015/02/02 17:32:26 etcd: stopping listening for client requests on http://localhost:2379
2015/02/02 17:32:26 etcd: stopping listening for peers on http://:2380
2015/02/02 17:32:26 etcd: member node-3 has previously registered with discovery service (https://discovery.etcd.io/8f169dbffae67a303f19e31c73811da9), but the data-dir (node-3.etcd) on disk cannot be found.
```
The `./node-3.etcd` is removed.
I try many times. 

Can I use REST API to admin the public service discovery ?
Is this a bug?

**Comment by xiang90** [comment] 2015-02-02 17:44
@spontaneous01 
If any of your machine failed with doing discovery:
1. the cluster wont come up if a majority failed 
    retry
2. the cluster comes up
    2.1 retry the whole cluster with new token
    2.2 remove the previously failed member and re-add it via runtime re-configuration

etcd does not persist the discovery status on to disk at this moment. And we expect the cluster failure rate the the bootstrap face is very small.

**Comment by spontaneous01** [comment] 2015-02-02 18:04
@xiang90 
Here is the another situation:
First node joins cluster, shows 
```
2015/02/02 17:57:24 discovery: found 1 peer(s), waiting for 2 more
```

Second node joins, it shows this message at first time:
```
2015/02/02 17:56:40 etcd: client: no leader
```
And it exits. After second try:
```
2015/02/02 18:00:36 etcd: member node-Suck-1 has previously registered with discovery service (https://discovery.etcd.io/fce077ac311e88886a214f9e3c348f71), but the data-dir (node-1.etcd) on disk cannot be found.
```
It breaks again.

**Comment by xiang90** [comment] 2015-02-02 18:05
@spontaneous01 Can you please copy me the full log?

**Comment by spontaneous01** [comment] 2015-02-02 18:09
@xiang90 
Sorry, I didn't keep it. 
The message I post is the last line.
The message before it is the initialize message like:
```
(bla bla bla)
2015/02/02 17:32:26 etcd: stopping listening for client requests on http://localhost:4001
2015/02/02 17:32:26 etcd: stopping listening for client requests on http://localhost:2379
2015/02/02 17:32:26 etcd: stopping listening for peers on http://:2380
```

**Comment by xiang90** [comment] 2015-02-02 18:13
@spontaneous01 Can you please try to reproduce it?

**Comment by spontaneous01** [comment] 2015-02-02 18:19
@xiang90 
I am starting a new cluster. The old one has been removed. I'll rebuild it from its cloned images for 0.5~2 days.
If there is any news, I will report.

**Comment by spontaneous01** [comment] 2015-02-03 13:45
I build two VM to simulate the situation.
Two VMs was built by same os-image.

---
**Log**

VM 1
```
$ ./etcd -name node-${HOSTNAME} -initial-advertise-peer-urls http://${HOSTIP}:2380   -listen-peer-urls http://${HOSTIP}:2380   -discovery https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6
2015/02/03 13:43:57 netutil: Resolving :2380 to :2380
2015/02/03 13:43:57 netutil: Resolving :2380 to :2380
2015/02/03 13:43:57 no data-dir provided, using default data-dir ./node-1.etcd
2015/02/03 13:43:57 etcd: listening for peers on http://:2380
2015/02/03 13:43:57 etcd: listening for client requests on http://localhost:2379
2015/02/03 13:43:57 etcd: listening for client requests on http://localhost:4001
2015/02/03 13:43:59 etcd: stopping listening for client requests on http://localhost:4001
2015/02/03 13:43:59 etcd: stopping listening for client requests on http://localhost:2379
2015/02/03 13:43:59 etcd: stopping listening for peers on http://:2380
2015/02/03 13:43:59 etcd: member node-1 has previously registered with discovery service (https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6), but the data-dir (node-1.etcd) on disk cannot be found.
```

VM2
```
$ ./etcd -name node-${HOSTNAME} -initial-advertise-peer-urls http://${HOSTIP}:2380   -listen-peer-urls http://${HOSTIP}:2380   -discovery https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6

vertise-peer-urls http://${HOSTIP}:2380 \etcd -name node-${HOSTNAME} -initial-ad 
>   -listen-peer-urls http://${HOSTIP}:2380 \
>   -discovery https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6
2015/02/03 13:38:42 netutil: Resolving :2380 to :2380
2015/02/03 13:38:42 netutil: Resolving :2380 to :2380
2015/02/03 13:38:42 no data-dir provided, using default data-dir ./node-2.etcd
2015/02/03 13:38:42 etcd: listening for peers on http://:2380
2015/02/03 13:38:42 etcd: listening for client requests on http://localhost:2379
2015/02/03 13:38:42 etcd: listening for client requests on http://localhost:4001
2015/02/03 13:38:44 discovery: found self 9996989a308f307b in the cluster
2015/02/03 13:38:44 discovery: found 1 peer(s), waiting for 2 more
2015/02/03 13:39:44 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 2s
2015/02/03 13:39:47 discovery: found self 9996989a308f307b in the cluster
2015/02/03 13:39:47 discovery: found 1 peer(s), waiting for 2 more
2015/02/03 13:40:47 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 4s
2015/02/03 13:40:52 discovery: found self 9996989a308f307b in the cluster
2015/02/03 13:40:52 discovery: found 1 peer(s), waiting for 2 more
```

**Comment by yichengq** [comment] 2015-02-04 03:02
I think there are two possiblities that may cause this:
1. Discovery url can only be used one time. You should use a new one for a new cluster.
More details:
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#lifetime-of-a-discovery-url
2. Does these two etcds use the same name to bootstrap? The name is supposed to be different at bootstrap stage. Could you share the command line with us?

**Comment by spontaneous01** [comment] 2015-02-04 08:10
Here's the hostname
VM1: 
```
$ echo ${HOSTNAME}
1

$ ./etcd -name node-${HOSTNAME} -initial-advertise-peer-urls http://${HOSTIP}:2380   -listen-peer-urls http://${HOSTIP}:2380   -discovery https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6
(...)
2015/02/03 13:43:57 no data-dir provided, using default data-dir ./node-1.etcd
(...)
```

VM2:
```
$ echo ${HOSTNAME}
2

$ ./etcd -name node-${HOSTNAME} -initial-advertise-peer-urls http://${HOSTIP}:2380   -listen-peer-urls http://${HOSTIP}:2380   -discovery https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6
(...)
2015/02/03 13:38:42 no data-dir provided, using default data-dir ./node-2.etcd
(...)
```

---

This problem is only occurred in VM based on cloned-image at Azure.
If I create each VM manually, it will not happened.
Does etcd read `-name` for identify only? Or it read something else potentially?

**Comment by yichengq** [comment] 2015-02-06 00:18
@spontaneous01 
One discovery url is only for 1 cluster. As i see, `https://discovery.etcd.io/3bf1a75abacfd03a9cd734ddd4734af6` is registered with `node-Suck-2=http://:2380`(you can check it by wget it). It has been used in the early time, and should not be used here.

**Comment by spontaneous01** [comment] 2015-02-06 12:22
Maybe using `hostname <new hostname>` is not enough for Ubuntu 14.10.
Sorry for my poor Linux skill.
I am using free plan for Azure, and I have no free core to build that condition again because some other plan. I will go back to try later. Thanks for answer.

**Comment by xiang90** [comment] 2015-02-11 06:01
@spontaneous01 Any result?

**Comment by akaspin** [comment] 2015-02-19 23:26
etcd 2.0.3
```
{
"action": "get",
"node": {
"key": "/_etcd/registry/2f0fc5714e64c9353da0670e6d820aa7",
"dir": true,
"nodes": [
{
"key": "/_etcd/registry/2f0fc5714e64c9353da0670e6d820aa7/27e6404248259ff1",
"value": "core-01=http://172.17.8.101:2380,core-01=http://172.17.8.101:7001",
"modifiedIndex": 351874834,
"createdIndex": 351874834
},
{
"key": "/_etcd/registry/2f0fc5714e64c9353da0670e6d820aa7/f784b275ca1e85df",
"value": "core-02=http://172.17.8.102:2380,core-02=http://172.17.8.102:7001",
"modifiedIndex": 351875189,
"createdIndex": 351875189
},
{
"key": "/_etcd/registry/2f0fc5714e64c9353da0670e6d820aa7/f96485909996c501",
"value": "core-03=http://172.17.8.103:2380,core-03=http://172.17.8.103:7001",
"modifiedIndex": 351875651,
"createdIndex": 351875651
}
],
"modifiedIndex": 351873563,
"createdIndex": 351873563
}
}
```
...
```
Feb 19 23:24:25 core-02 etcd[1304]: 2015/02/19 23:24:25 etcd: member core-02 has previously registered with discovery service (https://discovery.etcd.io/2f0fc5714e64c9353da0670e6d820aa7), but the data-dir (/var/lib/etcd) on disk cannot be found.
```

**Comment by yichengq** [comment] 2015-02-23 07:47
@akaspin The discovery token looks good. I think `core-02` is stopped/killed in the bootstrap process, and etcd doesn't allow it. You need a new discovery token if this is happened.
If `core-02` is stopped without external reason, that might be a bug. If so, you can open a new issue with the log.

**Comment by xiang90** [comment] 2015-03-01 16:43
@spontaneous01 @yichengq I am closing this due to low activity. Feel free to reopen this if necessary.

**Closed** 2015-03-03 14:53 UTC

**Comment by willejs** [comment] 2015-03-09 17:03
I am seeing this too on 2.0.3. I have deleted the state directory cluster wide, and am trying to start the nodes with a new discovery key.
one node gets this
```
2015/03/09 16:59:04 discovery: found self 83b73ea2a028e138 in the cluster
2015/03/09 16:59:04 discovery: found 1 peer(s), waiting for 2 more
```
and the other two get this
```
member <unique host> has previously registered with discovery service (https://discovery.etcd.io/<disco key>), but the data-dir (/var/cache/etcd/state) on disk cannot be found.
```

When i curl the discovery end point, i only see one node in the list.

**Comment by willejs** [comment] 2015-03-09 18:28
I have changed the discovery url to http, and have run tcpdump and collected the calls made to the discovery service.
It appears that one node registers successfully. then the other two attempt to register with the same id, one is successful the other one isnt. 
I then restart all the nodes, and they all try and register with the same ID.

To me this seems strange, and would suggest that i am doing something wrong?
I am currently digging through the code to figure out how discovery works.

**Comment by willejs** [comment] 2015-03-09 22:35
@kelseyhightower I am experiencing this too, can you reopen, or should i start a new issue?

**Comment by kelseyhightower** [comment] 2015-03-09 22:40
@willejs Lets start a new issue.

**Comment by cfrett** [comment] 2015-04-04 22:06
I am also experiencing this on v2.0.8.
Did the new issue get created?

**Comment by cfrett** [comment] 2015-04-05 23:42
For me the problem was caused by ETCD_INITIAL_ADVERTISE_PEER_URLS listing more than one peer, as in static cluster configuration. Solved when setting each peer only to its own url.

Since etcd checks if the node is already registered by checking peer addresses, the error message should indicate that the address (instead of the peer name) have been previously registered because it creates confusion about the source of the issue.

**Comment by yichengq** [comment] 2015-04-07 18:35
@cfrett Could you give more details on how to reproduce your case in a new issue? We definitely want to improve it.
