### ISSUE TITLE
Panic: nodeToMember should never fail: raftAttributes key doesn't exist

### ISSUE THREAD

**Issue by ceecko** [coreos/etcd#5348] opened 2016-05-13 17:08 UTC
I'm trying to upgrade from etcd 2.1.3 to 2.2.5 but the migration fails. When I run v.2.2.5 over the v2.1.3 data directory, the following error is thrown:

```
etcdmain: etcd Version: 2.2.5
etcdmain: Git SHA: bc9ddf2
etcdmain: Go Version: go1.5.3
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: peerTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca = , trusted-ca =
etcdmain: listening for peers on https://0.0.0.0:2380
etcdmain: clientTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca = , trusted-ca
etcdmain: listening for client requests on https://0.0.0.0:4001
etcdserver: recovered store from snapshot at index 42924295
etcdserver: name = etcd0
etcdserver: data dir = /data/etcd0.etcd
etcdserver: member dir = /data/etcd0.etcd/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = https://example.com:4001
etcdserver: loaded cluster information from store: <nil>
etcdserver: restarting member cc6cc34f9b98d22c in cluster 5e5f1168c9014648 at commit index 42926187
raft: cc6cc34f9b98d22c became follower at term 1913
raft: newRaft cc6cc34f9b98d22c [peers: [cc6cc34f9b98d22c], term: 1913, commit: 42926187, applied: 42924295, lastindex: 42926187, last
etcdserver: nodeToMember should never fail: raftAttributes key doesn't exist
panic: nodeToMember should never fail: raftAttributes key doesn't exist
goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc8201ac980, 0xefb860, 0x22, 0xc8204f8560, 0x1, 0x1)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:
github.com/coreos/etcd/etcdserver.membersFromStore(0x7f42bb8613e0, 0xc8203c2d20, 0xc820401ce8, 0x7f42bb857798)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:388 +0x3b3
github.com/coreos/etcd/etcdserver.(*cluster).Recover(0xc820401cc0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:226 +0x9a
github.com/coreos/etcd/etcdserver.NewServer(0xc82038cfc0, 0xc82038cfe0, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:289 +0x3517
github.com/coreos/etcd/etcdmain.startEtcd(0xc8201f6000, 0x0, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:303 +0x1b51
github.com/coreos/etcd/etcdmain.Main()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:117 +0x212d
main.main()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
goroutine 44 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
goroutine 53 [select]:
github.com/coreos/etcd/raft.(*node).run(0xc820401e00, 0xc8203d89c0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:275 +0x1383
created by github.com/coreos/etcd/raft.RestartNode
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:190 +0x2e3
```

This occurs also after doing a `etcdctl backup` and trying to launch a new instance of the same etcd version.

Any ideas for how to solve this error to migrate to 2.2.5 and then to 2.3?

**Comment by ceecko** [comment] 2016-05-13 17:09
See also #3630 and #2297

**Comment by xiang90** [comment] 2016-05-13 17:11
@ceecko Can you try to stop all the members and start them with 2.3 again?

**Comment by ceecko** [comment] 2016-05-13 17:31
@xiang90 I tried 2.3.3 and got this

```
etcdmain: etcd Version: 2.3.3
etcdmain: Git SHA: c41345d
etcdmain: Go Version: go1.6.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: peerTLS: cert = /etc/ssl/etcd/etcd.example.com.crt, key = /etc/ssl/etcd/etcd.example.com.key.insecure, ca = , trusted-ca = /etc/ssl/etcd/ca.crt, client-cert-auth = true
etcdmain: listening for peers on https://0.0.0.0:2380
etcdmain: clientTLS: cert = /etc/ssl/etcd/etcd.example.com.crt, key = /etc/ssl/etcd/etcd.example.com.key.insecure, ca = , trusted-ca = /etc/ssl/etcd/ca.crt, client-cert-auth = true
etcdmain: listening for client requests on https://0.0.0.0:4001
etcdserver: recovered store from snapshot at index 42914294
etcdserver: name = eu1-sbg
etcdserver: force new cluster
etcdserver: data dir = /home/admin/etcd-backup-working
etcdserver: member dir = /home/admin/etcd-backup-working/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = https://eu1-sbg.etcd.example.com:4001
etcdserver: forcing restart of member 54aafd041d0001 in cluster 54aafd041d0002 at commit index 42924044
raft: 54aafd041d0001 became follower at term 1912
raft: newRaft 54aafd041d0001 [peers: [cc6cc34f9b98d22c], term: 1912, commit: 42924044, applied: 42914294, lastindex: 42924044, lastterm: 1912]
etcdserver: added member cc6cc34f9b98d22c [https://etcd.eu-1.example.com:2380] to cluster 54aafd041d0002 from store
etcdserver: set the cluster version to 2.1 from store
etcdserver: starting server... [version: 2.3.3, cluster version: 2.1]
etcdmain: failed to notify systemd for readiness: No socket
etcdmain: forgot to set Type=notify in systemd service file?
etcdserver: added member 40377592844e40d [https://167.114.248.178:2380] to cluster 54aafd041d0002
etcdserver: removed member 40377592844e40d from cluster 54aafd041d0002
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
etcdserver: skipped updating attributes of removed member 40377592844e40d
panic: runtime error: index out of range

goroutine 53 [running]:
panic(0xdc2620, 0xc820012080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/raft.(*raft).maybeCommit(0xc8200b0480, 0xc8203998f0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:382 +0x302
github.com/coreos/etcd/raft.(*raft).removeNode(0xc8200b0480, 0xcc6cc34f9b98d22c)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:842 +0x59
github.com/coreos/etcd/raft.(*node).run(0xc82059ec30, 0xc8200b0480)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:330 +0xca4
created by github.com/coreos/etcd/raft.RestartNode
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
```

I must have gotten into some weird state, because I have only one working copy of the data directory which starts etcd v2.1.3 correctly. But after I restart the same instance, I get the same raftAttribute error.

This is the output of starting form the working copy:

```
etcdmain: etcd Version: 2.1.3
etcdmain: Git SHA: 30801de
etcdmain: Go Version: go1.4.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: peerTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca =
etcdmain: listening for peers on https://0.0.0.0:2380
etcdmain: clientTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca =
etcdmain: listening for client requests on https://0.0.0.0:4001
etcdserver: recovered store from snapshot at index 42924295
etcdserver: name = etcd0
etcdserver: data dir = /data/etcd0.etcd
etcdserver: member dir = /data/etcd0.etcd/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = https://etcd.eu-1.evennode.com:4001
etcdserver: loaded cluster information from store: <nil>
etcdmain: etcd Version: 2.1.3
etcdmain: Git SHA: 30801de
etcdmain: Go Version: go1.4.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: peerTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca =
etcdmain: listening for peers on https://0.0.0.0:2380
etcdmain: clientTLS: cert = /etc/ssl/etcd/server.etcd.eu-1.crt, key = /etc/ssl/etcd/server.etcd.eu-1.key.insecure, ca =
etcdmain: listening for client requests on https://0.0.0.0:4001
etcdserver: recovered store from snapshot at index 42914294
etcdserver: name = etcd0
etcdserver: data dir = /data/etcd0.etcd
etcdserver: member dir = /data/etcd0.etcd/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = https://etcd.eu-1.evennode.com:4001
etcdserver: loaded cluster information from store: <nil>
etcdserver: restarting member cc6cc34f9b98d22c in cluster 5e5f1168c9014648 at commit index 42924042
raft: cc6cc34f9b98d22c became follower at term 1912
raft: newRaft cc6cc34f9b98d22c [peers: [cc6cc34f9b98d22c], term: 1912, commit: 42924042, applied: 42914294, lastindex: 42924042, lastterm: 1912]
etcdserver: starting server... [version: 2.1.3, cluster version: 2.1.0]
etcdserver: added member 40377592844e40d [https://167.114.248.178:2380] to cluster 5e5f1168c9014648
rafthttp: failed to dial 40377592844e40d on stream MsgApp v2 (dial tcp 167.114.248.178:2380: connection refused)
rafthttp: failed to dial 40377592844e40d on stream Message (dial tcp 167.114.248.178:2380: connection refused)
etcdserver: removed member 40377592844e40d from cluster 5e5f1168c9014648
raft: cc6cc34f9b98d22c is starting a new election at term 1912
raft: cc6cc34f9b98d22c became candidate at term 1913
raft: cc6cc34f9b98d22c received vote from cc6cc34f9b98d22c at term 1913
raft: cc6cc34f9b98d22c became leader at term 1913
raft: raft.node: cc6cc34f9b98d22c elected leader cc6cc34f9b98d22c at term 1913
etcdserver: published {Name:etcd0 ClientURLs:[https://etcd.eu-1.evennode.com:4001]} to cluster 5e5f1168c9014648
etcdserver: start to snapshot (applied: 42924295, lastsnap: 42914294)
etcdserver: saved snapshot at index 42924295
etcdserver: compacted raft log at 42919295
fileutil: purged file /data/etcd0.etcd/member/snap/0000000000000019-00000000028e35b2.snap successfully
```

And here's how I got to this strange situation:

1. I had running etcd 2.1.3
2. I wanted to add a new member
3. `etcdctl member add`
4. Started the new member (v2.1.3) with no data
5. I had wrong SSL certificate in the new member
6. Shutdown the new etcd
7. `etcdctl member remove` - this has failed because the cluster was not healthy
7. Fixed certificate
8. Started new member
9. Some weird error on the original etcd appeared (don't remember, but I could try to find out)
10. Stopped the new member
11. Restored original member from backup (this is the only working backup I have and cannot create any new backup because it always fails to start with the panic)
12. The output above is what happens when I start etcd from the only working backup

**Comment by xiang90** [comment] 2016-05-13 17:37
@ceecko OK... Seems like a few bad things happened in sequence... Let's try to use force-new-cluster to remove all the previous configuration? It might help with this situation. I am not exactly sure what really happened. https://github.com/coreos/etcd/blob/release-2.3/Documentation/admin_guide.md#restoring-a-backup

**Comment by ceecko** [comment] 2016-05-13 17:46
@xiang90 Probably too many things ;)
I've tried the -force-new-cluster before, but doesn't help either

```
/home/etcd/etcd-v2.3.3-linux-amd64/etcd  \
-name eu1-sbg  \
-data-dir /home/admin/etcd-backup-2.3  \
-client-cert-auth  \
-trusted-ca-file=/etc/ssl/etcd/ca.crt  \
-cert-file=/etc/ssl/etcd/etcd.example.com.crt \
-key-file=/etc/ssl/etcd/etcd.example.com.key.insecure  \
-peer-client-cert-auth  \
-peer-trusted-ca-file=/etc/ssl/etcd/ca.crt  \
-peer-cert-file=/etc/ssl/etcd/etcd.example.com.crt  \
-peer-key-file=/etc/ssl/etcd/etcd.example.com.key.insecure  \
-advertise-client-urls https://eu1-sbg.etcd.example.com:4001  \
-listen-client-urls https://0.0.0.0:4001  \
-listen-peer-urls https://0.0.0.0:2380  \
-initial-advertise-peer-urls https://eu1-sbg.etcd.example.com:2380  \
-initial-cluster-token etcd-cluster  \
-initial-cluster eu1-sbg=https://eu1-sbg.etcd.example.com:2380  \
-initial-cluster-state new -force-new-cluster

etcdmain: etcd Version: 2.3.3
etcdmain: Git SHA: c41345d
etcdmain: Go Version: go1.6.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: peerTLS: cert = /etc/ssl/etcd/etcd.example.com.crt, key = /etc/ssl/etcd/etcd.example.com.key.insecure, ca = , trusted-ca = /etc/ssl/etcd/ca.crt, client-cert-auth = true
etcdmain: listening for peers on https://0.0.0.0:2380
etcdmain: clientTLS: cert = /etc/ssl/etcd/etcd.example.com.crt, key = /etc/ssl/etcd/etcd.example.com.key.insecure, ca = , trusted-ca = /etc/ssl/etcd/ca.crt, client-cert-auth = true
etcdmain: listening for client requests on https://0.0.0.0:4001
etcdserver: recovered store from snapshot at index 42924295
etcdserver: name = eu1-sbg
etcdserver: force new cluster
etcdserver: data dir = /home/admin/etcd-backup-2.3
etcdserver: member dir = /home/admin/etcd-backup-2.3/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = https://eu1-sbg.etcd.example.com:4001
etcdserver: forcing restart of member 54ab3502af01 in cluster 54ab3502af02 at commit index 42926635
raft: 54ab3502af01 became follower at term 1913
raft: newRaft 54ab3502af01 [peers: [cc6cc34f9b98d22c], term: 1913, commit: 42926635, applied: 42924295, lastindex: 42926635, lastterm: 1913]
etcdserver: nodeToMember should never fail: raftAttributes key doesn't exist
panic: nodeToMember should never fail: raftAttributes key doesn't exist

goroutine 1 [running]:
panic(0xbeaea0, 0xc820752330)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc82015f060, 0x10510e0, 0x22, 0xc8204342d8, 0x1, 0x1)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x191
github.com/coreos/etcd/etcdserver.membersFromStore(0x7f85772badc8, 0xc8202d69a0, 0xc820750668, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:448 +0x3c7
github.com/coreos/etcd/etcdserver.(*cluster).Recover(0xc820750640)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:226 +0xce
github.com/coreos/etcd/etcdserver.NewServer(0xc8202548c0, 0xc820254978, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:334 +0x3c6f
github.com/coreos/etcd/etcdmain.startEtcd(0xc820079400, 0x0, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:302 +0x1b40
github.com/coreos/etcd/etcdmain.Main()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:118 +0x2142
main.main()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
```

**Comment by ceecko** [comment] 2016-05-13 17:47
I have tried to create the backup from v2.1.3 by using both etcdctl 2.1.3 and etcdctl 2.3.3

**Comment by xiang90** [comment] 2016-05-13 17:56
@ceecko 
Yea... The root cause is the bug we fixed in 2.3. That bug probably leads to something else that I am not aware of.

Is the data critical to you? Can you share it? If it is very critical to you and you can share it with me, probably I can try to recover the data for you with some "magic"... But still no guarantees...

**Comment by ceecko** [comment] 2016-05-13 19:28
@xiang90 Unfortunately it contains sensitive data, I can't share it. However we load data to etcd from a db and we wrote a script to reload the data into v2.3.3. Everything works fine now.

If there's anything I could provide to help you debug the issue, I'll be happy to help. Please let me know.

**Comment by ceecko** [comment] 2016-05-13 19:28
Thank you for your really quick help debugging btw.

**Comment by xiang90** [comment] 2016-05-13 19:30
@ceecko Yea. I think the root cause is fixed by https://github.com/coreos/etcd/pull/3657 . And to be honest with you, I do not have interest in investigating what other issues that bug might introduce into the cluster and led the cluster into an unrecoverable state. :(

**Closed** 2016-05-13 20:27 UTC
