### ISSUE TITLE
Watchers not getting updates

### ISSUE THREAD

**Issue by cw9** [coreos/etcd#8899] opened 2017-11-21 04:59 UTC
etcd Version: 3.2.4
Git SHA: c31bec0
Go Version: go1.8.3
Go OS/Arch: linux/amd64
Client version: 8ba2897a21e4fc51b298ca553d251318425f93ae

We are currently running a 5 node etcd cluster with 200k+ watchers, we have been rarely writing to the cluster. Today when we updated the value of a key, less than 1% of all the watchers did not receive the update, this is not the first time we observed this issue.

Some more debugging on a problematic application process shows this:
```
goroutine 79 [select, 4361 minutes]:
internal_code/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveSubstream(0xc4203615e0, 0xc420aa0000, 0xc42055ec00)
    /internal_code/vendor/github.com/coreos/etcd/clientv3/watch.go:591 +0x526
created by internal_code/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).run
    /internal_code/vendor/github.com/coreos/etcd/clientv3/watch.go:434 +0x47b
```
and we found this in the etcd log:
`Nov 18 01:54:51 {etcd_hostname} etcd[53042]: transport: http2Server.HandleStreams failed to read frame: read tcp {etcd_ip}:2379->{application_ip}:44460: read: connection timed out`

Not sure if this is red herring but the time of the error event does kinda match the waiting time on the goroutine. We do see this waiting time on a well-behaved box to be a few minutes and we think it's because we had `WithProgressNotify` option enabled by default, can you verify this theory?

We also see `read: connection timed out` and `read: connection reset by peer` pretty often in the logs.

We are not able to reproduce this issue, but restarting the problematic application could fix the issue. There are still a few applications running in the problematic state, they all seem to have connections to every etcd box, just won't be able to receive any updates. Is there any thing we could try to debug this?

**Comment by xiang90** [comment] 2017-11-21 15:58
We know there were some issues with clientv3 balancer that might cause the clients to be pending on bad connections.

We just released 3.2.10 to fix the client side issues we found.

However, we are not sure why you see `read: connection timed out` or `read: connection reset by peer`.

My suggestion is:

1. try hard to reproduce the problem
2. try to upgrade to 3.2.10 to see if it would solve the issue

**Comment by xiang90** [comment] 2017-11-21 16:00
> Not sure if this is red herring but the time of the error event does kinda match the waiting time on the goroutine. We do see this waiting time on a well-behaved box to be a few minutes and we think it's because we had WithProgressNotify option enabled by default, can you verify this theory?

maybe the connection set a timeout? and when notified, the read/write timeout already hit? what is the client configuration you use? i think you can easily reproduce this issue with a simple server and client.

**Comment by xichen2020** [comment] 2017-11-21 16:34
Thank you for the suggestions. We could try upgrading the clients to 3.2.10. Would it be necessary to upgrade the servers to 3.2.10 as well?

The `read: connection reset by peer` error is a red herring, it's primarily because client processes restarting.

I don't think we explicitly set a timeout on the connections, otherwise I'd imagine the client should get a watch error when the connection times out, in which case the goroutine watching the grpc stream shouldn't being blocked for 3 days, but I can double check.

**Comment by xichen2020** [comment] 2017-11-21 18:25
Just checked and verified that the reason why the goroutine was only blocked for a few minutes in the clients that did get the update was because we enabled "WithProgressNotify", so the well-behaved clients got notified approximately every 10 minutes even though there was no key/value updates in etcd. 

It seems the ill-behaved clients didn't get any notification updates since the etcd server it watches got the `http2Server.HandleStreams: ... read: connection timed out" error for the client, which led me to suspect that perhaps the GRPC watch stream was somehow leaked either on the client side or the server side for those ill-behaved clients, because no updates would be sent to those streams the clients were watching.

**Comment by xiang90** [comment] 2017-11-21 18:37
> Thank you for the suggestions. We could try upgrading the clients to 3.2.10. Would it be necessary to upgrade the servers to 3.2.10 as well?

It is mostly a client-side issue. You also need to update gRPC dependencies to 1.7.3. It would be great if you can update the server though.

> It seems the ill-behaved clients didn't get any progress notification updates since the etcd server it watches got the `http2Server.HandleStreams: ... read: connection timed out" error for the client, which led me to suspect that perhaps the GRPC watch stream was somehow leaked either on the client side or the server side for those ill-behaved clients, because no updates would be sent to those streams the clients were watching.

Right. There was a problem in the previous gRPC balancer implementation. I am not 100% sure the exact problem you hit is resolved. Thus, if you can reproduce it, we would like to take a look.

One thing I would suggest you look at is the slow watcher and watcher count metrics. If the slow watcher metrics are normal (at low count), we can probably rule out etcd server side issue (but it still can be a gRPC server side problem).

**Comment by xichen2020** [comment] 2017-11-21 18:47
Cool, we'll try upgrading the client and the server to 3.2.10 and perform the same operation that triggered this issue. I don't know how difficult it is to repro this locally since I'm not sure what condition triggered the server-side "read: connection timed out" error, which appeared to be the direct cause of this issue (?), and since not all clients are affected, i'd think it might be non-deterministic and thus difficult to repro locally, but I can give it a shot.

FYI, the slow watcher count is very low (mostly 0, occasionally 1).

**Comment by xiang90** [comment] 2017-11-21 18:48
@xichen2020 Great. We will also look into the problem in the next couple of days after thanks giving.

**Comment by xichen2020** [comment] 2017-11-21 18:56
I think the ill-behaved clients are still connected to the etcd servers (at least the connections are established in netstat). If it's the stream that's leaked but both sides are still connected, I don't think keepalives are going to help us in this particular case.

**Comment by xiang90** [comment] 2017-11-21 21:02
> If the stream is leaked but the connection is not closed

Possibly. It is also possible that the connection, the gRPC stream are all closed correctly, but the logical stream in client library fails to get closed.

**Comment by xiang90** [comment] 2017-11-21 21:33
@cw9 @xichen2020 

One quick question: are all the watchers on the same client blocked forever or just some of the watchers in the same client?

**Comment by xichen2020** [comment] 2017-11-21 21:34
All the watchers on the same client are blocked forever. No key value updates can be propagated to that client.

**Comment by xichen2020** [comment] 2017-11-25 20:58
cc @xiang90 @cw9 

Want to provide some update on this: we upgraded both our clients and our server to 3.2.10 and it seems to have helped. We performed the this operation that triggered this issue and this time it appears that there was one client that didn't get the latest update from etcd.

We saw the same issue with this ill-behaving client, i.e., the watchers on the client were blocked. However in this case, it appears that the client thinks it is still connected to all etcd servers (netstat on client side), but none of the etcd servers are actually connected to the client (netstat on server side). Looking further, in the server logs, all the servers got:
```
transport: http2Server.HandleStreams failed to read frame: read tcp server_ip:server_port->client_ip:client_port: read: connection timed out 
```
around the same time (a few minutes apart), which appeared to be when the watchers in the client stopped getting notification updates. I'm guessing this is a case where connections are closed on the server side but not on the client side, and since the client does not have keepAlives enabled, the client doesn't know the connection has been closed by the server and is therefor stuck forever.

I'll try enabling KeepAlives on the client side and see if that fixes the issue, unless you have other suggestions?

**Comment by xiang90** [comment] 2017-11-25 21:41
@xichen2020 

Please enable keepalive and give it another try.

**Comment by xiang90** [comment] 2017-11-25 21:44
>  We performed the this operation 

Did you find a way to reproduce the problem? We would like to know how to reproduce so that we can cover this case as an integration test. Thanks.

**Comment by xichen2020** [comment] 2017-11-25 22:26
I tried reproducing it locally but so far no luck, it appears to be somewhat nondeterministic. Will look into it a bit further.

**Comment by xiang90** [comment] 2017-11-26 03:16
@xichen2020 

I looked into the error you posted a little bit deeper today.

The error message is directly returned by the recv syscall (ETIMEDOUT as error 110: see https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/syscall/zerrors_linux_386.go#L1488).

Recv itself should not cause ETIMEDOUT apparently. Either a failure to send or a failure of TCP keepalive makes the server realize that connection is broken. 

If the client side however, I assume, only receives on the broken connection. So if the connection is not closed by the client-side (as you proved with netstats), the client side wont know its close anyway. Enabling client side keepalive will help on this case.

I am not entirely sure what caused the connection to be broken. However, since the error is returned from the kernel, I think there was something below etcd/gRPC layer.

**Comment by xichen2020** [comment] 2017-11-26 14:52
Possibly, I'm guessing some temporary network blip on the client-server link could have caused the broken connections but not 100% sure.

Just out of curiosity, it seems the keepAlives are done by sending periodic probes inside a goroutine rather than setting the keepAlive options on the TCP socket, any idea why?

**Comment by xiang90** [comment] 2017-11-26 17:21
> Just out of curiosity, it seems the keepAlives are done by sending periodic probes inside a goroutine rather than setting the keepAlive options on the TCP socket, any idea why?

This is a decision gRPC team made. So I can only speak of the reasoning behind it from my own experience.

Normally speaking, application layer keepalive is more reliable than TCP keepalive:
1. TCP keepalive behaviors differently across different platforms
2. TCP keepalive is not easy to config correctly
3. TCP keepalive cannot detect application layer "deadlock" or misbehavior; as long as the kernel still behaviors, the connection wont be closed

However, application layer keepalive might use more resources than TCP keepalive. Too frequent ping has to be avoided.

**Comment by xichen2020** [comment] 2017-11-26 19:27
That's fair, and thanks for the explanations. Seems the keepAlives are done per underlying connection rather than per gRPC stream, so the overhead is higher than socket-level probing but probably still manageable with not too frequent pings, although the clients probably need to add some jittering to avoid all clients sending keepAlive probes at the same time.

**Comment by xichen2020** [comment] 2017-12-04 23:12
Just to close the loop here: we performed a few more tests that previously triggered this issue after upgrading both the client and the server to 3.2.10 and adding client-side keepAlives, and did not see this issue come up since the change. As such, we consider this issue resolved with the version upgrade and the client-side keepAlives.

**Comment by xiang90** [comment] 2017-12-04 23:44
@xichen2020 Awesome. Thanks. I am closing this for now. If the same issue poped up again, please reopen. We will add more testing around watchers in the near future.

**Closed by xiang90** 2017-12-04 23:44 UTC
Labels: kind/bug
