### ISSUE TITLE
How long client can tolerate network interrupt

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#8941] opened 2017-11-30 10:45 UTC
My test case:
1. watch a key first, it is success. 
2. make network interrupt 20ms, interval 3s, repeat 10 times.
3. put key value interval 1s

Is there any parameter we can specify the time?

**Comment by xiang90** [comment] 2017-11-30 15:55
Can you share your test code? What is the version of the server and the client? How can we reproduce it?

**Comment by YuleiXiao** [comment] 2017-12-01 09:21
version: 3.2.7+git

I write a shell script to make network interrupt interval. test case and script run in the same time.

My test case code is like this. Put timeout is 3s.
```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/coreos/etcd/clientv3"
)

func main() {
	go put()
	watch()
}


func put() {
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"192.168.128.154:30296"}})
	if err != nil {
		fmt.Printf("new client fail. %s", err)
		return
	}

	for {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
		defer cancel()
		if _, err := cli.Put(ctx, "/test/key", time.Now().String()); err != nil {
			fmt.Printf("Put fail. %s\n", err)
		}
		time.Sleep(time.Second)
	}

}

func watch() {
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"192.168.128.154:30296"}})
	if err != nil {
		fmt.Printf("new client fail. %s", err)
		return
	}

	ch := cli.Watch(context.Background(), "/test/key", clientv3.WithPrevKV())
	for {
		select {
		case resp, ok := <-ch:
			if !ok {
				fmt.Printf("closed\n")
				return
			}
			fmt.Printf("resp: %#v\n", resp)
		}
	}
}
```

ifdown shell script, make network interupt 20ms
```
for ((i=0;i<100;i++))
do
        echo "start down"
        sudo ifdown enp130s0f0
        usleep 20000
        echo "start up"
        sudo ifup enp130s0f0
        sleep 3
done
```

test result, interrupt time is only 20ms, less then 3s, I thought it should be success. But put always fail after script run.
```
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:45, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc42023a1a0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:46, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc42023a1e0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:47, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc42023a2e0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:48, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc4201e21c0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:49, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc4201e22c0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:50, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc4202b20a0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
resp: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0xcdf818194e3a8c32, MemberId:0x8e9e05c52164694d, Revision:51, RaftTerm:0x2}, Events:[]*clientv3.Event{(*clientv3.Event)(0xc42023a4a0)}, CompactRevision:0, Canceled:false, Created:false, closeErr:error(nil), cancelReason:""}
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded
Put fail. context deadline exceeded

```

**Comment by YuleiXiao** [comment] 2017-12-04 03:08
I try test case on master, it is the same. @xiang90

**Comment by YuleiXiao** [comment] 2017-12-06 01:41
@xiang90 @gyuho I use tcpdump to  capture package in etcd server side, there is no package from client. It looks like rpc message is dropped in somewhere.

**Comment by xiang90** [comment] 2017-12-16 20:14
@YuleiXiao This is absolutely something we want to solve (or at least understand it and document the behavior). Can you help to dig into it more? I bet the problem is at the client side. Can you try to read the client code and see if there is any issue with it?

**Comment by YuleiXiao** [comment] 2017-12-18 03:10
OK, I am trying. @xiang90

**Comment by xiang90** [comment] 2017-12-23 00:00
@YuleiXiao Any progress?

**Comment by YuleiXiao** [comment] 2017-12-25 11:51
@xiang90 sorry for late. I was analyzing this issue these days. I found maybe it is not code problem. I tested it on virtual and physical machines, just ```ping``` between them and I found network recover time is not expected. Sometimes the command ```sudo ifup enp130s0f0``` execute time is over 2s on virtual machines, but physical it better. And in ```ping``` result(down 2s, up 2s), from network interrupted recover, sometimes more than 7s.

**Comment by xiang90** [comment] 2017-12-25 12:37
@YuleiXiao Can you try to increase the put timeout to > 7s?

**Comment by YuleiXiao** [comment] 2017-12-25 13:18
@xiang90 Yes, I had try it. I set timeout 10s, down 2s and up 2s, it put success on physical machines but fail on virtual machines.

**Comment by xiang90** [comment] 2017-12-25 14:18
try to bump the timeout again? I want to understand the problem with vm
before we close this issue.

**Comment by YuleiXiao** [comment] 2017-12-26 07:48
@xiang90 I try 10s/15s/20s in virtual machines,  they are not all succeed. About half fail.

**Comment by xiang90** [comment] 2017-12-28 03:34
Can you investigate a little bit why half of them fail?

**Comment by xiang90** [comment] 2018-01-17 22:56
@YuleiXiao kindly ping.

**Comment by YuleiXiao** [comment] 2018-01-18 03:29
@xiang90 I try to find the reason, but still not find it out.

**Comment by xiang90** [comment] 2018-01-23 22:25
I am going to close this for now. It seems like this is more a vm networking stack issue than an etcd issue.

**Closed by xiang90** 2018-01-23 22:25 UTC

**Comment by gyuho** [comment] 2018-01-23 22:31
Yes, let's revisit this when we hit this again.
