### ISSUE TITLE
etcd2 secure cluster won't finish configuration

### ISSUE THREAD

**Issue by vdemedes** [coreos/etcd#3027] opened 2015-06-20 12:06 UTC
Hello CoreOS,

I am experiencing a problem with configuring secure etcd2 cluster on coreos stable channel.
I used this cloud-config configuration for etcd (v1) previously and everything worked great:

```
#cloud-config

coreos:
  etcd:
    discovery: fresh discovery url
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    ca-file: /home/core/.etcd-ca/ca.crt
    cert-file: /home/core/.etcd-ca/node.crt
    key-file: /home/core/.etcd-ca/node.key
  fleet:
    public-ip: $private_ipv4
    etcd-servers: https://$private_ipv4:4001
    etcd-cafile: /home/core/.etcd-ca/ca.crt
    etcd-certfile: /home/core/.etcd-ca/node.crt
    etcd-keyfile: /home/core/.etcd-ca/node.key
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```

`ca.crt`, `node.crt` and `node.key` are certificates generated by etcd-ca tool. `ca.crt` is the same on each cluster machine. `node.crt` and `node.key` are generated on each machine upon first boot.

But when using the following configuration and latest etcd2 (coreos stable channel) etcd2.service can't complete configuration (logs later):

```
#cloud-config

coreos:
  etcd2:
    discovery: fresh discovery url
    listen-client-urls: https://$private_ipv4:2379,https://$private_ipv4:4001
    listen-peer-urls: https://$private_ipv4:2380,https://$private_ipv4:7001
    initial-advertise-peer-urls: https://$private_ipv4:2380,https://$private_ipv4:7001
    advertise-client-urls: https://$private_ipv4:2379,https://$private_ipv4:4001
    client-cert-auth: true
    ca-file: /home/core/.etcd-ca/ca.crt
    cert-file: /home/core/.etcd-ca/node.crt
    key-file: /home/core/.etcd-ca/node.key
    peer-client-cert-auth: true
    peer-ca-file: /home/core/.etcd-ca/ca.crt
    peer-cert-file: /home/core/.etcd-ca/node.crt
    peer-key-file: /home/core/.etcd-ca/node.key
  fleet:
    public-ip: $private_ipv4
    etcd-servers: https://$private_ipv4:2379,https://$private_ipv4:4001
    etcd-cafile: /home/core/.etcd-ca/ca.crt
    etcd-certfile: /home/core/.etcd-ca/node.crt
    etcd-keyfile: /home/core/.etcd-ca/node.key
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```

Output of `journalctl -u etcd2`:

```
Started etcd2.
Starting etcd2...
2015/06/20 11:54:59 etcd: peerTLS: cert = /home/core/.etcd-ca/node.crt, key = /home/core/.etcd-ca/node.key, ca = /home/core/.etcd-ca/ca.crt
2015/06/20 11:55:00 etcd: listening for peers on https://10.132.3.134:2380
2015/06/20 11:55:01 etcd: listening for peers on https://10.132.3.134:7001
2015/06/20 11:55:01 etcd: clientTLS: cert = /home/core/.etcd-ca/node.crt, key = /home/core/.etcd-ca/node.key, ca = /home/core/.etcd-ca/ca.crt
2015/06/20 11:55:01 etcd: listening for client requests on https://10.132.3.134:2379
2015/06/20 11:55:02 etcd: listening for client requests on https://10.132.3.134:4001
2015/06/20 11:55:02 etcdserver: datadir is valid for the 2.0.1 format
2015/06/20 11:55:03 discovery: found self 3fd4d50d8422fd19 in the cluster
2015/06/20 11:55:03 discovery: found 1 peer(s), waiting for 2 more
2015/06/20 11:56:03 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 2s
2015/06/20 11:56:05 discovery: found self 3fd4d50d8422fd19 in the cluster
2015/06/20 11:56:05 discovery: found 1 peer(s), waiting for 2 more
2015/06/20 11:56:25 discovery: found peer 25e9aafdf9fbecd0 in the cluster
2015/06/20 11:56:25 discovery: found 2 peer(s), waiting for 1 more
2015/06/20 11:57:14 discovery: found peer ae109ba6f565132 in the cluster
2015/06/20 11:57:14 discovery: found 3 needed peer(s)
2015/06/20 11:57:14 etcdserver: name = b96a1231014b4b55b122f1fd8efb6ce5
2015/06/20 11:57:14 etcdserver: data dir = /var/lib/etcd2
2015/06/20 11:57:14 etcdserver: member dir = /var/lib/etcd2/member
2015/06/20 11:57:14 etcdserver: heartbeat = 100ms
2015/06/20 11:57:14 etcdserver: election = 1000ms
2015/06/20 11:57:14 etcdserver: snapshot count = 10000
2015/06/20 11:57:14 etcdserver: discovery URL= https://discovery.etcd.io/f9ba6cc3ab455c43bf8402ef7421e3cc
2015/06/20 11:57:14 etcdserver: advertise client URLs = https://10.132.3.134:2379,https://10.132.3.134:4001
2015/06/20 11:57:14 etcdserver: initial advertise peer URLs = https://10.132.3.134:2380,https://10.132.3.134:7001
2015/06/20 11:57:14 etcdserver: initial cluster = 96496156fa6243ae8e23f9cdf0ed2671=https://10.132.116.46:2380,96496156fa6243ae8e23f9cdf0ed2671=https://10.132.116.46:7001,b96a1231014b4b55b122f1fd8efb6ce5=https://10.132.3.134:2380,b96a1231014b4b55b122f1fd8efb6ce5=https://10.132.3.134:7001,dc32179f2e9e49eabfb55231ffecb613=https://10.132.228.207:2380,dc32179f2e9e49eabfb55231ffecb613=https://10.132.228.207:7001
2015/06/20 11:57:14 etcdserver: start member 3fd4d50d8422fd19 in cluster 17882326f575cbbf
2015/06/20 11:57:14 raft: 3fd4d50d8422fd19 became follower at term 0
2015/06/20 11:57:14 raft: newRaft 3fd4d50d8422fd19 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/20 11:57:14 raft: 3fd4d50d8422fd19 became follower at term 1
2015/06/20 11:57:15 etcdserver: added member ae109ba6f565132 [https://10.132.116.46:2380 https://10.132.116.46:7001] to cluster 17882326f575cbbf
2015/06/20 11:57:16 etcdserver: added member 25e9aafdf9fbecd0 [https://10.132.228.207:2380 https://10.132.228.207:7001] to cluster 17882326f575cbbf
2015/06/20 11:57:16 etcdserver: added local member 3fd4d50d8422fd19 [https://10.132.3.134:2380 https://10.132.3.134:7001] to cluster 17882326f575cbbf
2015/06/20 11:57:16 raft: 3fd4d50d8422fd19 [term: 1] received a MsgVote message with higher term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:16 raft: 3fd4d50d8422fd19 became follower at term 2
2015/06/20 11:57:16 raft: 3fd4d50d8422fd19 [logterm: 1, index: 3, vote: 0] voted for ae109ba6f565132 [logterm: 1, index: 3] at term 2
2015/06/20 11:57:17 raft.node: 3fd4d50d8422fd19 elected leader ae109ba6f565132 at term 2
2015/06/20 11:57:18 rafthttp: starting client stream to ae109ba6f565132 at term 2
2015/06/20 11:57:19 etcdserver: publish error: etcdserver: request timed out
2015/06/20 11:57:22 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/20 11:57:23 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/20 11:57:24 etcdserver: publish error: etcdserver: request timed out
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 is starting a new election at term 2
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 became candidate at term 3
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 3
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 3
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 3
2015/06/20 11:57:28 raft.node: 3fd4d50d8422fd19 lost leader ae109ba6f565132 at term 3
2015/06/20 11:57:28 rafthttp: encountered error reading the client log stream: read tcp 10.132.116.46:2380: use of closed network connection
2015/06/20 11:57:28 rafthttp: client streaming to ae109ba6f565132 at term 2 has been stopped
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [term: 3] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [term: 3] ignored a MsgApp message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [term: 3] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:28 raft: 3fd4d50d8422fd19 [term: 3] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:29 raft: 3fd4d50d8422fd19 is starting a new election at term 3
2015/06/20 11:57:29 raft: 3fd4d50d8422fd19 became candidate at term 4
2015/06/20 11:57:29 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 4
2015/06/20 11:57:29 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 4
2015/06/20 11:57:29 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 4
2015/06/20 11:57:29 etcdserver: publish error: etcdserver: request timed out
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [term: 4] ignored a MsgApp message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [term: 4] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [term: 4] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [term: 4] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 is starting a new election at term 4
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 became candidate at term 5
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 5
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 5
2015/06/20 11:57:30 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 5
2015/06/20 11:57:31 raft: 3fd4d50d8422fd19 [term: 5] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:31 raft: 3fd4d50d8422fd19 [term: 5] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:31 raft: 3fd4d50d8422fd19 [term: 5] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:31 raft: 3fd4d50d8422fd19 [term: 5] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 is starting a new election at term 5
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 became candidate at term 6
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 6
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 6
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 6
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 [term: 6] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 [term: 6] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:32 raft: 3fd4d50d8422fd19 [term: 6] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 [term: 6] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 is starting a new election at term 6
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 became candidate at term 7
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 7
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 7
2015/06/20 11:57:33 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 7
2015/06/20 11:57:34 raft: 3fd4d50d8422fd19 [term: 7] ignored a MsgVoteResp message with lower term from 25e9aafdf9fbecd0 [term: 3]
2015/06/20 11:57:34 raft: 3fd4d50d8422fd19 [term: 7] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:34 raft: 3fd4d50d8422fd19 [term: 7] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:34 raft: 3fd4d50d8422fd19 [term: 7] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:34 raft: 3fd4d50d8422fd19 [term: 7] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:35 etcdserver: publish error: etcdserver: request timed out
2015/06/20 11:57:35 raft: 3fd4d50d8422fd19 is starting a new election at term 7
2015/06/20 11:57:35 raft: 3fd4d50d8422fd19 became candidate at term 8
2015/06/20 11:57:35 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 8
2015/06/20 11:57:35 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 8
2015/06/20 11:57:35 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 8
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [term: 8] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [term: 8] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [term: 8] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [term: 8] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 is starting a new election at term 8
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 became candidate at term 9
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 9
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 9
2015/06/20 11:57:36 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 9
2015/06/20 11:57:37 raft: 3fd4d50d8422fd19 [term: 9] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:37 raft: 3fd4d50d8422fd19 [term: 9] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:37 raft: 3fd4d50d8422fd19 [term: 9] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:37 raft: 3fd4d50d8422fd19 [term: 9] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 is starting a new election at term 9
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 became candidate at term 10
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 10
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 10
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 10
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [term: 10] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [term: 10] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [term: 10] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:38 raft: 3fd4d50d8422fd19 [term: 10] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 is starting a new election at term 10
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 became candidate at term 11
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 11
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 11
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 11
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:39 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgVoteResp message with lower term from 25e9aafdf9fbecd0 [term: 4]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgVoteResp message with lower term from 25e9aafdf9fbecd0 [term: 6]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgVoteResp message with lower term from 25e9aafdf9fbecd0 [term: 5]
2015/06/20 11:57:40 etcdserver: publish error: etcdserver: request timed out
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [term: 11] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 is starting a new election at term 11
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 became candidate at term 12
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 12
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 12
2015/06/20 11:57:40 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 12
2015/06/20 11:57:41 raft: 3fd4d50d8422fd19 [term: 12] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:41 raft: 3fd4d50d8422fd19 [term: 12] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:41 raft: 3fd4d50d8422fd19 [term: 12] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:41 raft: 3fd4d50d8422fd19 [term: 12] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 is starting a new election at term 12
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 became candidate at term 13
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 received vote from 3fd4d50d8422fd19 at term 13
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to ae109ba6f565132 at term 13
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [logterm: 2, index: 34] sent vote request to 25e9aafdf9fbecd0 at term 13
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [term: 13] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [term: 13] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [term: 13] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:42 raft: 3fd4d50d8422fd19 [term: 13] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
2015/06/20 11:57:43 raft: 3fd4d50d8422fd19 [term: 13] ignored a MsgHeartbeat message with lower term from ae109ba6f565132 [term: 2]
```

and it goes on and on like that.

Each machine has access to each other (ping, ssh, even etcdctl to another host). `etcdctl cluster-health` shows `cluster is unhealthy`.

Also must mention, without certificates and https everything works smoothly. But if there was something wrong with certificates, etcd v1 would not work also, but it does.

More info:
```
$ etcd2 --version
etcd version 2.0.10
$ etcdctl --version
etcdctl version 2.0.10
$ fleet -version
fleetd version 0.10.2
```

Did something change in security area of etcd v2?

Thank you for the awesome tools!

**Comment by yichengq** [comment] 2015-06-20 16:17
@vdemedes This is a duplicate of https://github.com/coreos/etcd/issues/2539. We fixed this in master, and is released in 2.1.0-alpha.1, which could handle this well.

**Comment by vdemedes** [comment] 2015-06-21 10:05
@yichengq Ok, good to know. When should it approximately land in coreos stable channel?

**Closed** 2015-06-21 11:32 UTC

**Comment by yichengq** [comment] 2015-06-22 17:15
@vdemedes My guess is probably 2-3 months(just guess!). etcd 2.1 is under testing and final improvements today, and it also takes time for coreos to upgrade to etcd2.1.
