### ISSUE TITLE
quay.io/coreos/etcd:v2.0.12 docker image launch failed on Fedora 22, docker 1.6.0

### ISSUE THREAD

**Issue by dove-young** [coreos/etcd#3054] opened 2015-06-25 09:24 UTC
It just crashes when I launch it in Fedora 22 x86_64. 
```

[root@xxx]# docker images 
REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
quay.io/coreos/etcd             v2.0.12             7f7c57dd55fc        8 days ago          12.83 MB
gcr.io/google_containers/etcd   2.0.9               b6b9a86dc06a        11 weeks ago        12.82 MB
quay.io/coreos/etcd             v2.0.9              a24d15817279        11 weeks ago        12.8 MB
[root@xxx]# 

[root@xxx]# docker history quay.io/coreos/etcd:v2.0.12
IMAGE               CREATED             CREATED BY                                      SIZE
7f7c57dd55fc        8 days ago          /bin/sh -c #(nop) ENTRYPOINT [/etcd]            0 B
e217c18bed2f        8 days ago          /bin/sh -c #(nop) EXPOSE map[4001/tcp:{} 7001   0 B
2ae64aa8466e        8 days ago          /bin/sh -c #(nop) ADD file:94fab2949e5fe6b87d   6.186 MB
6739c545b291        8 days ago          /bin/sh -c #(nop) ADD file:b85894357101fc409e   6.646 MB
6b8fdec062a8        8 days ago                                                          0 B
[root@xxx]# 


[root@xxx]# docker run -it --name=test  quay.io/coreos/etcd:v2.0.12  /bin/bash                                                                      
Timestamp: 2015-06-26 01:14:34.192254727 +0800 CST
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279243135438/_tmp.tar -C /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223FATA[0001] Error response from daemon: : exit status 2  
[root@xxx]# 

```

Here you can get log from it

```

[root@xxx]# docker ps -a
CONTAINER ID        IMAGE                                 COMMAND             CREATED             STATUS              PORTS               NAMES
54a6f634e9db        quay.io/coreos/etcd:v2.0.12           "/etcd /bin/bash"   34 seconds ago                                              test 

[root@xxx]# docker logs test
Timestamp: 2015-06-26 01:14:34.192254727 +0800 CST
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279243135438/_tmp.tar -C /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
[root@xxx]# 

```

And docker inspect result

```
[{
    "AppArmorProfile": "",
    "Args": [
        "/bin/bash"
    ],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": true,
        "AttachStdout": true,
        "Cmd": [
            "/bin/bash"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/etcd"
        ],
        "Env": [
            "HOME=/",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "ExposedPorts": {
            "2379/tcp": {},
            "2380/tcp": {},
            "4001/tcp": {},
            "7001/tcp": {}
        },
        "Hostname": "54a6f634e9db",
        "Image": "quay.io/coreos/etcd:v2.0.12",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": true,
        "PortSpecs": null,
        "StdinOnce": true,
        "Tty": true,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-06-25T17:14:33.845930891Z",
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "MountRun": true,
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/hostname",
    "HostsPath": "/var/lib/docker/containers/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/hosts",
    "Id": "54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279",
    "Image": "7f7c57dd55fca4ad32f2596d79e07295e096a02ac042e47cc2fe0a34e544a12a",
    "LogPath": "/var/lib/docker/containers/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279-json.log",
    "MountLabel": "",
    "Name": "/test",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/etcd",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "[8] System error: [/usr/bin/tar -cf /var/lib/docker/tmp/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279243135438/_tmp.tar -C /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/54a6f634e9dba4fadffbc1dd9c1330cad2fb91d79c2647bdf7354fe3c1f7f279/rootfs/tmp: Cannot open: No such file or directory\n/usr/bin/tar: Error is not recoverable: exiting now\n: exit status 2",
        "ExitCode": -1,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "0001-01-01T00:00:00Z"
    },
    "Volumes": {},
    "VolumesRW": {},
    "VolumesRelabel": {}
}
]

```

Here is the test environment

```

[root@xxx]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 9d26a07/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 9d26a07/1.6.0
OS/Arch (server): linux/amd64
[root@xxx]#




[root@xxx]# uname -a
Linux tivx93 4.0.4-301.fc22.x86_64 #1 SMP Thu May 21 13:10:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@xxx]# cat /etc/issue
Fedora release 22 (Twenty Two)
Kernel \r on an \m (\l)

[root@xxx]# 

```

**Comment by yichengq** [comment] 2015-06-25 15:05
Could you try to download the binary here(https://github.com/coreos/etcd/releases/tag/v2.0.12) and run it directly? So we could know whether it is the binary problem or a docker problem.

I just started it on ubuntu 14.04 using `docker run -p 4001:4001 -v /usr/share/ca-certificates/:/etc/ssl/certs quay.io/coreos/etcd:v2.0.12`.

**Comment by xiang90** [comment] 2015-07-03 18:54
@dove-young I am closing this due to low activity. Can you please try what @yichengq suggested? If you still have the same problem, feel free to reopen the issue. Thanks!

**Closed by xiang90** 2015-07-03 18:54 UTC

**Comment by nak3** [comment] 2015-07-11 08:03
I guess the root cause is same with:
https://bugzilla.redhat.com/show_bug.cgi?id=1213258

Although I also hit same issue with docker v1.6.0 (included in Fedora), I could fix it with v.1.6.2.
I hope this information will help you.
