### ISSUE TITLE
2 out of 5 cluster members show high CPU usage

### ISSUE THREAD

**Issue by aniketapte** [coreos/etcd#5473] opened 2016-05-27 19:13 UTC
I have a 5-member etcd2 cluster, with 2 of them showing high CPU usage.

Attached files show CPU usage as reported by top at 2-second intervals over a 4-minute period for all 5 members. Files named member{1,2,3} show max usage of 200%, member4 shows as much as 1800% and member5 as high as 2800%. All are running on machines with 48 CPUs.

Is CPU usage as high as this expected? Let me know if any more information is needed.

[member1_etcd.txt](https://github.com/coreos/etcd/files/287215/member1_etcd.txt)
[member2_etcd.txt](https://github.com/coreos/etcd/files/287214/member2_etcd.txt)
[member3_etcd.txt](https://github.com/coreos/etcd/files/287211/member3_etcd.txt)
[member4_etcd.txt](https://github.com/coreos/etcd/files/287212/member4_etcd.txt)
[member5_etcd.txt](https://github.com/coreos/etcd/files/287213/member5_etcd.txt)

**Comment by aniketapte** [comment] 2016-05-27 19:14
$ etcd2 --version
etcd Version: 2.2.0
Git SHA: e4561dd
Go Version: go1.4.2
Go OS/Arch: linux/amd64

**Comment by xiang90** [comment] 2016-05-27 20:00
@aniketapte The cluster was serving loads from clients? Without knowing the load distribution, it is hard to tell whether this is normal or not. Maybe your applications just sent more requests or more heavy requests to the last two members? Maybe etcd was doing something strange? So yes, we need more information about your application workload.

**Comment by gyuho** [comment] 2016-05-28 03:34
@aniketapte Also etcd log files would help as well. Thanks.

**Comment by aniketapte** [comment] 2016-05-31 18:51
@xiang90 The cluster is indeed serving load. There are about 100 etcd proxies connected to this cluster. All these 105 hosts (100 Proxies + 5 members) have fleet running on them. Fleet is configured to use 127.0.0.1:2379 as etcd endpoint, so I guess the fleet connections should be spread evenly across the 5 members.

High CPU usage has been observed when etcd member got network disconnect, then could not join back to the cluster, and had to be manually added back (via etcdctl member remove/add).

Will collect log file info.

**Comment by xiang90** [comment] 2016-05-31 18:52
@aniketapte Is there a way to reproduce the issue?

**Comment by aniketapte** [comment] 2016-05-31 18:58
@xiang90 Not sure really. There was a network issue in our datacenter which caused a few cluster members to be disconnected. After the issue was fixed, cluster health reported that one member is unhealthy. So we followed reconfiguration guide to remove and add this member back to the cluster. This is the member that has the high CPU usage.

**Comment by aniketapte** [comment] 2016-05-31 19:52
OK, so we experienced a network issue in our DC again, and after fixing it the same cluster member is again showing unhealthy. I restarted etcd2 and captured logs on all 5 nodes.

$ etcdctl --endpoint=https://127.0.0.1:2379 --ca-file=/etc/ca.crt --cert-file=/etc/etcd_client.crt --key-file=/etc/etcd_client.key cluster-health
member 3f595eb98ddc6057 is unhealthy: got unhealthy result from https://10.101.26.1:2379
member 587a9be10a641b35 is healthy: got healthy result from https://10.101.25.1:2379
member 6ec7f404c5e613d9 is healthy: got healthy result from https://10.102.25.1:2379
member a543a21eb7369eb0 is healthy: got healthy result from https://10.100.26.1:2379
member e9e070290b709056 is healthy: got healthy result from https://10.100.25.1:2379
cluster is healthy

Logs for all 5 members are attached. The log for the bad member (3f595eb98ddc6057) is for a 10 minute period as it is mostly reporting timeout errors.

[node_3f595eb98ddc6057_10min.txt](https://github.com/coreos/etcd/files/292009/node_3f595eb98ddc6057_10min.txt)
[node_6ec7f404c5e613d9.txt](https://github.com/coreos/etcd/files/292007/node_6ec7f404c5e613d9.txt)
[node_587a9be10a641b35.txt](https://github.com/coreos/etcd/files/292005/node_587a9be10a641b35.txt)
[node_a543a21eb7369eb0.txt](https://github.com/coreos/etcd/files/292006/node_a543a21eb7369eb0.txt)
[node_e9e070290b709056.txt](https://github.com/coreos/etcd/files/292008/node_e9e070290b709056.txt)

**Comment by xiang90** [comment] 2016-06-01 02:31
> The log for the bad member (3f595eb98ddc6057) is for a 10 minute period as it is mostly reporting timeout errors.

The bad member could not recover even after the network issue got resolved and the process itself got restarted?

**Comment by xiang90** [comment] 2016-06-01 02:41
@aniketapte I read through the code (almost got brain damaged since I have to guess for the root cause...). The only explanation that makes sense to me is that the bad node was experiencing very high client load. And a critical go-routine was consistently got blocked by routines that serving client requests for one to two minutes. I do not even trust this explanation too much...

If you can somehow reproduce this issue, it would be very helpful. Then we can add some logging to verify the assumption. Or I cannot see a way to get this 100% fixed.

**Comment by aniketapte** [comment] 2016-06-01 21:23
@xiang90 On the bad node, I can see a large number of CLOSE_WAIT connections (consistently between 800-1000). Also, netstat reports many connections with a large Recv-Q value (as high as 1988 which I think is the limit). We're trying to figure out what is causing those connections.

From what I understand, the etcd proxies will load-balance the connections between the members. So there shouldn't be so many connections to just one member, right?

[etcd_close_wait.txt](https://github.com/coreos/etcd/files/294394/etcd_close_wait.txt)
[etcd_recvq.txt](https://github.com/coreos/etcd/files/294393/etcd_recvq.txt)

**Comment by xiang90** [comment] 2016-06-01 21:57
> So there shouldn't be so many connections to just one member, right?

That actually depends on the application. Proxies balance load based on clients not connections. So if some clients send a lot of requests, then one member might suffer from an extensive amount of connections. So probably you want to look at the number of source ip, not source ip:port combination.

**Comment by philips** [comment] 2016-06-03 04:41
@aniketapte As we continue to root cause this issue with etcd one potential workaround would be to reduce the load on the cluster. 

This can be done by adjusting the various parameters that cause fleet to talk to etcd: https://coreos.com/fleet/docs/latest/deployment-and-configuration.html#general-options

A starting point would be tripling all of the values:

```
FLEET_ENGINE_RECONCILE_INTERVAL=8
FLEET_AGENT_TTL=60s
FLEET_ETCD_REQUEST_TIMEOUT=3.0
```

**Comment by xiang90** [comment] 2016-06-17 18:12
I am closing this out due to low activity. Please repoen if you have any follow-up questions to the same issue.

**Closed by xiang90** 2016-06-17 18:12 UTC
