### ISSUE TITLE
grpc gateway get error:  grpc: the connection is unavailable

### ISSUE THREAD

**Issue by ffffproton** [coreos/etcd#8002] opened 2017-05-29 12:39 UTC
do:
`curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "Zm9v"}'`
get:
`{"error":"grpc: the connection is unavailable","code":14}`

log:
```
May 29 19:40:30 platform1.vm bash[14858]: proto: no coders for int
May 29 19:45:20 platform1.vm bash[14858]: proto: no coders for int
May 29 19:58:41 platform1.vm bash[14858]: proto: no coders for int
May 29 20:00:43 platform1.vm bash[14858]: proto: no coders for int
```

my version:
```
etcd Version: 3.1.7
Git SHA: 43b7507
Go Version: go1.7.4
Go OS/Arch: linux/amd64
```

**Comment by hexfusion** [comment] 2017-05-30 00:14
FWIW I can not replicate this with 3.1.7 only difference being the go version

```
#!/bin/bash

ETCD_VER=v3.1.7

# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/coreos/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}

rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
rm -rf /tmp/test-etcd && mkdir -p /tmp/test-etcd

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/test-etcd --strip-components=1

 /tmp/test-etcd/etcd --debug=true &

curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "Zm9v"}'
```
```
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"}}
```
```
etcd Version: 3.1.7
Git SHA: 43b7507
Go Version: go1.7.5
Go OS/Arch: linux/amd64
```

**Comment by ffffproton** [comment] 2017-05-30 03:33
@hexfusion  I follow your step, it works, but if I add  --listen-client-urls=http://0.0.0.0:2379,
The question appear:
```
curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "Zm9v"}'
{"error":"grpc: the connection is unavailable","code":14}
```

**Comment by hexfusion** [comment] 2017-05-30 12:32
@ffffproton Seems related to https://github.com/coreos/etcd/issues/7961 have you tested any of the 3.2 releases?

**Comment by heyitsanthony** [comment] 2017-05-30 16:55
can't reproduce either.
@ffffproton full etcd server logs? what linux distribution / version?

**Comment by ffffproton** [comment] 2017-05-30 18:41
@hexfusion  Yes, Now I change http://0.0.0.0:2379 to http://172.18.129.235:2379, It works.
My linux distribution is centos-7.3.

**Comment by heyitsanthony** [comment] 2017-05-31 03:51
@ffffproton do you have the full server logs from when etcd is giving `grpc: the connection is unavailable`?

I can get `proto: no coders for int` from malformed inputs in 3.1.7 but not 3.2.0. I can't seem to reproduce `{"error":"grpc: the connection is unavailable","code":14}`, even on a centos 7.3 vm.

**Comment by dopykuh** [comment] 2017-05-31 09:25
I could verify this.

**Comment by heyitsanthony** [comment] 2017-05-31 16:02
@dopykuh OK, how can I reliably reproduce this?

**Comment by xiang90** [comment] 2017-12-23 00:31
I am closing this out due to low activity.

**Closed by xiang90** 2017-12-23 00:31 UTC
