### ISSUE TITLE
auth: TestRoleAdd fails with timeout

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5851] opened 2016-07-02 06:50 UTC
```
2016-07-02 00:06:08.693924 N | auth: added a new user: foo
2016-07-02 00:06:11.149224 N | auth: added a new user: root
2016-07-02 00:06:11.149343 N | auth: Role root is created
2016-07-02 00:06:11.149419 N | auth: granted role root to user root
2016-07-02 00:06:11.149491 N | auth: Authentication enabled
2016-07-02 00:06:12.210574 N | auth: added a new user: foo
2016-07-02 00:06:13.390574 I | auth: authorized foo, token is dummy.2
2016-07-02 00:06:14.546016 N | auth: authentication failed, invalid password for user foo
2016-07-02 00:06:16.052747 N | auth: added a new user: root
2016-07-02 00:06:16.052868 N | auth: Role root is created
2016-07-02 00:06:16.052942 N | auth: granted role root to user root
2016-07-02 00:06:16.053010 N | auth: Authentication enabled
2016-07-02 00:06:19.505342 N | auth: added a new user: foo
2016-07-02 00:06:19.505470 N | auth: deleted a user: foo
2016-07-02 00:06:21.231592 N | auth: added a new user: root
2016-07-02 00:06:21.231711 N | auth: Role root is created
2016-07-02 00:06:21.231788 N | auth: granted role root to user root
2016-07-02 00:06:21.231874 N | auth: Authentication enabled
2016-07-02 00:06:22.873114 N | auth: added a new user: foo
2016-07-02 00:06:24.111531 I | auth: authorized foo, token is dummy.1
2016-07-02 00:06:35.062706 N | auth: changed a password of a user: foo
2016-07-02 00:06:36.257291 I | auth: authorized foo, token is dummy.2
2016-07-02 00:06:50.141311 N | auth: added a new user: root
2016-07-02 00:06:50.141489 N | auth: Role root is created
2016-07-02 00:06:50.141635 N | auth: granted role root to user root
2016-07-02 00:06:50.141803 N | auth: Authentication enabled
2016-07-02 00:06:50.143364 N | auth: Role role-test is created
2016-07-02 00:06:51.665341 N | auth: added a new user: root
2016-07-02 00:06:51.665451 N | auth: Role root is created
2016-07-02 00:06:51.665522 N | auth: granted role root to user root
2016-07-02 00:06:51.665591 N | auth: Authentication enabled
2016-07-02 00:06:52.924156 N | auth: added a new user: foo
2016-07-02 00:06:52.924272 N | auth: Role role-test is created
2016-07-02 00:06:52.924386 N | auth: granted role role-test to user foo
2016-07-02 00:06:54.537500 N | auth: added a new user: foo
2016-07-02 00:06:57.328986 N | auth: added a new user: root
2016-07-02 00:06:57.329117 N | auth: Role root is created
2016-07-02 00:06:57.329196 N | auth: granted role root to user root
2016-07-02 00:06:57.329293 N | auth: Authentication enabled
2016-07-02 00:06:58.656121 N | auth: added a new user: foo
2016-07-02 00:06:59.815778 I | auth: authorized foo, token is dummy.2
2016-07-02 00:07:00.976593 N | auth: authentication failed, invalid password for user foo
2016-07-02 00:07:03.642649 N | auth: added a new user: root
2016-07-02 00:07:03.642758 N | auth: Role root is created
2016-07-02 00:07:03.642827 N | auth: granted role root to user root
2016-07-02 00:07:03.642897 N | auth: Authentication enabled
2016-07-02 00:07:04.788262 N | auth: added a new user: foo
2016-07-02 00:07:04.788360 N | auth: deleted a user: foo
2016-07-02 00:07:06.286165 N | auth: added a new user: root
2016-07-02 00:07:06.286362 N | auth: Role root is created
2016-07-02 00:07:06.286510 N | auth: granted role root to user root
2016-07-02 00:07:06.286666 N | auth: Authentication enabled
2016-07-02 00:07:08.026383 N | auth: added a new user: foo
2016-07-02 00:07:09.552559 I | auth: authorized foo, token is dummy.1
2016-07-02 00:07:11.153437 N | auth: changed a password of a user: foo
2016-07-02 00:07:12.363850 I | auth: authorized foo, token is dummy.2
2016-07-02 00:07:15.285916 N | auth: added a new user: root
2016-07-02 00:07:15.286021 N | auth: Role root is created
2016-07-02 00:07:15.286092 N | auth: granted role root to user root
2016-07-02 00:07:15.286168 N | auth: Authentication enabled
2016-07-02 00:07:31.625734 N | auth: Role role-test is created
2016-07-02 00:07:33.222466 N | auth: added a new user: root
2016-07-02 00:07:33.222547 N | auth: Role root is created
2016-07-02 00:07:33.222611 N | auth: granted role root to user root
2016-07-02 00:07:33.222674 N | auth: Authentication enabled
2016-07-02 00:07:48.922167 N | auth: added a new user: foo
2016-07-02 00:07:48.922249 N | auth: Role role-test is created
2016-07-02 00:07:48.922327 N | auth: granted role role-test to user foo
2016-07-02 00:08:08.127965 N | auth: added a new user: foo
2016-07-02 00:08:10.609343 N | auth: added a new user: root
2016-07-02 00:08:10.609507 N | auth: Role root is created
2016-07-02 00:08:10.609638 N | auth: granted role root to user root
2016-07-02 00:08:10.609788 N | auth: Authentication enabled
2016-07-02 00:08:11.955850 N | auth: added a new user: foo
2016-07-02 00:08:13.411535 I | auth: authorized foo, token is dummy.2
2016-07-02 00:08:14.968946 N | auth: authentication failed, invalid password for user foo
2016-07-02 00:08:16.725489 N | auth: added a new user: root
2016-07-02 00:08:16.725668 N | auth: Role root is created
2016-07-02 00:08:16.725815 N | auth: granted role root to user root
2016-07-02 00:08:16.725965 N | auth: Authentication enabled
2016-07-02 00:08:18.304661 N | auth: added a new user: foo
2016-07-02 00:08:18.304784 N | auth: deleted a user: foo
2016-07-02 00:08:27.519645 N | auth: added a new user: root
2016-07-02 00:08:27.519821 N | auth: Role root is created
2016-07-02 00:08:27.519935 N | auth: granted role root to user root
2016-07-02 00:08:27.520046 N | auth: Authentication enabled
2016-07-02 00:08:33.348103 N | auth: added a new user: foo
2016-07-02 00:08:34.978965 I | auth: authorized foo, token is dummy.1
2016-07-02 00:08:36.766920 N | auth: changed a password of a user: foo
2016-07-02 00:08:38.372808 I | auth: authorized foo, token is dummy.2
2016-07-02 00:08:47.890043 N | auth: added a new user: root
2016-07-02 00:08:47.890185 N | auth: Role root is created
2016-07-02 00:08:47.890329 N | auth: granted role root to user root
2016-07-02 00:08:47.890445 N | auth: Authentication enabled
panic: test timed out after 3m0s
goroutine 68 [running]:
panic(0xb2c3a0, 0xc82038eb70)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3ff
testing.startAlarm.func1()
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:725 +0x184
created by time.goFunc
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/time/sleep.go:129 +0x6e
goroutine 1 [chan receive]:
testing.RunTests(0xe6e418, 0x10e7620, 0x7, 0x7, 0x10e7c01)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc8201adee0, 0x10eea20)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:515 +0x11e
main.main()
        github.com/coreos/etcd/auth/_test/_testmain.go:118 +0x386

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1
goroutine 66 [syscall]:
syscall.Syscall(0x4b, 0x3, 0x0, 0x0, 0x464824, 0x70a6c7, 0x464824)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fdatasync(0x3, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/syscall/zsyscall_linux_amd64.go:472 +0x58
github.com/boltdb/bolt.fdatasync(0xc8203ae000, 0x0, 0x0)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/boltdb/bolt/bolt_linux.go:9 +0x64
github.com/boltdb/bolt.(*Tx).write(0xc8203902a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/boltdb/bolt/tx.go:517 +0x995
github.com/boltdb/bolt.(*Tx).Commit(0xc8203902a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/boltdb/bolt/tx.go:198 +0x955
github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc820372940, 0xe6d800)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:169 +0x2b1
github.com/coreos/etcd/mvcc/backend.(*batchTx).Commit(0xc820372940)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:140 +0x74
github.com/coreos/etcd/mvcc/backend.(*backend).ForceCommit(0xc820370180)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/backend.go:132 +0x46
github.com/coreos/etcd/auth.(*authStore).AuthEnable.func1(0x7f956cc09908, 0xc820372940, 0x7f956cc098b0, 0xc820370180)
        github.com/coreos/etcd/auth/_test/_obj_test/store.go:154 +0x65
github.com/coreos/etcd/auth.(*authStore).AuthEnable(0xc820370240, 0x0, 0x0)
        github.com/coreos/etcd/auth/_test/_obj_test/store.go:181 +0x439
github.com/coreos/etcd/auth.enableAuthAndCreateRoot(0xc820370240, 0x0, 0x0)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/auth/store_test.go:64 +0x251
github.com/coreos/etcd/auth.TestRoleAdd(0xc8203a01b0)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/auth/store_test.go:203 +0xde
testing.tRunner(0xc8203a01b0, 0x10e7698)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdd
created by testing.RunTests
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0xae3

goroutine 67 [semacquire]:
sync.runtime_Semacquire(0xc820372944)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820372940)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/sync/mutex.go:83 +0x1ee
github.com/coreos/etcd/mvcc/backend.(*batchTx).Commit(0xc820372940)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:138 +0x3a
github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc820370180)
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/backend.go:199 +0x19b
created by github.com/coreos/etcd/mvcc/backend.newBackend
        /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x449
FAIL    github.com/coreos/etcd/auth     183.545s
```

/cc @mitake

**Comment by mitake** [comment] 2016-07-02 08:06
@heyitsanthony thanks for letting me know and sorry for that. I'll work on it.

**Comment by xiang90** [comment] 2016-07-05 18:13
@mitake I assigned this to you.

**Comment by mitake** [comment] 2016-07-06 02:27
@xiang90 sure, I'm working on it.
@heyitsanthony I'm trying to reproduce it but it doesn't happen yet. Maybe it is rare on your environment, too?

**Comment by mitake** [comment] 2016-07-06 06:35
@heyitsanthony is this happened on your machine? It seems that `fdatasync()` took more than 3 mins. Maybe happened on CI server?

**Comment by heyitsanthony** [comment] 2016-07-06 13:15
@mitake this was on semaphore; can't repro locally

**Comment by mitake** [comment] 2016-07-07 05:42
@heyitsanthony I think the failure wouldn't mean bugs in etcd. The timeout was caused by very long `fdatasync()`. If the timeout of testing is longer, the failure won't appear. How do you think?

BTW does current etcd have a policy about a case of disk I/O timeout?

**Comment by heyitsanthony** [comment] 2016-07-07 06:42
@mitake I think I figured it out; it's timing out in fsync by coincidence. The cause for the slow test is bcrypt. When I run `go test --race -cpu=1,2,4` (i.e., what `./test` uses) in `auth`, it takes about a minute with `DefaultCost` but only 5 seconds with `MinCost`. See #5892 

I don't think etcd has any policy concerning slow disk IO aside from emitting some warnings.

**Comment by mitake** [comment] 2016-07-07 06:49
@heyitsanthony ah I see. The timeout happened during the call of `fdatasync()` but the system call itself wasn't taking a long time. Thanks a lot for the diagnosis.

**Closed** 2016-07-07 16:05 UTC
Labels: area/testing
