### ISSUE TITLE
[Regression] Remove from two member cluster fails with health check error

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#6305] opened 2016-08-30 04:12 UTC
A previously passing test I wrote in https://github.com/purpleidea/mgmt/ started failing. This is all using pure golang and the etcd `embed` stuff. What it approximately does:

* Starts up a single member etcd cluster.
* Starts up a second member and runs the MemberAdd API call.
* Hangs out for 5 seconds
* Runs MemberRemove API call to shutdown the second member.

IIRC this is where we hit the issue. This should be a safe operation in our elastic etcd work, but it's started failing at some point when we re-ran our tests on a newer version of git master.

Example failure: https://travis-ci.org/purpleidea/mgmt/jobs/156113435#L441
```
rpc error: code = 2 desc = etcdserver: unhealthy cluster
```

Versions:
golang 1.5*/1.6*
etcdv3, git master. ATM: https://github.com/coreos/etcd/commit/9e9bbb829ef25181e5178138af6349f7971cba59

Bonus: A video of this elastic work (and more) is available here: https://www.youtube.com/watch?v=KVmDCUA42wc&html5=1

**Comment by purpleidea** [comment] 2016-08-30 04:13
@heyitsanthony Asked me to open this. Here it is!

BTW I can get more etcd logs (to do this in mgmt set VERBOSE to true in main.go) but I'm kind of buried finishing an important patch, so if you can't reproduce with the simple example above, let me know and I'll do the lifting to provide more details. Thanks!

**Comment by purpleidea** [comment] 2016-08-30 04:35
Okay here's a present, I got longer logs.
Any error message from etcd itself starts with (etcd), the rest is mgmt stuff.
You can also see how to run this test yourself.
HTH

```
james@computer:~/code/mgmt/test (feat/remote)$ ./test-shell.sh t8.sh
running test-shell.sh
Building: mgmt, version: 0.0.3-88-g08bb9b9-dirty...
time go build -ldflags "-X main.program=mgmt -X main.version=0.0.3-88-g08bb9b9-dirty" -o mgmt;

real	0m21.637s
user	1m1.320s
sys	0m3.787s
FAIL	t8.sh
FAIL
The following tests failed:
Script: t8.sh
Exited: 137
Output:
00:30:46 main.go:69: This is: mgmt, version: 0.0.3-88-g08bb9b9-dirty
00:30:46 main.go:70: Main: Start: 1472531446035435571
00:30:46 main.go:156: Main: Warning: Working prefix directory is temporary!
00:30:46 main.go:163: Main: Working prefix is: /tmp/mgmt-744843553
00:30:46 main.go:186: Main: Seeds: No seeds specified!
00:30:46 etcd.go:375: Etcd: Bootstrapping...
00:30:46 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380
00:30:46 etcd.go:1381: Etcd: StartServer(newCluster: true): h1=http://127.0.0.1:2380
00:30:46 etcd.go:1630: Etcd: StartServer: Starting server...
00:30:46 etcd.go:290: Etcd: Connect: Endpoints: []
00:30:46 etcd.go:304: Etcd: Connect: CtxError...
00:30:46 etcd.go:573: Etcd: CtxError: Reason: CtxDelayErr(1s): No endpoints available yet!
00:30:46 etcd.go:77: (etcd) embed: listening for peers on http://127.0.0.1:2380
00:30:46 etcd.go:80: (etcd) embed: listening for client requests on 127.0.0.1:2379
00:30:46 config.go:155: (etcd) etcdserver: name = h1
00:30:46 config.go:159: (etcd) etcdserver: data dir = /tmp/mgmt-744843553/etcd
00:30:46 config.go:160: (etcd) etcdserver: member dir = /tmp/mgmt-744843553/etcd/member
00:30:46 config.go:164: (etcd) etcdserver: heartbeat = 100ms
00:30:46 config.go:165: (etcd) etcdserver: election = 1000ms
00:30:46 config.go:166: (etcd) etcdserver: snapshot count = 10000
00:30:46 config.go:173: (etcd) etcdserver: advertise client URLs = http://127.0.0.1:2379
00:30:46 config.go:175: (etcd) etcdserver: initial advertise peer URLs = http://127.0.0.1:2380
00:30:46 config.go:176: (etcd) etcdserver: initial cluster = h1=http://127.0.0.1:2380
00:30:46 raft.go:323: (etcd) etcdserver: starting member b71f75320dc06a6c in cluster 1c45a069f3a1d796
00:30:46 raft.go:493: (etcd) raft: b71f75320dc06a6c became follower at term 0
00:30:46 raft.go:265: (etcd) raft: newRaft b71f75320dc06a6c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
00:30:46 raft.go:493: (etcd) raft: b71f75320dc06a6c became follower at term 1
00:30:46 server.go:486: (etcd) etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
00:30:46 cluster.go:295: (etcd) membership: added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 1c45a069f3a1d796
00:30:46 raft.go:586: (etcd) raft: b71f75320dc06a6c is starting a new election at term 1
00:30:46 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 2
00:30:46 raft.go:559: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 2
00:30:46 raft.go:533: (etcd) raft: b71f75320dc06a6c became leader at term 2
00:30:46 node.go:302: (etcd) raft: raft.node: b71f75320dc06a6c elected leader b71f75320dc06a6c at term 2
00:30:46 server.go:1415: (etcd) etcdserver: setting up the initial cluster version to 3.0
00:30:46 cluster.go:366: (etcd) membership: set the initial cluster version to 3.0
00:30:46 etcd.go:1637: Etcd: StartServer: Done starting server!
00:30:46 capability.go:69: (etcd) api: enabled capabilities for version 3.0
00:30:46 etcd.go:1647: Etcd: StartServer: Server running...
00:30:46 etcd.go:1400: Etcd: Addresses are: http://127.0.0.1:2379
00:30:46 server.go:1053: (etcd) etcdserver: published {Name:h1 ClientURLs:[http://127.0.0.1:2379]} to cluster 1c45a069f3a1d796
00:30:46 etcd.go:317: (etcd) embed: ready to serve client requests
00:30:46 serve.go:85: (etcd) embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
00:30:47 etcd.go:288: Etcd: Connect: Endpoints: h1=http://127.0.0.1:2379
00:30:47 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h1
00:30:47 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380
00:30:47 etcd.go:387: Etcd: Startup: Volunteering...
00:30:47 etcd.go:1561: Etcd: Ideal cluster size is now: 5
00:30:47 etcd.go:928: Etcd: Set(/_mgmt/idealClusterSize): &{cluster_id:2037210783374497686 member_id:13195394291058371180 revision:4 raft_term:2  <nil>}
00:30:47 main.go:375: Main: Running...
00:30:47 main.go:241: Etcd: Starting...
00:30:47 etcd.go:1165: Etcd: Members: List: [h1]
00:30:47 main.go:245: Main: Waiting...
00:30:47 main.go:277: Config: Parse failure
00:30:47 main.go:245: Main: Waiting...
00:30:47 etcd.go:1188: Etcd: Leader: h1
00:30:47 etcd.go:1207: Etcd: Volunteers: [h1]
00:30:47 etcd.go:1211: Etcd: Quitters: []
00:30:47 etcd.go:1223: Etcd: Candidates: []
00:30:47 etcd.go:1165: Etcd: Members: List: [h1]
00:30:47 etcd.go:1188: Etcd: Leader: h1
00:30:47 etcd.go:1207: Etcd: Volunteers: [h1]
00:30:47 etcd.go:1211: Etcd: Quitters: []
00:30:47 etcd.go:1223: Etcd: Candidates: []
00:30:51 main.go:69: This is: mgmt, version: 0.0.3-88-g08bb9b9-dirty
00:30:51 main.go:70: Main: Start: 1472531451050320229
00:30:51 main.go:156: Main: Warning: Working prefix directory is temporary!
00:30:51 main.go:163: Main: Working prefix is: /tmp/mgmt-827947648
00:30:51 main.go:188: Main: Seeds(1): http://127.0.0.1:2379
00:30:51 etcd.go:348: Etcd: Startup: Getting initial values...
00:30:51 etcd.go:288: Etcd: Connect: Endpoints: _seed=http://127.0.0.1:2379
00:30:51 etcd.go:360: Etcd: Startup: Ideal cluster size is: 5
00:30:51 etcd.go:387: Etcd: Startup: Volunteering...
00:30:51 main.go:375: Main: Running...
00:30:51 main.go:241: Etcd: Starting...
00:30:51 main.go:245: Main: Waiting...
00:30:51 main.go:277: Config: Parse failure
00:30:51 main.go:245: Main: Waiting...
00:30:51 etcd.go:1165: Etcd: Members: List: [h1]
00:30:51 etcd.go:1188: Etcd: Leader: h1
00:30:51 etcd.go:1207: Etcd: Volunteers: [h1 h2]
00:30:51 etcd.go:1211: Etcd: Quitters: []
00:30:51 etcd.go:1223: Etcd: Candidates: [h2]
00:30:51 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:51 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:51 etcd.go:1381: Etcd: StartServer(newCluster: false): h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:51 etcd.go:1250: Etcd: Member Add: http://127.0.0.1:2382
00:30:51 etcd.go:1630: Etcd: StartServer: Starting server...
00:30:51 etcd.go:77: (etcd) embed: listening for peers on http://127.0.0.1:2382
00:30:51 etcd.go:80: (etcd) embed: listening for client requests on 127.0.0.1:2381
00:30:51 cluster.go:295: (etcd) membership: added member dba436326af479dc [http://127.0.0.1:2382] to cluster 1c45a069f3a1d796
00:30:51 peer.go:121: (etcd) rafthttp: starting peer dba436326af479dc...
00:30:51 pipeline.go:67: (etcd) rafthttp: started HTTP pipelining with peer dba436326af479dc
00:30:51 stream.go:144: (etcd) rafthttp: started streaming with peer dba436326af479dc (writer)
00:30:51 stream.go:144: (etcd) rafthttp: started streaming with peer dba436326af479dc (writer)
00:30:51 config.go:155: (etcd) etcdserver: name = h2
00:30:51 config.go:159: (etcd) etcdserver: data dir = /tmp/mgmt-827947648/etcd
00:30:51 config.go:160: (etcd) etcdserver: member dir = /tmp/mgmt-827947648/etcd/member
00:30:51 config.go:164: (etcd) etcdserver: heartbeat = 100ms
00:30:51 config.go:165: (etcd) etcdserver: election = 1000ms
00:30:51 config.go:166: (etcd) etcdserver: snapshot count = 10000
00:30:51 config.go:173: (etcd) etcdserver: advertise client URLs = http://127.0.0.1:2381
00:30:51 peer.go:206: (etcd) rafthttp: started peer dba436326af479dc
00:30:51 transport.go:279: (etcd) rafthttp: added peer dba436326af479dc
00:30:51 stream.go:297: (etcd) rafthttp: started streaming with peer dba436326af479dc (stream Message reader)
00:30:51 stream.go:297: (etcd) rafthttp: started streaming with peer dba436326af479dc (stream MsgApp v2 reader)
00:30:51 etcd.go:1257: Etcd: Member Add: [http://127.0.0.1:2382]
00:30:51 etcd.go:573: Etcd: CtxError: Reason: CtxDelayErr(1s): Member h2 added successfully!
00:30:51 raft.go:323: (etcd) etcdserver: starting member dba436326af479dc in cluster 1c45a069f3a1d796
00:30:51 raft.go:493: (etcd) raft: dba436326af479dc became follower at term 0
00:30:51 raft.go:265: (etcd) raft: newRaft dba436326af479dc [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
00:30:51 raft.go:493: (etcd) raft: dba436326af479dc became follower at term 1
00:30:51 pipeline.go:67: (etcd) rafthttp: started HTTP pipelining with peer b71f75320dc06a6c
00:30:51 peer.go:121: (etcd) rafthttp: starting peer b71f75320dc06a6c...
00:30:51 pipeline.go:67: (etcd) rafthttp: started HTTP pipelining with peer b71f75320dc06a6c
00:30:51 stream.go:144: (etcd) rafthttp: started streaming with peer b71f75320dc06a6c (writer)
00:30:51 stream.go:144: (etcd) rafthttp: started streaming with peer b71f75320dc06a6c (writer)
00:30:51 peer.go:206: (etcd) rafthttp: started peer b71f75320dc06a6c
00:30:51 stream.go:297: (etcd) rafthttp: started streaming with peer b71f75320dc06a6c (stream Message reader)
00:30:51 transport.go:279: (etcd) rafthttp: added peer b71f75320dc06a6c
00:30:51 server.go:486: (etcd) etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
00:30:51 stream.go:297: (etcd) rafthttp: started streaming with peer b71f75320dc06a6c (stream MsgApp v2 reader)
00:30:51 peer_status.go:47: (etcd) rafthttp: peer b71f75320dc06a6c became active
00:30:51 stream.go:210: (etcd) rafthttp: established a TCP streaming connection with peer b71f75320dc06a6c (stream Message writer)
00:30:51 stream.go:210: (etcd) rafthttp: established a TCP streaming connection with peer b71f75320dc06a6c (stream MsgApp v2 writer)
00:30:51 peer_status.go:47: (etcd) rafthttp: peer dba436326af479dc became active
00:30:51 stream.go:306: (etcd) rafthttp: established a TCP streaming connection with peer dba436326af479dc (stream MsgApp v2 reader)
00:30:51 stream.go:306: (etcd) rafthttp: established a TCP streaming connection with peer dba436326af479dc (stream Message reader)
00:30:51 stream.go:210: (etcd) rafthttp: established a TCP streaming connection with peer dba436326af479dc (stream Message writer)
00:30:51 stream.go:306: (etcd) rafthttp: established a TCP streaming connection with peer b71f75320dc06a6c (stream Message reader)
00:30:51 stream.go:210: (etcd) rafthttp: established a TCP streaming connection with peer dba436326af479dc (stream MsgApp v2 writer)
00:30:51 stream.go:306: (etcd) rafthttp: established a TCP streaming connection with peer b71f75320dc06a6c (stream MsgApp v2 reader)
00:30:51 raft.go:612: (etcd) raft: dba436326af479dc [term: 1] received a MsgHeartbeat message with higher term from b71f75320dc06a6c [term: 2]
00:30:51 raft.go:493: (etcd) raft: dba436326af479dc became follower at term 2
00:30:51 node.go:302: (etcd) raft: raft.node: dba436326af479dc elected leader b71f75320dc06a6c at term 2
00:30:51 cluster.go:295: (etcd) membership: added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 1c45a069f3a1d796
00:30:51 cluster.go:366: (etcd) membership: set the initial cluster version to 3.0
00:30:51 capability.go:69: (etcd) api: enabled capabilities for version 3.0
00:30:51 cluster.go:295: (etcd) membership: added member dba436326af479dc [http://127.0.0.1:2382] to cluster 1c45a069f3a1d796
00:30:51 etcd.go:1637: Etcd: StartServer: Done starting server!
00:30:51 etcd.go:1647: Etcd: StartServer: Server running...
00:30:51 server.go:1053: (etcd) etcdserver: published {Name:h2 ClientURLs:[http://127.0.0.1:2381]} to cluster 1c45a069f3a1d796
00:30:51 etcd.go:317: (etcd) embed: ready to serve client requests
00:30:51 serve.go:85: (etcd) embed: serving insecure client requests on 127.0.0.1:2381, this is strongly discouraged!
00:30:51 etcd.go:1527: Etcd: Endpoints: h1=http://127.0.0.1:2379,h2=http://127.0.0.1:2381
00:30:51 etcd.go:616: Etcd: CtxError: Reason: CtxReconnectErr: local server is running
00:30:51 etcd.go:640: Etcd: CtxError: Cancelling 6 operations...
00:30:51 etcd.go:647: Etcd: CtxError: Reconnecting...
00:30:51 etcd.go:288: Etcd: Connect: Endpoints: h1=http://127.0.0.1:2379,h2=http://127.0.0.1:2381
00:30:51 etcd.go:657: Etcd: CtxError: Reconnected!
00:30:51 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:51 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:51 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:51 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:51 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:1165: Etcd: Members: List: [h1 h2]
00:30:52 etcd.go:1188: Etcd: Leader: h1
00:30:52 etcd.go:1207: Etcd: Volunteers: [h1 h2]
00:30:52 etcd.go:1211: Etcd: Quitters: []
00:30:52 etcd.go:1223: Etcd: Candidates: []
00:30:52 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:52 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:1527: Etcd: Endpoints: h1=http://127.0.0.1:2379,h2=http://127.0.0.1:2381
00:30:52 etcd.go:616: Etcd: CtxError: Reason: CtxReconnectErr: endpoint list changed
00:30:52 etcd.go:640: Etcd: CtxError: Cancelling 6 operations...
00:30:52 etcd.go:647: Etcd: CtxError: Reconnecting...
00:30:52 etcd.go:288: Etcd: Connect: Endpoints: h1=http://127.0.0.1:2379,h2=http://127.0.0.1:2381
00:30:52 etcd.go:657: Etcd: CtxError: Reconnected!
00:30:52 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380,h2=http://127.0.0.1:2382
00:30:52 etcd.go:1561: Etcd: Ideal cluster size is now: 5
00:30:52 etcd.go:1165: Etcd: Members: List: [h1 h2]
00:30:52 etcd.go:1188: Etcd: Leader: h1
00:30:52 etcd.go:1207: Etcd: Volunteers: [h1 h2]
00:30:52 etcd.go:1211: Etcd: Quitters: []
00:30:52 etcd.go:1223: Etcd: Candidates: []
00:30:52 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(PUT): h2
00:30:52 etcd.go:1165: Etcd: Members: List: [h1 h2]
00:30:52 etcd.go:1188: Etcd: Leader: h1
00:30:52 etcd.go:1207: Etcd: Volunteers: [h1 h2]
00:30:52 etcd.go:1211: Etcd: Quitters: []
00:30:52 etcd.go:1223: Etcd: Candidates: []
00:31:01 main.go:57: Interrupted by ^C
00:31:01 main.go:379: Destroy...
00:31:01 etcd.go:412: Etcd: Destroy: Unvolunteering...
00:31:01 etcd.go:1165: Etcd: Members: List: [h1 h2]
00:31:01 etcd.go:1165: Etcd: Members: List: [h1 h2]
00:31:01 etcd.go:1188: Etcd: Leader: h1
00:31:01 etcd.go:1207: Etcd: Volunteers: [h1]
00:31:01 etcd.go:1211: Etcd: Quitters: [h2]
00:31:01 etcd.go:1223: Etcd: Candidates: []
00:31:01 etcd.go:1274: Etcd: Quitters: Shutting down 1 members...
00:31:01 etcd.go:1188: Etcd: Leader: h1
00:31:01 etcd.go:1190: Etcd: We are not the leader...
00:31:01 etcd.go:1290: Etcd: Waiting 3 seconds for h2 to self remove...
00:31:01 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h2
00:31:01 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380
00:31:01 etcd.go:1429: Etcd: Member Remove: Removing self: 15826834580657437148
00:31:01 cluster.go:313: (etcd) membership: removed member dba436326af479dc from cluster 1c45a069f3a1d796
00:31:01 peer.go:278: (etcd) rafthttp: stopping peer dba436326af479dc...
00:31:01 cluster.go:313: (etcd) membership: removed member dba436326af479dc from cluster 1c45a069f3a1d796
00:31:01 stream.go:214: (etcd) rafthttp: closed the TCP streaming connection with peer dba436326af479dc (stream MsgApp v2 writer)
00:31:01 stream.go:216: (etcd) rafthttp: stopped streaming with peer dba436326af479dc (writer)
00:31:01 etcd.go:1435: Etcd: Member Removed (self): h2(15826834580657437148)
00:31:01 etcd.go:1439: Etcd: DestroyServer...
00:31:01 etcd.go:1657: Etcd: DestroyServer: Destroying...
00:31:01 server.go:816: (etcd) etcdserver: skipped leadership transfer for stopping non-leader member
00:31:01 stream.go:214: (etcd) rafthttp: closed the TCP streaming connection with peer dba436326af479dc (stream Message writer)
00:31:01 stream.go:216: (etcd) rafthttp: stopped streaming with peer dba436326af479dc (writer)
00:31:01 pipeline.go:73: (etcd) rafthttp: stopped HTTP pipelining with peer dba436326af479dc
00:31:01 stream.go:308: (etcd) rafthttp: lost the TCP streaming connection with peer b71f75320dc06a6c (stream MsgApp v2 reader)
00:31:01 stream.go:308: (etcd) rafthttp: lost the TCP streaming connection with peer dba436326af479dc (stream MsgApp v2 reader)
00:31:01 stream.go:324: (etcd) rafthttp: stopped streaming with peer dba436326af479dc (stream MsgApp v2 reader)
00:31:01 stream.go:308: (etcd) rafthttp: lost the TCP streaming connection with peer dba436326af479dc (stream Message reader)
00:31:01 stream.go:324: (etcd) rafthttp: stopped streaming with peer dba436326af479dc (stream Message reader)
00:31:01 peer.go:289: (etcd) rafthttp: stopped peer dba436326af479dc
00:31:01 transport.go:306: (etcd) rafthttp: removed peer dba436326af479dc
00:31:01 pipeline.go:73: (etcd) rafthttp: stopped HTTP pipelining with peer b71f75320dc06a6c
00:31:01 peer.go:278: (etcd) rafthttp: stopping peer b71f75320dc06a6c...
00:31:01 stream.go:308: (etcd) rafthttp: lost the TCP streaming connection with peer b71f75320dc06a6c (stream Message reader)
00:31:01 stream.go:214: (etcd) rafthttp: closed the TCP streaming connection with peer b71f75320dc06a6c (stream MsgApp v2 writer)
00:31:01 stream.go:216: (etcd) rafthttp: stopped streaming with peer b71f75320dc06a6c (writer)
00:31:01 stream.go:214: (etcd) rafthttp: closed the TCP streaming connection with peer b71f75320dc06a6c (stream Message writer)
00:31:01 stream.go:216: (etcd) rafthttp: stopped streaming with peer b71f75320dc06a6c (writer)
00:31:01 pipeline.go:73: (etcd) rafthttp: stopped HTTP pipelining with peer b71f75320dc06a6c
00:31:01 stream.go:324: (etcd) rafthttp: stopped streaming with peer b71f75320dc06a6c (stream MsgApp v2 reader)
00:31:01 stream.go:324: (etcd) rafthttp: stopped streaming with peer b71f75320dc06a6c (stream Message reader)
00:31:01 peer.go:289: (etcd) rafthttp: stopped peer b71f75320dc06a6c
00:31:01 etcd.go:1661: Etcd: DestroyServer: Done closing...
00:31:01 etcd.go:1668: Etcd: DestroyServer: Unlocking server...
00:31:01 etcd.go:1461: Etcd: Forcing endpoint callback...
00:31:01 etcd.go:423: Etcd: Destroy: Cancelling 6 operations...
00:31:04 etcd.go:1311: Member h2 (15826834580657437148) removed successfully!
00:31:04 etcd.go:616: Etcd: CtxError: Reason: CtxReconnectErr: a member was removed
00:31:04 etcd.go:640: Etcd: CtxError: Cancelling 6 operations...
00:31:04 etcd.go:647: Etcd: CtxError: Reconnecting...
00:31:04 etcd.go:288: Etcd: Connect: Endpoints: h1=http://127.0.0.1:2379
00:31:04 etcd.go:657: Etcd: CtxError: Reconnected!
00:31:04 etcd.go:1165: Etcd: Members: List: [h1]
00:31:04 etcd.go:1188: Etcd: Leader: h1
00:31:04 etcd.go:1207: Etcd: Volunteers: [h1]
00:31:04 etcd.go:1211: Etcd: Quitters: []
00:31:04 etcd.go:1223: Etcd: Candidates: []
00:31:04 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h2
00:31:04 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380
00:31:04 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h2
00:31:04 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h2
00:31:04 etcd.go:1366: Etcd: Nominated: h1=http://127.0.0.1:2380
00:31:04 etcd.go:1165: Etcd: Members: List: [h1]
00:31:04 etcd.go:1188: Etcd: Leader: h1
00:31:04 etcd.go:1207: Etcd: Volunteers: [h1]
00:31:04 etcd.go:1211: Etcd: Quitters: []
00:31:04 etcd.go:1223: Etcd: Candidates: []
00:31:04 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h2
00:32:16 main.go:59: Interrupted by signal
00:32:16 main.go:379: Destroy...
00:32:16 etcd.go:412: Etcd: Destroy: Unvolunteering...
00:32:16 etcd.go:1165: Etcd: Members: List: [h1]
00:32:16 etcd.go:1188: Etcd: Leader: h1
00:32:16 etcd.go:1207: Etcd: Volunteers: []
00:32:16 etcd.go:1211: Etcd: Quitters: [h1]
00:32:16 etcd.go:1215: Etcd: Quitters: Shutting down self...
00:32:16 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h1
00:32:16 etcd.go:1368: Etcd: Nominated: []
00:32:16 etcd.go:1439: Etcd: DestroyServer...
00:32:16 etcd.go:1657: Etcd: DestroyServer: Destroying...
00:32:16 server.go:821: (etcd) etcdserver: skipped leadership transfer for single member cluster
00:32:16 etcd.go:1661: Etcd: DestroyServer: Done closing...
00:32:16 etcd.go:1668: Etcd: DestroyServer: Unlocking server...
00:32:16 etcd.go:2269: Etcd: ApplyDeltaEvents: Event(DELETE): h1
00:32:16 etcd.go:1529: Etcd: Endpoints: []
00:32:16 etcd.go:423: Etcd: Destroy: Cancelling 6 operations...
00:32:16 main.go:404: Goodbye!
00:32:16 logger.go:87: (etcd) v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken EOF.
00:32:17 logger.go:87: (etcd) v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:2379: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:2379" <nil>}
00:32:18 logger.go:87: (etcd) v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:2379: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:2379" <nil>}
00:32:21 logger.go:87: (etcd) v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:2379: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:2379" <nil>}
/home/james/code/mgmt/test/shell/t8.sh: line 13: 25714 Killed                  timeout --kill-after=120s 90s ./mgmt run --hostname h2 --seeds http://127.0.0.1:2379 --client-urls http://127.0.0.1:2381 --server-urls http://127.0.0.1:2382 --tmp-prefix
```

**Comment by purpleidea** [comment] 2016-08-30 04:40
Changing the 5s sleeps in my test to 10s seems to make it pass. @heyitsanthony pointed out that 5s happens to also be the health check interval. So bad luck that I chose 5s, but I guess this is a bug, sorry.

**Comment by purpleidea** [comment] 2016-08-30 04:47
Some additional info for the logs. chzz pointed out that I could disable the extra health check by doing:

`cfg.StrictReconfigCheck = false`

but I'd like to leave it enabled, because more safety is good. Maybe this is good docs for someone who wants this to work ASAP and doesn't want safety. HTH

**Comment by purpleidea** [comment] 2016-08-30 09:34
@heyitsanthony Bad news, I think there's something racy about your health check, because even with 10s, sometimes this fails...

**Comment by heyitsanthony** [comment] 2016-09-01 23:19
@purpleidea If there's a race causing rejects for  `> 2*etcdserver.HealthInterval`, why aren't `TestRejectUnhealthyAdd` and `TestRejectUnhealthyRemove` failing in CI? There's not much about the code path that could race...

**Comment by purpleidea** [comment] 2016-09-02 00:31
On Thu, Sep 1, 2016 at 7:20 PM, Anthony Romano <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> If there's a race causing
> rejects for > 2*etcdserver.HealthInterval, why aren't
> TestRejectUnhealthyAdd and TestRejectUnhealthyRemove failing in CI?
> There's not much about the code path that could race...



Actually I don't know if there's a race for sure, because it's always
failing. So I might have either gotten lucky for some reason, or was
looking at the wrong data.

**Comment by xiang90** [comment] 2016-09-26 11:14
@heyitsanthony @purpleidea Is this still a problem? If it is, can we reproduce this with an isolated and etcd centric way reliably? If not, shall we close this?

**Comment by purpleidea** [comment] 2016-09-26 12:40
I think we should keep it open. @heyitsanthony had some comments about
the arbitrary nature of the health check and the 5s limit. IIRC.

**Comment by xiang90** [comment] 2016-09-26 12:43
There will be a timeout anyway. I feel 5 seconds is fine. Does it cause you any problem.

**Comment by purpleidea** [comment] 2016-09-26 13:30
@xiang90 To be honest, I don't know enough about the internals to know what is best here. I think it's better that I defer to your and @heyitsanthony's good judgement.

**Comment by heyitsanthony** [comment] 2016-10-04 18:09
Keeping the interval hardcoded for now to avoid adding an unnecessary configuration knob since the check can already be disabled via `--strict-reconfig-check=false`. If there's a convincing use case for making the interval user configurable we can circle back and add the option in the future.

**Closed by heyitsanthony** 2016-10-04 18:09 UTC
